package com.sil.hbm;
// Generated May 7, 2018 12:21:31 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgencyBankingTrn generated by hbm2java
 */
@Entity
@Table(name = "AGENCY_BANKING_TRN")
public class AgencyBankingTrn implements java.io.Serializable {
	private static final long serialVersionUID = 343612185484110864L;
	private AgencyBankingTrnId id;
	private Date transTime;
	private BigDecimal amount;
	private String fromacc;
	private String toacc;
	private String respCode;
	private String errorDesc;
	private String name;
	private String ownerId;
	private String deviceId;

	public AgencyBankingTrn() {
	}

	public AgencyBankingTrn(AgencyBankingTrnId id, Date transTime, BigDecimal amount, String fromacc, String toacc,
			String respCode, String errorDesc, String name) {
		this.id = id;
		this.transTime = transTime;
		this.amount = amount;
		this.fromacc = fromacc;
		this.toacc = toacc;
		this.respCode = respCode;
		this.errorDesc = errorDesc;
		this.name = name;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rrn", column = @Column(name = "RRN", nullable = false, length = 12)),
			@AttributeOverride(name = "transDate", column = @Column(name = "TRANS_DATE", nullable = false, length = 10)) })
	public AgencyBankingTrnId getId() {
		return this.id;
	}

	public void setId(AgencyBankingTrnId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "TRANS_TIME", nullable = false, length = 16)
	public Date getTransTime() {
		return this.transTime;
	}

	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "FROMACC", nullable = false, length = 50)
	public String getFromacc() {
		return this.fromacc;
	}

	public void setFromacc(String fromacc) {
		this.fromacc = fromacc;
	}

	@Column(name = "TOACC", nullable = false, length = 50)
	public String getToacc() {
		return this.toacc;
	}

	public void setToacc(String toacc) {
		this.toacc = toacc;
	}

	@Column(name = "RESP_CODE", nullable = false, length = 2)
	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	@Column(name = "ERROR_DESC", nullable = false, length = 500)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "NAME", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "OWNER_ID", nullable = false, length = 20)
	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}
	@Column(name = "DEVICE_ID", nullable = false, length = 20)
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

}
