package com.sil.hbm;
// Generated May 7, 2018 12:21:31 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgencyBankingTrnId generated by hbm2java
 */
@Embeddable
public class AgencyBankingTrnId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2029386798898546713L;
	private String rrn;
	private Date transDate;

	public AgencyBankingTrnId() {
	}

	public AgencyBankingTrnId(String rrn, Date transDate) {
		this.rrn = rrn;
		this.transDate = transDate;
	}

	@Column(name = "RRN", nullable = false, length = 12)
	public String getRrn() {
		return this.rrn;
	}

	public void setRrn(String rrn) {
		this.rrn = rrn;
	}

	@Column(name = "TRANS_DATE", nullable = false, length = 10)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgencyBankingTrnId))
			return false;
		AgencyBankingTrnId castOther = (AgencyBankingTrnId) other;

		return ((this.getRrn() == castOther.getRrn())
				|| (this.getRrn() != null && castOther.getRrn() != null && this.getRrn().equals(castOther.getRrn())))
				&& ((this.getTransDate() == castOther.getTransDate()) || (this.getTransDate() != null
						&& castOther.getTransDate() != null && this.getTransDate().equals(castOther.getTransDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRrn() == null ? 0 : this.getRrn().hashCode());
		result = 37 * result + (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		return result;
	}

}
