package com.sil.hbm;
// Generated Dec 22, 2016 11:52:11 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Billpayment generated by hbm2java
 */

@Entity
@Table(name = "D390221")
@DynamicInsert
@DynamicUpdate
public class Billpayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1139146020505232209L;
	private BillpaymentId id;
	private String accountno;
	private String consumerno;
	private String operator;
	private Double amount;
	private String responsecode;
	private String responsedesc;
	private Date entrytime;
	private String merchantrespcode;
	private String merchantrespdesc;
	private Date transactiondate;
	private String drcr;
	// private String refno;
	private String status;

	public Billpayment() {
	}

	public Billpayment(BillpaymentId id, String accountno, String consumerno, String operator, String responsecode,
			String responsedesc, Date entrytime) {
		this.id = id;
		this.accountno = accountno;
		this.consumerno = consumerno;
		this.operator = operator;
		this.responsecode = responsecode;
		this.responsedesc = responsedesc;
		this.entrytime = entrytime;
	}

	public Billpayment(BillpaymentId id, String accountno, String consumerno, String operator, Double amount,
			String responsecode, String responsedesc, Date entrytime, String merchantrespcode, String merchantrespdesc,
			Date transactiondate, String drcr,String status) {
		this.id = id;
		this.accountno = accountno;
		this.consumerno = consumerno;
		this.operator = operator;
		this.amount = amount;
		this.responsecode = responsecode;
		this.responsedesc = responsedesc;
		this.entrytime = entrytime;
		this.merchantrespcode = merchantrespcode;
		this.merchantrespdesc = merchantrespdesc;
		this.transactiondate = transactiondate;
		this.drcr = drcr;
		this.status=status;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrcode", column = @Column(name = "LBRCODE", nullable = false)),
			@AttributeOverride(name = "entrydate", column = @Column(name = "ENTRYDATE", nullable = false, length = 23)),
			@AttributeOverride(name = "batchcode", column = @Column(name = "BATCHCODE", nullable = false, length = 8)),
			@AttributeOverride(name = "setno", column = @Column(name = "SETNO", nullable = false)),
			@AttributeOverride(name = "scrollno", column = @Column(name = "SCROLLNO", nullable = false)),
			@AttributeOverride(name = "rrrnno", column = @Column(name = "RRRNNO", nullable = false, length = 20)) })
	public BillpaymentId getId() {
		return this.id;
	}

	public void setId(BillpaymentId id) {
		this.id = id;
	}

	@Column(name = "ACCOUNTNO", nullable = false, length = 30)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	@Column(name = "CONSUMERNO", nullable = false, length = 30)
	public String getConsumerno() {
		return this.consumerno;
	}

	public void setConsumerno(String consumerno) {
		this.consumerno = consumerno;
	}

	@Column(name = "OPERATOR", nullable = false, length = 50)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "AMOUNT", precision = 53, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "RESPONSECODE", nullable = false, length = 8)
	public String getResponsecode() {
		return this.responsecode;
	}

	public void setResponsecode(String responsecode) {
		this.responsecode = responsecode;
	}

	@Column(name = "RESPONSEDESC", nullable = false, length = 100)
	public String getResponsedesc() {
		return this.responsedesc;
	}

	public void setResponsedesc(String responsedesc) {
		this.responsedesc = responsedesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRYTIME", nullable = false, length = 23)
	public Date getEntrytime() {
		return this.entrytime;
	}

	public void setEntrytime(Date entrytime) {
		this.entrytime = entrytime;
	}

	@Column(name = "MERCHANTRESPCODE", length = 8)
	public String getMerchantrespcode() {
		return this.merchantrespcode;
	}

	public void setMerchantrespcode(String merchantrespcode) {
		this.merchantrespcode = merchantrespcode;
	}

	@Column(name = "MERCHANTRESPDESC", length = 100)
	public String getMerchantrespdesc() {
		return this.merchantrespdesc;
	}

	public void setMerchantrespdesc(String merchantrespdesc) {
		this.merchantrespdesc = merchantrespdesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSACTIONDATE", length = 23)
	public Date getTransactiondate() {
		return this.transactiondate;
	}

	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}

	@Column(name = "DRCR", length = 2)
	public String getDrcr() {
		return this.drcr;
	}

	public void setDrcr(String drcr) {
		this.drcr = drcr;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
