package com.sil.hbm;
// Generated Dec 14, 2017 4:20:51 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerdetailsId generated by hbm2java
 */
@Embeddable
public class CustomerdetailsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8849693017067290753L;
	private int custNo;
	private String nameTitle;
	private String longname;
	private String add1;
	private String add2;
	private String add3;
	private String cityCd;
	private String pinCode;
	private byte indOth;
	private byte panNo;
	private String panNoDesc;
	private char tdsYn;
	private Date dob;
	private short residence;
	private short profCd;
	private short cusType;
	private short maritalStatus;
	private double annualIncome;
	private byte resiStatus;
	private String adharNo;
	private String emailId;
	private String mobileNo;
	private String sexCode;
	private String relOff;
	
	@Column(name = "RelOff", nullable = false, length = 35)
	public String getRelOff() {
		return relOff;
	}

	public void setRelOff(String relOff) {
		this.relOff = relOff;
	}

	@Column(name = "SexCode", nullable = false, length = 2)
	public String getSexCode() {
		return sexCode;
	}

	public void setSexCode(String sexCode) {
		this.sexCode = sexCode;
	}

	public CustomerdetailsId() {
	}

	public CustomerdetailsId(int custNo, String nameTitle, String longname, String add1, String add2, String add3,
			String cityCd, String pinCode, byte indOth, byte panNo, String panNoDesc, char tdsYn, Date dob,
			short residence, short cusType, short maritalStatus, double annualIncome, byte resiStatus,
			String mobileNo) {
		this.custNo = custNo;
		this.nameTitle = nameTitle;
		this.longname = longname;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.cityCd = cityCd;
		this.pinCode = pinCode;
		this.indOth = indOth;
		this.panNo = panNo;
		this.panNoDesc = panNoDesc;
		this.tdsYn = tdsYn;
		this.dob = dob;
		this.residence = residence;
		this.cusType = cusType;
		this.maritalStatus = maritalStatus;
		this.annualIncome = annualIncome;
		this.resiStatus = resiStatus;
		this.mobileNo = mobileNo;
	}

	public CustomerdetailsId(int custNo, String nameTitle, String longname, String add1, String add2, String add3,
			String cityCd, String pinCode, byte indOth, byte panNo, String panNoDesc, char tdsYn, Date dob,
			short residence, short cusType, short maritalStatus, double annualIncome, byte resiStatus, String adharNo,
			String emailId, String mobileNo) {
		this.custNo = custNo;
		this.nameTitle = nameTitle;
		this.longname = longname;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.cityCd = cityCd;
		this.pinCode = pinCode;
		this.indOth = indOth;
		this.panNo = panNo;
		this.panNoDesc = panNoDesc;
		this.tdsYn = tdsYn;
		this.dob = dob;
		this.residence = residence;
		this.cusType = cusType;
		this.maritalStatus = maritalStatus;
		this.annualIncome = annualIncome;
		this.resiStatus = resiStatus;
		this.adharNo = adharNo;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
	}

	@Column(name = "CustNo", nullable = false)
	public int getCustNo() {
		return this.custNo;
	}

	public void setCustNo(int custNo) {
		this.custNo = custNo;
	}

	@Column(name = "NameTitle", nullable = false, length = 4)
	public String getNameTitle() {
		return this.nameTitle;
	}

	public void setNameTitle(String nameTitle) {
		this.nameTitle = nameTitle;
	}

	@Column(name = "Longname", nullable = false, length = 50)
	public String getLongname() {
		return this.longname;
	}

	public void setLongname(String longname) {
		this.longname = longname;
	}

	@Column(name = "Add1", nullable = false, length = 35)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "Add2", nullable = false, length = 35)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "Add3", nullable = false, length = 35)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "CityCd", nullable = false, length = 3)
	public String getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(String cityCd) {
		this.cityCd = cityCd;
	}

	@Column(name = "PinCode", nullable = false, length = 8)
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "IndOth", nullable = false)
	public byte getIndOth() {
		return this.indOth;
	}

	public void setIndOth(byte indOth) {
		this.indOth = indOth;
	}

	@Column(name = "PanNo", nullable = false)
	public byte getPanNo() {
		return this.panNo;
	}

	public void setPanNo(byte panNo) {
		this.panNo = panNo;
	}

	@Column(name = "PanNoDesc", nullable = false, length = 15)
	public String getPanNoDesc() {
		return this.panNoDesc;
	}

	public void setPanNoDesc(String panNoDesc) {
		this.panNoDesc = panNoDesc;
	}

	@Column(name = "TdsYN", nullable = false, length = 1)
	public char getTdsYn() {
		return this.tdsYn;
	}

	public void setTdsYn(char tdsYn) {
		this.tdsYn = tdsYn;
	}

	@Column(name = "DOB", nullable = false, length = 23)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Residence", nullable = false)
	public short getResidence() {
		return this.residence;
	}

	public void setResidence(short residence) {
		this.residence = residence;
	}

	@Column(name = "CusType", nullable = false)
	public short getCusType() {
		return this.cusType;
	}

	public void setCusType(short cusType) {
		this.cusType = cusType;
	}

	@Column(name = "MaritalStatus", nullable = false)
	public short getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(short maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "AnnualIncome", nullable = false, precision = 53, scale = 0)
	public double getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(double annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "ResiStatus", nullable = false)
	public byte getResiStatus() {
		return this.resiStatus;
	}

	public void setResiStatus(byte resiStatus) {
		this.resiStatus = resiStatus;
	}

	@Column(name = "AdharNo", length = 15)
	public String getAdharNo() {
		return this.adharNo;
	}

	public void setAdharNo(String adharNo) {
		this.adharNo = adharNo;
	}

	@Column(name = "EmailId", length = 35)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "MobileNo", nullable = false, length = 13)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "ProfCd", nullable = false)
	public short getProfCd() {
		return profCd;
	}

	public void setProfCd(short profCd) {
		this.profCd = profCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerdetailsId))
			return false;
		CustomerdetailsId castOther = (CustomerdetailsId) other;

		return (this.getCustNo() == castOther.getCustNo())
				&& ((this.getNameTitle() == castOther.getNameTitle()) || (this.getNameTitle() != null
						&& castOther.getNameTitle() != null && this.getNameTitle().equals(castOther.getNameTitle())))
				&& ((this.getLongname() == castOther.getLongname()) || (this.getLongname() != null
						&& castOther.getLongname() != null && this.getLongname().equals(castOther.getLongname())))
				&& ((this.getAdd1() == castOther.getAdd1()) || (this.getAdd1() != null && castOther.getAdd1() != null
						&& this.getAdd1().equals(castOther.getAdd1())))
				&& ((this.getAdd2() == castOther.getAdd2()) || (this.getAdd2() != null && castOther.getAdd2() != null
						&& this.getAdd2().equals(castOther.getAdd2())))
				&& ((this.getAdd3() == castOther.getAdd3()) || (this.getAdd3() != null && castOther.getAdd3() != null
						&& this.getAdd3().equals(castOther.getAdd3())))
				&& ((this.getCityCd() == castOther.getCityCd()) || (this.getCityCd() != null
						&& castOther.getCityCd() != null && this.getCityCd().equals(castOther.getCityCd())))
				&& ((this.getPinCode() == castOther.getPinCode()) || (this.getPinCode() != null
						&& castOther.getPinCode() != null && this.getPinCode().equals(castOther.getPinCode())))
				&& (this.getIndOth() == castOther.getIndOth()) && (this.getPanNo() == castOther.getPanNo())
				&& ((this.getPanNoDesc() == castOther.getPanNoDesc()) || (this.getPanNoDesc() != null
						&& castOther.getPanNoDesc() != null && this.getPanNoDesc().equals(castOther.getPanNoDesc())))
				&& (this.getTdsYn() == castOther.getTdsYn())
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null && castOther.getDob() != null
						&& this.getDob().equals(castOther.getDob())))
				&& (this.getResidence() == castOther.getResidence()) && (this.getCusType() == castOther.getCusType())
				&& (this.getMaritalStatus() == castOther.getMaritalStatus())
				&& (this.getAnnualIncome() == castOther.getAnnualIncome())
				&& (this.getResiStatus() == castOther.getResiStatus())
				&& ((this.getAdharNo() == castOther.getAdharNo()) || (this.getAdharNo() != null
						&& castOther.getAdharNo() != null && this.getAdharNo().equals(castOther.getAdharNo())))
				&& ((this.getEmailId() == castOther.getEmailId()) || (this.getEmailId() != null
						&& castOther.getEmailId() != null && this.getEmailId().equals(castOther.getEmailId())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this.getMobileNo() != null
						&& castOther.getMobileNo() != null && this.getMobileNo().equals(castOther.getMobileNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustNo();
		result = 37 * result + (getNameTitle() == null ? 0 : this.getNameTitle().hashCode());
		result = 37 * result + (getLongname() == null ? 0 : this.getLongname().hashCode());
		result = 37 * result + (getAdd1() == null ? 0 : this.getAdd1().hashCode());
		result = 37 * result + (getAdd2() == null ? 0 : this.getAdd2().hashCode());
		result = 37 * result + (getAdd3() == null ? 0 : this.getAdd3().hashCode());
		result = 37 * result + (getCityCd() == null ? 0 : this.getCityCd().hashCode());
		result = 37 * result + (getPinCode() == null ? 0 : this.getPinCode().hashCode());
		result = 37 * result + this.getIndOth();
		result = 37 * result + this.getPanNo();
		result = 37 * result + (getPanNoDesc() == null ? 0 : this.getPanNoDesc().hashCode());
		result = 37 * result + this.getTdsYn();
		result = 37 * result + (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result + this.getResidence();
		result = 37 * result + this.getCusType();
		result = 37 * result + this.getMaritalStatus();
		result = 37 * result + (int) this.getAnnualIncome();
		result = 37 * result + this.getResiStatus();
		result = 37 * result + (getAdharNo() == null ? 0 : this.getAdharNo().hashCode());
		result = 37 * result + (getEmailId() == null ? 0 : this.getEmailId().hashCode());
		result = 37 * result + (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "CustomerdetailsId [custNo=" + custNo + ", nameTitle=" + nameTitle + ", longname=" + longname + ", add1="
				+ add1 + ", add2=" + add2 + ", add3=" + add3 + ", cityCd=" + cityCd + ", pinCode=" + pinCode
				+ ", indOth=" + indOth + ", panNo=" + panNo + ", panNoDesc=" + panNoDesc + ", tdsYn=" + tdsYn + ", dob="
				+ dob + ", residence=" + residence + ", profCd=" + profCd + ", cusType=" + cusType + ", maritalStatus="
				+ maritalStatus + ", annualIncome=" + annualIncome + ", resiStatus=" + resiStatus + ", adharNo="
				+ adharNo + ", emailId=" + emailId + ", mobileNo=" + mobileNo + ", sexCode=" + sexCode + ", relOff="
				+ relOff + "]";
	}

}
