package com.sil.hbm;
// Generated Dec 14, 2017 4:20:51 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customerdetails generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERDETAILS")
public class Customerdetails implements java.io.Serializable {

	private static final long serialVersionUID = 8546669541557750937L;
	private CustomerdetailsId id;

	public Customerdetails() {
	}

	public Customerdetails(CustomerdetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false)),
			@AttributeOverride(name = "nameTitle", column = @Column(name = "NameTitle", nullable = false, length = 4)),
			@AttributeOverride(name = "longname", column = @Column(name = "Longname", nullable = false, length = 50)),
			@AttributeOverride(name = "add1", column = @Column(name = "Add1", nullable = false, length = 35)),
			@AttributeOverride(name = "add2", column = @Column(name = "Add2", nullable = false, length = 35)),
			@AttributeOverride(name = "add3", column = @Column(name = "Add3", nullable = false, length = 35)),
			@AttributeOverride(name = "cityCd", column = @Column(name = "CityCd", nullable = false, length = 3)),
			@AttributeOverride(name = "pinCode", column = @Column(name = "PinCode", nullable = false, length = 8)),
			@AttributeOverride(name = "indOth", column = @Column(name = "IndOth", nullable = false)),
			@AttributeOverride(name = "panNo", column = @Column(name = "PanNo", nullable = false)),
			@AttributeOverride(name = "panNoDesc", column = @Column(name = "PanNoDesc", nullable = false, length = 15)),
			@AttributeOverride(name = "tdsYn", column = @Column(name = "TdsYN", nullable = false, length = 1)),
			@AttributeOverride(name = "dob", column = @Column(name = "DOB", nullable = false, length = 23)),
			@AttributeOverride(name = "residence", column = @Column(name = "Residence", nullable = false)),
			@AttributeOverride(name = "cusType", column = @Column(name = "CusType", nullable = false)),
			@AttributeOverride(name = "maritalStatus", column = @Column(name = "MaritalStatus", nullable = false)),
			@AttributeOverride(name = "annualIncome", column = @Column(name = "AnnualIncome", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "resiStatus", column = @Column(name = "ResiStatus", nullable = false)),
			@AttributeOverride(name = "adharNo", column = @Column(name = "AdharNo", length = 15)),
			@AttributeOverride(name = "emailId", column = @Column(name = "EmailId", length = 35)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo", nullable = false, length = 13)) })
	public CustomerdetailsId getId() {
		return this.id;
	}

	public void setId(CustomerdetailsId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Customerdetails [id=" + id + "]";
	}

}
