package com.sil.hbm;
// Generated 20 Sep, 2016 7:20:51 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D001005Id generated by hbm2java
 */
@Embeddable
public class D001005Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1185900688842660642L;
	private int lbrCode;
	private char cat;
	private String catType;
	private String code1;
	private String code2;
	private Date lnodate;

	public D001005Id() {
	}

	public D001005Id(int lbrCode, char cat, String catType, String code1, String code2, Date lnodate) {
		this.lbrCode = lbrCode;
		this.cat = cat;
		this.catType = catType;
		this.code1 = code1;
		this.code2 = code2;
		this.lnodate = lnodate;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "Cat", nullable = false, length = 1)
	public char getCat() {
		return this.cat;
	}

	public void setCat(char cat) {
		this.cat = cat;
	}

	@Column(name = "CatType", nullable = false, length = 8)
	public String getCatType() {
		return this.catType;
	}

	public void setCatType(String catType) {
		this.catType = catType;
	}

	@Column(name = "Code1", nullable = false, length = 8)
	public String getCode1() {
		return this.code1;
	}

	public void setCode1(String code1) {
		this.code1 = code1;
	}

	@Column(name = "Code2", nullable = false, length = 8)
	public String getCode2() {
		return this.code2;
	}

	public void setCode2(String code2) {
		this.code2 = code2;
	}

	@Column(name = "Lnodate", nullable = false, length = 23)
	public Date getLnodate() {
		return this.lnodate;
	}

	public void setLnodate(Date lnodate) {
		this.lnodate = lnodate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D001005Id))
			return false;
		D001005Id castOther = (D001005Id) other;

		return (this.getLbrCode() == castOther.getLbrCode()) && (this.getCat() == castOther.getCat())
				&& ((this.getCatType() == castOther.getCatType()) || (this.getCatType() != null
						&& castOther.getCatType() != null && this.getCatType().equals(castOther.getCatType())))
				&& ((this.getCode1() == castOther.getCode1()) || (this.getCode1() != null
						&& castOther.getCode1() != null && this.getCode1().equals(castOther.getCode1())))
				&& ((this.getCode2() == castOther.getCode2()) || (this.getCode2() != null
						&& castOther.getCode2() != null && this.getCode2().equals(castOther.getCode2())))
				&& ((this.getLnodate() == castOther.getLnodate()) || (this.getLnodate() != null
						&& castOther.getLnodate() != null && this.getLnodate().equals(castOther.getLnodate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + this.getCat();
		result = 37 * result + (getCatType() == null ? 0 : this.getCatType().hashCode());
		result = 37 * result + (getCode1() == null ? 0 : this.getCode1().hashCode());
		result = 37 * result + (getCode2() == null ? 0 : this.getCode2().hashCode());
		result = 37 * result + (getLnodate() == null ? 0 : this.getLnodate().hashCode());
		return result;
	}

}
