
package com.sil.hbm;
// Generated Mar 7, 2017 1:37:54 PM by Hibernate Tools 5.2.0.Beta1
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D001003 generated by hbm2java
 */
@Entity
@Table(name = "D001003")
@DynamicUpdate
@DynamicInsert
public class D001003 implements java.io.Serializable {

	private static final long serialVersionUID = -3904237730779536395L;
	private int pbrCode;
	private String name;
	private String shortName;
	private String add1;
	private String add2;
	private String add3;
	private String cityCd;
	private int pinCode;
	private String countryCd;
	private int area;
	private byte branchType;
	private int tele1;
	private int tele2;
	private int tele3;
	private int tele4;
	private String faxNo1;
	private String faxNo2;
	private String telexNo1;
	private String telexNo2;
	private String swiftAddr;
	private byte weekOff1;
	private byte weekOff2;
	private Date gmttimeOffset;
	private Date localTimeOffset;
	private byte fromDay1;
	private byte toDay1;
	private String morningTime1;
	private String eveningTime1;
	private byte fromDay2;
	private byte toDay2;
	private String morningTime2;
	private String eveningTime2;
	private byte finYearFrom;
	private byte finYearTo;
	private String homeCurrency;
	private byte halfDay1;
	private byte halfDay2;
	private int clusterNo;
	private String ipNo;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
//	private String stateCode;
//	private String contactPerson;
//	private String emailid;
//	private String language;
//	private Double latitude;
//	private Double longitude;
//	private String title;

	public D001003() {
	}

	public D001003(int pbrCode, String name, String shortName, String add1, String add2, String add3, String cityCd,
			int pinCode, String countryCd, int area, byte branchType, int tele1, int tele2, int tele3, int tele4,
			String faxNo1, String faxNo2, String telexNo1, String telexNo2, String swiftAddr, byte weekOff1,
			byte weekOff2, Date gmttimeOffset, Date localTimeOffset, byte fromDay1, byte toDay1, String morningTime1,
			String eveningTime1, byte fromDay2, byte toDay2, String morningTime2, String eveningTime2, byte finYearFrom,
			byte finYearTo, String homeCurrency, byte halfDay1, byte halfDay2, int clusterNo, String ipNo,
			int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb,
			short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs,
			Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd,
			Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded,
			short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.pbrCode = pbrCode;
		this.name = name;
		this.shortName = shortName;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.cityCd = cityCd;
		this.pinCode = pinCode;
		this.countryCd = countryCd;
		this.area = area;
		this.branchType = branchType;
		this.tele1 = tele1;
		this.tele2 = tele2;
		this.tele3 = tele3;
		this.tele4 = tele4;
		this.faxNo1 = faxNo1;
		this.faxNo2 = faxNo2;
		this.telexNo1 = telexNo1;
		this.telexNo2 = telexNo2;
		this.swiftAddr = swiftAddr;
		this.weekOff1 = weekOff1;
		this.weekOff2 = weekOff2;
		this.gmttimeOffset = gmttimeOffset;
		this.localTimeOffset = localTimeOffset;
		this.fromDay1 = fromDay1;
		this.toDay1 = toDay1;
		this.morningTime1 = morningTime1;
		this.eveningTime1 = eveningTime1;
		this.fromDay2 = fromDay2;
		this.toDay2 = toDay2;
		this.morningTime2 = morningTime2;
		this.eveningTime2 = eveningTime2;
		this.finYearFrom = finYearFrom;
		this.finYearTo = finYearTo;
		this.homeCurrency = homeCurrency;
		this.halfDay1 = halfDay1;
		this.halfDay2 = halfDay2;
		this.clusterNo = clusterNo;
		this.ipNo = ipNo;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	public D001003(int pbrCode, String name, String shortName, String add1, String add2, String add3, String cityCd,
			int pinCode, String countryCd, int area, byte branchType, int tele1, int tele2, int tele3, int tele4,
			String faxNo1, String faxNo2, String telexNo1, String telexNo2, String swiftAddr, byte weekOff1,
			byte weekOff2, Date gmttimeOffset, Date localTimeOffset, byte fromDay1, byte toDay1, String morningTime1,
			String eveningTime1, byte fromDay2, byte toDay2, String morningTime2, String eveningTime2, byte finYearFrom,
			byte finYearTo, String homeCurrency, byte halfDay1, byte halfDay2, int clusterNo, String ipNo,
			int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb,
			short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs,
			Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd,
			Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded,
			short dbtrUpdtChkId, int dbtrLhisTrnNo, String stateCode, String contactPerson, String emailid,
			String language, Double latitude, Double longitude, String title) {
		this.pbrCode = pbrCode;
		this.name = name;
		this.shortName = shortName;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.cityCd = cityCd;
		this.pinCode = pinCode;
		this.countryCd = countryCd;
		this.area = area;
		this.branchType = branchType;
		this.tele1 = tele1;
		this.tele2 = tele2;
		this.tele3 = tele3;
		this.tele4 = tele4;
		this.faxNo1 = faxNo1;
		this.faxNo2 = faxNo2;
		this.telexNo1 = telexNo1;
		this.telexNo2 = telexNo2;
		this.swiftAddr = swiftAddr;
		this.weekOff1 = weekOff1;
		this.weekOff2 = weekOff2;
		this.gmttimeOffset = gmttimeOffset;
		this.localTimeOffset = localTimeOffset;
		this.fromDay1 = fromDay1;
		this.toDay1 = toDay1;
		this.morningTime1 = morningTime1;
		this.eveningTime1 = eveningTime1;
		this.fromDay2 = fromDay2;
		this.toDay2 = toDay2;
		this.morningTime2 = morningTime2;
		this.eveningTime2 = eveningTime2;
		this.finYearFrom = finYearFrom;
		this.finYearTo = finYearTo;
		this.homeCurrency = homeCurrency;
		this.halfDay1 = halfDay1;
		this.halfDay2 = halfDay2;
		this.clusterNo = clusterNo;
		this.ipNo = ipNo;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
//		this.stateCode = stateCode;
//		this.contactPerson = contactPerson;
//		this.emailid = emailid;
//		this.language = language;
//		this.latitude = latitude;
//		this.longitude = longitude;
//		this.title = title;
	}

	@Id

	@Column(name = "PBrCode", unique = true, nullable = false)
	public int getPbrCode() {
		return this.pbrCode;
	}

	public void setPbrCode(int pbrCode) {
		this.pbrCode = pbrCode;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ShortName", nullable = false, length = 15)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "Add1", nullable = false, length = 30)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "Add2", nullable = false, length = 30)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "Add3", nullable = false, length = 30)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "CityCd", nullable = false, length = 3)
	public String getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(String cityCd) {
		this.cityCd = cityCd;
	}

	@Column(name = "PinCode", nullable = false)
	public int getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(int pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "CountryCd", nullable = false, length = 3)
	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	@Column(name = "Area", nullable = false)
	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	@Column(name = "BranchType", nullable = false)
	public byte getBranchType() {
		return this.branchType;
	}

	public void setBranchType(byte branchType) {
		this.branchType = branchType;
	}

	@Column(name = "Tele1", nullable = false)
	public int getTele1() {
		return this.tele1;
	}

	public void setTele1(int tele1) {
		this.tele1 = tele1;
	}

	@Column(name = "Tele2", nullable = false)
	public int getTele2() {
		return this.tele2;
	}

	public void setTele2(int tele2) {
		this.tele2 = tele2;
	}

	@Column(name = "Tele3", nullable = false)
	public int getTele3() {
		return this.tele3;
	}

	public void setTele3(int tele3) {
		this.tele3 = tele3;
	}

	@Column(name = "Tele4", nullable = false)
	public int getTele4() {
		return this.tele4;
	}

	public void setTele4(int tele4) {
		this.tele4 = tele4;
	}

	@Column(name = "FaxNo1", nullable = false, length = 12)
	public String getFaxNo1() {
		return this.faxNo1;
	}

	public void setFaxNo1(String faxNo1) {
		this.faxNo1 = faxNo1;
	}

	@Column(name = "FaxNo2", nullable = false, length = 16)
	public String getFaxNo2() {
		return this.faxNo2;
	}

	public void setFaxNo2(String faxNo2) {
		this.faxNo2 = faxNo2;
	}

	@Column(name = "TelexNo1", nullable = false, length = 16)
	public String getTelexNo1() {
		return this.telexNo1;
	}

	public void setTelexNo1(String telexNo1) {
		this.telexNo1 = telexNo1;
	}

	@Column(name = "TelexNo2", nullable = false, length = 16)
	public String getTelexNo2() {
		return this.telexNo2;
	}

	public void setTelexNo2(String telexNo2) {
		this.telexNo2 = telexNo2;
	}

	@Column(name = "SwiftAddr", nullable = false, length = 30)
	public String getSwiftAddr() {
		return this.swiftAddr;
	}

	public void setSwiftAddr(String swiftAddr) {
		this.swiftAddr = swiftAddr;
	}

	@Column(name = "WeekOff1", nullable = false)
	public byte getWeekOff1() {
		return this.weekOff1;
	}

	public void setWeekOff1(byte weekOff1) {
		this.weekOff1 = weekOff1;
	}

	@Column(name = "WeekOff2", nullable = false)
	public byte getWeekOff2() {
		return this.weekOff2;
	}

	public void setWeekOff2(byte weekOff2) {
		this.weekOff2 = weekOff2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GMTTimeOffset", nullable = false, length = 23)
	public Date getGmttimeOffset() {
		return this.gmttimeOffset;
	}

	public void setGmttimeOffset(Date gmttimeOffset) {
		this.gmttimeOffset = gmttimeOffset;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LocalTimeOffset", nullable = false, length = 23)
	public Date getLocalTimeOffset() {
		return this.localTimeOffset;
	}

	public void setLocalTimeOffset(Date localTimeOffset) {
		this.localTimeOffset = localTimeOffset;
	}

	@Column(name = "FromDay1", nullable = false)
	public byte getFromDay1() {
		return this.fromDay1;
	}

	public void setFromDay1(byte fromDay1) {
		this.fromDay1 = fromDay1;
	}

	@Column(name = "ToDay1", nullable = false)
	public byte getToDay1() {
		return this.toDay1;
	}

	public void setToDay1(byte toDay1) {
		this.toDay1 = toDay1;
	}

	@Column(name = "MorningTime1", nullable = false, length = 15)
	public String getMorningTime1() {
		return this.morningTime1;
	}

	public void setMorningTime1(String morningTime1) {
		this.morningTime1 = morningTime1;
	}

	@Column(name = "EveningTime1", nullable = false, length = 15)
	public String getEveningTime1() {
		return this.eveningTime1;
	}

	public void setEveningTime1(String eveningTime1) {
		this.eveningTime1 = eveningTime1;
	}

	@Column(name = "FromDay2", nullable = false)
	public byte getFromDay2() {
		return this.fromDay2;
	}

	public void setFromDay2(byte fromDay2) {
		this.fromDay2 = fromDay2;
	}

	@Column(name = "ToDay2", nullable = false)
	public byte getToDay2() {
		return this.toDay2;
	}

	public void setToDay2(byte toDay2) {
		this.toDay2 = toDay2;
	}

	@Column(name = "MorningTime2", nullable = false, length = 15)
	public String getMorningTime2() {
		return this.morningTime2;
	}

	public void setMorningTime2(String morningTime2) {
		this.morningTime2 = morningTime2;
	}

	@Column(name = "EveningTime2", nullable = false, length = 15)
	public String getEveningTime2() {
		return this.eveningTime2;
	}

	public void setEveningTime2(String eveningTime2) {
		this.eveningTime2 = eveningTime2;
	}

	@Column(name = "FinYearFrom", nullable = false)
	public byte getFinYearFrom() {
		return this.finYearFrom;
	}

	public void setFinYearFrom(byte finYearFrom) {
		this.finYearFrom = finYearFrom;
	}

	@Column(name = "FinYearTo", nullable = false)
	public byte getFinYearTo() {
		return this.finYearTo;
	}

	public void setFinYearTo(byte finYearTo) {
		this.finYearTo = finYearTo;
	}

	@Column(name = "HomeCurrency", nullable = false, length = 3)
	public String getHomeCurrency() {
		return this.homeCurrency;
	}

	public void setHomeCurrency(String homeCurrency) {
		this.homeCurrency = homeCurrency;
	}

	@Column(name = "HalfDay1", nullable = false)
	public byte getHalfDay1() {
		return this.halfDay1;
	}

	public void setHalfDay1(byte halfDay1) {
		this.halfDay1 = halfDay1;
	}

	@Column(name = "HalfDay2", nullable = false)
	public byte getHalfDay2() {
		return this.halfDay2;
	}

	public void setHalfDay2(byte halfDay2) {
		this.halfDay2 = halfDay2;
	}

	@Column(name = "ClusterNo", nullable = false)
	public int getClusterNo() {
		return this.clusterNo;
	}

	public void setClusterNo(int clusterNo) {
		this.clusterNo = clusterNo;
	}

	@Column(name = "IpNo", nullable = false, length = 32)
	public String getIpNo() {
		return this.ipNo;
	}

	public void setIpNo(String ipNo) {
		this.ipNo = ipNo;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	/*@Column(name = "STATE_CODE", length = 3)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "CONTACT_PERSON", length = 50)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "EMAILID", length = 100)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "LANGUAGE", length = 25)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "LATITUDE", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "TITLE", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}*/
}
