package com.sil.hbm;
// Generated Mar 20, 2017 1:36:04 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D001011Id generated by hbm2java
 */
@Embeddable
public class D001011Id implements java.io.Serializable {
	private static final long serialVersionUID = -5817442907251967010L;
	private String stateCode;
	private char rtgsneft;
	private short calYear;
	private byte calMonth;
	private byte day;

	public D001011Id() {
	}

	public D001011Id(String stateCode, char rtgsneft, short calYear, byte calMonth, byte day) {
		this.stateCode = stateCode;
		this.rtgsneft = rtgsneft;
		this.calYear = calYear;
		this.calMonth = calMonth;
		this.day = day;
	}

	@Column(name = "StateCode", nullable = false, length = 4)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "RTGSNEFT", nullable = false, length = 1)
	public char getRtgsneft() {
		return this.rtgsneft;
	}

	public void setRtgsneft(char rtgsneft) {
		this.rtgsneft = rtgsneft;
	}

	@Column(name = "CalYear", nullable = false)
	public short getCalYear() {
		return this.calYear;
	}

	public void setCalYear(short calYear) {
		this.calYear = calYear;
	}

	@Column(name = "CalMonth", nullable = false)
	public byte getCalMonth() {
		return this.calMonth;
	}

	public void setCalMonth(byte calMonth) {
		this.calMonth = calMonth;
	}

	@Column(name = "Day", nullable = false)
	public byte getDay() {
		return this.day;
	}

	public void setDay(byte day) {
		this.day = day;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D001011Id))
			return false;
		D001011Id castOther = (D001011Id) other;

		return ((this.getStateCode() == castOther.getStateCode()) || (this.getStateCode() != null
				&& castOther.getStateCode() != null && this.getStateCode().equals(castOther.getStateCode())))
				&& (this.getRtgsneft() == castOther.getRtgsneft()) && (this.getCalYear() == castOther.getCalYear())
				&& (this.getCalMonth() == castOther.getCalMonth()) && (this.getDay() == castOther.getDay());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStateCode() == null ? 0 : this.getStateCode().hashCode());
		result = 37 * result + this.getRtgsneft();
		result = 37 * result + this.getCalYear();
		result = 37 * result + this.getCalMonth();
		result = 37 * result + this.getDay();
		return result;
	}

}
