package com.sil.hbm;

// default package
// Generated Sep 8, 2016 12:22:49 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D002011 generated by hbm2java
 */
@Entity
@Table(name = "D002011")
@DynamicUpdate
@DynamicInsert
public class D002011 implements java.io.Serializable {
	private static final long serialVersionUID = -9186433592910941525L;
	private String custNo;
	private int usrBrCode;
	private byte status;
	private int autoLogoutAfterSecs;
	private int pwdChgPeriodDays;
	private int minLiPeriodDays;
	private int maxBadLiPerDay;
	private int maxBadLiPerInst;
	private byte pwdNegativesMod;
	private Date nextPwdChgDt;
	private Date lastSysLiDt;
	private Date lastSysLiTime;
	private Date nextSysLiDt;
	private Date badLoginsDt;
	private int noOfBadLogins;
	private int noOfBadLoginsFndTr;
	private int activeInStn;
	private byte activeSrNoInd;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private Date nextTranPwdChgDt;
	private byte tranPinStatus;
//	private String custUsrId;

	public D002011() {
	}

	public D002011(String custNo, int usrBrCode, byte status, int autoLogoutAfterSecs, int pwdChgPeriodDays,
			int minLiPeriodDays, int maxBadLiPerDay, int maxBadLiPerInst, byte pwdNegativesMod, Date nextPwdChgDt,
			Date lastSysLiDt, Date lastSysLiTime, Date nextSysLiDt, Date badLoginsDt, int noOfBadLogins,
			int noOfBadLoginsFndTr, int activeInStn, byte activeSrNoInd, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			Date nextTranPwdChgDt, byte tranPinStatus) {
		this.custNo = custNo;
		this.usrBrCode = usrBrCode;
		this.status = status;
		this.autoLogoutAfterSecs = autoLogoutAfterSecs;
		this.pwdChgPeriodDays = pwdChgPeriodDays;
		this.minLiPeriodDays = minLiPeriodDays;
		this.maxBadLiPerDay = maxBadLiPerDay;
		this.maxBadLiPerInst = maxBadLiPerInst;
		this.pwdNegativesMod = pwdNegativesMod;
		this.nextPwdChgDt = nextPwdChgDt;
		this.lastSysLiDt = lastSysLiDt;
		this.lastSysLiTime = lastSysLiTime;
		this.nextSysLiDt = nextSysLiDt;
		this.badLoginsDt = badLoginsDt;
		this.noOfBadLogins = noOfBadLogins;
		this.noOfBadLoginsFndTr = noOfBadLoginsFndTr;
		this.activeInStn = activeInStn;
		this.activeSrNoInd = activeSrNoInd;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.nextTranPwdChgDt = nextTranPwdChgDt;
		this.tranPinStatus = tranPinStatus;
	}

	public D002011(String custNo, int usrBrCode, byte status, int autoLogoutAfterSecs, int pwdChgPeriodDays,
			int minLiPeriodDays, int maxBadLiPerDay, int maxBadLiPerInst, byte pwdNegativesMod, Date nextPwdChgDt,
			Date lastSysLiDt, Date lastSysLiTime, Date nextSysLiDt, Date badLoginsDt, int noOfBadLogins,
			int noOfBadLoginsFndTr, int activeInStn, byte activeSrNoInd, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			Date nextTranPwdChgDt, byte tranPinStatus, String custUsrId) {
		this.custNo = custNo;
		this.usrBrCode = usrBrCode;
		this.status = status;
		this.autoLogoutAfterSecs = autoLogoutAfterSecs;
		this.pwdChgPeriodDays = pwdChgPeriodDays;
		this.minLiPeriodDays = minLiPeriodDays;
		this.maxBadLiPerDay = maxBadLiPerDay;
		this.maxBadLiPerInst = maxBadLiPerInst;
		this.pwdNegativesMod = pwdNegativesMod;
		this.nextPwdChgDt = nextPwdChgDt;
		this.lastSysLiDt = lastSysLiDt;
		this.lastSysLiTime = lastSysLiTime;
		this.nextSysLiDt = nextSysLiDt;
		this.badLoginsDt = badLoginsDt;
		this.noOfBadLogins = noOfBadLogins;
		this.noOfBadLoginsFndTr = noOfBadLoginsFndTr;
		this.activeInStn = activeInStn;
		this.activeSrNoInd = activeSrNoInd;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.nextTranPwdChgDt = nextTranPwdChgDt;
		this.tranPinStatus = tranPinStatus;
//		this.custUsrId = custUsrId;
	}

	@Id

	@Column(name = "CustNo", unique = true, nullable = false, length = 19)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "UsrBrCode", nullable = false)
	public int getUsrBrCode() {
		return this.usrBrCode;
	}

	public void setUsrBrCode(int usrBrCode) {
		this.usrBrCode = usrBrCode;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "AutoLogoutAfterSecs", nullable = false)
	public int getAutoLogoutAfterSecs() {
		return this.autoLogoutAfterSecs;
	}

	public void setAutoLogoutAfterSecs(int autoLogoutAfterSecs) {
		this.autoLogoutAfterSecs = autoLogoutAfterSecs;
	}

	@Column(name = "PwdChgPeriodDays", nullable = false)
	public int getPwdChgPeriodDays() {
		return this.pwdChgPeriodDays;
	}

	public void setPwdChgPeriodDays(int pwdChgPeriodDays) {
		this.pwdChgPeriodDays = pwdChgPeriodDays;
	}

	@Column(name = "MinLiPeriodDays", nullable = false)
	public int getMinLiPeriodDays() {
		return this.minLiPeriodDays;
	}

	public void setMinLiPeriodDays(int minLiPeriodDays) {
		this.minLiPeriodDays = minLiPeriodDays;
	}

	@Column(name = "MaxBadLiPerDay", nullable = false)
	public int getMaxBadLiPerDay() {
		return this.maxBadLiPerDay;
	}

	public void setMaxBadLiPerDay(int maxBadLiPerDay) {
		this.maxBadLiPerDay = maxBadLiPerDay;
	}

	@Column(name = "MaxBadLiPerInst", nullable = false)
	public int getMaxBadLiPerInst() {
		return this.maxBadLiPerInst;
	}

	public void setMaxBadLiPerInst(int maxBadLiPerInst) {
		this.maxBadLiPerInst = maxBadLiPerInst;
	}

	@Column(name = "PwdNegativesMod", nullable = false)
	public byte getPwdNegativesMod() {
		return this.pwdNegativesMod;
	}

	public void setPwdNegativesMod(byte pwdNegativesMod) {
		this.pwdNegativesMod = pwdNegativesMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextPwdChgDt", nullable = false, length = 23)
	public Date getNextPwdChgDt() {
		return this.nextPwdChgDt;
	}

	public void setNextPwdChgDt(Date nextPwdChgDt) {
		this.nextPwdChgDt = nextPwdChgDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastSysLiDt", nullable = false, length = 23)
	public Date getLastSysLiDt() {
		return this.lastSysLiDt;
	}

	public void setLastSysLiDt(Date lastSysLiDt) {
		this.lastSysLiDt = lastSysLiDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastSysLiTime", nullable = false, length = 23)
	public Date getLastSysLiTime() {
		return this.lastSysLiTime;
	}

	public void setLastSysLiTime(Date lastSysLiTime) {
		this.lastSysLiTime = lastSysLiTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextSysLiDt", nullable = false, length = 23)
	public Date getNextSysLiDt() {
		return this.nextSysLiDt;
	}

	public void setNextSysLiDt(Date nextSysLiDt) {
		this.nextSysLiDt = nextSysLiDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BadLoginsDt", nullable = false, length = 23)
	public Date getBadLoginsDt() {
		return this.badLoginsDt;
	}

	public void setBadLoginsDt(Date badLoginsDt) {
		this.badLoginsDt = badLoginsDt;
	}

	@Column(name = "NoOfBadLogins", nullable = false)
	public int getNoOfBadLogins() {
		return this.noOfBadLogins;
	}

	public void setNoOfBadLogins(int noOfBadLogins) {
		this.noOfBadLogins = noOfBadLogins;
	}

	@Column(name = "NoOfBadLoginsFndTr", nullable = false)
	public int getNoOfBadLoginsFndTr() {
		return this.noOfBadLoginsFndTr;
	}

	public void setNoOfBadLoginsFndTr(int noOfBadLoginsFndTr) {
		this.noOfBadLoginsFndTr = noOfBadLoginsFndTr;
	}

	@Column(name = "ActiveInStn", nullable = false)
	public int getActiveInStn() {
		return this.activeInStn;
	}

	public void setActiveInStn(int activeInStn) {
		this.activeInStn = activeInStn;
	}

	@Column(name = "ActiveSrNoInd", nullable = false)
	public byte getActiveSrNoInd() {
		return this.activeSrNoInd;
	}

	public void setActiveSrNoInd(byte activeSrNoInd) {
		this.activeSrNoInd = activeSrNoInd;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextTranPwdChgDt", nullable = false, length = 23)
	public Date getNextTranPwdChgDt() {
		return this.nextTranPwdChgDt;
	}

	public void setNextTranPwdChgDt(Date nextTranPwdChgDt) {
		this.nextTranPwdChgDt = nextTranPwdChgDt;
	}

	@Column(name = "TranPinStatus", nullable = false)
	public byte getTranPinStatus() {
		return this.tranPinStatus;
	}

	public void setTranPinStatus(byte tranPinStatus) {
		this.tranPinStatus = tranPinStatus;
	}

	/*@Column(name = "CustUsrId", length = 10)
	public String getCustUsrId() {
		return this.custUsrId;
	}

	public void setCustUsrId(String custUsrId) {
		this.custUsrId = custUsrId;
	}*/

}
