package com.sil.hbm;
// Generated 16 Sep, 2016 1:45:49 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D002001 generated by hbm2java
 */
@Entity
@Table(name = "D002001")
@DynamicUpdate
@DynamicInsert
public class D002001 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8622683282894884323L;
	private String usrCode1;
	private int usrCode2;
	private String usrCode3;
	private String usrShortName;
	private String usrName;
	private int usrBrCode;
	private char lgnFrmOthBr;
	private char multiBrAccess;
	private short grpCd;
	private byte status;
	private char scrLockYn;
	private int scrLockAfterSecs;
	private char autoLogoutYn;
	private int autoLogoutAfterSecs;
	private char pwdChgForcedYn;
	private int pwdChgPeriodDays;
	private char minLiFreqForcedYn;
	private int minLiPeriodDays;
	private int maxBadLiPerDay;
	private int maxBadLiPerInst;
	private byte maxRptFiles;
	private char accProfMnu;
	private char accProfNodes;
	private char accProfSysEnt;
	private byte pwdNegativesMod;
	private Date lastPwdChgDt;
	private Date nextPwdChgDt;
	private Date lastSysLiDt;
	private Date nextSysLiDt;
	private Date badLoginsDt;
	private int noOfBadLogins;
	private int activeInStn;
	private byte activeSrNoInd;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private short custAccessLvl;

	public D002001() {
	}

	public D002001(String usrCode1, int usrCode2, String usrCode3, String usrShortName, String usrName, int usrBrCode,
			char lgnFrmOthBr, char multiBrAccess, short grpCd, byte status, char scrLockYn, int scrLockAfterSecs,
			char autoLogoutYn, int autoLogoutAfterSecs, char pwdChgForcedYn, int pwdChgPeriodDays,
			char minLiFreqForcedYn, int minLiPeriodDays, int maxBadLiPerDay, int maxBadLiPerInst, byte maxRptFiles,
			char accProfMnu, char accProfNodes, char accProfSysEnt, byte pwdNegativesMod, Date lastPwdChgDt,
			Date nextPwdChgDt, Date lastSysLiDt, Date nextSysLiDt, Date badLoginsDt, int noOfBadLogins, int activeInStn,
			byte activeSrNoInd, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt,
			int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk,
			int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb,
			short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat,
			byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo, short custAccessLvl) {
		this.usrCode1 = usrCode1;
		this.usrCode2 = usrCode2;
		this.usrCode3 = usrCode3;
		this.usrShortName = usrShortName;
		this.usrName = usrName;
		this.usrBrCode = usrBrCode;
		this.lgnFrmOthBr = lgnFrmOthBr;
		this.multiBrAccess = multiBrAccess;
		this.grpCd = grpCd;
		this.status = status;
		this.scrLockYn = scrLockYn;
		this.scrLockAfterSecs = scrLockAfterSecs;
		this.autoLogoutYn = autoLogoutYn;
		this.autoLogoutAfterSecs = autoLogoutAfterSecs;
		this.pwdChgForcedYn = pwdChgForcedYn;
		this.pwdChgPeriodDays = pwdChgPeriodDays;
		this.minLiFreqForcedYn = minLiFreqForcedYn;
		this.minLiPeriodDays = minLiPeriodDays;
		this.maxBadLiPerDay = maxBadLiPerDay;
		this.maxBadLiPerInst = maxBadLiPerInst;
		this.maxRptFiles = maxRptFiles;
		this.accProfMnu = accProfMnu;
		this.accProfNodes = accProfNodes;
		this.accProfSysEnt = accProfSysEnt;
		this.pwdNegativesMod = pwdNegativesMod;
		this.lastPwdChgDt = lastPwdChgDt;
		this.nextPwdChgDt = nextPwdChgDt;
		this.lastSysLiDt = lastSysLiDt;
		this.nextSysLiDt = nextSysLiDt;
		this.badLoginsDt = badLoginsDt;
		this.noOfBadLogins = noOfBadLogins;
		this.activeInStn = activeInStn;
		this.activeSrNoInd = activeSrNoInd;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.custAccessLvl = custAccessLvl;
	}

	@Id

	@Column(name = "UsrCode1", unique = true, nullable = false, length = 8)
	public String getUsrCode1() {
		return this.usrCode1;
	}

	public void setUsrCode1(String usrCode1) {
		this.usrCode1 = usrCode1;
	}

	@Column(name = "UsrCode2", nullable = false)
	public int getUsrCode2() {
		return this.usrCode2;
	}

	public void setUsrCode2(int usrCode2) {
		this.usrCode2 = usrCode2;
	}

	@Column(name = "UsrCode3", nullable = false, length = 16)
	public String getUsrCode3() {
		return this.usrCode3;
	}

	public void setUsrCode3(String usrCode3) {
		this.usrCode3 = usrCode3;
	}

	@Column(name = "UsrShortName", nullable = false, length = 10)
	public String getUsrShortName() {
		return this.usrShortName;
	}

	public void setUsrShortName(String usrShortName) {
		this.usrShortName = usrShortName;
	}

	@Column(name = "UsrName", nullable = false, length = 35)
	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	@Column(name = "UsrBrCode", nullable = false)
	public int getUsrBrCode() {
		return this.usrBrCode;
	}

	public void setUsrBrCode(int usrBrCode) {
		this.usrBrCode = usrBrCode;
	}

	@Column(name = "LgnFrmOthBr", nullable = false, length = 1)
	public char getLgnFrmOthBr() {
		return this.lgnFrmOthBr;
	}

	public void setLgnFrmOthBr(char lgnFrmOthBr) {
		this.lgnFrmOthBr = lgnFrmOthBr;
	}

	@Column(name = "MultiBrAccess", nullable = false, length = 1)
	public char getMultiBrAccess() {
		return this.multiBrAccess;
	}

	public void setMultiBrAccess(char multiBrAccess) {
		this.multiBrAccess = multiBrAccess;
	}

	@Column(name = "GrpCd", nullable = false)
	public short getGrpCd() {
		return this.grpCd;
	}

	public void setGrpCd(short grpCd) {
		this.grpCd = grpCd;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "ScrLockYN", nullable = false, length = 1)
	public char getScrLockYn() {
		return this.scrLockYn;
	}

	public void setScrLockYn(char scrLockYn) {
		this.scrLockYn = scrLockYn;
	}

	@Column(name = "ScrLockAfterSecs", nullable = false)
	public int getScrLockAfterSecs() {
		return this.scrLockAfterSecs;
	}

	public void setScrLockAfterSecs(int scrLockAfterSecs) {
		this.scrLockAfterSecs = scrLockAfterSecs;
	}

	@Column(name = "AutoLogoutYN", nullable = false, length = 1)
	public char getAutoLogoutYn() {
		return this.autoLogoutYn;
	}

	public void setAutoLogoutYn(char autoLogoutYn) {
		this.autoLogoutYn = autoLogoutYn;
	}

	@Column(name = "AutoLogoutAfterSecs", nullable = false)
	public int getAutoLogoutAfterSecs() {
		return this.autoLogoutAfterSecs;
	}

	public void setAutoLogoutAfterSecs(int autoLogoutAfterSecs) {
		this.autoLogoutAfterSecs = autoLogoutAfterSecs;
	}

	@Column(name = "PwdChgForcedYN", nullable = false, length = 1)
	public char getPwdChgForcedYn() {
		return this.pwdChgForcedYn;
	}

	public void setPwdChgForcedYn(char pwdChgForcedYn) {
		this.pwdChgForcedYn = pwdChgForcedYn;
	}

	@Column(name = "PwdChgPeriodDays", nullable = false)
	public int getPwdChgPeriodDays() {
		return this.pwdChgPeriodDays;
	}

	public void setPwdChgPeriodDays(int pwdChgPeriodDays) {
		this.pwdChgPeriodDays = pwdChgPeriodDays;
	}

	@Column(name = "MinLiFreqForcedYN", nullable = false, length = 1)
	public char getMinLiFreqForcedYn() {
		return this.minLiFreqForcedYn;
	}

	public void setMinLiFreqForcedYn(char minLiFreqForcedYn) {
		this.minLiFreqForcedYn = minLiFreqForcedYn;
	}

	@Column(name = "MinLiPeriodDays", nullable = false)
	public int getMinLiPeriodDays() {
		return this.minLiPeriodDays;
	}

	public void setMinLiPeriodDays(int minLiPeriodDays) {
		this.minLiPeriodDays = minLiPeriodDays;
	}

	@Column(name = "MaxBadLiPerDay", nullable = false)
	public int getMaxBadLiPerDay() {
		return this.maxBadLiPerDay;
	}

	public void setMaxBadLiPerDay(int maxBadLiPerDay) {
		this.maxBadLiPerDay = maxBadLiPerDay;
	}

	@Column(name = "MaxBadLiPerInst", nullable = false)
	public int getMaxBadLiPerInst() {
		return this.maxBadLiPerInst;
	}

	public void setMaxBadLiPerInst(int maxBadLiPerInst) {
		this.maxBadLiPerInst = maxBadLiPerInst;
	}

	@Column(name = "MaxRptFiles", nullable = false)
	public byte getMaxRptFiles() {
		return this.maxRptFiles;
	}

	public void setMaxRptFiles(byte maxRptFiles) {
		this.maxRptFiles = maxRptFiles;
	}

	@Column(name = "AccProfMnu", nullable = false, length = 1)
	public char getAccProfMnu() {
		return this.accProfMnu;
	}

	public void setAccProfMnu(char accProfMnu) {
		this.accProfMnu = accProfMnu;
	}

	@Column(name = "AccProfNodes", nullable = false, length = 1)
	public char getAccProfNodes() {
		return this.accProfNodes;
	}

	public void setAccProfNodes(char accProfNodes) {
		this.accProfNodes = accProfNodes;
	}

	@Column(name = "AccProfSysEnt", nullable = false, length = 1)
	public char getAccProfSysEnt() {
		return this.accProfSysEnt;
	}

	public void setAccProfSysEnt(char accProfSysEnt) {
		this.accProfSysEnt = accProfSysEnt;
	}

	@Column(name = "PwdNegativesMod", nullable = false)
	public byte getPwdNegativesMod() {
		return this.pwdNegativesMod;
	}

	public void setPwdNegativesMod(byte pwdNegativesMod) {
		this.pwdNegativesMod = pwdNegativesMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastPwdChgDt", nullable = false, length = 23)
	public Date getLastPwdChgDt() {
		return this.lastPwdChgDt;
	}

	public void setLastPwdChgDt(Date lastPwdChgDt) {
		this.lastPwdChgDt = lastPwdChgDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextPwdChgDt", nullable = false, length = 23)
	public Date getNextPwdChgDt() {
		return this.nextPwdChgDt;
	}

	public void setNextPwdChgDt(Date nextPwdChgDt) {
		this.nextPwdChgDt = nextPwdChgDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastSysLiDt", nullable = false, length = 23)
	public Date getLastSysLiDt() {
		return this.lastSysLiDt;
	}

	public void setLastSysLiDt(Date lastSysLiDt) {
		this.lastSysLiDt = lastSysLiDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextSysLiDt", nullable = false, length = 23)
	public Date getNextSysLiDt() {
		return this.nextSysLiDt;
	}

	public void setNextSysLiDt(Date nextSysLiDt) {
		this.nextSysLiDt = nextSysLiDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BadLoginsDt", nullable = false, length = 23)
	public Date getBadLoginsDt() {
		return this.badLoginsDt;
	}

	public void setBadLoginsDt(Date badLoginsDt) {
		this.badLoginsDt = badLoginsDt;
	}

	@Column(name = "NoOfBadLogins", nullable = false)
	public int getNoOfBadLogins() {
		return this.noOfBadLogins;
	}

	public void setNoOfBadLogins(int noOfBadLogins) {
		this.noOfBadLogins = noOfBadLogins;
	}

	@Column(name = "ActiveInStn", nullable = false)
	public int getActiveInStn() {
		return this.activeInStn;
	}

	public void setActiveInStn(int activeInStn) {
		this.activeInStn = activeInStn;
	}

	@Column(name = "ActiveSrNoInd", nullable = false)
	public byte getActiveSrNoInd() {
		return this.activeSrNoInd;
	}

	public void setActiveSrNoInd(byte activeSrNoInd) {
		this.activeSrNoInd = activeSrNoInd;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "CustAccessLvl", nullable = false)
	public short getCustAccessLvl() {
		return this.custAccessLvl;
	}

	public void setCustAccessLvl(short custAccessLvl) {
		this.custAccessLvl = custAccessLvl;
	}

}
