package com.sil.hbm;
// Generated Mar 7, 2018 6:39:14 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009037 generated by hbm2java
 */
@Entity
@Table(name = "D009037")
@DynamicUpdate
@DynamicInsert
public class D009037 implements java.io.Serializable {

	private static final long serialVersionUID = 1089957200478647976L;
	private D009037Id id;
	private char minBalChgYn;
	private char chqBookYn;
	private char chqBookChgYn;
	private char tdsYn;
	private byte tdsReasonCd;
	private char inspChgsYn;
	private char dematYn;
	private char serviceChgsYn;
	private char atmYn;
	private char freqStmtOfAcctYn;
	private char passBookChgYn;
	private char trfrAcctYn;
	private char plrLinkYn;
	private char inspecYn;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private char folioChgsYn;
	private char dpYn;
	private char alChgDpYn;

	public D009037() {
	}

	public D009037(D009037Id id, char minBalChgYn, char chqBookYn, char chqBookChgYn, char tdsYn, byte tdsReasonCd,
			char inspChgsYn, char dematYn, char serviceChgsYn, char atmYn, char freqStmtOfAcctYn, char passBookChgYn,
			char trfrAcctYn, char plrLinkYn, char inspecYn, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			char folioChgsYn, char dpYn, char alChgDpYn) {
		this.id = id;
		this.minBalChgYn = minBalChgYn;
		this.chqBookYn = chqBookYn;
		this.chqBookChgYn = chqBookChgYn;
		this.tdsYn = tdsYn;
		this.tdsReasonCd = tdsReasonCd;
		this.inspChgsYn = inspChgsYn;
		this.dematYn = dematYn;
		this.serviceChgsYn = serviceChgsYn;
		this.atmYn = atmYn;
		this.freqStmtOfAcctYn = freqStmtOfAcctYn;
		this.passBookChgYn = passBookChgYn;
		this.trfrAcctYn = trfrAcctYn;
		this.plrLinkYn = plrLinkYn;
		this.inspecYn = inspecYn;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.folioChgsYn = folioChgsYn;
		this.dpYn = dpYn;
		this.alChgDpYn = alChgDpYn;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdCd", column = @Column(name = "PrdCd", nullable = false, length = 8)) })
	public D009037Id getId() {
		return this.id;
	}

	public void setId(D009037Id id) {
		this.id = id;
	}

	@Column(name = "MinBalChgYN", nullable = false, length = 1)
	public char getMinBalChgYn() {
		return this.minBalChgYn;
	}

	public void setMinBalChgYn(char minBalChgYn) {
		this.minBalChgYn = minBalChgYn;
	}

	@Column(name = "ChqBookYN", nullable = false, length = 1)
	public char getChqBookYn() {
		return this.chqBookYn;
	}

	public void setChqBookYn(char chqBookYn) {
		this.chqBookYn = chqBookYn;
	}

	@Column(name = "ChqBookChgYN", nullable = false, length = 1)
	public char getChqBookChgYn() {
		return this.chqBookChgYn;
	}

	public void setChqBookChgYn(char chqBookChgYn) {
		this.chqBookChgYn = chqBookChgYn;
	}

	@Column(name = "TdsYN", nullable = false, length = 1)
	public char getTdsYn() {
		return this.tdsYn;
	}

	public void setTdsYn(char tdsYn) {
		this.tdsYn = tdsYn;
	}

	@Column(name = "TdsReasonCd", nullable = false)
	public byte getTdsReasonCd() {
		return this.tdsReasonCd;
	}

	public void setTdsReasonCd(byte tdsReasonCd) {
		this.tdsReasonCd = tdsReasonCd;
	}

	@Column(name = "InspChgsYN", nullable = false, length = 1)
	public char getInspChgsYn() {
		return this.inspChgsYn;
	}

	public void setInspChgsYn(char inspChgsYn) {
		this.inspChgsYn = inspChgsYn;
	}

	@Column(name = "DematYN", nullable = false, length = 1)
	public char getDematYn() {
		return this.dematYn;
	}

	public void setDematYn(char dematYn) {
		this.dematYn = dematYn;
	}

	@Column(name = "ServiceChgsYN", nullable = false, length = 1)
	public char getServiceChgsYn() {
		return this.serviceChgsYn;
	}

	public void setServiceChgsYn(char serviceChgsYn) {
		this.serviceChgsYn = serviceChgsYn;
	}

	@Column(name = "AtmYN", nullable = false, length = 1)
	public char getAtmYn() {
		return this.atmYn;
	}

	public void setAtmYn(char atmYn) {
		this.atmYn = atmYn;
	}

	@Column(name = "FreqStmtOfAcctYN", nullable = false, length = 1)
	public char getFreqStmtOfAcctYn() {
		return this.freqStmtOfAcctYn;
	}

	public void setFreqStmtOfAcctYn(char freqStmtOfAcctYn) {
		this.freqStmtOfAcctYn = freqStmtOfAcctYn;
	}

	@Column(name = "PassBookChgYN", nullable = false, length = 1)
	public char getPassBookChgYn() {
		return this.passBookChgYn;
	}

	public void setPassBookChgYn(char passBookChgYn) {
		this.passBookChgYn = passBookChgYn;
	}

	@Column(name = "TrfrAcctYN", nullable = false, length = 1)
	public char getTrfrAcctYn() {
		return this.trfrAcctYn;
	}

	public void setTrfrAcctYn(char trfrAcctYn) {
		this.trfrAcctYn = trfrAcctYn;
	}

	@Column(name = "PlrLinkYN", nullable = false, length = 1)
	public char getPlrLinkYn() {
		return this.plrLinkYn;
	}

	public void setPlrLinkYn(char plrLinkYn) {
		this.plrLinkYn = plrLinkYn;
	}

	@Column(name = "InspecYN", nullable = false, length = 1)
	public char getInspecYn() {
		return this.inspecYn;
	}

	public void setInspecYn(char inspecYn) {
		this.inspecYn = inspecYn;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "FolioChgsYN", nullable = false, length = 1)
	public char getFolioChgsYn() {
		return this.folioChgsYn;
	}

	public void setFolioChgsYn(char folioChgsYn) {
		this.folioChgsYn = folioChgsYn;
	}

	@Column(name = "DpYN", nullable = false, length = 1)
	public char getDpYn() {
		return this.dpYn;
	}

	public void setDpYn(char dpYn) {
		this.dpYn = dpYn;
	}

	@Column(name = "AlChgDpYN", nullable = false, length = 1)
	public char getAlChgDpYn() {
		return this.alChgDpYn;
	}

	public void setAlChgDpYn(char alChgDpYn) {
		this.alChgDpYn = alChgDpYn;
	}

}
