package com.sil.hbm;
// Generated 14 Sep, 2016 5:56:05 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009021 generated by hbm2java
 */
@Entity
@Table(name = "D009021")
@DynamicUpdate
@DynamicInsert
public class D009021 implements java.io.Serializable {
	private static final long serialVersionUID = 4858157721371532871L;
	private D009021Id id;
	private String name;
	private char custInt;
	private short moduleType;
	private char autoGenAcct;
	private char autoGenSubAcct;
	private char multiCurYn;
	private char multiCurAcctYn;
	private String curCd;
	private String condAssetGl;
	private String condLiabGl;
	private Date dateOpened;
	private Date dateClosed;
	private Date dateReOpened;
	private Date dateSealed;
	private byte acctStat;
	private char assetLiab;
	private char finNonFin;
	private char acctOpenLevel;
	private char reconType;
	private Date implDate;
	private char implLevelVp;
	private Date lastDrDate;
	private Date lastCrDate;
	private double minBal;
	private double minBalNonChq;
	private double lcyBal;
	private double fcyBal;
	private char cashDrTrnYn;
	private char cashCrTrnYn;
	private char trfrDrTrnYn;
	private char trfrCrTrnYn;
	private char clrgDrTrnYn;
	private char clrgCrTrnYn;
	private char accuredYn;
	private Date accuredUpToDate;
	private String accDebitAcctId;
	private String accCreditAcctId;
	private double accAmount;
	private byte almMain;
	private byte almSub;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;

	public D009021() {
	}

	public D009021(D009021Id id, String name, char custInt, short moduleType, char autoGenAcct, char autoGenSubAcct,
			char multiCurYn, char multiCurAcctYn, String curCd, String condAssetGl, String condLiabGl, Date dateOpened,
			Date dateClosed, Date dateReOpened, Date dateSealed, byte acctStat, char assetLiab, char finNonFin,
			char acctOpenLevel, char reconType, Date implDate, char implLevelVp, Date lastDrDate, Date lastCrDate,
			double minBal, double minBalNonChq, double lcyBal, double fcyBal, char cashDrTrnYn, char cashCrTrnYn,
			char trfrDrTrnYn, char trfrCrTrnYn, char clrgDrTrnYn, char clrgCrTrnYn, char accuredYn,
			Date accuredUpToDate, String accDebitAcctId, String accCreditAcctId, double accAmount, byte almMain,
			byte almSub, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk,
			int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb,
			short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs,
			Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone,
			byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.id = id;
		this.name = name;
		this.custInt = custInt;
		this.moduleType = moduleType;
		this.autoGenAcct = autoGenAcct;
		this.autoGenSubAcct = autoGenSubAcct;
		this.multiCurYn = multiCurYn;
		this.multiCurAcctYn = multiCurAcctYn;
		this.curCd = curCd;
		this.condAssetGl = condAssetGl;
		this.condLiabGl = condLiabGl;
		this.dateOpened = dateOpened;
		this.dateClosed = dateClosed;
		this.dateReOpened = dateReOpened;
		this.dateSealed = dateSealed;
		this.acctStat = acctStat;
		this.assetLiab = assetLiab;
		this.finNonFin = finNonFin;
		this.acctOpenLevel = acctOpenLevel;
		this.reconType = reconType;
		this.implDate = implDate;
		this.implLevelVp = implLevelVp;
		this.lastDrDate = lastDrDate;
		this.lastCrDate = lastCrDate;
		this.minBal = minBal;
		this.minBalNonChq = minBalNonChq;
		this.lcyBal = lcyBal;
		this.fcyBal = fcyBal;
		this.cashDrTrnYn = cashDrTrnYn;
		this.cashCrTrnYn = cashCrTrnYn;
		this.trfrDrTrnYn = trfrDrTrnYn;
		this.trfrCrTrnYn = trfrCrTrnYn;
		this.clrgDrTrnYn = clrgDrTrnYn;
		this.clrgCrTrnYn = clrgCrTrnYn;
		this.accuredYn = accuredYn;
		this.accuredUpToDate = accuredUpToDate;
		this.accDebitAcctId = accDebitAcctId;
		this.accCreditAcctId = accCreditAcctId;
		this.accAmount = accAmount;
		this.almMain = almMain;
		this.almSub = almSub;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdCd", column = @Column(name = "PrdCd", nullable = false, length = 8)) })
	public D009021Id getId() {
		return this.id;
	}

	public void setId(D009021Id id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CustInt", nullable = false, length = 1)
	public char getCustInt() {
		return this.custInt;
	}

	public void setCustInt(char custInt) {
		this.custInt = custInt;
	}

	@Column(name = "ModuleType", nullable = false)
	public short getModuleType() {
		return this.moduleType;
	}

	public void setModuleType(short moduleType) {
		this.moduleType = moduleType;
	}

	@Column(name = "AutoGenAcct", nullable = false, length = 1)
	public char getAutoGenAcct() {
		return this.autoGenAcct;
	}

	public void setAutoGenAcct(char autoGenAcct) {
		this.autoGenAcct = autoGenAcct;
	}

	@Column(name = "AutoGenSubAcct", nullable = false, length = 1)
	public char getAutoGenSubAcct() {
		return this.autoGenSubAcct;
	}

	public void setAutoGenSubAcct(char autoGenSubAcct) {
		this.autoGenSubAcct = autoGenSubAcct;
	}

	@Column(name = "MultiCurYN", nullable = false, length = 1)
	public char getMultiCurYn() {
		return this.multiCurYn;
	}

	public void setMultiCurYn(char multiCurYn) {
		this.multiCurYn = multiCurYn;
	}

	@Column(name = "MultiCurAcctYN", nullable = false, length = 1)
	public char getMultiCurAcctYn() {
		return this.multiCurAcctYn;
	}

	public void setMultiCurAcctYn(char multiCurAcctYn) {
		this.multiCurAcctYn = multiCurAcctYn;
	}

	@Column(name = "CurCd", nullable = false, length = 3)
	public String getCurCd() {
		return this.curCd;
	}

	public void setCurCd(String curCd) {
		this.curCd = curCd;
	}

	@Column(name = "CondAssetGl", nullable = false, length = 8)
	public String getCondAssetGl() {
		return this.condAssetGl;
	}

	public void setCondAssetGl(String condAssetGl) {
		this.condAssetGl = condAssetGl;
	}

	@Column(name = "CondLiabGl", nullable = false, length = 8)
	public String getCondLiabGl() {
		return this.condLiabGl;
	}

	public void setCondLiabGl(String condLiabGl) {
		this.condLiabGl = condLiabGl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateOpened", nullable = false, length = 23)
	public Date getDateOpened() {
		return this.dateOpened;
	}

	public void setDateOpened(Date dateOpened) {
		this.dateOpened = dateOpened;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateClosed", nullable = false, length = 23)
	public Date getDateClosed() {
		return this.dateClosed;
	}

	public void setDateClosed(Date dateClosed) {
		this.dateClosed = dateClosed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateReOpened", nullable = false, length = 23)
	public Date getDateReOpened() {
		return this.dateReOpened;
	}

	public void setDateReOpened(Date dateReOpened) {
		this.dateReOpened = dateReOpened;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSealed", nullable = false, length = 23)
	public Date getDateSealed() {
		return this.dateSealed;
	}

	public void setDateSealed(Date dateSealed) {
		this.dateSealed = dateSealed;
	}

	@Column(name = "AcctStat", nullable = false)
	public byte getAcctStat() {
		return this.acctStat;
	}

	public void setAcctStat(byte acctStat) {
		this.acctStat = acctStat;
	}

	@Column(name = "AssetLiab", nullable = false, length = 1)
	public char getAssetLiab() {
		return this.assetLiab;
	}

	public void setAssetLiab(char assetLiab) {
		this.assetLiab = assetLiab;
	}

	@Column(name = "FinNonFin", nullable = false, length = 1)
	public char getFinNonFin() {
		return this.finNonFin;
	}

	public void setFinNonFin(char finNonFin) {
		this.finNonFin = finNonFin;
	}

	@Column(name = "AcctOpenLevel", nullable = false, length = 1)
	public char getAcctOpenLevel() {
		return this.acctOpenLevel;
	}

	public void setAcctOpenLevel(char acctOpenLevel) {
		this.acctOpenLevel = acctOpenLevel;
	}

	@Column(name = "ReconType", nullable = false, length = 1)
	public char getReconType() {
		return this.reconType;
	}

	public void setReconType(char reconType) {
		this.reconType = reconType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ImplDate", nullable = false, length = 23)
	public Date getImplDate() {
		return this.implDate;
	}

	public void setImplDate(Date implDate) {
		this.implDate = implDate;
	}

	@Column(name = "ImplLevelVP", nullable = false, length = 1)
	public char getImplLevelVp() {
		return this.implLevelVp;
	}

	public void setImplLevelVp(char implLevelVp) {
		this.implLevelVp = implLevelVp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastDrDate", nullable = false, length = 23)
	public Date getLastDrDate() {
		return this.lastDrDate;
	}

	public void setLastDrDate(Date lastDrDate) {
		this.lastDrDate = lastDrDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastCrDate", nullable = false, length = 23)
	public Date getLastCrDate() {
		return this.lastCrDate;
	}

	public void setLastCrDate(Date lastCrDate) {
		this.lastCrDate = lastCrDate;
	}

	@Column(name = "MinBal", nullable = false, precision = 53, scale = 0)
	public double getMinBal() {
		return this.minBal;
	}

	public void setMinBal(double minBal) {
		this.minBal = minBal;
	}

	@Column(name = "MinBalNonChq", nullable = false, precision = 53, scale = 0)
	public double getMinBalNonChq() {
		return this.minBalNonChq;
	}

	public void setMinBalNonChq(double minBalNonChq) {
		this.minBalNonChq = minBalNonChq;
	}

	@Column(name = "LcyBal", nullable = false, precision = 53, scale = 0)
	public double getLcyBal() {
		return this.lcyBal;
	}

	public void setLcyBal(double lcyBal) {
		this.lcyBal = lcyBal;
	}

	@Column(name = "FcyBal", nullable = false, precision = 53, scale = 0)
	public double getFcyBal() {
		return this.fcyBal;
	}

	public void setFcyBal(double fcyBal) {
		this.fcyBal = fcyBal;
	}

	@Column(name = "CashDrTrnYN", nullable = false, length = 1)
	public char getCashDrTrnYn() {
		return this.cashDrTrnYn;
	}

	public void setCashDrTrnYn(char cashDrTrnYn) {
		this.cashDrTrnYn = cashDrTrnYn;
	}

	@Column(name = "CashCrTrnYN", nullable = false, length = 1)
	public char getCashCrTrnYn() {
		return this.cashCrTrnYn;
	}

	public void setCashCrTrnYn(char cashCrTrnYn) {
		this.cashCrTrnYn = cashCrTrnYn;
	}

	@Column(name = "TrfrDrTrnYN", nullable = false, length = 1)
	public char getTrfrDrTrnYn() {
		return this.trfrDrTrnYn;
	}

	public void setTrfrDrTrnYn(char trfrDrTrnYn) {
		this.trfrDrTrnYn = trfrDrTrnYn;
	}

	@Column(name = "TrfrCrTrnYN", nullable = false, length = 1)
	public char getTrfrCrTrnYn() {
		return this.trfrCrTrnYn;
	}

	public void setTrfrCrTrnYn(char trfrCrTrnYn) {
		this.trfrCrTrnYn = trfrCrTrnYn;
	}

	@Column(name = "ClrgDrTrnYN", nullable = false, length = 1)
	public char getClrgDrTrnYn() {
		return this.clrgDrTrnYn;
	}

	public void setClrgDrTrnYn(char clrgDrTrnYn) {
		this.clrgDrTrnYn = clrgDrTrnYn;
	}

	@Column(name = "ClrgCrTrnYN", nullable = false, length = 1)
	public char getClrgCrTrnYn() {
		return this.clrgCrTrnYn;
	}

	public void setClrgCrTrnYn(char clrgCrTrnYn) {
		this.clrgCrTrnYn = clrgCrTrnYn;
	}

	@Column(name = "AccuredYN", nullable = false, length = 1)
	public char getAccuredYn() {
		return this.accuredYn;
	}

	public void setAccuredYn(char accuredYn) {
		this.accuredYn = accuredYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AccuredUpToDate", nullable = false, length = 23)
	public Date getAccuredUpToDate() {
		return this.accuredUpToDate;
	}

	public void setAccuredUpToDate(Date accuredUpToDate) {
		this.accuredUpToDate = accuredUpToDate;
	}

	@Column(name = "AccDebitAcctID", nullable = false, length = 32)
	public String getAccDebitAcctId() {
		return this.accDebitAcctId;
	}

	public void setAccDebitAcctId(String accDebitAcctId) {
		this.accDebitAcctId = accDebitAcctId;
	}

	@Column(name = "AccCreditAcctID", nullable = false, length = 32)
	public String getAccCreditAcctId() {
		return this.accCreditAcctId;
	}

	public void setAccCreditAcctId(String accCreditAcctId) {
		this.accCreditAcctId = accCreditAcctId;
	}

	@Column(name = "AccAmount", nullable = false, precision = 53, scale = 0)
	public double getAccAmount() {
		return this.accAmount;
	}

	public void setAccAmount(double accAmount) {
		this.accAmount = accAmount;
	}

	@Column(name = "AlmMain", nullable = false)
	public byte getAlmMain() {
		return this.almMain;
	}

	public void setAlmMain(byte almMain) {
		this.almMain = almMain;
	}

	@Column(name = "AlmSub", nullable = false)
	public byte getAlmSub() {
		return this.almSub;
	}

	public void setAlmSub(byte almSub) {
		this.almSub = almSub;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Override
	public String toString() {
		return "D009021 [id=" + id + ", name=" + name + ", custInt=" + custInt + ", moduleType=" + moduleType
				+ ", autoGenAcct=" + autoGenAcct + ", autoGenSubAcct=" + autoGenSubAcct + ", multiCurYn=" + multiCurYn
				+ ", multiCurAcctYn=" + multiCurAcctYn + ", curCd=" + curCd + ", condAssetGl=" + condAssetGl
				+ ", condLiabGl=" + condLiabGl + ", dateOpened=" + dateOpened + ", dateClosed=" + dateClosed
				+ ", dateReOpened=" + dateReOpened + ", dateSealed=" + dateSealed + ", acctStat=" + acctStat
				+ ", assetLiab=" + assetLiab + ", finNonFin=" + finNonFin + ", acctOpenLevel=" + acctOpenLevel
				+ ", reconType=" + reconType + ", implDate=" + implDate + ", implLevelVp=" + implLevelVp
				+ ", lastDrDate=" + lastDrDate + ", lastCrDate=" + lastCrDate + ", minBal=" + minBal + ", minBalNonChq="
				+ minBalNonChq + ", lcyBal=" + lcyBal + ", fcyBal=" + fcyBal + ", cashDrTrnYn=" + cashDrTrnYn
				+ ", cashCrTrnYn=" + cashCrTrnYn + ", trfrDrTrnYn=" + trfrDrTrnYn + ", trfrCrTrnYn=" + trfrCrTrnYn
				+ ", clrgDrTrnYn=" + clrgDrTrnYn + ", clrgCrTrnYn=" + clrgCrTrnYn + ", accuredYn=" + accuredYn
				+ ", accuredUpToDate=" + accuredUpToDate + ", accDebitAcctId=" + accDebitAcctId + ", accCreditAcctId="
				+ accCreditAcctId + ", accAmount=" + accAmount + ", almMain=" + almMain + ", almSub=" + almSub
				+ ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb=" + dbtrAddMb + ", dbtrAddMs=" + dbtrAddMs + ", dbtrAddMd="
				+ dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt + ", dbtrAddCk=" + dbtrAddCk + ", dbtrAddCb=" + dbtrAddCb
				+ ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd=" + dbtrAddCd + ", dbtrAddCt=" + dbtrAddCt + ", dbtrLupdMk="
				+ dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb + ", dbtrLupdMs=" + dbtrLupdMs + ", dbtrLupdMd="
				+ dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt + ", dbtrLupdCk=" + dbtrLupdCk + ", dbtrLupdCb="
				+ dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs + ", dbtrLupdCd=" + dbtrLupdCd + ", dbtrLupdCt="
				+ dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone + ", dbtrRecStat=" + dbtrRecStat + ", dbtrAuthDone="
				+ dbtrAuthDone + ", dbtrAuthNeeded=" + dbtrAuthNeeded + ", dbtrUpdtChkId=" + dbtrUpdtChkId
				+ ", dbtrLhisTrnNo=" + dbtrLhisTrnNo + "]";
	}

	
}
