package com.sil.hbm;
// Generated Nov 18, 2016 3:14:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009142 generated by hbm2java
 */
@Entity
@Table(name = "D009142")
@DynamicUpdate
@DynamicInsert
public class D009142 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5043470498268451740L;
	private D009142Id id;
	private double disbursedAmt;
	private Date instlStartDate;
	private double instlAmt;
	private double instlIntComp;
	private short mlDbtrBijIdx;
	private short mlDbtrUaeIdx;

	public D009142() {
	}

	public D009142(D009142Id id, double disbursedAmt, Date instlStartDate, double instlAmt, double instlIntComp,
			short mlDbtrBijIdx, short mlDbtrUaeIdx) {
		this.id = id;
		this.disbursedAmt = disbursedAmt;
		this.instlStartDate = instlStartDate;
		this.instlAmt = instlAmt;
		this.instlIntComp = instlIntComp;
		this.mlDbtrBijIdx = mlDbtrBijIdx;
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "effFromDate", column = @Column(name = "EffFromDate", nullable = false, length = 23)),
			@AttributeOverride(name = "disbursedDate", column = @Column(name = "DisbursedDate", nullable = false, length = 23)) })
	public D009142Id getId() {
		return this.id;
	}

	public void setId(D009142Id id) {
		this.id = id;
	}

	@Column(name = "DisbursedAmt", nullable = false, precision = 53, scale = 0)
	public double getDisbursedAmt() {
		return this.disbursedAmt;
	}

	public void setDisbursedAmt(double disbursedAmt) {
		this.disbursedAmt = disbursedAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InstlStartDate", nullable = false, length = 23)
	public Date getInstlStartDate() {
		return this.instlStartDate;
	}

	public void setInstlStartDate(Date instlStartDate) {
		this.instlStartDate = instlStartDate;
	}

	@Column(name = "InstlAmt", nullable = false, precision = 53, scale = 0)
	public double getInstlAmt() {
		return this.instlAmt;
	}

	public void setInstlAmt(double instlAmt) {
		this.instlAmt = instlAmt;
	}

	@Column(name = "InstlIntComp", nullable = false, precision = 53, scale = 0)
	public double getInstlIntComp() {
		return this.instlIntComp;
	}

	public void setInstlIntComp(double instlIntComp) {
		this.instlIntComp = instlIntComp;
	}

	@Column(name = "MlDbtrBijIdx", nullable = false)
	public short getMlDbtrBijIdx() {
		return this.mlDbtrBijIdx;
	}

	public void setMlDbtrBijIdx(short mlDbtrBijIdx) {
		this.mlDbtrBijIdx = mlDbtrBijIdx;
	}

	@Column(name = "MlDbtrUaeIdx", nullable = false)
	public short getMlDbtrUaeIdx() {
		return this.mlDbtrUaeIdx;
	}

	public void setMlDbtrUaeIdx(short mlDbtrUaeIdx) {
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

}
