package com.sil.hbm;
// Generated Mar 10, 2018 4:06:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009122 generated by hbm2java
 */
@Entity
@Table(name = "D009122")
@DynamicUpdate
@DynamicInsert
public class D009122 implements java.io.Serializable {

	private static final long serialVersionUID = -7394938009109570509L;
	private D009122Id id;
	private byte memberType;
	private int memberNo;
	private char minBalChgYn;
	private char chqBookChgYn;
	private char tdsYn;
	private short tdsReasonCd;
	private char inspChgsYn;
	private char dematYn;
	private String dematNo;
	private char serviceChgsYn;
	private char atmYn;
	private char freqStmtOfAcctYn;
	private Date lastPrintDt;
	private char passBookChgYn;
	private char trFrAcctYn;
	private char inspecYn;
	private byte graceDp;
	private String payInAcctId;
	private short bicCode;
	private short sicCode;
	private char folioChgsYn;
	private byte stmtType;
	private char inDirRelation;
	private byte dirRelation;
	private byte emailDayInFreq;
	private short memReasonCd;
	private char todYn;
	private char writeOffYn;
	private char rebateYn;
	private byte acctOpnType;
	private String empId;
	private String empName;
	private char pensionAcyn;
	private String accountType;
	private String businessCat;
	private String businessInd;
	private String gstInNo;

	public D009122() {
	}

	public D009122(D009122Id id, byte memberType, int memberNo, char minBalChgYn, char chqBookChgYn, char tdsYn,
			short tdsReasonCd, char inspChgsYn, char dematYn, String dematNo, char serviceChgsYn, char atmYn,
			char freqStmtOfAcctYn, Date lastPrintDt, char passBookChgYn, char trFrAcctYn, char inspecYn, byte graceDp,
			String payInAcctId, short bicCode, short sicCode, char folioChgsYn, byte stmtType, char inDirRelation,
			byte dirRelation, byte emailDayInFreq, short memReasonCd, char todYn, char writeOffYn, char rebateYn,
			byte acctOpnType, String empId, String empName, char pensionAcyn, String accountType, String businessCat,
			String businessInd,String gstInNo) {
		this.id = id;
		this.memberType = memberType;
		this.memberNo = memberNo;
		this.minBalChgYn = minBalChgYn;
		this.chqBookChgYn = chqBookChgYn;
		this.tdsYn = tdsYn;
		this.tdsReasonCd = tdsReasonCd;
		this.inspChgsYn = inspChgsYn;
		this.dematYn = dematYn;
		this.dematNo = dematNo;
		this.serviceChgsYn = serviceChgsYn;
		this.atmYn = atmYn;
		this.freqStmtOfAcctYn = freqStmtOfAcctYn;
		this.lastPrintDt = lastPrintDt;
		this.passBookChgYn = passBookChgYn;
		this.trFrAcctYn = trFrAcctYn;
		this.inspecYn = inspecYn;
		this.graceDp = graceDp;
		this.payInAcctId = payInAcctId;
		this.bicCode = bicCode;
		this.sicCode = sicCode;
		this.folioChgsYn = folioChgsYn;
		this.stmtType = stmtType;
		this.inDirRelation = inDirRelation;
		this.dirRelation = dirRelation;
		this.emailDayInFreq = emailDayInFreq;
		this.memReasonCd = memReasonCd;
		this.todYn = todYn;
		this.writeOffYn = writeOffYn;
		this.rebateYn = rebateYn;
		this.acctOpnType = acctOpnType;
		this.empId = empId;
		this.empName = empName;
		this.pensionAcyn = pensionAcyn;
		this.accountType = accountType;
		this.businessCat = businessCat;
		this.businessInd = businessInd;
		this.gstInNo = gstInNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)) })
	public D009122Id getId() {
		return this.id;
	}

	public void setId(D009122Id id) {
		this.id = id;
	}

	@Column(name = "MemberType", nullable = false)
	public byte getMemberType() {
		return this.memberType;
	}

	public void setMemberType(byte memberType) {
		this.memberType = memberType;
	}

	@Column(name = "MemberNo", nullable = false)
	public int getMemberNo() {
		return this.memberNo;
	}

	public void setMemberNo(int memberNo) {
		this.memberNo = memberNo;
	}

	@Column(name = "MinBalChgYN", nullable = false, length = 1)
	public char getMinBalChgYn() {
		return this.minBalChgYn;
	}

	public void setMinBalChgYn(char minBalChgYn) {
		this.minBalChgYn = minBalChgYn;
	}

	@Column(name = "ChqBookChgYN", nullable = false, length = 1)
	public char getChqBookChgYn() {
		return this.chqBookChgYn;
	}

	public void setChqBookChgYn(char chqBookChgYn) {
		this.chqBookChgYn = chqBookChgYn;
	}

	@Column(name = "TdsYN", nullable = false, length = 1)
	public char getTdsYn() {
		return this.tdsYn;
	}

	public void setTdsYn(char tdsYn) {
		this.tdsYn = tdsYn;
	}

	@Column(name = "TdsReasonCd", nullable = false)
	public short getTdsReasonCd() {
		return this.tdsReasonCd;
	}

	public void setTdsReasonCd(short tdsReasonCd) {
		this.tdsReasonCd = tdsReasonCd;
	}

	@Column(name = "InspChgsYN", nullable = false, length = 1)
	public char getInspChgsYn() {
		return this.inspChgsYn;
	}

	public void setInspChgsYn(char inspChgsYn) {
		this.inspChgsYn = inspChgsYn;
	}

	@Column(name = "DematYN", nullable = false, length = 1)
	public char getDematYn() {
		return this.dematYn;
	}

	public void setDematYn(char dematYn) {
		this.dematYn = dematYn;
	}

	@Column(name = "DematNo", nullable = false, length = 16)
	public String getDematNo() {
		return this.dematNo;
	}

	public void setDematNo(String dematNo) {
		this.dematNo = dematNo;
	}

	@Column(name = "ServiceChgsYN", nullable = false, length = 1)
	public char getServiceChgsYn() {
		return this.serviceChgsYn;
	}

	public void setServiceChgsYn(char serviceChgsYn) {
		this.serviceChgsYn = serviceChgsYn;
	}

	@Column(name = "AtmYN", nullable = false, length = 1)
	public char getAtmYn() {
		return this.atmYn;
	}

	public void setAtmYn(char atmYn) {
		this.atmYn = atmYn;
	}

	@Column(name = "FreqStmtOfAcctYN", nullable = false, length = 1)
	public char getFreqStmtOfAcctYn() {
		return this.freqStmtOfAcctYn;
	}

	public void setFreqStmtOfAcctYn(char freqStmtOfAcctYn) {
		this.freqStmtOfAcctYn = freqStmtOfAcctYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastPrintDt", nullable = false, length = 23)
	public Date getLastPrintDt() {
		return this.lastPrintDt;
	}

	public void setLastPrintDt(Date lastPrintDt) {
		this.lastPrintDt = lastPrintDt;
	}

	@Column(name = "PassBookChgYN", nullable = false, length = 1)
	public char getPassBookChgYn() {
		return this.passBookChgYn;
	}

	public void setPassBookChgYn(char passBookChgYn) {
		this.passBookChgYn = passBookChgYn;
	}

	@Column(name = "TrFrAcctYN", nullable = false, length = 1)
	public char getTrFrAcctYn() {
		return this.trFrAcctYn;
	}

	public void setTrFrAcctYn(char trFrAcctYn) {
		this.trFrAcctYn = trFrAcctYn;
	}

	@Column(name = "InspecYN", nullable = false, length = 1)
	public char getInspecYn() {
		return this.inspecYn;
	}

	public void setInspecYn(char inspecYn) {
		this.inspecYn = inspecYn;
	}

	@Column(name = "GraceDp", nullable = false)
	public byte getGraceDp() {
		return this.graceDp;
	}

	public void setGraceDp(byte graceDp) {
		this.graceDp = graceDp;
	}

	@Column(name = "PayInAcctId", nullable = false, length = 32)
	public String getPayInAcctId() {
		return this.payInAcctId;
	}

	public void setPayInAcctId(String payInAcctId) {
		this.payInAcctId = payInAcctId;
	}

	@Column(name = "BicCode", nullable = false)
	public short getBicCode() {
		return this.bicCode;
	}

	public void setBicCode(short bicCode) {
		this.bicCode = bicCode;
	}

	@Column(name = "SicCode", nullable = false)
	public short getSicCode() {
		return this.sicCode;
	}

	public void setSicCode(short sicCode) {
		this.sicCode = sicCode;
	}

	@Column(name = "FolioChgsYN", nullable = false, length = 1)
	public char getFolioChgsYn() {
		return this.folioChgsYn;
	}

	public void setFolioChgsYn(char folioChgsYn) {
		this.folioChgsYn = folioChgsYn;
	}

	@Column(name = "StmtType", nullable = false)
	public byte getStmtType() {
		return this.stmtType;
	}

	public void setStmtType(byte stmtType) {
		this.stmtType = stmtType;
	}

	@Column(name = "InDirRelation", nullable = false, length = 1)
	public char getInDirRelation() {
		return this.inDirRelation;
	}

	public void setInDirRelation(char inDirRelation) {
		this.inDirRelation = inDirRelation;
	}

	@Column(name = "DirRelation", nullable = false)
	public byte getDirRelation() {
		return this.dirRelation;
	}

	public void setDirRelation(byte dirRelation) {
		this.dirRelation = dirRelation;
	}

	@Column(name = "EmailDayInFreq", nullable = false)
	public byte getEmailDayInFreq() {
		return this.emailDayInFreq;
	}

	public void setEmailDayInFreq(byte emailDayInFreq) {
		this.emailDayInFreq = emailDayInFreq;
	}

	@Column(name = "MemReasonCd", nullable = false)
	public short getMemReasonCd() {
		return this.memReasonCd;
	}

	public void setMemReasonCd(short memReasonCd) {
		this.memReasonCd = memReasonCd;
	}

	@Column(name = "TodYN", nullable = false, length = 1)
	public char getTodYn() {
		return this.todYn;
	}

	public void setTodYn(char todYn) {
		this.todYn = todYn;
	}

	@Column(name = "WriteOffYN", nullable = false, length = 1)
	public char getWriteOffYn() {
		return this.writeOffYn;
	}

	public void setWriteOffYn(char writeOffYn) {
		this.writeOffYn = writeOffYn;
	}

	@Column(name = "RebateYN", nullable = false, length = 1)
	public char getRebateYn() {
		return this.rebateYn;
	}

	public void setRebateYn(char rebateYn) {
		this.rebateYn = rebateYn;
	}

	@Column(name = "AcctOpnType", nullable = false)
	public byte getAcctOpnType() {
		return this.acctOpnType;
	}

	public void setAcctOpnType(byte acctOpnType) {
		this.acctOpnType = acctOpnType;
	}

	@Column(name = "EmpId", nullable = false, length = 8)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "EmpName", nullable = false, length = 25)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "PensionACYN", nullable = false, length = 1)
	public char getPensionAcyn() {
		return this.pensionAcyn;
	}

	public void setPensionAcyn(char pensionAcyn) {
		this.pensionAcyn = pensionAcyn;
	}

	@Column(name = "AccountType", nullable = false, length = 8)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "BusinessCat", nullable = false, length = 8)
	public String getBusinessCat() {
		return this.businessCat;
	}

	public void setBusinessCat(String businessCat) {
		this.businessCat = businessCat;
	}

	@Column(name = "BusinessInd", nullable = false, length = 8)
	public String getBusinessInd() {
		return this.businessInd;
	}

	public void setBusinessInd(String businessInd) {
		this.businessInd = businessInd;
	}

	@Column(name = "GSTINNo", nullable = false, length = 15)
	public String getGstInNo() {
		return this.gstInNo;
	}
	
	public void setGstInNo(String gstInNo) {
		this.gstInNo = gstInNo;
	}
}
