package com.sil.hbm;
// Generated Jan 23, 2017 8:48:32 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D009047Id generated by hbm2java
 */
@Embeddable
public class D009047Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1578589302785295050L;
	private int lbrCode;
	private String prdAcctId;
	private Date effFromDate;

	public D009047Id() {
	}

	public D009047Id(int lbrCode, String prdAcctId, Date effFromDate) {
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
		this.effFromDate = effFromDate;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "EffFromDate", nullable = false, length = 23)
	public Date getEffFromDate() {
		return this.effFromDate;
	}

	public void setEffFromDate(Date effFromDate) {
		this.effFromDate = effFromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D009047Id))
			return false;
		D009047Id castOther = (D009047Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getPrdAcctId() == castOther.getPrdAcctId()) || (this.getPrdAcctId() != null
						&& castOther.getPrdAcctId() != null && this.getPrdAcctId().equals(castOther.getPrdAcctId())))
				&& ((this.getEffFromDate() == castOther.getEffFromDate())
						|| (this.getEffFromDate() != null && castOther.getEffFromDate() != null
								&& this.getEffFromDate().equals(castOther.getEffFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getPrdAcctId() == null ? 0 : this.getPrdAcctId().hashCode());
		result = 37 * result + (getEffFromDate() == null ? 0 : this.getEffFromDate().hashCode());
		return result;
	}

}
