package com.sil.hbm;
// Generated 14 Mar, 2017 5:57:48 PM by Hibernate Tools 5.1.0.Beta1

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.sil.util.DateUtil;

/**
 * D009500 generated by hbm2java
 */
@Entity
@Table(name = "D009500")
@DynamicUpdate
@DynamicInsert
public class D009500 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3787790854884005829L;
	private D009500Id id;
	private double tdsProjected;
	private double intProjected;
	private double tdsProvision;
	private double intProvision;
	@Column(name="DbtrAddCb")
	private int dbtrAddCb = 0;

	@Column(name="DbtrAddCd")
	private Date dbtrAddCd = DateUtil.getDateFromStringNew("19000101");

	@Column(name="DbtrAddCk")
	private int dbtrAddCk = 0;

	@Column(name="DbtrAddCs")
	private short dbtrAddCs = 0;

	@Column(name="DbtrAddCt")
	private Date dbtrAddCt = DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrAddMb")
	private int dbtrAddMb = 0;

	@Column(name="DbtrAddMd")
	private Date dbtrAddMd = DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrAddMk")
	private int dbtrAddMk = 0;

	@Column(name="DbtrAddMs")
	private short dbtrAddMs = 0;

	@Column(name="DbtrAddMt")
	private Date dbtrAddMt = DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrAuthDone")
	private short dbtrAuthDone = 0;

	@Column(name="DbtrAuthNeeded")
	private short dbtrAuthNeeded = 0;

	@Column(name="DbtrLHisTrnNo")
	private int dbtrLhisTrnNo=0;

	@Column(name="DbtrLupdCb")
	private int dbtrLupdCb = 0;

	@Column(name="DbtrLupdCd")
	private Date dbtrLupdCd= DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrLupdCk")
	private int dbtrLupdCk = 0;

	@Column(name="DbtrLupdCs")
	private short dbtrLupdCs = 0;

	@Column(name="DbtrLupdCt")
	private Date dbtrLupdCt= DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrLupdMb")
	private int dbtrLupdMb = 0;

	@Column(name="DbtrLupdMd")
	private Date dbtrLupdMd= DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrLupdMk")
	private int dbtrLupdMk = 0;

	@Column(name="DbtrLupdMs")
	private short dbtrLupdMs = 0;

	@Column(name="DbtrLupdMt")
	private Date dbtrLupdMt= DateUtil.getDateFromStringNew("19000101");;

	@Column(name="DbtrRecStat")
	private short dbtrRecStat = 0;

	@Column(name="DbtrTAuthDone")
	private short dbtrTauthDone = 0;

	@Column(name="DbtrUpdtChkId")
	private short dbtrUpdtChkId = 0;	
	private Date fincalEndDate;

	public D009500() {
	}

	public D009500(D009500Id id, double tdsProjected, double intProjected, double tdsProvision, double intProvision,
			int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb,
			short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs,
			Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd,
			Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded,
			short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.id = id;
		this.tdsProjected = tdsProjected;
		this.intProjected = intProjected;
		this.tdsProvision = tdsProvision;
		this.intProvision = intProvision;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mainCustNo", column = @Column(name = "MainCustNo", nullable = false)),
			@AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)) })
	public D009500Id getId() {
		return this.id;
	}

	public void setId(D009500Id id) {
		this.id = id;
	}

	@Column(name = "TdsProjected", nullable = false, precision = 53, scale = 0)
	public double getTdsProjected() {
		return this.tdsProjected;
	}

	public void setTdsProjected(double tdsProjected) {
		this.tdsProjected = tdsProjected;
	}

	@Column(name = "IntProjected", nullable = false, precision = 53, scale = 0)
	public double getIntProjected() {
		return this.intProjected;
	}

	public void setIntProjected(double intProjected) {
		this.intProjected = intProjected;
	}

	@Column(name = "TdsProvision", nullable = false, precision = 53, scale = 0)
	public double getTdsProvision() {
		return this.tdsProvision;
	}

	public void setTdsProvision(double tdsProvision) {
		this.tdsProvision = tdsProvision;
	}

	@Column(name = "IntProvision", nullable = false, precision = 53, scale = 0)
	public double getIntProvision() {
		return this.intProvision;
	}

	public void setIntProvision(double intProvision) {
		this.intProvision = intProvision;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public short getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(short dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public short getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(short dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public short getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(short dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Transient
	public Date getFincalEndDate() {
		return fincalEndDate;
	}

	public void setFincalEndDate(Date fincalEndDate) {
		this.fincalEndDate = fincalEndDate;
	}
	
}
