package com.sil.hbm;
// Generated 14 Mar, 2017 5:57:48 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D009500Id generated by hbm2java
 */
@Embeddable
public class D009500Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7943173805518189981L;
	private int mainCustNo;
	private int lbrCode;

	public D009500Id() {
	}

	public D009500Id(int mainCustNo, int lbrCode) {
		this.mainCustNo = mainCustNo;
		this.lbrCode = lbrCode;
	}

	@Column(name = "MainCustNo", nullable = false)
	public int getMainCustNo() {
		return this.mainCustNo;
	}

	public void setMainCustNo(int mainCustNo) {
		this.mainCustNo = mainCustNo;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D009500Id))
			return false;
		D009500Id castOther = (D009500Id) other;

		return (this.getMainCustNo() == castOther.getMainCustNo()) && (this.getLbrCode() == castOther.getLbrCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMainCustNo();
		result = 37 * result + this.getLbrCode();
		return result;
	}

}
