package com.sil.hbm;
// Generated 15 Sep, 2016 5:16:47 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009040 generated by hbm2java
 */
@Entity
@Table(name = "D009040")
@DynamicUpdate
@DynamicInsert
public class D009040 implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2325543636693950731L;
	private D009040Id id;
	private int mainScrollNo;
	private Date postDate;
	private Date feffDate;
	private String activityType;
	private String cashFlowType;
	private Date valueDate;
	private String bookType;
	private char drCr;
	private String vcrAcctId;
	private String mainAcctId;
	private short mainModType;
	private short vcrModType;
	private String trnCurCd;
	private double fcyTrnAmt;
	private double lcyConvRate;
	private double lcyTrnAmt;
	private short instrBankCd;
	private short instrBranchCd;
	private short instrType;
	private String instrNo;
	private Date instrDate;
	private int tokenNo;
	private String particulars;
	private byte sysGenVcr;
	private char shTotFlag;
	private char shClrFlag;
	private char acTotFlag;
	private char acClrFlag;
	private int maker;
	private Date makerDate;
	private int makerTime;
	private int checker1;
	private int checker2;
	private int checker3;
	private int checker4;
	private Date checkerDate;
	private int checkerTime;
	private byte noAuthPending;
	private byte noAuthOver;
	private char postFlag;
	private char authFlag;
	private char feffFlag;
	private char canceledFlag;
	private byte postAuthFeffCncl;
	private short updtChkId;
	private double partClearAmt;
	private int postTime;

	public D009040() {
	}

	public D009040(D009040Id id, int mainScrollNo, Date postDate, Date feffDate, String activityType,
			String cashFlowType, Date valueDate, String bookType, char drCr, String vcrAcctId, String mainAcctId,
			short mainModType, short vcrModType, String trnCurCd, double fcyTrnAmt, double lcyConvRate,
			double lcyTrnAmt, short instrBankCd, short instrBranchCd, short instrType, String instrNo, Date instrDate,
			int tokenNo, String particulars, byte sysGenVcr, char shTotFlag, char shClrFlag, char acTotFlag,
			char acClrFlag, int maker, Date makerDate, int makerTime, int checker1, int checker2, int checker3,
			int checker4, Date checkerDate, int checkerTime, byte noAuthPending, byte noAuthOver, char postFlag,
			char authFlag, char feffFlag, char canceledFlag, byte postAuthFeffCncl, short updtChkId,
			double partClearAmt, int postTime) {
		this.id = id;
		this.mainScrollNo = mainScrollNo;
		this.postDate = postDate;
		this.feffDate = feffDate;
		this.activityType = activityType;
		this.cashFlowType = cashFlowType;
		this.valueDate = valueDate;
		this.bookType = bookType;
		this.drCr = drCr;
		this.vcrAcctId = vcrAcctId;
		this.mainAcctId = mainAcctId;
		this.mainModType = mainModType;
		this.vcrModType = vcrModType;
		this.trnCurCd = trnCurCd;
		this.fcyTrnAmt = fcyTrnAmt;
		this.lcyConvRate = lcyConvRate;
		this.lcyTrnAmt = lcyTrnAmt;
		this.instrBankCd = instrBankCd;
		this.instrBranchCd = instrBranchCd;
		this.instrType = instrType;
		this.instrNo = instrNo;
		this.instrDate = instrDate;
		this.tokenNo = tokenNo;
		this.particulars = particulars;
		this.sysGenVcr = sysGenVcr;
		this.shTotFlag = shTotFlag;
		this.shClrFlag = shClrFlag;
		this.acTotFlag = acTotFlag;
		this.acClrFlag = acClrFlag;
		this.maker = maker;
		this.makerDate = makerDate;
		this.makerTime = makerTime;
		this.checker1 = checker1;
		this.checker2 = checker2;
		this.checker3 = checker3;
		this.checker4 = checker4;
		this.checkerDate = checkerDate;
		this.checkerTime = checkerTime;
		this.noAuthPending = noAuthPending;
		this.noAuthOver = noAuthOver;
		this.postFlag = postFlag;
		this.authFlag = authFlag;
		this.feffFlag = feffFlag;
		this.canceledFlag = canceledFlag;
		this.postAuthFeffCncl = postAuthFeffCncl;
		this.updtChkId = updtChkId;
		this.partClearAmt = partClearAmt;
		this.postTime = postTime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", nullable = false, length = 23)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", nullable = false, length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo", nullable = false)),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo", nullable = false)) })
	public D009040Id getId() {
		return this.id;
	}

	public void setId(D009040Id id) {
		this.id = id;
	}

	@Column(name = "MainScrollNo", nullable = false)
	public int getMainScrollNo() {
		return this.mainScrollNo;
	}

	public void setMainScrollNo(int mainScrollNo) {
		this.mainScrollNo = mainScrollNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", nullable = false, length = 23)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEffDate", nullable = false, length = 23)
	public Date getFeffDate() {
		return this.feffDate;
	}

	public void setFeffDate(Date feffDate) {
		this.feffDate = feffDate;
	}

	@Column(name = "ActivityType", nullable = false, length = 8)
	public String getActivityType() {
		return this.activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}

	@Column(name = "CashFlowType", nullable = false, length = 8)
	public String getCashFlowType() {
		return this.cashFlowType;
	}

	public void setCashFlowType(String cashFlowType) {
		this.cashFlowType = cashFlowType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValueDate", nullable = false, length = 23)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "BookType", nullable = false, length = 2)
	public String getBookType() {
		return this.bookType;
	}

	public void setBookType(String bookType) {
		this.bookType = bookType;
	}

	@Column(name = "DrCr", nullable = false, length = 1)
	public char getDrCr() {
		return this.drCr;
	}

	public void setDrCr(char drCr) {
		this.drCr = drCr;
	}

	@Column(name = "VcrAcctId", nullable = false, length = 32)
	public String getVcrAcctId() {
		return this.vcrAcctId;
	}

	public void setVcrAcctId(String vcrAcctId) {
		this.vcrAcctId = vcrAcctId;
	}

	@Column(name = "MainAcctId", nullable = false, length = 32)
	public String getMainAcctId() {
		return this.mainAcctId;
	}

	public void setMainAcctId(String mainAcctId) {
		this.mainAcctId = mainAcctId;
	}

	@Column(name = "MainModType", nullable = false)
	public short getMainModType() {
		return this.mainModType;
	}

	public void setMainModType(short mainModType) {
		this.mainModType = mainModType;
	}

	@Column(name = "VcrModType", nullable = false)
	public short getVcrModType() {
		return this.vcrModType;
	}

	public void setVcrModType(short vcrModType) {
		this.vcrModType = vcrModType;
	}

	@Column(name = "TrnCurCd", nullable = false, length = 3)
	public String getTrnCurCd() {
		return this.trnCurCd;
	}

	public void setTrnCurCd(String trnCurCd) {
		this.trnCurCd = trnCurCd;
	}

	@Column(name = "FcyTrnAmt", nullable = false, precision = 53, scale = 0)
	public double getFcyTrnAmt() {
		return this.fcyTrnAmt;
	}

	public void setFcyTrnAmt(double fcyTrnAmt) {
		this.fcyTrnAmt = fcyTrnAmt;
	}

	@Column(name = "LcyConvRate", nullable = false, precision = 53, scale = 0)
	public double getLcyConvRate() {
		return this.lcyConvRate;
	}

	public void setLcyConvRate(double lcyConvRate) {
		this.lcyConvRate = lcyConvRate;
	}

	@Column(name = "LcyTrnAmt", nullable = false, precision = 53, scale = 0)
	public double getLcyTrnAmt() {
		return this.lcyTrnAmt;
	}

	public void setLcyTrnAmt(double lcyTrnAmt) {
		this.lcyTrnAmt = lcyTrnAmt;
	}

	@Column(name = "InstrBankCd", nullable = false)
	public short getInstrBankCd() {
		return this.instrBankCd;
	}

	public void setInstrBankCd(short instrBankCd) {
		this.instrBankCd = instrBankCd;
	}

	@Column(name = "InstrBranchCd", nullable = false)
	public short getInstrBranchCd() {
		return this.instrBranchCd;
	}

	public void setInstrBranchCd(short instrBranchCd) {
		this.instrBranchCd = instrBranchCd;
	}

	@Column(name = "InstrType", nullable = false)
	public short getInstrType() {
		return this.instrType;
	}

	public void setInstrType(short instrType) {
		this.instrType = instrType;
	}

	@Column(name = "InstrNo", nullable = false, length = 12)
	public String getInstrNo() {
		return this.instrNo;
	}

	public void setInstrNo(String instrNo) {
		this.instrNo = instrNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InstrDate", nullable = false, length = 23)
	public Date getInstrDate() {
		return this.instrDate;
	}

	public void setInstrDate(Date instrDate) {
		this.instrDate = instrDate;
	}

	@Column(name = "TokenNo", nullable = false)
	public int getTokenNo() {
		return this.tokenNo;
	}

	public void setTokenNo(int tokenNo) {
		this.tokenNo = tokenNo;
	}

	@Column(name = "Particulars", nullable = false, length = 70)
	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	@Column(name = "SysGenVcr", nullable = false)
	public byte getSysGenVcr() {
		return this.sysGenVcr;
	}

	public void setSysGenVcr(byte sysGenVcr) {
		this.sysGenVcr = sysGenVcr;
	}

	@Column(name = "ShTotFlag", nullable = false, length = 1)
	public char getShTotFlag() {
		return this.shTotFlag;
	}

	public void setShTotFlag(char shTotFlag) {
		this.shTotFlag = shTotFlag;
	}

	@Column(name = "ShClrFlag", nullable = false, length = 1)
	public char getShClrFlag() {
		return this.shClrFlag;
	}

	public void setShClrFlag(char shClrFlag) {
		this.shClrFlag = shClrFlag;
	}

	@Column(name = "AcTotFlag", nullable = false, length = 1)
	public char getAcTotFlag() {
		return this.acTotFlag;
	}

	public void setAcTotFlag(char acTotFlag) {
		this.acTotFlag = acTotFlag;
	}

	@Column(name = "AcClrFlag", nullable = false, length = 1)
	public char getAcClrFlag() {
		return this.acClrFlag;
	}

	public void setAcClrFlag(char acClrFlag) {
		this.acClrFlag = acClrFlag;
	}

	@Column(name = "Maker", nullable = false)
	public int getMaker() {
		return this.maker;
	}

	public void setMaker(int maker) {
		this.maker = maker;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MakerDate", nullable = false, length = 23)
	public Date getMakerDate() {
		return this.makerDate;
	}

	public void setMakerDate(Date makerDate) {
		this.makerDate = makerDate;
	}

	@Column(name = "MakerTime", nullable = false)
	public int getMakerTime() {
		return this.makerTime;
	}

	public void setMakerTime(int makerTime) {
		this.makerTime = makerTime;
	}

	@Column(name = "Checker1", nullable = false)
	public int getChecker1() {
		return this.checker1;
	}

	public void setChecker1(int checker1) {
		this.checker1 = checker1;
	}

	@Column(name = "Checker2", nullable = false)
	public int getChecker2() {
		return this.checker2;
	}

	public void setChecker2(int checker2) {
		this.checker2 = checker2;
	}

	@Column(name = "Checker3", nullable = false)
	public int getChecker3() {
		return this.checker3;
	}

	public void setChecker3(int checker3) {
		this.checker3 = checker3;
	}

	@Column(name = "Checker4", nullable = false)
	public int getChecker4() {
		return this.checker4;
	}

	public void setChecker4(int checker4) {
		this.checker4 = checker4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CheckerDate", nullable = false, length = 23)
	public Date getCheckerDate() {
		return this.checkerDate;
	}

	public void setCheckerDate(Date checkerDate) {
		this.checkerDate = checkerDate;
	}

	@Column(name = "CheckerTime", nullable = false)
	public int getCheckerTime() {
		return this.checkerTime;
	}

	public void setCheckerTime(int checkerTime) {
		this.checkerTime = checkerTime;
	}

	@Column(name = "NoAuthPending", nullable = false)
	public byte getNoAuthPending() {
		return this.noAuthPending;
	}

	public void setNoAuthPending(byte noAuthPending) {
		this.noAuthPending = noAuthPending;
	}

	@Column(name = "NoAuthOver", nullable = false)
	public byte getNoAuthOver() {
		return this.noAuthOver;
	}

	public void setNoAuthOver(byte noAuthOver) {
		this.noAuthOver = noAuthOver;
	}

	@Column(name = "PostFlag", nullable = false, length = 1)
	public char getPostFlag() {
		return this.postFlag;
	}

	public void setPostFlag(char postFlag) {
		this.postFlag = postFlag;
	}

	@Column(name = "AuthFlag", nullable = false, length = 1)
	public char getAuthFlag() {
		return this.authFlag;
	}

	public void setAuthFlag(char authFlag) {
		this.authFlag = authFlag;
	}

	@Column(name = "FEffFlag", nullable = false, length = 1)
	public char getFeffFlag() {
		return this.feffFlag;
	}

	public void setFeffFlag(char feffFlag) {
		this.feffFlag = feffFlag;
	}

	@Column(name = "CanceledFlag", nullable = false, length = 1)
	public char getCanceledFlag() {
		return this.canceledFlag;
	}

	public void setCanceledFlag(char canceledFlag) {
		this.canceledFlag = canceledFlag;
	}

	@Column(name = "PostAuthFeffCncl", nullable = false)
	public byte getPostAuthFeffCncl() {
		return this.postAuthFeffCncl;
	}

	public void setPostAuthFeffCncl(byte postAuthFeffCncl) {
		this.postAuthFeffCncl = postAuthFeffCncl;
	}

	@Column(name = "UpdtChkId", nullable = false)
	public short getUpdtChkId() {
		return this.updtChkId;
	}

	public void setUpdtChkId(short updtChkId) {
		this.updtChkId = updtChkId;
	}

	@Column(name = "PartClearAmt", nullable = false, precision = 53, scale = 0)
	public double getPartClearAmt() {
		return this.partClearAmt;
	}

	public void setPartClearAmt(double partClearAmt) {
		this.partClearAmt = partClearAmt;
	}

	@Column(name = "PostTime", nullable = false)
	public int getPostTime() {
		return this.postTime;
	}

	public void setPostTime(int postTime) {
		this.postTime = postTime;
	}

	@Override
	public String toString() {
		return "D009040 [id=" + id + ", mainScrollNo=" + mainScrollNo + ", postDate=" + postDate + ", feffDate="
				+ feffDate + ", activityType=" + activityType + ", cashFlowType=" + cashFlowType + ", valueDate="
				+ valueDate + ", bookType=" + bookType + ", drCr=" + drCr + ", vcrAcctId=" + vcrAcctId + ", mainAcctId="
				+ mainAcctId + ", mainModType=" + mainModType + ", vcrModType=" + vcrModType + ", trnCurCd=" + trnCurCd
				+ ", fcyTrnAmt=" + fcyTrnAmt + ", lcyConvRate=" + lcyConvRate + ", lcyTrnAmt=" + lcyTrnAmt
				+ ", instrBankCd=" + instrBankCd + ", instrBranchCd=" + instrBranchCd + ", instrType=" + instrType
				+ ", instrNo=" + instrNo + ", instrDate=" + instrDate + ", tokenNo=" + tokenNo + ", particulars="
				+ particulars + ", sysGenVcr=" + sysGenVcr + ", shTotFlag=" + shTotFlag + ", shClrFlag=" + shClrFlag
				+ ", acTotFlag=" + acTotFlag + ", acClrFlag=" + acClrFlag + ", maker=" + maker + ", makerDate="
				+ makerDate + ", makerTime=" + makerTime + ", checker1=" + checker1 + ", checker2=" + checker2
				+ ", checker3=" + checker3 + ", checker4=" + checker4 + ", checkerDate=" + checkerDate
				+ ", checkerTime=" + checkerTime + ", noAuthPending=" + noAuthPending + ", noAuthOver=" + noAuthOver
				+ ", postFlag=" + postFlag + ", authFlag=" + authFlag + ", feffFlag=" + feffFlag + ", canceledFlag="
				+ canceledFlag + ", postAuthFeffCncl=" + postAuthFeffCncl + ", updtChkId=" + updtChkId
				+ ", partClearAmt=" + partClearAmt + ", postTime=" + postTime + "]";
	}
	
}
