package com.sil.hbm;
// Generated Nov 18, 2016 3:14:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D009142Id generated by hbm2java
 */
@Embeddable
public class D009142Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -351803405994409579L;
	private int lbrCode;
	private String prdAcctId;
	private Date effFromDate;
	private Date disbursedDate;

	public D009142Id() {
	}

	public D009142Id(int lbrCode, String prdAcctId, Date effFromDate, Date disbursedDate) {
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
		this.effFromDate = effFromDate;
		this.disbursedDate = disbursedDate;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "EffFromDate", nullable = false, length = 23)
	public Date getEffFromDate() {
		return this.effFromDate;
	}

	public void setEffFromDate(Date effFromDate) {
		this.effFromDate = effFromDate;
	}

	@Column(name = "DisbursedDate", nullable = false, length = 23)
	public Date getDisbursedDate() {
		return this.disbursedDate;
	}

	public void setDisbursedDate(Date disbursedDate) {
		this.disbursedDate = disbursedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D009142Id))
			return false;
		D009142Id castOther = (D009142Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getPrdAcctId() == castOther.getPrdAcctId()) || (this.getPrdAcctId() != null
						&& castOther.getPrdAcctId() != null && this.getPrdAcctId().equals(castOther.getPrdAcctId())))
				&& ((this.getEffFromDate() == castOther.getEffFromDate())
						|| (this.getEffFromDate() != null && castOther.getEffFromDate() != null
								&& this.getEffFromDate().equals(castOther.getEffFromDate())))
				&& ((this.getDisbursedDate() == castOther.getDisbursedDate())
						|| (this.getDisbursedDate() != null && castOther.getDisbursedDate() != null
								&& this.getDisbursedDate().equals(castOther.getDisbursedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getPrdAcctId() == null ? 0 : this.getPrdAcctId().hashCode());
		result = 37 * result + (getEffFromDate() == null ? 0 : this.getEffFromDate().hashCode());
		result = 37 * result + (getDisbursedDate() == null ? 0 : this.getDisbursedDate().hashCode());
		return result;
	}

}
