package com.sil.hbm;
// Generated Nov 18, 2016 3:14:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009042 generated by hbm2java
 */
@Entity
@Table(name = "D009042")
@DynamicUpdate
@DynamicInsert
public class D009042 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4114004251559522720L;
	private D009042Id id;
	private String curCd;
	private char plrLinkYn;
	private String sancAuthority;
	private Date sancDate;
	private double totSancLimit;
	private Date expDate;
	private String remarks;
	private char equatedYn;
	private char intFundedYn;
	private char lnInstFreq;
	private short noOfInstl;
	private byte grcDaysForInst;
	private byte grcDaysForInt;
	private byte fromMnth1;
	private byte noOfMnth1;
	private byte fromMnth2;
	private byte noOfMnth2;
	private String recom;
	private Date expLessGrace;
	private char reScheduleYn;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private String recomUsrCd;
	private String sancUsrCd;
	private double othChgApprop;

	public D009042() {
	}

	public D009042(D009042Id id, String curCd, char plrLinkYn, String sancAuthority, Date sancDate, double totSancLimit,
			Date expDate, String remarks, char equatedYn, char intFundedYn, char lnInstFreq, short noOfInstl,
			byte grcDaysForInst, byte grcDaysForInt, byte fromMnth1, byte noOfMnth1, byte fromMnth2, byte noOfMnth2,
			String recom, Date expLessGrace, char reScheduleYn, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			String recomUsrCd, String sancUsrCd, double othChgApprop) {
		this.id = id;
		this.curCd = curCd;
		this.plrLinkYn = plrLinkYn;
		this.sancAuthority = sancAuthority;
		this.sancDate = sancDate;
		this.totSancLimit = totSancLimit;
		this.expDate = expDate;
		this.remarks = remarks;
		this.equatedYn = equatedYn;
		this.intFundedYn = intFundedYn;
		this.lnInstFreq = lnInstFreq;
		this.noOfInstl = noOfInstl;
		this.grcDaysForInst = grcDaysForInst;
		this.grcDaysForInt = grcDaysForInt;
		this.fromMnth1 = fromMnth1;
		this.noOfMnth1 = noOfMnth1;
		this.fromMnth2 = fromMnth2;
		this.noOfMnth2 = noOfMnth2;
		this.recom = recom;
		this.expLessGrace = expLessGrace;
		this.reScheduleYn = reScheduleYn;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.recomUsrCd = recomUsrCd;
		this.sancUsrCd = sancUsrCd;
		this.othChgApprop = othChgApprop;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "effFromDate", column = @Column(name = "EffFromDate", nullable = false, length = 23)) })
	public D009042Id getId() {
		return this.id;
	}

	public void setId(D009042Id id) {
		this.id = id;
	}

	@Column(name = "CurCd", nullable = false, length = 3)
	public String getCurCd() {
		return this.curCd;
	}

	public void setCurCd(String curCd) {
		this.curCd = curCd;
	}

	@Column(name = "PlrLinkYN", nullable = false, length = 1)
	public char getPlrLinkYn() {
		return this.plrLinkYn;
	}

	public void setPlrLinkYn(char plrLinkYn) {
		this.plrLinkYn = plrLinkYn;
	}

	@Column(name = "SancAuthority", nullable = false, length = 2)
	public String getSancAuthority() {
		return this.sancAuthority;
	}

	public void setSancAuthority(String sancAuthority) {
		this.sancAuthority = sancAuthority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SancDate", nullable = false, length = 23)
	public Date getSancDate() {
		return this.sancDate;
	}

	public void setSancDate(Date sancDate) {
		this.sancDate = sancDate;
	}

	@Column(name = "TotSancLimit", nullable = false, precision = 53, scale = 0)
	public double getTotSancLimit() {
		return this.totSancLimit;
	}

	public void setTotSancLimit(double totSancLimit) {
		this.totSancLimit = totSancLimit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpDate", nullable = false, length = 23)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "Remarks", nullable = false, length = 35)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "EquatedYN", nullable = false, length = 1)
	public char getEquatedYn() {
		return this.equatedYn;
	}

	public void setEquatedYn(char equatedYn) {
		this.equatedYn = equatedYn;
	}

	@Column(name = "IntFundedYN", nullable = false, length = 1)
	public char getIntFundedYn() {
		return this.intFundedYn;
	}

	public void setIntFundedYn(char intFundedYn) {
		this.intFundedYn = intFundedYn;
	}

	@Column(name = "LnInstFreq", nullable = false, length = 1)
	public char getLnInstFreq() {
		return this.lnInstFreq;
	}

	public void setLnInstFreq(char lnInstFreq) {
		this.lnInstFreq = lnInstFreq;
	}

	@Column(name = "NoOfInstl", nullable = false)
	public short getNoOfInstl() {
		return this.noOfInstl;
	}

	public void setNoOfInstl(short noOfInstl) {
		this.noOfInstl = noOfInstl;
	}

	@Column(name = "GrcDaysForInst", nullable = false)
	public byte getGrcDaysForInst() {
		return this.grcDaysForInst;
	}

	public void setGrcDaysForInst(byte grcDaysForInst) {
		this.grcDaysForInst = grcDaysForInst;
	}

	@Column(name = "GrcDaysForInt", nullable = false)
	public byte getGrcDaysForInt() {
		return this.grcDaysForInt;
	}

	public void setGrcDaysForInt(byte grcDaysForInt) {
		this.grcDaysForInt = grcDaysForInt;
	}

	@Column(name = "FromMnth1", nullable = false)
	public byte getFromMnth1() {
		return this.fromMnth1;
	}

	public void setFromMnth1(byte fromMnth1) {
		this.fromMnth1 = fromMnth1;
	}

	@Column(name = "NoOfMnth1", nullable = false)
	public byte getNoOfMnth1() {
		return this.noOfMnth1;
	}

	public void setNoOfMnth1(byte noOfMnth1) {
		this.noOfMnth1 = noOfMnth1;
	}

	@Column(name = "FromMnth2", nullable = false)
	public byte getFromMnth2() {
		return this.fromMnth2;
	}

	public void setFromMnth2(byte fromMnth2) {
		this.fromMnth2 = fromMnth2;
	}

	@Column(name = "NoOfMnth2", nullable = false)
	public byte getNoOfMnth2() {
		return this.noOfMnth2;
	}

	public void setNoOfMnth2(byte noOfMnth2) {
		this.noOfMnth2 = noOfMnth2;
	}

	@Column(name = "Recom", nullable = false, length = 2)
	public String getRecom() {
		return this.recom;
	}

	public void setRecom(String recom) {
		this.recom = recom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpLessGrace", nullable = false, length = 23)
	public Date getExpLessGrace() {
		return this.expLessGrace;
	}

	public void setExpLessGrace(Date expLessGrace) {
		this.expLessGrace = expLessGrace;
	}

	@Column(name = "ReScheduleYN", nullable = false, length = 1)
	public char getReScheduleYn() {
		return this.reScheduleYn;
	}

	public void setReScheduleYn(char reScheduleYn) {
		this.reScheduleYn = reScheduleYn;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "RecomUsrCd", nullable = false, length = 8)
	public String getRecomUsrCd() {
		return this.recomUsrCd;
	}

	public void setRecomUsrCd(String recomUsrCd) {
		this.recomUsrCd = recomUsrCd;
	}

	@Column(name = "SancUsrCd", nullable = false, length = 8)
	public String getSancUsrCd() {
		return this.sancUsrCd;
	}

	public void setSancUsrCd(String sancUsrCd) {
		this.sancUsrCd = sancUsrCd;
	}

	@Column(name = "OthChgApprop", nullable = false, precision = 53, scale = 0)
	public double getOthChgApprop() {
		return this.othChgApprop;
	}

	public void setOthChgApprop(double othChgApprop) {
		this.othChgApprop = othChgApprop;
	}

}
