package com.sil.hbm;
// Generated Mar 10, 2018 4:06:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D009012 generated by hbm2java
 */
@Entity
@Table(name = "D009012")
@DynamicUpdate
@DynamicInsert
public class D009012 implements java.io.Serializable {
	private static final long serialVersionUID = 6729563299858412656L;
	private int custNo;
	private String nameTitle;
	private String longname;
	private Date dob;
	private Date dtFromCust;
	private short residence;
	private short cusType;
	private short maritalStatus;
	private byte noOfChildren;
	private double annualIncome;
	private String panNo;
	private String educationalQual;
	private short profCd;
	private String designation;
	private String ophone;
	private char phBanking;
	private char pwdAssigned;
	private String atmno;
	private Date validUpto;
	private short desMail;
	private String freqSt;
	private short decision;
	private short documents;
	private String documentsDet;
	private int intrCustNo;
	private String bank1;
	private String bank2;
	private String br1;
	private String br2;
	private String creditCards1;
	private String creditCards2;
	private Date valid1;
	private Date valid2;
	private String debitCard;
	private String creditCard;
	private short religionCd;
	private String employeeNo;
	private String passPort;
	private String empNameTitle;
	private String empLongName;
	private String empAddr1;
	private String empAddr2;
	private String empAddr3;
	private short noOfService;
	private short employedWith;
	private String casteCode;
	private short assetCode;
	private String otherBrAcctCode1;
	private String otherBrAcctCode2;
	private int cusIdbtrAddMk;
	private int cusIdbtrAddMb;
	private short cusIdbtrAddMs;
	private Date cusIdbtrAddMd;
	private Date cusIdbtrAddMt;
	private int cusIdbtrAddCk;
	private int cusIdbtrAddCb;
	private short cusIdbtrAddCs;
	private Date cusIdbtrAddCd;
	private Date cusIdbtrAddCt;
	private int cusIdbtrLupdMk;
	private int cusIdbtrLupdMb;
	private short cusIdbtrLupdMs;
	private Date cusIdbtrLupdMd;
	private Date cusIdbtrLupdMt;
	private int cusIdbtrLupdCk;
	private int cusIdbtrLupdCb;
	private short cusIdbtrLupdCs;
	private Date cusIdbtrLupdCd;
	private Date cusIdbtrLupdCt;
	private short cusIdbtrTauthDone;
	private byte cusIdbtrRecStat;
	private byte cusIdbtrAuthDone;
	private byte cusIdbtrAuthNeeded;
	private short cusIdbtrUpdtChkId;
	private int cusIdbtrLhisTrnNo;
	private int memberNo;
	private String sexCode;
	private byte memberType;
	private Date retiredDate;
	private short employerCd;
	private short station;
	private byte recovThru;
	private String relationName;
	private String bldGrp;
	private byte resiStatus;
	private String relationType;
	private String passPortNo;
	private Date visaValUpTo;
	private short amlrating;
	private char resdYn;
	private char kycyn;
	private int introCustno;
	private String relOffCode;
	private Date marriageDt;
	private short isuAuthority;
	private String isuPlace;
	private String adharNo;
	private Date panRegDate;
	private Date deathDate;

	public D009012() {
	}

	public D009012(int custNo, String nameTitle, String longname, Date dob, Date dtFromCust, short residence,
			short cusType, short maritalStatus, byte noOfChildren, double annualIncome, String panNo,
			String educationalQual, short profCd, String designation, String ophone, char phBanking, char pwdAssigned,
			String atmno, Date validUpto, short desMail, String freqSt, short decision, short documents,
			String documentsDet, int intrCustNo, String bank1, String bank2, String br1, String br2,
			String creditCards1, String creditCards2, Date valid1, Date valid2, String debitCard, String creditCard,
			short religionCd, String employeeNo, String passPort, String empNameTitle, String empLongName,
			String empAddr1, String empAddr2, String empAddr3, short noOfService, short employedWith, String casteCode,
			short assetCode, String otherBrAcctCode1, String otherBrAcctCode2, int cusIdbtrAddMk, int cusIdbtrAddMb,
			short cusIdbtrAddMs, Date cusIdbtrAddMd, Date cusIdbtrAddMt, int cusIdbtrAddCk, int cusIdbtrAddCb,
			short cusIdbtrAddCs, Date cusIdbtrAddCd, Date cusIdbtrAddCt, int cusIdbtrLupdMk, int cusIdbtrLupdMb,
			short cusIdbtrLupdMs, Date cusIdbtrLupdMd, Date cusIdbtrLupdMt, int cusIdbtrLupdCk, int cusIdbtrLupdCb,
			short cusIdbtrLupdCs, Date cusIdbtrLupdCd, Date cusIdbtrLupdCt, short cusIdbtrTauthDone,
			byte cusIdbtrRecStat, byte cusIdbtrAuthDone, byte cusIdbtrAuthNeeded, short cusIdbtrUpdtChkId,
			int cusIdbtrLhisTrnNo, int memberNo, String sexCode, byte memberType, Date retiredDate, short employerCd,
			short station, byte recovThru, String relationName, String bldGrp, byte resiStatus, String relationType,
			String passPortNo, Date visaValUpTo, short amlrating, char resdYn, char kycyn, int introCustno,
			String relOffCode, Date marriageDt, short isuAuthority, String isuPlace, Date panRegDate, Date deathDate) {
		this.custNo = custNo;
		this.nameTitle = nameTitle;
		this.longname = longname;
		this.dob = dob;
		this.dtFromCust = dtFromCust;
		this.residence = residence;
		this.cusType = cusType;
		this.maritalStatus = maritalStatus;
		this.noOfChildren = noOfChildren;
		this.annualIncome = annualIncome;
		this.panNo = panNo;
		this.educationalQual = educationalQual;
		this.profCd = profCd;
		this.designation = designation;
		this.ophone = ophone;
		this.phBanking = phBanking;
		this.pwdAssigned = pwdAssigned;
		this.atmno = atmno;
		this.validUpto = validUpto;
		this.desMail = desMail;
		this.freqSt = freqSt;
		this.decision = decision;
		this.documents = documents;
		this.documentsDet = documentsDet;
		this.intrCustNo = intrCustNo;
		this.bank1 = bank1;
		this.bank2 = bank2;
		this.br1 = br1;
		this.br2 = br2;
		this.creditCards1 = creditCards1;
		this.creditCards2 = creditCards2;
		this.valid1 = valid1;
		this.valid2 = valid2;
		this.debitCard = debitCard;
		this.creditCard = creditCard;
		this.religionCd = religionCd;
		this.employeeNo = employeeNo;
		this.passPort = passPort;
		this.empNameTitle = empNameTitle;
		this.empLongName = empLongName;
		this.empAddr1 = empAddr1;
		this.empAddr2 = empAddr2;
		this.empAddr3 = empAddr3;
		this.noOfService = noOfService;
		this.employedWith = employedWith;
		this.casteCode = casteCode;
		this.assetCode = assetCode;
		this.otherBrAcctCode1 = otherBrAcctCode1;
		this.otherBrAcctCode2 = otherBrAcctCode2;
		this.cusIdbtrAddMk = cusIdbtrAddMk;
		this.cusIdbtrAddMb = cusIdbtrAddMb;
		this.cusIdbtrAddMs = cusIdbtrAddMs;
		this.cusIdbtrAddMd = cusIdbtrAddMd;
		this.cusIdbtrAddMt = cusIdbtrAddMt;
		this.cusIdbtrAddCk = cusIdbtrAddCk;
		this.cusIdbtrAddCb = cusIdbtrAddCb;
		this.cusIdbtrAddCs = cusIdbtrAddCs;
		this.cusIdbtrAddCd = cusIdbtrAddCd;
		this.cusIdbtrAddCt = cusIdbtrAddCt;
		this.cusIdbtrLupdMk = cusIdbtrLupdMk;
		this.cusIdbtrLupdMb = cusIdbtrLupdMb;
		this.cusIdbtrLupdMs = cusIdbtrLupdMs;
		this.cusIdbtrLupdMd = cusIdbtrLupdMd;
		this.cusIdbtrLupdMt = cusIdbtrLupdMt;
		this.cusIdbtrLupdCk = cusIdbtrLupdCk;
		this.cusIdbtrLupdCb = cusIdbtrLupdCb;
		this.cusIdbtrLupdCs = cusIdbtrLupdCs;
		this.cusIdbtrLupdCd = cusIdbtrLupdCd;
		this.cusIdbtrLupdCt = cusIdbtrLupdCt;
		this.cusIdbtrTauthDone = cusIdbtrTauthDone;
		this.cusIdbtrRecStat = cusIdbtrRecStat;
		this.cusIdbtrAuthDone = cusIdbtrAuthDone;
		this.cusIdbtrAuthNeeded = cusIdbtrAuthNeeded;
		this.cusIdbtrUpdtChkId = cusIdbtrUpdtChkId;
		this.cusIdbtrLhisTrnNo = cusIdbtrLhisTrnNo;
		this.memberNo = memberNo;
		this.sexCode = sexCode;
		this.memberType = memberType;
		this.retiredDate = retiredDate;
		this.employerCd = employerCd;
		this.station = station;
		this.recovThru = recovThru;
		this.relationName = relationName;
		this.bldGrp = bldGrp;
		this.resiStatus = resiStatus;
		this.relationType = relationType;
		this.passPortNo = passPortNo;
		this.visaValUpTo = visaValUpTo;
		this.amlrating = amlrating;
		this.resdYn = resdYn;
		this.kycyn = kycyn;
		this.introCustno = introCustno;
		this.relOffCode = relOffCode;
		this.marriageDt = marriageDt;
		this.isuAuthority = isuAuthority;
		this.isuPlace = isuPlace;
		this.panRegDate = panRegDate;
		this.deathDate = deathDate;
	}

	public D009012(int custNo, String nameTitle, String longname, Date dob, Date dtFromCust, short residence,
			short cusType, short maritalStatus, byte noOfChildren, double annualIncome, String panNo,
			String educationalQual, short profCd, String designation, String ophone, char phBanking, char pwdAssigned,
			String atmno, Date validUpto, short desMail, String freqSt, short decision, short documents,
			String documentsDet, int intrCustNo, String bank1, String bank2, String br1, String br2,
			String creditCards1, String creditCards2, Date valid1, Date valid2, String debitCard, String creditCard,
			short religionCd, String employeeNo, String passPort, String empNameTitle, String empLongName,
			String empAddr1, String empAddr2, String empAddr3, short noOfService, short employedWith, String casteCode,
			short assetCode, String otherBrAcctCode1, String otherBrAcctCode2, int cusIdbtrAddMk, int cusIdbtrAddMb,
			short cusIdbtrAddMs, Date cusIdbtrAddMd, Date cusIdbtrAddMt, int cusIdbtrAddCk, int cusIdbtrAddCb,
			short cusIdbtrAddCs, Date cusIdbtrAddCd, Date cusIdbtrAddCt, int cusIdbtrLupdMk, int cusIdbtrLupdMb,
			short cusIdbtrLupdMs, Date cusIdbtrLupdMd, Date cusIdbtrLupdMt, int cusIdbtrLupdCk, int cusIdbtrLupdCb,
			short cusIdbtrLupdCs, Date cusIdbtrLupdCd, Date cusIdbtrLupdCt, short cusIdbtrTauthDone,
			byte cusIdbtrRecStat, byte cusIdbtrAuthDone, byte cusIdbtrAuthNeeded, short cusIdbtrUpdtChkId,
			int cusIdbtrLhisTrnNo, int memberNo, String sexCode, byte memberType, Date retiredDate, short employerCd,
			short station, byte recovThru, String relationName, String bldGrp, byte resiStatus, String relationType,
			String passPortNo, Date visaValUpTo, short amlrating, char resdYn, char kycyn, int introCustno,
			String relOffCode, Date marriageDt, short isuAuthority, String isuPlace, String adharNo, Date panRegDate,
			Date deathDate) {
		this.custNo = custNo;
		this.nameTitle = nameTitle;
		this.longname = longname;
		this.dob = dob;
		this.dtFromCust = dtFromCust;
		this.residence = residence;
		this.cusType = cusType;
		this.maritalStatus = maritalStatus;
		this.noOfChildren = noOfChildren;
		this.annualIncome = annualIncome;
		this.panNo = panNo;
		this.educationalQual = educationalQual;
		this.profCd = profCd;
		this.designation = designation;
		this.ophone = ophone;
		this.phBanking = phBanking;
		this.pwdAssigned = pwdAssigned;
		this.atmno = atmno;
		this.validUpto = validUpto;
		this.desMail = desMail;
		this.freqSt = freqSt;
		this.decision = decision;
		this.documents = documents;
		this.documentsDet = documentsDet;
		this.intrCustNo = intrCustNo;
		this.bank1 = bank1;
		this.bank2 = bank2;
		this.br1 = br1;
		this.br2 = br2;
		this.creditCards1 = creditCards1;
		this.creditCards2 = creditCards2;
		this.valid1 = valid1;
		this.valid2 = valid2;
		this.debitCard = debitCard;
		this.creditCard = creditCard;
		this.religionCd = religionCd;
		this.employeeNo = employeeNo;
		this.passPort = passPort;
		this.empNameTitle = empNameTitle;
		this.empLongName = empLongName;
		this.empAddr1 = empAddr1;
		this.empAddr2 = empAddr2;
		this.empAddr3 = empAddr3;
		this.noOfService = noOfService;
		this.employedWith = employedWith;
		this.casteCode = casteCode;
		this.assetCode = assetCode;
		this.otherBrAcctCode1 = otherBrAcctCode1;
		this.otherBrAcctCode2 = otherBrAcctCode2;
		this.cusIdbtrAddMk = cusIdbtrAddMk;
		this.cusIdbtrAddMb = cusIdbtrAddMb;
		this.cusIdbtrAddMs = cusIdbtrAddMs;
		this.cusIdbtrAddMd = cusIdbtrAddMd;
		this.cusIdbtrAddMt = cusIdbtrAddMt;
		this.cusIdbtrAddCk = cusIdbtrAddCk;
		this.cusIdbtrAddCb = cusIdbtrAddCb;
		this.cusIdbtrAddCs = cusIdbtrAddCs;
		this.cusIdbtrAddCd = cusIdbtrAddCd;
		this.cusIdbtrAddCt = cusIdbtrAddCt;
		this.cusIdbtrLupdMk = cusIdbtrLupdMk;
		this.cusIdbtrLupdMb = cusIdbtrLupdMb;
		this.cusIdbtrLupdMs = cusIdbtrLupdMs;
		this.cusIdbtrLupdMd = cusIdbtrLupdMd;
		this.cusIdbtrLupdMt = cusIdbtrLupdMt;
		this.cusIdbtrLupdCk = cusIdbtrLupdCk;
		this.cusIdbtrLupdCb = cusIdbtrLupdCb;
		this.cusIdbtrLupdCs = cusIdbtrLupdCs;
		this.cusIdbtrLupdCd = cusIdbtrLupdCd;
		this.cusIdbtrLupdCt = cusIdbtrLupdCt;
		this.cusIdbtrTauthDone = cusIdbtrTauthDone;
		this.cusIdbtrRecStat = cusIdbtrRecStat;
		this.cusIdbtrAuthDone = cusIdbtrAuthDone;
		this.cusIdbtrAuthNeeded = cusIdbtrAuthNeeded;
		this.cusIdbtrUpdtChkId = cusIdbtrUpdtChkId;
		this.cusIdbtrLhisTrnNo = cusIdbtrLhisTrnNo;
		this.memberNo = memberNo;
		this.sexCode = sexCode;
		this.memberType = memberType;
		this.retiredDate = retiredDate;
		this.employerCd = employerCd;
		this.station = station;
		this.recovThru = recovThru;
		this.relationName = relationName;
		this.bldGrp = bldGrp;
		this.resiStatus = resiStatus;
		this.relationType = relationType;
		this.passPortNo = passPortNo;
		this.visaValUpTo = visaValUpTo;
		this.amlrating = amlrating;
		this.resdYn = resdYn;
		this.kycyn = kycyn;
		this.introCustno = introCustno;
		this.relOffCode = relOffCode;
		this.marriageDt = marriageDt;
		this.isuAuthority = isuAuthority;
		this.isuPlace = isuPlace;
		this.adharNo = adharNo;
		this.panRegDate = panRegDate;
		this.deathDate = deathDate;
	}

	@Id

	@Column(name = "CustNo", unique = true, nullable = false)
	public int getCustNo() {
		return this.custNo;
	}

	public void setCustNo(int custNo) {
		this.custNo = custNo;
	}

	@Column(name = "NameTitle", nullable = false, length = 4)
	public String getNameTitle() {
		return this.nameTitle;
	}

	public void setNameTitle(String nameTitle) {
		this.nameTitle = nameTitle;
	}

	@Column(name = "Longname", nullable = false, length = 50)
	public String getLongname() {
		return this.longname;
	}

	public void setLongname(String longname) {
		this.longname = longname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", nullable = false, length = 23)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtFromCust", nullable = false, length = 23)
	public Date getDtFromCust() {
		return this.dtFromCust;
	}

	public void setDtFromCust(Date dtFromCust) {
		this.dtFromCust = dtFromCust;
	}

	@Column(name = "Residence", nullable = false)
	public short getResidence() {
		return this.residence;
	}

	public void setResidence(short residence) {
		this.residence = residence;
	}

	@Column(name = "CusType", nullable = false)
	public short getCusType() {
		return this.cusType;
	}

	public void setCusType(short cusType) {
		this.cusType = cusType;
	}

	@Column(name = "MaritalStatus", nullable = false)
	public short getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(short maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "NoOfChildren", nullable = false)
	public byte getNoOfChildren() {
		return this.noOfChildren;
	}

	public void setNoOfChildren(byte noOfChildren) {
		this.noOfChildren = noOfChildren;
	}

	@Column(name = "AnnualIncome", nullable = false, precision = 53, scale = 0)
	public double getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(double annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "PanNo", nullable = false, length = 20)
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "EducationalQual", nullable = false, length = 15)
	public String getEducationalQual() {
		return this.educationalQual;
	}

	public void setEducationalQual(String educationalQual) {
		this.educationalQual = educationalQual;
	}

	@Column(name = "ProfCd", nullable = false)
	public short getProfCd() {
		return this.profCd;
	}

	public void setProfCd(short profCd) {
		this.profCd = profCd;
	}

	@Column(name = "Designation", nullable = false, length = 15)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "OPhone", nullable = false, length = 15)
	public String getOphone() {
		return this.ophone;
	}

	public void setOphone(String ophone) {
		this.ophone = ophone;
	}

	@Column(name = "PhBanking", nullable = false, length = 1)
	public char getPhBanking() {
		return this.phBanking;
	}

	public void setPhBanking(char phBanking) {
		this.phBanking = phBanking;
	}

	@Column(name = "PwdAssigned", nullable = false, length = 1)
	public char getPwdAssigned() {
		return this.pwdAssigned;
	}

	public void setPwdAssigned(char pwdAssigned) {
		this.pwdAssigned = pwdAssigned;
	}

	@Column(name = "ATMNo", nullable = false, length = 32)
	public String getAtmno() {
		return this.atmno;
	}

	public void setAtmno(String atmno) {
		this.atmno = atmno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValidUpto", nullable = false, length = 23)
	public Date getValidUpto() {
		return this.validUpto;
	}

	public void setValidUpto(Date validUpto) {
		this.validUpto = validUpto;
	}

	@Column(name = "DesMail", nullable = false)
	public short getDesMail() {
		return this.desMail;
	}

	public void setDesMail(short desMail) {
		this.desMail = desMail;
	}

	@Column(name = "FreqSt", nullable = false, length = 10)
	public String getFreqSt() {
		return this.freqSt;
	}

	public void setFreqSt(String freqSt) {
		this.freqSt = freqSt;
	}

	@Column(name = "Decision", nullable = false)
	public short getDecision() {
		return this.decision;
	}

	public void setDecision(short decision) {
		this.decision = decision;
	}

	@Column(name = "Documents", nullable = false)
	public short getDocuments() {
		return this.documents;
	}

	public void setDocuments(short documents) {
		this.documents = documents;
	}

	@Column(name = "DocumentsDet", nullable = false, length = 100)
	public String getDocumentsDet() {
		return this.documentsDet;
	}

	public void setDocumentsDet(String documentsDet) {
		this.documentsDet = documentsDet;
	}

	@Column(name = "IntrCustNo", nullable = false)
	public int getIntrCustNo() {
		return this.intrCustNo;
	}

	public void setIntrCustNo(int intrCustNo) {
		this.intrCustNo = intrCustNo;
	}

	@Column(name = "Bank1", nullable = false, length = 6)
	public String getBank1() {
		return this.bank1;
	}

	public void setBank1(String bank1) {
		this.bank1 = bank1;
	}

	@Column(name = "Bank2", nullable = false, length = 6)
	public String getBank2() {
		return this.bank2;
	}

	public void setBank2(String bank2) {
		this.bank2 = bank2;
	}

	@Column(name = "Br1", nullable = false, length = 6)
	public String getBr1() {
		return this.br1;
	}

	public void setBr1(String br1) {
		this.br1 = br1;
	}

	@Column(name = "Br2", nullable = false, length = 6)
	public String getBr2() {
		return this.br2;
	}

	public void setBr2(String br2) {
		this.br2 = br2;
	}

	@Column(name = "CreditCards1", nullable = false, length = 20)
	public String getCreditCards1() {
		return this.creditCards1;
	}

	public void setCreditCards1(String creditCards1) {
		this.creditCards1 = creditCards1;
	}

	@Column(name = "CreditCards2", nullable = false, length = 20)
	public String getCreditCards2() {
		return this.creditCards2;
	}

	public void setCreditCards2(String creditCards2) {
		this.creditCards2 = creditCards2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Valid1", nullable = false, length = 23)
	public Date getValid1() {
		return this.valid1;
	}

	public void setValid1(Date valid1) {
		this.valid1 = valid1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Valid2", nullable = false, length = 23)
	public Date getValid2() {
		return this.valid2;
	}

	public void setValid2(Date valid2) {
		this.valid2 = valid2;
	}

	@Column(name = "DebitCard", nullable = false, length = 20)
	public String getDebitCard() {
		return this.debitCard;
	}

	public void setDebitCard(String debitCard) {
		this.debitCard = debitCard;
	}

	@Column(name = "CreditCard", nullable = false, length = 20)
	public String getCreditCard() {
		return this.creditCard;
	}

	public void setCreditCard(String creditCard) {
		this.creditCard = creditCard;
	}

	@Column(name = "ReligionCd", nullable = false)
	public short getReligionCd() {
		return this.religionCd;
	}

	public void setReligionCd(short religionCd) {
		this.religionCd = religionCd;
	}

	@Column(name = "EmployeeNo", nullable = false, length = 10)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	@Column(name = "PassPort", nullable = false, length = 20)
	public String getPassPort() {
		return this.passPort;
	}

	public void setPassPort(String passPort) {
		this.passPort = passPort;
	}

	@Column(name = "EmpNameTitle", nullable = false, length = 4)
	public String getEmpNameTitle() {
		return this.empNameTitle;
	}

	public void setEmpNameTitle(String empNameTitle) {
		this.empNameTitle = empNameTitle;
	}

	@Column(name = "EmpLongName", nullable = false, length = 50)
	public String getEmpLongName() {
		return this.empLongName;
	}

	public void setEmpLongName(String empLongName) {
		this.empLongName = empLongName;
	}

	@Column(name = "EmpAddr1", nullable = false, length = 30)
	public String getEmpAddr1() {
		return this.empAddr1;
	}

	public void setEmpAddr1(String empAddr1) {
		this.empAddr1 = empAddr1;
	}

	@Column(name = "EmpAddr2", nullable = false, length = 30)
	public String getEmpAddr2() {
		return this.empAddr2;
	}

	public void setEmpAddr2(String empAddr2) {
		this.empAddr2 = empAddr2;
	}

	@Column(name = "EmpAddr3", nullable = false, length = 30)
	public String getEmpAddr3() {
		return this.empAddr3;
	}

	public void setEmpAddr3(String empAddr3) {
		this.empAddr3 = empAddr3;
	}

	@Column(name = "NoOfService", nullable = false)
	public short getNoOfService() {
		return this.noOfService;
	}

	public void setNoOfService(short noOfService) {
		this.noOfService = noOfService;
	}

	@Column(name = "EmployedWith", nullable = false)
	public short getEmployedWith() {
		return this.employedWith;
	}

	public void setEmployedWith(short employedWith) {
		this.employedWith = employedWith;
	}

	@Column(name = "CasteCode", nullable = false, length = 4)
	public String getCasteCode() {
		return this.casteCode;
	}

	public void setCasteCode(String casteCode) {
		this.casteCode = casteCode;
	}

	@Column(name = "AssetCode", nullable = false)
	public short getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(short assetCode) {
		this.assetCode = assetCode;
	}

	@Column(name = "OtherBrAcctCode1", nullable = false, length = 15)
	public String getOtherBrAcctCode1() {
		return this.otherBrAcctCode1;
	}

	public void setOtherBrAcctCode1(String otherBrAcctCode1) {
		this.otherBrAcctCode1 = otherBrAcctCode1;
	}

	@Column(name = "OtherBrAcctCode2", nullable = false, length = 15)
	public String getOtherBrAcctCode2() {
		return this.otherBrAcctCode2;
	}

	public void setOtherBrAcctCode2(String otherBrAcctCode2) {
		this.otherBrAcctCode2 = otherBrAcctCode2;
	}

	@Column(name = "CusIDbtrAddMk", nullable = false)
	public int getCusIdbtrAddMk() {
		return this.cusIdbtrAddMk;
	}

	public void setCusIdbtrAddMk(int cusIdbtrAddMk) {
		this.cusIdbtrAddMk = cusIdbtrAddMk;
	}

	@Column(name = "CusIDbtrAddMb", nullable = false)
	public int getCusIdbtrAddMb() {
		return this.cusIdbtrAddMb;
	}

	public void setCusIdbtrAddMb(int cusIdbtrAddMb) {
		this.cusIdbtrAddMb = cusIdbtrAddMb;
	}

	@Column(name = "CusIDbtrAddMs", nullable = false)
	public short getCusIdbtrAddMs() {
		return this.cusIdbtrAddMs;
	}

	public void setCusIdbtrAddMs(short cusIdbtrAddMs) {
		this.cusIdbtrAddMs = cusIdbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrAddMd", nullable = false, length = 23)
	public Date getCusIdbtrAddMd() {
		return this.cusIdbtrAddMd;
	}

	public void setCusIdbtrAddMd(Date cusIdbtrAddMd) {
		this.cusIdbtrAddMd = cusIdbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrAddMt", nullable = false, length = 23)
	public Date getCusIdbtrAddMt() {
		return this.cusIdbtrAddMt;
	}

	public void setCusIdbtrAddMt(Date cusIdbtrAddMt) {
		this.cusIdbtrAddMt = cusIdbtrAddMt;
	}

	@Column(name = "CusIDbtrAddCk", nullable = false)
	public int getCusIdbtrAddCk() {
		return this.cusIdbtrAddCk;
	}

	public void setCusIdbtrAddCk(int cusIdbtrAddCk) {
		this.cusIdbtrAddCk = cusIdbtrAddCk;
	}

	@Column(name = "CusIDbtrAddCb", nullable = false)
	public int getCusIdbtrAddCb() {
		return this.cusIdbtrAddCb;
	}

	public void setCusIdbtrAddCb(int cusIdbtrAddCb) {
		this.cusIdbtrAddCb = cusIdbtrAddCb;
	}

	@Column(name = "CusIDbtrAddCs", nullable = false)
	public short getCusIdbtrAddCs() {
		return this.cusIdbtrAddCs;
	}

	public void setCusIdbtrAddCs(short cusIdbtrAddCs) {
		this.cusIdbtrAddCs = cusIdbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrAddCd", nullable = false, length = 23)
	public Date getCusIdbtrAddCd() {
		return this.cusIdbtrAddCd;
	}

	public void setCusIdbtrAddCd(Date cusIdbtrAddCd) {
		this.cusIdbtrAddCd = cusIdbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrAddCt", nullable = false, length = 23)
	public Date getCusIdbtrAddCt() {
		return this.cusIdbtrAddCt;
	}

	public void setCusIdbtrAddCt(Date cusIdbtrAddCt) {
		this.cusIdbtrAddCt = cusIdbtrAddCt;
	}

	@Column(name = "CusIDbtrLupdMk", nullable = false)
	public int getCusIdbtrLupdMk() {
		return this.cusIdbtrLupdMk;
	}

	public void setCusIdbtrLupdMk(int cusIdbtrLupdMk) {
		this.cusIdbtrLupdMk = cusIdbtrLupdMk;
	}

	@Column(name = "CusIDbtrLupdMb", nullable = false)
	public int getCusIdbtrLupdMb() {
		return this.cusIdbtrLupdMb;
	}

	public void setCusIdbtrLupdMb(int cusIdbtrLupdMb) {
		this.cusIdbtrLupdMb = cusIdbtrLupdMb;
	}

	@Column(name = "CusIDbtrLupdMs", nullable = false)
	public short getCusIdbtrLupdMs() {
		return this.cusIdbtrLupdMs;
	}

	public void setCusIdbtrLupdMs(short cusIdbtrLupdMs) {
		this.cusIdbtrLupdMs = cusIdbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrLupdMd", nullable = false, length = 23)
	public Date getCusIdbtrLupdMd() {
		return this.cusIdbtrLupdMd;
	}

	public void setCusIdbtrLupdMd(Date cusIdbtrLupdMd) {
		this.cusIdbtrLupdMd = cusIdbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrLupdMt", nullable = false, length = 23)
	public Date getCusIdbtrLupdMt() {
		return this.cusIdbtrLupdMt;
	}

	public void setCusIdbtrLupdMt(Date cusIdbtrLupdMt) {
		this.cusIdbtrLupdMt = cusIdbtrLupdMt;
	}

	@Column(name = "CusIDbtrLupdCk", nullable = false)
	public int getCusIdbtrLupdCk() {
		return this.cusIdbtrLupdCk;
	}

	public void setCusIdbtrLupdCk(int cusIdbtrLupdCk) {
		this.cusIdbtrLupdCk = cusIdbtrLupdCk;
	}

	@Column(name = "CusIDbtrLupdCb", nullable = false)
	public int getCusIdbtrLupdCb() {
		return this.cusIdbtrLupdCb;
	}

	public void setCusIdbtrLupdCb(int cusIdbtrLupdCb) {
		this.cusIdbtrLupdCb = cusIdbtrLupdCb;
	}

	@Column(name = "CusIDbtrLupdCs", nullable = false)
	public short getCusIdbtrLupdCs() {
		return this.cusIdbtrLupdCs;
	}

	public void setCusIdbtrLupdCs(short cusIdbtrLupdCs) {
		this.cusIdbtrLupdCs = cusIdbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrLupdCd", nullable = false, length = 23)
	public Date getCusIdbtrLupdCd() {
		return this.cusIdbtrLupdCd;
	}

	public void setCusIdbtrLupdCd(Date cusIdbtrLupdCd) {
		this.cusIdbtrLupdCd = cusIdbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CusIDbtrLupdCt", nullable = false, length = 23)
	public Date getCusIdbtrLupdCt() {
		return this.cusIdbtrLupdCt;
	}

	public void setCusIdbtrLupdCt(Date cusIdbtrLupdCt) {
		this.cusIdbtrLupdCt = cusIdbtrLupdCt;
	}

	@Column(name = "CusIDbtrTAuthDone", nullable = false)
	public short getCusIdbtrTauthDone() {
		return this.cusIdbtrTauthDone;
	}

	public void setCusIdbtrTauthDone(short cusIdbtrTauthDone) {
		this.cusIdbtrTauthDone = cusIdbtrTauthDone;
	}

	@Column(name = "CusIDbtrRecStat", nullable = false)
	public byte getCusIdbtrRecStat() {
		return this.cusIdbtrRecStat;
	}

	public void setCusIdbtrRecStat(byte cusIdbtrRecStat) {
		this.cusIdbtrRecStat = cusIdbtrRecStat;
	}

	@Column(name = "CusIDbtrAuthDone", nullable = false)
	public byte getCusIdbtrAuthDone() {
		return this.cusIdbtrAuthDone;
	}

	public void setCusIdbtrAuthDone(byte cusIdbtrAuthDone) {
		this.cusIdbtrAuthDone = cusIdbtrAuthDone;
	}

	@Column(name = "CusIDbtrAuthNeeded", nullable = false)
	public byte getCusIdbtrAuthNeeded() {
		return this.cusIdbtrAuthNeeded;
	}

	public void setCusIdbtrAuthNeeded(byte cusIdbtrAuthNeeded) {
		this.cusIdbtrAuthNeeded = cusIdbtrAuthNeeded;
	}

	@Column(name = "CusIDbtrUpdtChkId", nullable = false)
	public short getCusIdbtrUpdtChkId() {
		return this.cusIdbtrUpdtChkId;
	}

	public void setCusIdbtrUpdtChkId(short cusIdbtrUpdtChkId) {
		this.cusIdbtrUpdtChkId = cusIdbtrUpdtChkId;
	}

	@Column(name = "CusIDbtrLHisTrnNo", nullable = false)
	public int getCusIdbtrLhisTrnNo() {
		return this.cusIdbtrLhisTrnNo;
	}

	public void setCusIdbtrLhisTrnNo(int cusIdbtrLhisTrnNo) {
		this.cusIdbtrLhisTrnNo = cusIdbtrLhisTrnNo;
	}

	@Column(name = "MemberNo", nullable = false)
	public int getMemberNo() {
		return this.memberNo;
	}

	public void setMemberNo(int memberNo) {
		this.memberNo = memberNo;
	}

	@Column(name = "SexCode", nullable = false, length = 2)
	public String getSexCode() {
		return this.sexCode;
	}

	public void setSexCode(String sexCode) {
		this.sexCode = sexCode;
	}

	@Column(name = "MemberType", nullable = false)
	public byte getMemberType() {
		return this.memberType;
	}

	public void setMemberType(byte memberType) {
		this.memberType = memberType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RetiredDate", nullable = false, length = 23)
	public Date getRetiredDate() {
		return this.retiredDate;
	}

	public void setRetiredDate(Date retiredDate) {
		this.retiredDate = retiredDate;
	}

	@Column(name = "EmployerCd", nullable = false)
	public short getEmployerCd() {
		return this.employerCd;
	}

	public void setEmployerCd(short employerCd) {
		this.employerCd = employerCd;
	}

	@Column(name = "Station", nullable = false)
	public short getStation() {
		return this.station;
	}

	public void setStation(short station) {
		this.station = station;
	}

	@Column(name = "RecovThru", nullable = false)
	public byte getRecovThru() {
		return this.recovThru;
	}

	public void setRecovThru(byte recovThru) {
		this.recovThru = recovThru;
	}

	@Column(name = "RelationName", nullable = false, length = 50)
	public String getRelationName() {
		return this.relationName;
	}

	public void setRelationName(String relationName) {
		this.relationName = relationName;
	}

	@Column(name = "BldGrp", nullable = false, length = 5)
	public String getBldGrp() {
		return this.bldGrp;
	}

	public void setBldGrp(String bldGrp) {
		this.bldGrp = bldGrp;
	}

	@Column(name = "ResiStatus", nullable = false)
	public byte getResiStatus() {
		return this.resiStatus;
	}

	public void setResiStatus(byte resiStatus) {
		this.resiStatus = resiStatus;
	}

	@Column(name = "RelationType", nullable = false, length = 4)
	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

	@Column(name = "PassPortNo", nullable = false, length = 20)
	public String getPassPortNo() {
		return this.passPortNo;
	}

	public void setPassPortNo(String passPortNo) {
		this.passPortNo = passPortNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VisaValUpTo", nullable = false, length = 23)
	public Date getVisaValUpTo() {
		return this.visaValUpTo;
	}

	public void setVisaValUpTo(Date visaValUpTo) {
		this.visaValUpTo = visaValUpTo;
	}

	@Column(name = "AMLRating", nullable = false)
	public short getAmlrating() {
		return this.amlrating;
	}

	public void setAmlrating(short amlrating) {
		this.amlrating = amlrating;
	}

	@Column(name = "ResdYN", nullable = false, length = 1)
	public char getResdYn() {
		return this.resdYn;
	}

	public void setResdYn(char resdYn) {
		this.resdYn = resdYn;
	}

	@Column(name = "KYCYN", nullable = false, length = 1)
	public char getKycyn() {
		return this.kycyn;
	}

	public void setKycyn(char kycyn) {
		this.kycyn = kycyn;
	}

	@Column(name = "IntroCustno", nullable = false)
	public int getIntroCustno() {
		return this.introCustno;
	}

	public void setIntroCustno(int introCustno) {
		this.introCustno = introCustno;
	}

	@Column(name = "RelOffCode", nullable = false, length = 8)
	public String getRelOffCode() {
		return this.relOffCode;
	}

	public void setRelOffCode(String relOffCode) {
		this.relOffCode = relOffCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MarriageDt", nullable = false, length = 23)
	public Date getMarriageDt() {
		return this.marriageDt;
	}

	public void setMarriageDt(Date marriageDt) {
		this.marriageDt = marriageDt;
	}

	@Column(name = "IsuAuthority", nullable = false)
	public short getIsuAuthority() {
		return this.isuAuthority;
	}

	public void setIsuAuthority(short isuAuthority) {
		this.isuAuthority = isuAuthority;
	}

	@Column(name = "IsuPlace", nullable = false, length = 3)
	public String getIsuPlace() {
		return this.isuPlace;
	}

	public void setIsuPlace(String isuPlace) {
		this.isuPlace = isuPlace;
	}

	@Column(name = "AdharNo", length = 15)
	public String getAdharNo() {
		return this.adharNo;
	}

	public void setAdharNo(String adharNo) {
		this.adharNo = adharNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PanRegDate", nullable = false, length = 23)
	public Date getPanRegDate() {
		return this.panRegDate;
	}

	public void setPanRegDate(Date panRegDate) {
		this.panRegDate = panRegDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeathDate", nullable = false, length = 23)
	public Date getDeathDate() {
		return this.deathDate;
	}

	public void setDeathDate(Date deathDate) {
		this.deathDate = deathDate;
	}

}
