package com.sil.hbm;
// Generated 16 Sep, 2016 12:40:53 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D010001 generated by hbm2java
 */
@Entity
@Table(name = "D010001")
@DynamicUpdate
@DynamicInsert
public class D010001 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1862553004755690690L;
	private D010001Id id;
	private String name;
	private String procStage1dr;
	private String balUdtTyp1dr;
	private String procStage2dr;
	private String balUdtTyp2dr;
	private String procStage3dr;
	private String balUdtTyp3dr;
	private String procStage4dr;
	private String balUdtTyp4dr;
	private char cancelUpToDr;
	private String procStage1cr;
	private String balUdtTyp1cr;
	private String procStage2cr;
	private String balUdtTyp2cr;
	private String procStage3cr;
	private String balUdtTyp3cr;
	private String procStage4cr;
	private String balUdtTyp4cr;
	private char cancelUpToCr;
	private String bookType;
	private char defOpenYn;
	private byte defPostDays;
	private byte defFeffDays;
	private char drCrVcPerm;
	private double maxDrAmt;
	private double maxCrAmt;
	private String defDesc;
	private byte vcEntryMngr;
	private byte status;
	private byte opClDay1;
	private byte opClDay2;
	private byte opClDay3;
	private char tallyType;
	private char tellerBatchYn;
	private char onOffBatch;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;

	public D010001() {
	}

	public D010001(D010001Id id, String name, String procStage1dr, String balUdtTyp1dr, String procStage2dr,
			String balUdtTyp2dr, String procStage3dr, String balUdtTyp3dr, String procStage4dr, String balUdtTyp4dr,
			char cancelUpToDr, String procStage1cr, String balUdtTyp1cr, String procStage2cr, String balUdtTyp2cr,
			String procStage3cr, String balUdtTyp3cr, String procStage4cr, String balUdtTyp4cr, char cancelUpToCr,
			String bookType, char defOpenYn, byte defPostDays, byte defFeffDays, char drCrVcPerm, double maxDrAmt,
			double maxCrAmt, String defDesc, byte vcEntryMngr, byte status, byte opClDay1, byte opClDay2, byte opClDay3,
			char tallyType, char tellerBatchYn, char onOffBatch, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.id = id;
		this.name = name;
		this.procStage1dr = procStage1dr;
		this.balUdtTyp1dr = balUdtTyp1dr;
		this.procStage2dr = procStage2dr;
		this.balUdtTyp2dr = balUdtTyp2dr;
		this.procStage3dr = procStage3dr;
		this.balUdtTyp3dr = balUdtTyp3dr;
		this.procStage4dr = procStage4dr;
		this.balUdtTyp4dr = balUdtTyp4dr;
		this.cancelUpToDr = cancelUpToDr;
		this.procStage1cr = procStage1cr;
		this.balUdtTyp1cr = balUdtTyp1cr;
		this.procStage2cr = procStage2cr;
		this.balUdtTyp2cr = balUdtTyp2cr;
		this.procStage3cr = procStage3cr;
		this.balUdtTyp3cr = balUdtTyp3cr;
		this.procStage4cr = procStage4cr;
		this.balUdtTyp4cr = balUdtTyp4cr;
		this.cancelUpToCr = cancelUpToCr;
		this.bookType = bookType;
		this.defOpenYn = defOpenYn;
		this.defPostDays = defPostDays;
		this.defFeffDays = defFeffDays;
		this.drCrVcPerm = drCrVcPerm;
		this.maxDrAmt = maxDrAmt;
		this.maxCrAmt = maxCrAmt;
		this.defDesc = defDesc;
		this.vcEntryMngr = vcEntryMngr;
		this.status = status;
		this.opClDay1 = opClDay1;
		this.opClDay2 = opClDay2;
		this.opClDay3 = opClDay3;
		this.tallyType = tallyType;
		this.tellerBatchYn = tellerBatchYn;
		this.onOffBatch = onOffBatch;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "code", column = @Column(name = "Code", nullable = false, length = 8)) })
	public D010001Id getId() {
		return this.id;
	}

	public void setId(D010001Id id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ProcStage1Dr", nullable = false, length = 5)
	public String getProcStage1dr() {
		return this.procStage1dr;
	}

	public void setProcStage1dr(String procStage1dr) {
		this.procStage1dr = procStage1dr;
	}

	@Column(name = "BalUdtTyp1Dr", nullable = false, length = 5)
	public String getBalUdtTyp1dr() {
		return this.balUdtTyp1dr;
	}

	public void setBalUdtTyp1dr(String balUdtTyp1dr) {
		this.balUdtTyp1dr = balUdtTyp1dr;
	}

	@Column(name = "ProcStage2Dr", nullable = false, length = 5)
	public String getProcStage2dr() {
		return this.procStage2dr;
	}

	public void setProcStage2dr(String procStage2dr) {
		this.procStage2dr = procStage2dr;
	}

	@Column(name = "BalUdtTyp2Dr", nullable = false, length = 5)
	public String getBalUdtTyp2dr() {
		return this.balUdtTyp2dr;
	}

	public void setBalUdtTyp2dr(String balUdtTyp2dr) {
		this.balUdtTyp2dr = balUdtTyp2dr;
	}

	@Column(name = "ProcStage3Dr", nullable = false, length = 5)
	public String getProcStage3dr() {
		return this.procStage3dr;
	}

	public void setProcStage3dr(String procStage3dr) {
		this.procStage3dr = procStage3dr;
	}

	@Column(name = "BalUdtTyp3Dr", nullable = false, length = 5)
	public String getBalUdtTyp3dr() {
		return this.balUdtTyp3dr;
	}

	public void setBalUdtTyp3dr(String balUdtTyp3dr) {
		this.balUdtTyp3dr = balUdtTyp3dr;
	}

	@Column(name = "ProcStage4Dr", nullable = false, length = 5)
	public String getProcStage4dr() {
		return this.procStage4dr;
	}

	public void setProcStage4dr(String procStage4dr) {
		this.procStage4dr = procStage4dr;
	}

	@Column(name = "BalUdtTyp4Dr", nullable = false, length = 5)
	public String getBalUdtTyp4dr() {
		return this.balUdtTyp4dr;
	}

	public void setBalUdtTyp4dr(String balUdtTyp4dr) {
		this.balUdtTyp4dr = balUdtTyp4dr;
	}

	@Column(name = "CancelUpToDr", nullable = false, length = 1)
	public char getCancelUpToDr() {
		return this.cancelUpToDr;
	}

	public void setCancelUpToDr(char cancelUpToDr) {
		this.cancelUpToDr = cancelUpToDr;
	}

	@Column(name = "ProcStage1Cr", nullable = false, length = 5)
	public String getProcStage1cr() {
		return this.procStage1cr;
	}

	public void setProcStage1cr(String procStage1cr) {
		this.procStage1cr = procStage1cr;
	}

	@Column(name = "BalUdtTyp1Cr", nullable = false, length = 5)
	public String getBalUdtTyp1cr() {
		return this.balUdtTyp1cr;
	}

	public void setBalUdtTyp1cr(String balUdtTyp1cr) {
		this.balUdtTyp1cr = balUdtTyp1cr;
	}

	@Column(name = "ProcStage2Cr", nullable = false, length = 5)
	public String getProcStage2cr() {
		return this.procStage2cr;
	}

	public void setProcStage2cr(String procStage2cr) {
		this.procStage2cr = procStage2cr;
	}

	@Column(name = "BalUdtTyp2Cr", nullable = false, length = 5)
	public String getBalUdtTyp2cr() {
		return this.balUdtTyp2cr;
	}

	public void setBalUdtTyp2cr(String balUdtTyp2cr) {
		this.balUdtTyp2cr = balUdtTyp2cr;
	}

	@Column(name = "ProcStage3Cr", nullable = false, length = 5)
	public String getProcStage3cr() {
		return this.procStage3cr;
	}

	public void setProcStage3cr(String procStage3cr) {
		this.procStage3cr = procStage3cr;
	}

	@Column(name = "BalUdtTyp3Cr", nullable = false, length = 5)
	public String getBalUdtTyp3cr() {
		return this.balUdtTyp3cr;
	}

	public void setBalUdtTyp3cr(String balUdtTyp3cr) {
		this.balUdtTyp3cr = balUdtTyp3cr;
	}

	@Column(name = "ProcStage4Cr", nullable = false, length = 5)
	public String getProcStage4cr() {
		return this.procStage4cr;
	}

	public void setProcStage4cr(String procStage4cr) {
		this.procStage4cr = procStage4cr;
	}

	@Column(name = "BalUdtTyp4Cr", nullable = false, length = 5)
	public String getBalUdtTyp4cr() {
		return this.balUdtTyp4cr;
	}

	public void setBalUdtTyp4cr(String balUdtTyp4cr) {
		this.balUdtTyp4cr = balUdtTyp4cr;
	}

	@Column(name = "CancelUpToCr", nullable = false, length = 1)
	public char getCancelUpToCr() {
		return this.cancelUpToCr;
	}

	public void setCancelUpToCr(char cancelUpToCr) {
		this.cancelUpToCr = cancelUpToCr;
	}

	@Column(name = "BookType", nullable = false, length = 2)
	public String getBookType() {
		return this.bookType;
	}

	public void setBookType(String bookType) {
		this.bookType = bookType;
	}

	@Column(name = "DefOpenYN", nullable = false, length = 1)
	public char getDefOpenYn() {
		return this.defOpenYn;
	}

	public void setDefOpenYn(char defOpenYn) {
		this.defOpenYn = defOpenYn;
	}

	@Column(name = "DefPostDays", nullable = false)
	public byte getDefPostDays() {
		return this.defPostDays;
	}

	public void setDefPostDays(byte defPostDays) {
		this.defPostDays = defPostDays;
	}

	@Column(name = "DefFeffDays", nullable = false)
	public byte getDefFeffDays() {
		return this.defFeffDays;
	}

	public void setDefFeffDays(byte defFeffDays) {
		this.defFeffDays = defFeffDays;
	}

	@Column(name = "DrCrVcPerm", nullable = false, length = 1)
	public char getDrCrVcPerm() {
		return this.drCrVcPerm;
	}

	public void setDrCrVcPerm(char drCrVcPerm) {
		this.drCrVcPerm = drCrVcPerm;
	}

	@Column(name = "MaxDrAmt", nullable = false, precision = 53, scale = 0)
	public double getMaxDrAmt() {
		return this.maxDrAmt;
	}

	public void setMaxDrAmt(double maxDrAmt) {
		this.maxDrAmt = maxDrAmt;
	}

	@Column(name = "MaxCrAmt", nullable = false, precision = 53, scale = 0)
	public double getMaxCrAmt() {
		return this.maxCrAmt;
	}

	public void setMaxCrAmt(double maxCrAmt) {
		this.maxCrAmt = maxCrAmt;
	}

	@Column(name = "DefDesc", nullable = false, length = 30)
	public String getDefDesc() {
		return this.defDesc;
	}

	public void setDefDesc(String defDesc) {
		this.defDesc = defDesc;
	}

	@Column(name = "VcEntryMngr", nullable = false)
	public byte getVcEntryMngr() {
		return this.vcEntryMngr;
	}

	public void setVcEntryMngr(byte vcEntryMngr) {
		this.vcEntryMngr = vcEntryMngr;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "OpClDay1", nullable = false)
	public byte getOpClDay1() {
		return this.opClDay1;
	}

	public void setOpClDay1(byte opClDay1) {
		this.opClDay1 = opClDay1;
	}

	@Column(name = "OpClDay2", nullable = false)
	public byte getOpClDay2() {
		return this.opClDay2;
	}

	public void setOpClDay2(byte opClDay2) {
		this.opClDay2 = opClDay2;
	}

	@Column(name = "OpClDay3", nullable = false)
	public byte getOpClDay3() {
		return this.opClDay3;
	}

	public void setOpClDay3(byte opClDay3) {
		this.opClDay3 = opClDay3;
	}

	@Column(name = "TallyType", nullable = false, length = 1)
	public char getTallyType() {
		return this.tallyType;
	}

	public void setTallyType(char tallyType) {
		this.tallyType = tallyType;
	}

	@Column(name = "TellerBatchYN", nullable = false, length = 1)
	public char getTellerBatchYn() {
		return this.tellerBatchYn;
	}

	public void setTellerBatchYn(char tellerBatchYn) {
		this.tellerBatchYn = tellerBatchYn;
	}

	@Column(name = "OnOffBatch", nullable = false, length = 1)
	public char getOnOffBatch() {
		return this.onOffBatch;
	}

	public void setOnOffBatch(char onOffBatch) {
		this.onOffBatch = onOffBatch;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

}
