package com.sil.hbm;
// Generated Dec 7, 2016 1:04:36 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D010080 generated by hbm2java
 */
@Entity
@Table(name = "D010080")
@DynamicUpdate
@DynamicInsert
public class D010080 implements java.io.Serializable {

	private static final long serialVersionUID = 4099318197209321869L;
	private D010080Id id;
	private int noofCheqBook;
	private byte status;
	private short insType;
	private String alphaCd;
	private String startInsNo;
	private short booksize;
	private Date createDate;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private int olbrCode;
	private String oissuedTo;
	private Date oissuedDate;
	private short oinsType;
	private String oalphaCd;
	private String ostartInsNo;
	private String oendInsNo;
	private byte addrType;
	private byte acctAddrType;
	private byte courierOnDay;
	private String insPrdCd;
	private char jtHolderYn;
	private byte signTitle;
	private short jtNameSrNo;
	private char atParYn;
	private short jtNameSrNo1;
	private short jtNameSrNo2;

	public D010080() {
	}

	public D010080(D010080Id id, int noofCheqBook, byte status, short insType, String alphaCd, String startInsNo,
			short booksize, Date createDate, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt,
			int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk,
			int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat,
			byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo, int olbrCode,
			String oissuedTo, Date oissuedDate, short oinsType, String oalphaCd, String ostartInsNo, String oendInsNo,
			byte addrType, byte acctAddrType, byte courierOnDay, String insPrdCd, char jtHolderYn, byte signTitle,
			short jtNameSrNo, char atParYn, short jtNameSrNo1, short jtNameSrNo2) {
		this.id = id;
		this.noofCheqBook = noofCheqBook;
		this.status = status;
		this.insType = insType;
		this.alphaCd = alphaCd;
		this.startInsNo = startInsNo;
		this.booksize = booksize;
		this.createDate = createDate;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.olbrCode = olbrCode;
		this.oissuedTo = oissuedTo;
		this.oissuedDate = oissuedDate;
		this.oinsType = oinsType;
		this.oalphaCd = oalphaCd;
		this.ostartInsNo = ostartInsNo;
		this.oendInsNo = oendInsNo;
		this.addrType = addrType;
		this.acctAddrType = acctAddrType;
		this.courierOnDay = courierOnDay;
		this.insPrdCd = insPrdCd;
		this.jtHolderYn = jtHolderYn;
		this.signTitle = signTitle;
		this.jtNameSrNo = jtNameSrNo;
		this.atParYn = atParYn;
		this.jtNameSrNo1 = jtNameSrNo1;
		this.jtNameSrNo2 = jtNameSrNo2;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "effDate", column = @Column(name = "EffDate", nullable = false, length = 23)),
			@AttributeOverride(name = "acctId", column = @Column(name = "AcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SrNo", nullable = false)) })
	public D010080Id getId() {
		return this.id;
	}

	public void setId(D010080Id id) {
		this.id = id;
	}

	@Column(name = "NoofCheqBook", nullable = false)
	public int getNoofCheqBook() {
		return this.noofCheqBook;
	}

	public void setNoofCheqBook(int noofCheqBook) {
		this.noofCheqBook = noofCheqBook;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "InsType", nullable = false)
	public short getInsType() {
		return this.insType;
	}

	public void setInsType(short insType) {
		this.insType = insType;
	}

	@Column(name = "AlphaCd", nullable = false, length = 4)
	public String getAlphaCd() {
		return this.alphaCd;
	}

	public void setAlphaCd(String alphaCd) {
		this.alphaCd = alphaCd;
	}

	@Column(name = "StartInsNo", nullable = false, length = 12)
	public String getStartInsNo() {
		return this.startInsNo;
	}

	public void setStartInsNo(String startInsNo) {
		this.startInsNo = startInsNo;
	}

	@Column(name = "Booksize", nullable = false)
	public short getBooksize() {
		return this.booksize;
	}

	public void setBooksize(short booksize) {
		this.booksize = booksize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "OLBrCode", nullable = false)
	public int getOlbrCode() {
		return this.olbrCode;
	}

	public void setOlbrCode(int olbrCode) {
		this.olbrCode = olbrCode;
	}

	@Column(name = "OissuedTo", nullable = false, length = 32)
	public String getOissuedTo() {
		return this.oissuedTo;
	}

	public void setOissuedTo(String oissuedTo) {
		this.oissuedTo = oissuedTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OissuedDate", nullable = false, length = 23)
	public Date getOissuedDate() {
		return this.oissuedDate;
	}

	public void setOissuedDate(Date oissuedDate) {
		this.oissuedDate = oissuedDate;
	}

	@Column(name = "OinsType", nullable = false)
	public short getOinsType() {
		return this.oinsType;
	}

	public void setOinsType(short oinsType) {
		this.oinsType = oinsType;
	}

	@Column(name = "OalphaCd", nullable = false, length = 4)
	public String getOalphaCd() {
		return this.oalphaCd;
	}

	public void setOalphaCd(String oalphaCd) {
		this.oalphaCd = oalphaCd;
	}

	@Column(name = "OstartInsNo", nullable = false, length = 12)
	public String getOstartInsNo() {
		return this.ostartInsNo;
	}

	public void setOstartInsNo(String ostartInsNo) {
		this.ostartInsNo = ostartInsNo;
	}

	@Column(name = "OEndInsNo", nullable = false, length = 12)
	public String getOendInsNo() {
		return this.oendInsNo;
	}

	public void setOendInsNo(String oendInsNo) {
		this.oendInsNo = oendInsNo;
	}

	@Column(name = "AddrType", nullable = false)
	public byte getAddrType() {
		return this.addrType;
	}

	public void setAddrType(byte addrType) {
		this.addrType = addrType;
	}

	@Column(name = "AcctAddrType", nullable = false)
	public byte getAcctAddrType() {
		return this.acctAddrType;
	}

	public void setAcctAddrType(byte acctAddrType) {
		this.acctAddrType = acctAddrType;
	}

	@Column(name = "CourierOnDay", nullable = false)
	public byte getCourierOnDay() {
		return this.courierOnDay;
	}

	public void setCourierOnDay(byte courierOnDay) {
		this.courierOnDay = courierOnDay;
	}

	@Column(name = "InsPrdCd", nullable = false, length = 8)
	public String getInsPrdCd() {
		return this.insPrdCd;
	}

	public void setInsPrdCd(String insPrdCd) {
		this.insPrdCd = insPrdCd;
	}

	@Column(name = "JtHolderYN", nullable = false, length = 1)
	public char getJtHolderYn() {
		return this.jtHolderYn;
	}

	public void setJtHolderYn(char jtHolderYn) {
		this.jtHolderYn = jtHolderYn;
	}

	@Column(name = "SignTitle", nullable = false)
	public byte getSignTitle() {
		return this.signTitle;
	}

	public void setSignTitle(byte signTitle) {
		this.signTitle = signTitle;
	}

	@Column(name = "JtNameSrNo", nullable = false)
	public short getJtNameSrNo() {
		return this.jtNameSrNo;
	}

	public void setJtNameSrNo(short jtNameSrNo) {
		this.jtNameSrNo = jtNameSrNo;
	}

	@Column(name = "AtParYN", nullable = false, length = 1)
	public char getAtParYn() {
		return this.atParYn;
	}

	public void setAtParYn(char atParYn) {
		this.atParYn = atParYn;
	}

	@Column(name = "JtNameSrNo1", nullable = false)
	public short getJtNameSrNo1() {
		return this.jtNameSrNo1;
	}

	public void setJtNameSrNo1(short jtNameSrNo1) {
		this.jtNameSrNo1 = jtNameSrNo1;
	}

	@Column(name = "JtNameSrNo2", nullable = false)
	public short getJtNameSrNo2() {
		return this.jtNameSrNo2;
	}

	public void setJtNameSrNo2(short jtNameSrNo2) {
		this.jtNameSrNo2 = jtNameSrNo2;
	}

}
