package com.sil.hbm;
// Generated Dec 7, 2016 1:04:36 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D010080Id generated by hbm2java
 */
@Embeddable
public class D010080Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9008948483226536649L;
	private int lbrCode;
	private Date effDate;
	private String acctId;
	private int srNo;

	public D010080Id() {
	}

	public D010080Id(int lbrCode, Date effDate, String acctId, int srNo) {
		this.lbrCode = lbrCode;
		this.effDate = effDate;
		this.acctId = acctId;
		this.srNo = srNo;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "EffDate", nullable = false, length = 23)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Column(name = "AcctId", nullable = false, length = 32)
	public String getAcctId() {
		return this.acctId;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	@Column(name = "SrNo", nullable = false)
	public int getSrNo() {
		return this.srNo;
	}

	public void setSrNo(int srNo) {
		this.srNo = srNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D010080Id))
			return false;
		D010080Id castOther = (D010080Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getEffDate() == castOther.getEffDate()) || (this.getEffDate() != null
						&& castOther.getEffDate() != null && this.getEffDate().equals(castOther.getEffDate())))
				&& ((this.getAcctId() == castOther.getAcctId()) || (this.getAcctId() != null
						&& castOther.getAcctId() != null && this.getAcctId().equals(castOther.getAcctId())))
				&& (this.getSrNo() == castOther.getSrNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getEffDate() == null ? 0 : this.getEffDate().hashCode());
		result = 37 * result + (getAcctId() == null ? 0 : this.getAcctId().hashCode());
		result = 37 * result + this.getSrNo();
		return result;
	}

}
