package com.sil.hbm;
// Generated Jan 31, 2017 3:32:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D010103 generated by hbm2java
 */
@Entity
@Table(name = "D010103")
@DynamicUpdate
@DynamicInsert
public class D010103 implements java.io.Serializable {

	private static final long serialVersionUID = -7743794802995193481L;
	private D010103Id id;
	private short validBookSize;
	private short mlDbtrBijIdx;
	private short mlDbtrUaeIdx;

	public D010103() {
	}

	public D010103(D010103Id id, short validBookSize, short mlDbtrBijIdx, short mlDbtrUaeIdx) {
		this.id = id;
		this.validBookSize = validBookSize;
		this.mlDbtrBijIdx = mlDbtrBijIdx;
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itpType", column = @Column(name = "ItpType", nullable = false)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SrNo", nullable = false)) })
	public D010103Id getId() {
		return this.id;
	}

	public void setId(D010103Id id) {
		this.id = id;
	}

	@Column(name = "ValidBookSize", nullable = false)
	public short getValidBookSize() {
		return this.validBookSize;
	}

	public void setValidBookSize(short validBookSize) {
		this.validBookSize = validBookSize;
	}

	@Column(name = "MlDbtrBijIdx", nullable = false)
	public short getMlDbtrBijIdx() {
		return this.mlDbtrBijIdx;
	}

	public void setMlDbtrBijIdx(short mlDbtrBijIdx) {
		this.mlDbtrBijIdx = mlDbtrBijIdx;
	}

	@Column(name = "MlDbtrUaeIdx", nullable = false)
	public short getMlDbtrUaeIdx() {
		return this.mlDbtrUaeIdx;
	}

	public void setMlDbtrUaeIdx(short mlDbtrUaeIdx) {
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

}
