package com.sil.hbm;
// Generated Jan 31, 2017 3:32:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D010103Id generated by hbm2java
 */
@Embeddable
public class D010103Id implements java.io.Serializable {

	private short itpType;
	private byte srNo;

	public D010103Id() {
	}

	public D010103Id(short itpType, byte srNo) {
		this.itpType = itpType;
		this.srNo = srNo;
	}

	@Column(name = "ItpType", nullable = false)
	public short getItpType() {
		return this.itpType;
	}

	public void setItpType(short itpType) {
		this.itpType = itpType;
	}

	@Column(name = "SrNo", nullable = false)
	public byte getSrNo() {
		return this.srNo;
	}

	public void setSrNo(byte srNo) {
		this.srNo = srNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D010103Id))
			return false;
		D010103Id castOther = (D010103Id) other;

		return (this.getItpType() == castOther.getItpType()) && (this.getSrNo() == castOther.getSrNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItpType();
		result = 37 * result + this.getSrNo();
		return result;
	}

}
