package com.sil.hbm;
// Generated Mar 10, 2018 4:06:03 PM by Hibernate Tools 5.2.0.Beta1
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D010153Id generated by hbm2java
 */
@Embeddable
public class D010153Id implements java.io.Serializable {
	private static final long serialVersionUID = 5141896590896452781L;
	private int lbrCode;
	private String prdAcctId;
	private byte nameType;
	private short srNo;

	public D010153Id() {
	}

	public D010153Id(int lbrCode, String prdAcctId, byte nameType, short srNo) {
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
		this.nameType = nameType;
		this.srNo = srNo;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "NameType", nullable = false)
	public byte getNameType() {
		return this.nameType;
	}

	public void setNameType(byte nameType) {
		this.nameType = nameType;
	}

	@Column(name = "SrNo", nullable = false)
	public short getSrNo() {
		return this.srNo;
	}

	public void setSrNo(short srNo) {
		this.srNo = srNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D010153Id))
			return false;
		D010153Id castOther = (D010153Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getPrdAcctId() == castOther.getPrdAcctId()) || (this.getPrdAcctId() != null
						&& castOther.getPrdAcctId() != null && this.getPrdAcctId().equals(castOther.getPrdAcctId())))
				&& (this.getNameType() == castOther.getNameType()) && (this.getSrNo() == castOther.getSrNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getPrdAcctId() == null ? 0 : this.getPrdAcctId().hashCode());
		result = 37 * result + this.getNameType();
		result = 37 * result + this.getSrNo();
		return result;
	}

}
