package com.sil.hbm;
// Generated Mar 10, 2018 4:06:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D010153 generated by hbm2java
 */
@Entity
@Table(name = "D010153")
@DynamicUpdate
@DynamicInsert
public class D010153 implements java.io.Serializable {

	private static final long serialVersionUID = 2391407273356843358L;
	private D010153Id id;
	private int cusNo;
	private String name;
	private String nameTitle;
	private short mlDbtrBijIdx;
	private short mlDbtrUaeIdx;

	public D010153() {
	}

	public D010153(D010153Id id, int cusNo, String name, String nameTitle, short mlDbtrBijIdx, short mlDbtrUaeIdx) {
		this.id = id;
		this.cusNo = cusNo;
		this.name = name;
		this.nameTitle = nameTitle;
		this.mlDbtrBijIdx = mlDbtrBijIdx;
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "nameType", column = @Column(name = "NameType", nullable = false)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SrNo", nullable = false)) })
	public D010153Id getId() {
		return this.id;
	}

	public void setId(D010153Id id) {
		this.id = id;
	}

	@Column(name = "CusNo", nullable = false)
	public int getCusNo() {
		return this.cusNo;
	}

	public void setCusNo(int cusNo) {
		this.cusNo = cusNo;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NameTitle", nullable = false, length = 4)
	public String getNameTitle() {
		return this.nameTitle;
	}

	public void setNameTitle(String nameTitle) {
		this.nameTitle = nameTitle;
	}

	@Column(name = "MlDbtrBijIdx", nullable = false)
	public short getMlDbtrBijIdx() {
		return this.mlDbtrBijIdx;
	}

	public void setMlDbtrBijIdx(short mlDbtrBijIdx) {
		this.mlDbtrBijIdx = mlDbtrBijIdx;
	}

	@Column(name = "MlDbtrUaeIdx", nullable = false)
	public short getMlDbtrUaeIdx() {
		return this.mlDbtrUaeIdx;
	}

	public void setMlDbtrUaeIdx(short mlDbtrUaeIdx) {
		this.mlDbtrUaeIdx = mlDbtrUaeIdx;
	}

}
