package com.sil.hbm;
// Generated 14 Mar, 2017 6:08:16 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D010014 generated by hbm2java
 */
@Entity
@Table(name = "D010014")
@DynamicUpdate
@DynamicInsert
public class D010014 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4281776360833529137L;
	private D010014Id id;
	private double balance1;
	private double balance2;
	private double balance3;
	private double balance4;
	private double balance5;
	private double balance6;
	private double balance7;
	private double balance8;
	private double balance9;
	private double balance10;
	private double balance11;
	private double balance12;
	private double balance13;
	private double balance14;
	private double balance15;

	public D010014() {
	}

	public D010014(D010014Id id, double balance1, double balance2, double balance3, double balance4, double balance5,
			double balance6, double balance7, double balance8, double balance9, double balance10, double balance11,
			double balance12, double balance13, double balance14, double balance15) {
		this.id = id;
		this.balance1 = balance1;
		this.balance2 = balance2;
		this.balance3 = balance3;
		this.balance4 = balance4;
		this.balance5 = balance5;
		this.balance6 = balance6;
		this.balance7 = balance7;
		this.balance8 = balance8;
		this.balance9 = balance9;
		this.balance10 = balance10;
		this.balance11 = balance11;
		this.balance12 = balance12;
		this.balance13 = balance13;
		this.balance14 = balance14;
		this.balance15 = balance15;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "cblDate", column = @Column(name = "CblDate", nullable = false, length = 23)) })
	public D010014Id getId() {
		return this.id;
	}

	public void setId(D010014Id id) {
		this.id = id;
	}

	@Column(name = "Balance1", nullable = false, precision = 53, scale = 0)
	public double getBalance1() {
		return this.balance1;
	}

	public void setBalance1(double balance1) {
		this.balance1 = balance1;
	}

	@Column(name = "Balance2", nullable = false, precision = 53, scale = 0)
	public double getBalance2() {
		return this.balance2;
	}

	public void setBalance2(double balance2) {
		this.balance2 = balance2;
	}

	@Column(name = "Balance3", nullable = false, precision = 53, scale = 0)
	public double getBalance3() {
		return this.balance3;
	}

	public void setBalance3(double balance3) {
		this.balance3 = balance3;
	}

	@Column(name = "Balance4", nullable = false, precision = 53, scale = 0)
	public double getBalance4() {
		return this.balance4;
	}

	public void setBalance4(double balance4) {
		this.balance4 = balance4;
	}

	@Column(name = "Balance5", nullable = false, precision = 53, scale = 0)
	public double getBalance5() {
		return this.balance5;
	}

	public void setBalance5(double balance5) {
		this.balance5 = balance5;
	}

	@Column(name = "Balance6", nullable = false, precision = 53, scale = 0)
	public double getBalance6() {
		return this.balance6;
	}

	public void setBalance6(double balance6) {
		this.balance6 = balance6;
	}

	@Column(name = "Balance7", nullable = false, precision = 53, scale = 0)
	public double getBalance7() {
		return this.balance7;
	}

	public void setBalance7(double balance7) {
		this.balance7 = balance7;
	}

	@Column(name = "Balance8", nullable = false, precision = 53, scale = 0)
	public double getBalance8() {
		return this.balance8;
	}

	public void setBalance8(double balance8) {
		this.balance8 = balance8;
	}

	@Column(name = "Balance9", nullable = false, precision = 53, scale = 0)
	public double getBalance9() {
		return this.balance9;
	}

	public void setBalance9(double balance9) {
		this.balance9 = balance9;
	}

	@Column(name = "Balance10", nullable = false, precision = 53, scale = 0)
	public double getBalance10() {
		return this.balance10;
	}

	public void setBalance10(double balance10) {
		this.balance10 = balance10;
	}

	@Column(name = "Balance11", nullable = false, precision = 53, scale = 0)
	public double getBalance11() {
		return this.balance11;
	}

	public void setBalance11(double balance11) {
		this.balance11 = balance11;
	}

	@Column(name = "Balance12", nullable = false, precision = 53, scale = 0)
	public double getBalance12() {
		return this.balance12;
	}

	public void setBalance12(double balance12) {
		this.balance12 = balance12;
	}

	@Column(name = "Balance13", nullable = false, precision = 53, scale = 0)
	public double getBalance13() {
		return this.balance13;
	}

	public void setBalance13(double balance13) {
		this.balance13 = balance13;
	}

	@Column(name = "Balance14", nullable = false, precision = 53, scale = 0)
	public double getBalance14() {
		return this.balance14;
	}

	public void setBalance14(double balance14) {
		this.balance14 = balance14;
	}

	@Column(name = "Balance15", nullable = false, precision = 53, scale = 0)
	public double getBalance15() {
		return this.balance15;
	}

	public void setBalance15(double balance15) {
		this.balance15 = balance15;
	}

}
