package com.sil.hbm;
// Generated Jul 4, 2017 1:26:28 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D030002 generated by hbm2java
 */
@Entity
@Table(name = "D030002")
@DynamicUpdate
@DynamicInsert
public class D030002 implements java.io.Serializable {
	private static final long serialVersionUID = 6110164560418387012L;
	private D030002Id id;
	private byte lnType;
	private char equatedYn;
	private char intFundedYn;
	private char staffLnYn;
	private char intApplFreq;
	private byte prodCalcType;
	private byte grcDaysForInst;
	private byte grcDaysForInt;
	private double penalRate;
	private double intTax;
	private String intRoffOpt;
	private String defBatchCd;
	private String drCrPrdAcctId;
	private String irPrdAcctId;
	private String ioPrdAcctId;
	private String lastIntAppStat;
	private Date lastIntAppFrDt;
	private Date lastIntAppToDt;
	private int lastIntTotAcct;
	private String lastIntAppAcct;
	private short noOfMthsValDate;
	private char intChgFlag;
	private String penalChgDrId;
	private String penalChgCrId;
	private byte minDayForInt;
	private char disIntYn;
	private short daysInYear;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private double maxPenalRate;
	private double npaPenRate;
	private double maxSancLimit;
	private char npaDtYn;
	private char fullMonthIntYn;
	private String unRecovExpAc;
	private String nirPrdAcctId;
	private String nioPrdAcctId;
	private String npirPrdAcctId;
	private String npioPrdAcctId;
	private String norPrdAcctId;
	private String nooPrdAcctId;
	private byte gfrate;

	public D030002() {
	}

	public D030002(D030002Id id, byte lnType, char equatedYn, char intFundedYn, char staffLnYn, char intApplFreq,
			byte prodCalcType, byte grcDaysForInst, byte grcDaysForInt, double penalRate, double intTax,
			String intRoffOpt, String defBatchCd, String drCrPrdAcctId, String irPrdAcctId, String ioPrdAcctId,
			String lastIntAppStat, Date lastIntAppFrDt, Date lastIntAppToDt, int lastIntTotAcct, String lastIntAppAcct,
			short noOfMthsValDate, char intChgFlag, String penalChgDrId, String penalChgCrId, byte minDayForInt,
			char disIntYn, short daysInYear, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt,
			int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk,
			int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat,
			byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo, double maxPenalRate,
			double npaPenRate, double maxSancLimit, char npaDtYn, char fullMonthIntYn, String unRecovExpAc,
			String nirPrdAcctId, String nioPrdAcctId, String npirPrdAcctId, String npioPrdAcctId, String norPrdAcctId,
			String nooPrdAcctId, byte gfrate) {
		this.id = id;
		this.lnType = lnType;
		this.equatedYn = equatedYn;
		this.intFundedYn = intFundedYn;
		this.staffLnYn = staffLnYn;
		this.intApplFreq = intApplFreq;
		this.prodCalcType = prodCalcType;
		this.grcDaysForInst = grcDaysForInst;
		this.grcDaysForInt = grcDaysForInt;
		this.penalRate = penalRate;
		this.intTax = intTax;
		this.intRoffOpt = intRoffOpt;
		this.defBatchCd = defBatchCd;
		this.drCrPrdAcctId = drCrPrdAcctId;
		this.irPrdAcctId = irPrdAcctId;
		this.ioPrdAcctId = ioPrdAcctId;
		this.lastIntAppStat = lastIntAppStat;
		this.lastIntAppFrDt = lastIntAppFrDt;
		this.lastIntAppToDt = lastIntAppToDt;
		this.lastIntTotAcct = lastIntTotAcct;
		this.lastIntAppAcct = lastIntAppAcct;
		this.noOfMthsValDate = noOfMthsValDate;
		this.intChgFlag = intChgFlag;
		this.penalChgDrId = penalChgDrId;
		this.penalChgCrId = penalChgCrId;
		this.minDayForInt = minDayForInt;
		this.disIntYn = disIntYn;
		this.daysInYear = daysInYear;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.maxPenalRate = maxPenalRate;
		this.npaPenRate = npaPenRate;
		this.maxSancLimit = maxSancLimit;
		this.npaDtYn = npaDtYn;
		this.fullMonthIntYn = fullMonthIntYn;
		this.unRecovExpAc = unRecovExpAc;
		this.nirPrdAcctId = nirPrdAcctId;
		this.nioPrdAcctId = nioPrdAcctId;
		this.npirPrdAcctId = npirPrdAcctId;
		this.npioPrdAcctId = npioPrdAcctId;
		this.norPrdAcctId = norPrdAcctId;
		this.nooPrdAcctId = nooPrdAcctId;
		this.gfrate = gfrate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdCd", column = @Column(name = "PrdCd", nullable = false, length = 8)) })
	public D030002Id getId() {
		return this.id;
	}

	public void setId(D030002Id id) {
		this.id = id;
	}

	@Column(name = "LnType", nullable = false)
	public byte getLnType() {
		return this.lnType;
	}

	public void setLnType(byte lnType) {
		this.lnType = lnType;
	}

	@Column(name = "EquatedYN", nullable = false, length = 1)
	public char getEquatedYn() {
		return this.equatedYn;
	}

	public void setEquatedYn(char equatedYn) {
		this.equatedYn = equatedYn;
	}

	@Column(name = "IntFundedYN", nullable = false, length = 1)
	public char getIntFundedYn() {
		return this.intFundedYn;
	}

	public void setIntFundedYn(char intFundedYn) {
		this.intFundedYn = intFundedYn;
	}

	@Column(name = "StaffLnYN", nullable = false, length = 1)
	public char getStaffLnYn() {
		return this.staffLnYn;
	}

	public void setStaffLnYn(char staffLnYn) {
		this.staffLnYn = staffLnYn;
	}

	@Column(name = "IntApplFreq", nullable = false, length = 1)
	public char getIntApplFreq() {
		return this.intApplFreq;
	}

	public void setIntApplFreq(char intApplFreq) {
		this.intApplFreq = intApplFreq;
	}

	@Column(name = "ProdCalcType", nullable = false)
	public byte getProdCalcType() {
		return this.prodCalcType;
	}

	public void setProdCalcType(byte prodCalcType) {
		this.prodCalcType = prodCalcType;
	}

	@Column(name = "GrcDaysForInst", nullable = false)
	public byte getGrcDaysForInst() {
		return this.grcDaysForInst;
	}

	public void setGrcDaysForInst(byte grcDaysForInst) {
		this.grcDaysForInst = grcDaysForInst;
	}

	@Column(name = "GrcDaysForInt", nullable = false)
	public byte getGrcDaysForInt() {
		return this.grcDaysForInt;
	}

	public void setGrcDaysForInt(byte grcDaysForInt) {
		this.grcDaysForInt = grcDaysForInt;
	}

	@Column(name = "PenalRate", nullable = false, precision = 53, scale = 0)
	public double getPenalRate() {
		return this.penalRate;
	}

	public void setPenalRate(double penalRate) {
		this.penalRate = penalRate;
	}

	@Column(name = "IntTax", nullable = false, precision = 53, scale = 0)
	public double getIntTax() {
		return this.intTax;
	}

	public void setIntTax(double intTax) {
		this.intTax = intTax;
	}

	@Column(name = "IntRoffOpt", nullable = false, length = 2)
	public String getIntRoffOpt() {
		return this.intRoffOpt;
	}

	public void setIntRoffOpt(String intRoffOpt) {
		this.intRoffOpt = intRoffOpt;
	}

	@Column(name = "DefBatchCd", nullable = false, length = 8)
	public String getDefBatchCd() {
		return this.defBatchCd;
	}

	public void setDefBatchCd(String defBatchCd) {
		this.defBatchCd = defBatchCd;
	}

	@Column(name = "DrCrPrdAcctId", nullable = false, length = 32)
	public String getDrCrPrdAcctId() {
		return this.drCrPrdAcctId;
	}

	public void setDrCrPrdAcctId(String drCrPrdAcctId) {
		this.drCrPrdAcctId = drCrPrdAcctId;
	}

	@Column(name = "IrPrdAcctId", nullable = false, length = 32)
	public String getIrPrdAcctId() {
		return this.irPrdAcctId;
	}

	public void setIrPrdAcctId(String irPrdAcctId) {
		this.irPrdAcctId = irPrdAcctId;
	}

	@Column(name = "IoPrdAcctId", nullable = false, length = 32)
	public String getIoPrdAcctId() {
		return this.ioPrdAcctId;
	}

	public void setIoPrdAcctId(String ioPrdAcctId) {
		this.ioPrdAcctId = ioPrdAcctId;
	}

	@Column(name = "LastIntAppStat", nullable = false, length = 25)
	public String getLastIntAppStat() {
		return this.lastIntAppStat;
	}

	public void setLastIntAppStat(String lastIntAppStat) {
		this.lastIntAppStat = lastIntAppStat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastIntAppFrDt", nullable = false, length = 23)
	public Date getLastIntAppFrDt() {
		return this.lastIntAppFrDt;
	}

	public void setLastIntAppFrDt(Date lastIntAppFrDt) {
		this.lastIntAppFrDt = lastIntAppFrDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastIntAppToDt", nullable = false, length = 23)
	public Date getLastIntAppToDt() {
		return this.lastIntAppToDt;
	}

	public void setLastIntAppToDt(Date lastIntAppToDt) {
		this.lastIntAppToDt = lastIntAppToDt;
	}

	@Column(name = "LastIntTotAcct", nullable = false)
	public int getLastIntTotAcct() {
		return this.lastIntTotAcct;
	}

	public void setLastIntTotAcct(int lastIntTotAcct) {
		this.lastIntTotAcct = lastIntTotAcct;
	}

	@Column(name = "LastIntAppAcct", nullable = false, length = 32)
	public String getLastIntAppAcct() {
		return this.lastIntAppAcct;
	}

	public void setLastIntAppAcct(String lastIntAppAcct) {
		this.lastIntAppAcct = lastIntAppAcct;
	}

	@Column(name = "NoOfMthsValDate", nullable = false)
	public short getNoOfMthsValDate() {
		return this.noOfMthsValDate;
	}

	public void setNoOfMthsValDate(short noOfMthsValDate) {
		this.noOfMthsValDate = noOfMthsValDate;
	}

	@Column(name = "IntChgFlag", nullable = false, length = 1)
	public char getIntChgFlag() {
		return this.intChgFlag;
	}

	public void setIntChgFlag(char intChgFlag) {
		this.intChgFlag = intChgFlag;
	}

	@Column(name = "PenalChgDrId", nullable = false, length = 32)
	public String getPenalChgDrId() {
		return this.penalChgDrId;
	}

	public void setPenalChgDrId(String penalChgDrId) {
		this.penalChgDrId = penalChgDrId;
	}

	@Column(name = "PenalChgCrId", nullable = false, length = 32)
	public String getPenalChgCrId() {
		return this.penalChgCrId;
	}

	public void setPenalChgCrId(String penalChgCrId) {
		this.penalChgCrId = penalChgCrId;
	}

	@Column(name = "MinDayForInt", nullable = false)
	public byte getMinDayForInt() {
		return this.minDayForInt;
	}

	public void setMinDayForInt(byte minDayForInt) {
		this.minDayForInt = minDayForInt;
	}

	@Column(name = "DisIntYN", nullable = false, length = 1)
	public char getDisIntYn() {
		return this.disIntYn;
	}

	public void setDisIntYn(char disIntYn) {
		this.disIntYn = disIntYn;
	}

	@Column(name = "DaysInYear", nullable = false)
	public short getDaysInYear() {
		return this.daysInYear;
	}

	public void setDaysInYear(short daysInYear) {
		this.daysInYear = daysInYear;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "MaxPenalRate", nullable = false, precision = 53, scale = 0)
	public double getMaxPenalRate() {
		return this.maxPenalRate;
	}

	public void setMaxPenalRate(double maxPenalRate) {
		this.maxPenalRate = maxPenalRate;
	}

	@Column(name = "NpaPenRate", nullable = false, precision = 53, scale = 0)
	public double getNpaPenRate() {
		return this.npaPenRate;
	}

	public void setNpaPenRate(double npaPenRate) {
		this.npaPenRate = npaPenRate;
	}

	@Column(name = "MaxSancLimit", nullable = false, precision = 53, scale = 0)
	public double getMaxSancLimit() {
		return this.maxSancLimit;
	}

	public void setMaxSancLimit(double maxSancLimit) {
		this.maxSancLimit = maxSancLimit;
	}

	@Column(name = "NpaDtYN", nullable = false, length = 1)
	public char getNpaDtYn() {
		return this.npaDtYn;
	}

	public void setNpaDtYn(char npaDtYn) {
		this.npaDtYn = npaDtYn;
	}

	@Column(name = "FullMonthIntYN", nullable = false, length = 1)
	public char getFullMonthIntYn() {
		return this.fullMonthIntYn;
	}

	public void setFullMonthIntYn(char fullMonthIntYn) {
		this.fullMonthIntYn = fullMonthIntYn;
	}

	@Column(name = "UnRecovExpAc", nullable = false, length = 32)
	public String getUnRecovExpAc() {
		return this.unRecovExpAc;
	}

	public void setUnRecovExpAc(String unRecovExpAc) {
		this.unRecovExpAc = unRecovExpAc;
	}

	@Column(name = "NIrPrdAcctId", nullable = false, length = 32)
	public String getNirPrdAcctId() {
		return this.nirPrdAcctId;
	}

	public void setNirPrdAcctId(String nirPrdAcctId) {
		this.nirPrdAcctId = nirPrdAcctId;
	}

	@Column(name = "NIoPrdAcctId", nullable = false, length = 32)
	public String getNioPrdAcctId() {
		return this.nioPrdAcctId;
	}

	public void setNioPrdAcctId(String nioPrdAcctId) {
		this.nioPrdAcctId = nioPrdAcctId;
	}

	@Column(name = "NPIrPrdAcctId", nullable = false, length = 32)
	public String getNpirPrdAcctId() {
		return this.npirPrdAcctId;
	}

	public void setNpirPrdAcctId(String npirPrdAcctId) {
		this.npirPrdAcctId = npirPrdAcctId;
	}

	@Column(name = "NPIoPrdAcctId", nullable = false, length = 32)
	public String getNpioPrdAcctId() {
		return this.npioPrdAcctId;
	}

	public void setNpioPrdAcctId(String npioPrdAcctId) {
		this.npioPrdAcctId = npioPrdAcctId;
	}

	@Column(name = "NOrPrdAcctId", nullable = false, length = 32)
	public String getNorPrdAcctId() {
		return this.norPrdAcctId;
	}

	public void setNorPrdAcctId(String norPrdAcctId) {
		this.norPrdAcctId = norPrdAcctId;
	}

	@Column(name = "NOoPrdAcctId", nullable = false, length = 32)
	public String getNooPrdAcctId() {
		return this.nooPrdAcctId;
	}

	public void setNooPrdAcctId(String nooPrdAcctId) {
		this.nooPrdAcctId = nooPrdAcctId;
	}

	@Column(name = "GFRate", nullable = false)
	public byte getGfrate() {
		return this.gfrate;
	}

	public void setGfrate(byte gfrate) {
		this.gfrate = gfrate;
	}

	@Override
	public String toString() {
		return "D030002 [id=" + id + ", lnType=" + lnType + ", equatedYn=" + equatedYn + ", intFundedYn=" + intFundedYn
				+ ", staffLnYn=" + staffLnYn + ", intApplFreq=" + intApplFreq + ", prodCalcType=" + prodCalcType
				+ ", grcDaysForInst=" + grcDaysForInst + ", grcDaysForInt=" + grcDaysForInt + ", penalRate=" + penalRate
				+ ", intTax=" + intTax + ", intRoffOpt=" + intRoffOpt + ", defBatchCd=" + defBatchCd
				+ ", drCrPrdAcctId=" + drCrPrdAcctId + ", irPrdAcctId=" + irPrdAcctId + ", ioPrdAcctId=" + ioPrdAcctId
				+ ", lastIntAppStat=" + lastIntAppStat + ", lastIntAppFrDt=" + lastIntAppFrDt + ", lastIntAppToDt="
				+ lastIntAppToDt + ", lastIntTotAcct=" + lastIntTotAcct + ", lastIntAppAcct=" + lastIntAppAcct
				+ ", noOfMthsValDate=" + noOfMthsValDate + ", intChgFlag=" + intChgFlag + ", penalChgDrId="
				+ penalChgDrId + ", penalChgCrId=" + penalChgCrId + ", minDayForInt=" + minDayForInt + ", disIntYn="
				+ disIntYn + ", daysInYear=" + daysInYear + ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb=" + dbtrAddMb
				+ ", dbtrAddMs=" + dbtrAddMs + ", dbtrAddMd=" + dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt + ", dbtrAddCk="
				+ dbtrAddCk + ", dbtrAddCb=" + dbtrAddCb + ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd=" + dbtrAddCd
				+ ", dbtrAddCt=" + dbtrAddCt + ", dbtrLupdMk=" + dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb
				+ ", dbtrLupdMs=" + dbtrLupdMs + ", dbtrLupdMd=" + dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt
				+ ", dbtrLupdCk=" + dbtrLupdCk + ", dbtrLupdCb=" + dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs
				+ ", dbtrLupdCd=" + dbtrLupdCd + ", dbtrLupdCt=" + dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone
				+ ", dbtrRecStat=" + dbtrRecStat + ", dbtrAuthDone=" + dbtrAuthDone + ", dbtrAuthNeeded="
				+ dbtrAuthNeeded + ", dbtrUpdtChkId=" + dbtrUpdtChkId + ", dbtrLhisTrnNo=" + dbtrLhisTrnNo
				+ ", maxPenalRate=" + maxPenalRate + ", npaPenRate=" + npaPenRate + ", maxSancLimit=" + maxSancLimit
				+ ", npaDtYn=" + npaDtYn + ", fullMonthIntYn=" + fullMonthIntYn + ", unRecovExpAc=" + unRecovExpAc
				+ ", nirPrdAcctId=" + nirPrdAcctId + ", nioPrdAcctId=" + nioPrdAcctId + ", npirPrdAcctId="
				+ npirPrdAcctId + ", npioPrdAcctId=" + npioPrdAcctId + ", norPrdAcctId=" + norPrdAcctId
				+ ", nooPrdAcctId=" + nooPrdAcctId + ", gfrate=" + gfrate + "]";
	}

}
