package com.sil.hbm;
// Generated Jul 4, 2017 1:26:28 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D030003 generated by hbm2java
 */
@Entity
@Table(name = "D030003")
@DynamicUpdate
@DynamicInsert
public class D030003 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2214214884413940000L;
	private D030003Id id;
	private double inClrgFcy;
	private double unClearFcy;
	private double mainBalFcy;
	private double intPrvdFcy;
	private double intPaidFcy;
	private double othChgPrvdFcy;
	private double othChgPaidFcy;
	private double penalPrvdFcy;
	private double penalPaidFcy;
	private double taxPrvdFcy;
	private double taxPaidFcy;
	private double disbursedAmtFcy;
	private double mainBalLcy;
	private double intLcy;
	private double othChgLcy;
	private double penalLcy;
	private double taxLcy;
	private double disbursedAmtLcy;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private double totalCredit;
	private double excessCredit;
	private double reserve2;

	public D030003() {
	}

	public D030003(D030003Id id, double inClrgFcy, double unClearFcy, double mainBalFcy, double intPrvdFcy,
			double intPaidFcy, double othChgPrvdFcy, double othChgPaidFcy, double penalPrvdFcy, double penalPaidFcy,
			double taxPrvdFcy, double taxPaidFcy, double disbursedAmtFcy, double mainBalLcy, double intLcy,
			double othChgLcy, double penalLcy, double taxLcy, double disbursedAmtLcy, int dbtrAddMk, int dbtrAddMb,
			short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs,
			Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd,
			Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt,
			short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId,
			int dbtrLhisTrnNo, double totalCredit, double excessCredit, double reserve2) {
		this.id = id;
		this.inClrgFcy = inClrgFcy;
		this.unClearFcy = unClearFcy;
		this.mainBalFcy = mainBalFcy;
		this.intPrvdFcy = intPrvdFcy;
		this.intPaidFcy = intPaidFcy;
		this.othChgPrvdFcy = othChgPrvdFcy;
		this.othChgPaidFcy = othChgPaidFcy;
		this.penalPrvdFcy = penalPrvdFcy;
		this.penalPaidFcy = penalPaidFcy;
		this.taxPrvdFcy = taxPrvdFcy;
		this.taxPaidFcy = taxPaidFcy;
		this.disbursedAmtFcy = disbursedAmtFcy;
		this.mainBalLcy = mainBalLcy;
		this.intLcy = intLcy;
		this.othChgLcy = othChgLcy;
		this.penalLcy = penalLcy;
		this.taxLcy = taxLcy;
		this.disbursedAmtLcy = disbursedAmtLcy;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.totalCredit = totalCredit;
		this.excessCredit = excessCredit;
		this.reserve2 = reserve2;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)) })
	public D030003Id getId() {
		return this.id;
	}

	public void setId(D030003Id id) {
		this.id = id;
	}

	@Column(name = "InClrgFcy", nullable = false, precision = 53, scale = 0)
	public double getInClrgFcy() {
		return this.inClrgFcy;
	}

	public void setInClrgFcy(double inClrgFcy) {
		this.inClrgFcy = inClrgFcy;
	}

	@Column(name = "UnClearFcy", nullable = false, precision = 53, scale = 0)
	public double getUnClearFcy() {
		return this.unClearFcy;
	}

	public void setUnClearFcy(double unClearFcy) {
		this.unClearFcy = unClearFcy;
	}

	@Column(name = "MainBalFcy", nullable = false, precision = 53, scale = 0)
	public double getMainBalFcy() {
		return this.mainBalFcy;
	}

	public void setMainBalFcy(double mainBalFcy) {
		this.mainBalFcy = mainBalFcy;
	}

	@Column(name = "IntPrvdFcy", nullable = false, precision = 53, scale = 0)
	public double getIntPrvdFcy() {
		return this.intPrvdFcy;
	}

	public void setIntPrvdFcy(double intPrvdFcy) {
		this.intPrvdFcy = intPrvdFcy;
	}

	@Column(name = "IntPaidFcy", nullable = false, precision = 53, scale = 0)
	public double getIntPaidFcy() {
		return this.intPaidFcy;
	}

	public void setIntPaidFcy(double intPaidFcy) {
		this.intPaidFcy = intPaidFcy;
	}

	@Column(name = "OthChgPrvdFcy", nullable = false, precision = 53, scale = 0)
	public double getOthChgPrvdFcy() {
		return this.othChgPrvdFcy;
	}

	public void setOthChgPrvdFcy(double othChgPrvdFcy) {
		this.othChgPrvdFcy = othChgPrvdFcy;
	}

	@Column(name = "OthChgPaidFcy", nullable = false, precision = 53, scale = 0)
	public double getOthChgPaidFcy() {
		return this.othChgPaidFcy;
	}

	public void setOthChgPaidFcy(double othChgPaidFcy) {
		this.othChgPaidFcy = othChgPaidFcy;
	}

	@Column(name = "PenalPrvdFcy", nullable = false, precision = 53, scale = 0)
	public double getPenalPrvdFcy() {
		return this.penalPrvdFcy;
	}

	public void setPenalPrvdFcy(double penalPrvdFcy) {
		this.penalPrvdFcy = penalPrvdFcy;
	}

	@Column(name = "PenalPaidFcy", nullable = false, precision = 53, scale = 0)
	public double getPenalPaidFcy() {
		return this.penalPaidFcy;
	}

	public void setPenalPaidFcy(double penalPaidFcy) {
		this.penalPaidFcy = penalPaidFcy;
	}

	@Column(name = "TaxPrvdFcy", nullable = false, precision = 53, scale = 0)
	public double getTaxPrvdFcy() {
		return this.taxPrvdFcy;
	}

	public void setTaxPrvdFcy(double taxPrvdFcy) {
		this.taxPrvdFcy = taxPrvdFcy;
	}

	@Column(name = "TaxPaidFcy", nullable = false, precision = 53, scale = 0)
	public double getTaxPaidFcy() {
		return this.taxPaidFcy;
	}

	public void setTaxPaidFcy(double taxPaidFcy) {
		this.taxPaidFcy = taxPaidFcy;
	}

	@Column(name = "DisbursedAmtFcy", nullable = false, precision = 53, scale = 0)
	public double getDisbursedAmtFcy() {
		return this.disbursedAmtFcy;
	}

	public void setDisbursedAmtFcy(double disbursedAmtFcy) {
		this.disbursedAmtFcy = disbursedAmtFcy;
	}

	@Column(name = "MainBalLcy", nullable = false, precision = 53, scale = 0)
	public double getMainBalLcy() {
		return this.mainBalLcy;
	}

	public void setMainBalLcy(double mainBalLcy) {
		this.mainBalLcy = mainBalLcy;
	}

	@Column(name = "IntLcy", nullable = false, precision = 53, scale = 0)
	public double getIntLcy() {
		return this.intLcy;
	}

	public void setIntLcy(double intLcy) {
		this.intLcy = intLcy;
	}

	@Column(name = "OthChgLcy", nullable = false, precision = 53, scale = 0)
	public double getOthChgLcy() {
		return this.othChgLcy;
	}

	public void setOthChgLcy(double othChgLcy) {
		this.othChgLcy = othChgLcy;
	}

	@Column(name = "PenalLcy", nullable = false, precision = 53, scale = 0)
	public double getPenalLcy() {
		return this.penalLcy;
	}

	public void setPenalLcy(double penalLcy) {
		this.penalLcy = penalLcy;
	}

	@Column(name = "TaxLcy", nullable = false, precision = 53, scale = 0)
	public double getTaxLcy() {
		return this.taxLcy;
	}

	public void setTaxLcy(double taxLcy) {
		this.taxLcy = taxLcy;
	}

	@Column(name = "DisbursedAmtLcy", nullable = false, precision = 53, scale = 0)
	public double getDisbursedAmtLcy() {
		return this.disbursedAmtLcy;
	}

	public void setDisbursedAmtLcy(double disbursedAmtLcy) {
		this.disbursedAmtLcy = disbursedAmtLcy;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "TotalCredit", nullable = false, precision = 53, scale = 0)
	public double getTotalCredit() {
		return this.totalCredit;
	}

	public void setTotalCredit(double totalCredit) {
		this.totalCredit = totalCredit;
	}

	@Column(name = "ExcessCredit", nullable = false, precision = 53, scale = 0)
	public double getExcessCredit() {
		return this.excessCredit;
	}

	public void setExcessCredit(double excessCredit) {
		this.excessCredit = excessCredit;
	}

	@Column(name = "Reserve2", nullable = false, precision = 53, scale = 0)
	public double getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(double reserve2) {
		this.reserve2 = reserve2;
	}

}
