package com.sil.hbm;
// Generated Jul 26, 2017 7:11:45 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D047001 generated by hbm2java
 */
@Entity
@Table(name = "D047001")
@DynamicUpdate
@DynamicInsert
public class D047001_Shiv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3785633773428669434L;
	private D047001Id id;

	public D047001_Shiv() {
	}

	public D047001_Shiv(D047001Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "crPrdAcctId", column = @Column(name = "CrPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "secPrdAcctId", column = @Column(name = "SecPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "tdsPrdAcctId", column = @Column(name = "TdsPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "lastCommPaidDt", column = @Column(name = "LastCommPaidDt", nullable = false, length = 23)),
			@AttributeOverride(name = "popCode", column = @Column(name = "PopCode", nullable = false)),
			@AttributeOverride(name = "commAmt", column = @Column(name = "CommAmt", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "lastAllowPaidDt", column = @Column(name = "LastAllowPaidDt", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrAddMk", column = @Column(name = "DbtrAddMk", nullable = false)),
			@AttributeOverride(name = "dbtrAddMb", column = @Column(name = "DbtrAddMb", nullable = false)),
			@AttributeOverride(name = "dbtrAddMs", column = @Column(name = "DbtrAddMs", nullable = false)),
			@AttributeOverride(name = "dbtrAddMd", column = @Column(name = "DbtrAddMd", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrAddMt", column = @Column(name = "DbtrAddMt", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrAddCk", column = @Column(name = "DbtrAddCk", nullable = false)),
			@AttributeOverride(name = "dbtrAddCb", column = @Column(name = "DbtrAddCb", nullable = false)),
			@AttributeOverride(name = "dbtrAddCs", column = @Column(name = "DbtrAddCs", nullable = false)),
			@AttributeOverride(name = "dbtrAddCd", column = @Column(name = "DbtrAddCd", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrAddCt", column = @Column(name = "DbtrAddCt", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrLupdMk", column = @Column(name = "DbtrLupdMk", nullable = false)),
			@AttributeOverride(name = "dbtrLupdMb", column = @Column(name = "DbtrLupdMb", nullable = false)),
			@AttributeOverride(name = "dbtrLupdMs", column = @Column(name = "DbtrLupdMs", nullable = false)),
			@AttributeOverride(name = "dbtrLupdMd", column = @Column(name = "DbtrLupdMd", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrLupdMt", column = @Column(name = "DbtrLupdMt", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrLupdCk", column = @Column(name = "DbtrLupdCk", nullable = false)),
			@AttributeOverride(name = "dbtrLupdCb", column = @Column(name = "DbtrLupdCb", nullable = false)),
			@AttributeOverride(name = "dbtrLupdCs", column = @Column(name = "DbtrLupdCs", nullable = false)),
			@AttributeOverride(name = "dbtrLupdCd", column = @Column(name = "DbtrLupdCd", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrLupdCt", column = @Column(name = "DbtrLupdCt", nullable = false, length = 23)),
			@AttributeOverride(name = "dbtrTauthDone", column = @Column(name = "DbtrTAuthDone", nullable = false)),
			@AttributeOverride(name = "dbtrRecStat", column = @Column(name = "DbtrRecStat", nullable = false)),
			@AttributeOverride(name = "dbtrAuthDone", column = @Column(name = "DbtrAuthDone", nullable = false)),
			@AttributeOverride(name = "dbtrAuthNeeded", column = @Column(name = "DbtrAuthNeeded", nullable = false)),
			@AttributeOverride(name = "dbtrUpdtChkId", column = @Column(name = "DbtrUpdtChkId", nullable = false)),
			@AttributeOverride(name = "dbtrLhisTrnNo", column = @Column(name = "DbtrLHisTrnNo", nullable = false)),
			@AttributeOverride(name = "servPrdAcctId", column = @Column(name = "ServPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "machPrdAcctId", column = @Column(name = "MachPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "commPrdAcctId", column = @Column(name = "CommPrdAcctId", nullable = false, length = 32)),
			@AttributeOverride(name = "agtgrade", column = @Column(name = "Agtgrade", nullable = false, length = 1)),
			@AttributeOverride(name = "tdsRate", column = @Column(name = "TdsRate", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "custPrdCd", column = @Column(name = "CustPrdCd", nullable = false, length = 8)),
			@AttributeOverride(name = "insuranceAmt", column = @Column(name = "InsuranceAmt", nullable = false, precision = 53, scale = 0)) })
	public D047001Id getId() {
		return this.id;
	}

	public void setId(D047001Id id) {
		this.id = id;
	}

}
