package com.sil.hbm;
// Generated Oct 30, 2017 3:31:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D047001 generated by hbm2java
 */
@Entity
@Table(name = "D047001")
@DynamicUpdate
@DynamicInsert
public class D047001 implements java.io.Serializable {
	private static final long serialVersionUID = -2239860830058069121L;
	private D047001Id id;
	private String crPrdAcctId;
	private String secPrdAcctId;
	private String tdsPrdAcctId;
	private Date lastCommPaidDt;
	private short popCode;
	private double commAmt;
	private Date lastAllowPaidDt;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private String servPrdAcctId;
	private String machPrdAcctId;
	private String commPrdAcctId;
	private char agtgrade;
	private double tdsRate;
	private String custPrdCd;
	private Double insuranceAmt;

	public D047001() {
	}

	public D047001(D047001Id id, String crPrdAcctId, String secPrdAcctId, String tdsPrdAcctId, Date lastCommPaidDt,
			short popCode, double commAmt, Date lastAllowPaidDt, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			String servPrdAcctId, String machPrdAcctId, String commPrdAcctId, char agtgrade, double tdsRate) {
		this.id = id;
		this.crPrdAcctId = crPrdAcctId;
		this.secPrdAcctId = secPrdAcctId;
		this.tdsPrdAcctId = tdsPrdAcctId;
		this.lastCommPaidDt = lastCommPaidDt;
		this.popCode = popCode;
		this.commAmt = commAmt;
		this.lastAllowPaidDt = lastAllowPaidDt;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.servPrdAcctId = servPrdAcctId;
		this.machPrdAcctId = machPrdAcctId;
		this.commPrdAcctId = commPrdAcctId;
		this.agtgrade = agtgrade;
		this.tdsRate = tdsRate;
	}

	public D047001(D047001Id id, String crPrdAcctId, String secPrdAcctId, String tdsPrdAcctId, Date lastCommPaidDt,
			short popCode, double commAmt, Date lastAllowPaidDt, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			String servPrdAcctId, String machPrdAcctId, String commPrdAcctId, char agtgrade, double tdsRate,
			String custPrdCd, Double insuranceAmt) {
		this.id = id;
		this.crPrdAcctId = crPrdAcctId;
		this.secPrdAcctId = secPrdAcctId;
		this.tdsPrdAcctId = tdsPrdAcctId;
		this.lastCommPaidDt = lastCommPaidDt;
		this.popCode = popCode;
		this.commAmt = commAmt;
		this.lastAllowPaidDt = lastAllowPaidDt;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.servPrdAcctId = servPrdAcctId;
		this.machPrdAcctId = machPrdAcctId;
		this.commPrdAcctId = commPrdAcctId;
		this.agtgrade = agtgrade;
		this.tdsRate = tdsRate;
		this.custPrdCd = custPrdCd;
		this.insuranceAmt = insuranceAmt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "prdAcctId", column = @Column(name = "PrdAcctId", nullable = false, length = 32)) })
	public D047001Id getId() {
		return this.id;
	}

	public void setId(D047001Id id) {
		this.id = id;
	}

	@Column(name = "CrPrdAcctId", nullable = false, length = 32)
	public String getCrPrdAcctId() {
		return this.crPrdAcctId;
	}

	public void setCrPrdAcctId(String crPrdAcctId) {
		this.crPrdAcctId = crPrdAcctId;
	}

	@Column(name = "SecPrdAcctId", nullable = false, length = 32)
	public String getSecPrdAcctId() {
		return this.secPrdAcctId;
	}

	public void setSecPrdAcctId(String secPrdAcctId) {
		this.secPrdAcctId = secPrdAcctId;
	}

	@Column(name = "TdsPrdAcctId", nullable = false, length = 32)
	public String getTdsPrdAcctId() {
		return this.tdsPrdAcctId;
	}

	public void setTdsPrdAcctId(String tdsPrdAcctId) {
		this.tdsPrdAcctId = tdsPrdAcctId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastCommPaidDt", nullable = false, length = 23)
	public Date getLastCommPaidDt() {
		return this.lastCommPaidDt;
	}

	public void setLastCommPaidDt(Date lastCommPaidDt) {
		this.lastCommPaidDt = lastCommPaidDt;
	}

	@Column(name = "PopCode", nullable = false)
	public short getPopCode() {
		return this.popCode;
	}

	public void setPopCode(short popCode) {
		this.popCode = popCode;
	}

	@Column(name = "CommAmt", nullable = false, precision = 53, scale = 0)
	public double getCommAmt() {
		return this.commAmt;
	}

	public void setCommAmt(double commAmt) {
		this.commAmt = commAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastAllowPaidDt", nullable = false, length = 23)
	public Date getLastAllowPaidDt() {
		return this.lastAllowPaidDt;
	}

	public void setLastAllowPaidDt(Date lastAllowPaidDt) {
		this.lastAllowPaidDt = lastAllowPaidDt;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "ServPrdAcctId", nullable = false, length = 32)
	public String getServPrdAcctId() {
		return this.servPrdAcctId;
	}

	public void setServPrdAcctId(String servPrdAcctId) {
		this.servPrdAcctId = servPrdAcctId;
	}

	@Column(name = "MachPrdAcctId", nullable = false, length = 32)
	public String getMachPrdAcctId() {
		return this.machPrdAcctId;
	}

	public void setMachPrdAcctId(String machPrdAcctId) {
		this.machPrdAcctId = machPrdAcctId;
	}

	@Column(name = "CommPrdAcctId", nullable = false, length = 32)
	public String getCommPrdAcctId() {
		return this.commPrdAcctId;
	}

	public void setCommPrdAcctId(String commPrdAcctId) {
		this.commPrdAcctId = commPrdAcctId;
	}

	@Column(name = "Agtgrade", nullable = false, length = 1)
	public char getAgtgrade() {
		return this.agtgrade;
	}

	public void setAgtgrade(char agtgrade) {
		this.agtgrade = agtgrade;
	}

	@Column(name = "TdsRate", nullable = false, precision = 53, scale = 0)
	public double getTdsRate() {
		return this.tdsRate;
	}

	public void setTdsRate(double tdsRate) {
		this.tdsRate = tdsRate;
	}

	@Column(name = "CustPrdCd", length = 8)
	public String getCustPrdCd() {
		return this.custPrdCd;
	}

	public void setCustPrdCd(String custPrdCd) {
		this.custPrdCd = custPrdCd;
	}

	@Column(name = "InsuranceAmt", precision = 53, scale = 0)
	public Double getInsuranceAmt() {
		return this.insuranceAmt;
	}

	public void setInsuranceAmt(Double insuranceAmt) {
		this.insuranceAmt = insuranceAmt;
	}

}
