package com.sil.hbm;
// Generated Oct 30, 2017 3:31:02 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D047001Id generated by hbm2java
 */
@Embeddable
public class D047001Id implements java.io.Serializable {
	private static final long serialVersionUID = -1850134244747357261L;
	private int lbrCode;
	private String prdAcctId;

	public D047001Id() {
	}

	public D047001Id(int lbrCode, String prdAcctId) {
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D047001Id))
			return false;
		D047001Id castOther = (D047001Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getPrdAcctId() == castOther.getPrdAcctId()) || (this.getPrdAcctId() != null
						&& castOther.getPrdAcctId() != null && this.getPrdAcctId().equals(castOther.getPrdAcctId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getPrdAcctId() == null ? 0 : this.getPrdAcctId().hashCode());
		return result;
	}

}
