package com.sil.hbm;
// Generated 14 Sep, 2016 5:56:05 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D100002Id generated by hbm2java
 */
@Embeddable
public class D100002Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6141778056631651168L;
	private int fromBrCode;
	private int fromBrReconNo;

	public D100002Id() {
	}

	public D100002Id(int fromBrCode, int fromBrReconNo) {
		this.fromBrCode = fromBrCode;
		this.fromBrReconNo = fromBrReconNo;
	}

	@Column(name = "FromBrCode", nullable = false)
	public int getFromBrCode() {
		return this.fromBrCode;
	}

	public void setFromBrCode(int fromBrCode) {
		this.fromBrCode = fromBrCode;
	}

	@Column(name = "FromBrReconNo", nullable = false)
	public int getFromBrReconNo() {
		return this.fromBrReconNo;
	}

	public void setFromBrReconNo(int fromBrReconNo) {
		this.fromBrReconNo = fromBrReconNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D100002Id))
			return false;
		D100002Id castOther = (D100002Id) other;

		return (this.getFromBrCode() == castOther.getFromBrCode())
				&& (this.getFromBrReconNo() == castOther.getFromBrReconNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFromBrCode();
		result = 37 * result + this.getFromBrReconNo();
		return result;
	}

}
