package com.sil.hbm;
// Generated 14 Sep, 2016 5:56:05 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D100001 generated by hbm2java
 */
@Entity
@Table(name = "D100001")
@DynamicUpdate
@DynamicInsert
public class D100001 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -926835512673009652L;
	private D100001Id id;
	private Date requestDate;
	private Date requestTime;
	private short abbTrType;
	private int userCd;
	private Date pendingForDate;
	private byte handledFlag;
	private Date entryDate;
	private String batchCd;
	private int setNo;
	private int mainScrollNo;
	private char status;
	private int toBrCode;
	private Date toBrEntryDate;
	private String toBrBatchCd;
	private int toBrSetNo;
	private int toBrMainScrollNo;
	private int toBrMainScrollNo1;
	private String toBrAcctId;
	private String toBrAcctAct;
	private char toBrDrCr;
	private double toBrNetAmt;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;

	public D100001() {
	}

	public D100001(D100001Id id, Date requestDate, Date requestTime, short abbTrType, int userCd, Date pendingForDate,
			byte handledFlag, Date entryDate, String batchCd, int setNo, int mainScrollNo, char status, int toBrCode,
			Date toBrEntryDate, String toBrBatchCd, int toBrSetNo, int toBrMainScrollNo, int toBrMainScrollNo1,
			String toBrAcctId, String toBrAcctAct, char toBrDrCr, double toBrNetAmt, int dbtrAddMk, int dbtrAddMb,
			short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs,
			Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd,
			Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt,
			short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId,
			int dbtrLhisTrnNo) {
		this.id = id;
		this.requestDate = requestDate;
		this.requestTime = requestTime;
		this.abbTrType = abbTrType;
		this.userCd = userCd;
		this.pendingForDate = pendingForDate;
		this.handledFlag = handledFlag;
		this.entryDate = entryDate;
		this.batchCd = batchCd;
		this.setNo = setNo;
		this.mainScrollNo = mainScrollNo;
		this.status = status;
		this.toBrCode = toBrCode;
		this.toBrEntryDate = toBrEntryDate;
		this.toBrBatchCd = toBrBatchCd;
		this.toBrSetNo = toBrSetNo;
		this.toBrMainScrollNo = toBrMainScrollNo;
		this.toBrMainScrollNo1 = toBrMainScrollNo1;
		this.toBrAcctId = toBrAcctId;
		this.toBrAcctAct = toBrAcctAct;
		this.toBrDrCr = toBrDrCr;
		this.toBrNetAmt = toBrNetAmt;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LBrCode", nullable = false)),
			@AttributeOverride(name = "reconNo", column = @Column(name = "ReconNo", nullable = false)) })
	public D100001Id getId() {
		return this.id;
	}

	public void setId(D100001Id id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestDate", nullable = false, length = 23)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestTime", nullable = false, length = 23)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "AbbTrType", nullable = false)
	public short getAbbTrType() {
		return this.abbTrType;
	}

	public void setAbbTrType(short abbTrType) {
		this.abbTrType = abbTrType;
	}

	@Column(name = "UserCd", nullable = false)
	public int getUserCd() {
		return this.userCd;
	}

	public void setUserCd(int userCd) {
		this.userCd = userCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PendingForDate", nullable = false, length = 23)
	public Date getPendingForDate() {
		return this.pendingForDate;
	}

	public void setPendingForDate(Date pendingForDate) {
		this.pendingForDate = pendingForDate;
	}

	@Column(name = "HandledFlag", nullable = false)
	public byte getHandledFlag() {
		return this.handledFlag;
	}

	public void setHandledFlag(byte handledFlag) {
		this.handledFlag = handledFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EntryDate", nullable = false, length = 23)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "BatchCd", nullable = false, length = 8)
	public String getBatchCd() {
		return this.batchCd;
	}

	public void setBatchCd(String batchCd) {
		this.batchCd = batchCd;
	}

	@Column(name = "SetNo", nullable = false)
	public int getSetNo() {
		return this.setNo;
	}

	public void setSetNo(int setNo) {
		this.setNo = setNo;
	}

	@Column(name = "MainScrollNo", nullable = false)
	public int getMainScrollNo() {
		return this.mainScrollNo;
	}

	public void setMainScrollNo(int mainScrollNo) {
		this.mainScrollNo = mainScrollNo;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "ToBrCode", nullable = false)
	public int getToBrCode() {
		return this.toBrCode;
	}

	public void setToBrCode(int toBrCode) {
		this.toBrCode = toBrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ToBrEntryDate", nullable = false, length = 23)
	public Date getToBrEntryDate() {
		return this.toBrEntryDate;
	}

	public void setToBrEntryDate(Date toBrEntryDate) {
		this.toBrEntryDate = toBrEntryDate;
	}

	@Column(name = "ToBrBatchCd", nullable = false, length = 8)
	public String getToBrBatchCd() {
		return this.toBrBatchCd;
	}

	public void setToBrBatchCd(String toBrBatchCd) {
		this.toBrBatchCd = toBrBatchCd;
	}

	@Column(name = "ToBrSetNo", nullable = false)
	public int getToBrSetNo() {
		return this.toBrSetNo;
	}

	public void setToBrSetNo(int toBrSetNo) {
		this.toBrSetNo = toBrSetNo;
	}

	@Column(name = "ToBrMainScrollNo", nullable = false)
	public int getToBrMainScrollNo() {
		return this.toBrMainScrollNo;
	}

	public void setToBrMainScrollNo(int toBrMainScrollNo) {
		this.toBrMainScrollNo = toBrMainScrollNo;
	}

	@Column(name = "ToBrMainScrollNo1", nullable = false)
	public int getToBrMainScrollNo1() {
		return this.toBrMainScrollNo1;
	}

	public void setToBrMainScrollNo1(int toBrMainScrollNo1) {
		this.toBrMainScrollNo1 = toBrMainScrollNo1;
	}

	@Column(name = "ToBrAcctId", nullable = false, length = 32)
	public String getToBrAcctId() {
		return this.toBrAcctId;
	}

	public void setToBrAcctId(String toBrAcctId) {
		this.toBrAcctId = toBrAcctId;
	}

	@Column(name = "ToBrAcctAct", nullable = false, length = 8)
	public String getToBrAcctAct() {
		return this.toBrAcctAct;
	}

	public void setToBrAcctAct(String toBrAcctAct) {
		this.toBrAcctAct = toBrAcctAct;
	}

	@Column(name = "ToBrDrCr", nullable = false, length = 1)
	public char getToBrDrCr() {
		return this.toBrDrCr;
	}

	public void setToBrDrCr(char toBrDrCr) {
		this.toBrDrCr = toBrDrCr;
	}

	@Column(name = "ToBrNetAmt", nullable = false, precision = 53, scale = 0)
	public double getToBrNetAmt() {
		return this.toBrNetAmt;
	}

	public void setToBrNetAmt(double toBrNetAmt) {
		this.toBrNetAmt = toBrNetAmt;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Override
	public String toString() {
		return "D100001 [id=" + id + ", requestDate=" + requestDate + ", requestTime=" + requestTime + ", abbTrType="
				+ abbTrType + ", userCd=" + userCd + ", pendingForDate=" + pendingForDate + ", handledFlag="
				+ handledFlag + ", entryDate=" + entryDate + ", batchCd=" + batchCd + ", setNo=" + setNo
				+ ", mainScrollNo=" + mainScrollNo + ", status=" + status + ", toBrCode=" + toBrCode
				+ ", toBrEntryDate=" + toBrEntryDate + ", toBrBatchCd=" + toBrBatchCd + ", toBrSetNo=" + toBrSetNo
				+ ", toBrMainScrollNo=" + toBrMainScrollNo + ", toBrMainScrollNo1=" + toBrMainScrollNo1
				+ ", toBrAcctId=" + toBrAcctId + ", toBrAcctAct=" + toBrAcctAct + ", toBrDrCr=" + toBrDrCr
				+ ", toBrNetAmt=" + toBrNetAmt + ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb=" + dbtrAddMb
				+ ", dbtrAddMs=" + dbtrAddMs + ", dbtrAddMd=" + dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt + ", dbtrAddCk="
				+ dbtrAddCk + ", dbtrAddCb=" + dbtrAddCb + ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd=" + dbtrAddCd
				+ ", dbtrAddCt=" + dbtrAddCt + ", dbtrLupdMk=" + dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb
				+ ", dbtrLupdMs=" + dbtrLupdMs + ", dbtrLupdMd=" + dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt
				+ ", dbtrLupdCk=" + dbtrLupdCk + ", dbtrLupdCb=" + dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs
				+ ", dbtrLupdCd=" + dbtrLupdCd + ", dbtrLupdCt=" + dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone
				+ ", dbtrRecStat=" + dbtrRecStat + ", dbtrAuthDone=" + dbtrAuthDone + ", dbtrAuthNeeded="
				+ dbtrAuthNeeded + ", dbtrUpdtChkId=" + dbtrUpdtChkId + ", dbtrLhisTrnNo=" + dbtrLhisTrnNo + "]";
	}

}
