package com.sil.hbm;
// Generated 14 Sep, 2016 5:56:05 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D100002 generated by hbm2java
 */
@Entity
@Table(name = "D100002")
@DynamicUpdate
@DynamicInsert
public class D100002 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1735391930478082445L;
	private D100002Id id;
	private int toBrCode;
	private Date toBrEntryDate;
	private String toBrBatchCd;
	private int toBrSetNo;
	private int toBrMainScrollNo;
	private int toBrMainScrollNo1;
	private String toBrAcctId;
	private String toBrAcctAct;
	private char toBrDrCr;
	private double toBrNetAmt;
	private char status;

	public D100002() {
	}

	public D100002(D100002Id id, int toBrCode, Date toBrEntryDate, String toBrBatchCd, int toBrSetNo,
			int toBrMainScrollNo, int toBrMainScrollNo1, String toBrAcctId, String toBrAcctAct, char toBrDrCr,
			double toBrNetAmt, char status) {
		this.id = id;
		this.toBrCode = toBrCode;
		this.toBrEntryDate = toBrEntryDate;
		this.toBrBatchCd = toBrBatchCd;
		this.toBrSetNo = toBrSetNo;
		this.toBrMainScrollNo = toBrMainScrollNo;
		this.toBrMainScrollNo1 = toBrMainScrollNo1;
		this.toBrAcctId = toBrAcctId;
		this.toBrAcctAct = toBrAcctAct;
		this.toBrDrCr = toBrDrCr;
		this.toBrNetAmt = toBrNetAmt;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fromBrCode", column = @Column(name = "FromBrCode", nullable = false)),
			@AttributeOverride(name = "fromBrReconNo", column = @Column(name = "FromBrReconNo", nullable = false)) })
	public D100002Id getId() {
		return this.id;
	}

	public void setId(D100002Id id) {
		this.id = id;
	}

	@Column(name = "ToBrCode", nullable = false)
	public int getToBrCode() {
		return this.toBrCode;
	}

	public void setToBrCode(int toBrCode) {
		this.toBrCode = toBrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ToBrEntryDate", nullable = false, length = 23)
	public Date getToBrEntryDate() {
		return this.toBrEntryDate;
	}

	public void setToBrEntryDate(Date toBrEntryDate) {
		this.toBrEntryDate = toBrEntryDate;
	}

	@Column(name = "ToBrBatchCd", nullable = false, length = 8)
	public String getToBrBatchCd() {
		return this.toBrBatchCd;
	}

	public void setToBrBatchCd(String toBrBatchCd) {
		this.toBrBatchCd = toBrBatchCd;
	}

	@Column(name = "ToBrSetNo", nullable = false)
	public int getToBrSetNo() {
		return this.toBrSetNo;
	}

	public void setToBrSetNo(int toBrSetNo) {
		this.toBrSetNo = toBrSetNo;
	}

	@Column(name = "ToBrMainScrollNo", nullable = false)
	public int getToBrMainScrollNo() {
		return this.toBrMainScrollNo;
	}

	public void setToBrMainScrollNo(int toBrMainScrollNo) {
		this.toBrMainScrollNo = toBrMainScrollNo;
	}

	@Column(name = "ToBrMainScrollNo1", nullable = false)
	public int getToBrMainScrollNo1() {
		return this.toBrMainScrollNo1;
	}

	public void setToBrMainScrollNo1(int toBrMainScrollNo1) {
		this.toBrMainScrollNo1 = toBrMainScrollNo1;
	}

	@Column(name = "ToBrAcctId", nullable = false, length = 32)
	public String getToBrAcctId() {
		return this.toBrAcctId;
	}

	public void setToBrAcctId(String toBrAcctId) {
		this.toBrAcctId = toBrAcctId;
	}

	@Column(name = "ToBrAcctAct", nullable = false, length = 8)
	public String getToBrAcctAct() {
		return this.toBrAcctAct;
	}

	public void setToBrAcctAct(String toBrAcctAct) {
		this.toBrAcctAct = toBrAcctAct;
	}

	@Column(name = "ToBrDrCr", nullable = false, length = 1)
	public char getToBrDrCr() {
		return this.toBrDrCr;
	}

	public void setToBrDrCr(char toBrDrCr) {
		this.toBrDrCr = toBrDrCr;
	}

	@Column(name = "ToBrNetAmt", nullable = false, precision = 53, scale = 0)
	public double getToBrNetAmt() {
		return this.toBrNetAmt;
	}

	public void setToBrNetAmt(double toBrNetAmt) {
		this.toBrNetAmt = toBrNetAmt;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "D100002 [id=" + id + ", toBrCode=" + toBrCode + ", toBrEntryDate=" + toBrEntryDate + ", toBrBatchCd="
				+ toBrBatchCd + ", toBrSetNo=" + toBrSetNo + ", toBrMainScrollNo=" + toBrMainScrollNo
				+ ", toBrMainScrollNo1=" + toBrMainScrollNo1 + ", toBrAcctId=" + toBrAcctId + ", toBrAcctAct="
				+ toBrAcctAct + ", toBrDrCr=" + toBrDrCr + ", toBrNetAmt=" + toBrNetAmt + ", status=" + status + "]";
	}

	
}
