package com.sil.hbm;
// Generated Feb 2, 2017 1:30:07 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D130031Id generated by hbm2java
 */
@Embeddable
public class D130031Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2637482827695535022L;
	private byte chgType;
	private Date effDate;

	public D130031Id() {
	}

	public D130031Id(byte chgType, Date effDate) {
		this.chgType = chgType;
		this.effDate = effDate;
	}

	@Column(name = "ChgType", nullable = false)
	public byte getChgType() {
		return this.chgType;
	}

	public void setChgType(byte chgType) {
		this.chgType = chgType;
	}

	@Column(name = "EffDate", nullable = false, length = 23)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D130031Id))
			return false;
		D130031Id castOther = (D130031Id) other;

		return (this.getChgType() == castOther.getChgType())
				&& ((this.getEffDate() == castOther.getEffDate()) || (this.getEffDate() != null
						&& castOther.getEffDate() != null && this.getEffDate().equals(castOther.getEffDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChgType();
		result = 37 * result + (getEffDate() == null ? 0 : this.getEffDate().hashCode());
		return result;
	}

}
