package com.sil.hbm;
// Generated Feb 2, 2017 1:30:07 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D130014Id generated by hbm2java
 */
@Embeddable
public class D130014Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4027882146163489261L;
	private int lbrCode;
	private String prdCd;
	private byte chgType;
	private short insType;
	private byte acctType;
	private Date effDate;

	public D130014Id() {
	}

	public D130014Id(int lbrCode, String prdCd, byte chgType, short insType, byte acctType, Date effDate) {
		this.lbrCode = lbrCode;
		this.prdCd = prdCd;
		this.chgType = chgType;
		this.insType = insType;
		this.acctType = acctType;
		this.effDate = effDate;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdCd", nullable = false, length = 8)
	public String getPrdCd() {
		return this.prdCd;
	}

	public void setPrdCd(String prdCd) {
		this.prdCd = prdCd;
	}

	@Column(name = "ChgType", nullable = false)
	public byte getChgType() {
		return this.chgType;
	}

	public void setChgType(byte chgType) {
		this.chgType = chgType;
	}

	@Column(name = "InsType", nullable = false)
	public short getInsType() {
		return this.insType;
	}

	public void setInsType(short insType) {
		this.insType = insType;
	}

	@Column(name = "AcctType", nullable = false)
	public byte getAcctType() {
		return this.acctType;
	}

	public void setAcctType(byte acctType) {
		this.acctType = acctType;
	}

	@Column(name = "EffDate", nullable = false, length = 23)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D130014Id))
			return false;
		D130014Id castOther = (D130014Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getPrdCd() == castOther.getPrdCd()) || (this.getPrdCd() != null
						&& castOther.getPrdCd() != null && this.getPrdCd().equals(castOther.getPrdCd())))
				&& (this.getChgType() == castOther.getChgType()) && (this.getInsType() == castOther.getInsType())
				&& (this.getAcctType() == castOther.getAcctType())
				&& ((this.getEffDate() == castOther.getEffDate()) || (this.getEffDate() != null
						&& castOther.getEffDate() != null && this.getEffDate().equals(castOther.getEffDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getPrdCd() == null ? 0 : this.getPrdCd().hashCode());
		result = 37 * result + this.getChgType();
		result = 37 * result + this.getInsType();
		result = 37 * result + this.getAcctType();
		result = 37 * result + (getEffDate() == null ? 0 : this.getEffDate().hashCode());
		return result;
	}

}
