package com.sil.hbm;
// Generated Jan 24, 2017 11:07:08 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350031 generated by hbm2java
 */
@Entity
@Table(name = "D350031")
@DynamicInsert
@DynamicUpdate
public class D350031 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1873915310121710773L;
	private String custNo;
	private String custName;
	private String mobileNo;
	private String transPin;
	private String queryPin;
	private int brCode;
	private Date createDate;
	private char mobBankingYn;
	private Date lastAccessDate;
	private Date lastAccessTime;
	private Date pinChangeDate;
	private Date pinChangeTime;
	private Date tpinChangeDate;
	private Date tpinChangeTime;
	private Date pinPrintDate;
	private int pinPrintCount;
	private String add1;
	private String add2;
	private String add3;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private int dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private int dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private int dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private int dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private int dbtrTauthDone;
	private int dbtrRecStat;
	private int dbtrAuthDone;
	private int dbtrAuthNeeded;
	private int dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private String transPassPin;
	private Date smsTrnDate;
	private Double smsLmtAmt;
	private Date appTrnDate;
	private Double appLmtAmt;
	private String nickName;
	private String regNo;
	private String newTransPin;
	private String newQueryPin;

	public D350031() {
	}

	public D350031(String custNo, String custName, String mobileNo, String transPin, String queryPin, int brCode,
			Date createDate, char mobBankingYn, Date lastAccessDate, Date lastAccessTime, Date pinChangeDate,
			Date pinChangeTime, Date tpinChangeDate, Date tpinChangeTime, Date pinPrintDate, int pinPrintCount,
			String add1, String add2, String add3, int dbtrAddMk, int dbtrAddMb, int dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, int dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk,
			int dbtrLupdMb, int dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb,
			int dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, int dbtrTauthDone, int dbtrRecStat, int dbtrAuthDone,
			int dbtrAuthNeeded, int dbtrUpdtChkId, int dbtrLhisTrnNo, String transPassPin, Date smsTrnDate,
			Date appTrnDate, String nickName, String newTransPin, String newQueryPin) {
		this.custNo = custNo;
		this.custName = custName;
		this.mobileNo = mobileNo;
		this.transPin = transPin;
		this.queryPin = queryPin;
		this.brCode = brCode;
		this.createDate = createDate;
		this.mobBankingYn = mobBankingYn;
		this.lastAccessDate = lastAccessDate;
		this.lastAccessTime = lastAccessTime;
		this.pinChangeDate = pinChangeDate;
		this.pinChangeTime = pinChangeTime;
		this.tpinChangeDate = tpinChangeDate;
		this.tpinChangeTime = tpinChangeTime;
		this.pinPrintDate = pinPrintDate;
		this.pinPrintCount = pinPrintCount;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.transPassPin = transPassPin;
		this.smsTrnDate = smsTrnDate;
		this.appTrnDate = appTrnDate;
		this.nickName = nickName;
		this.newTransPin = newTransPin;
		this.newQueryPin = newQueryPin;
	}

	public D350031(String custNo, String custName, String mobileNo, String transPin, String queryPin, int brCode,
			Date createDate, char mobBankingYn, Date lastAccessDate, Date lastAccessTime, Date pinChangeDate,
			Date pinChangeTime, Date tpinChangeDate, Date tpinChangeTime, Date pinPrintDate, int pinPrintCount,
			String add1, String add2, String add3, int dbtrAddMk, int dbtrAddMb, int dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, int dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk,
			int dbtrLupdMb, int dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb,
			int dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, int dbtrTauthDone, int dbtrRecStat, int dbtrAuthDone,
			int dbtrAuthNeeded, int dbtrUpdtChkId, int dbtrLhisTrnNo, String transPassPin, Date smsTrnDate,
			Double smsLmtAmt, Date appTrnDate, Double appLmtAmt, String nickName, String regNo, String newTransPin,
			String newQueryPin) {
		this.custNo = custNo;
		this.custName = custName;
		this.mobileNo = mobileNo;
		this.transPin = transPin;
		this.queryPin = queryPin;
		this.brCode = brCode;
		this.createDate = createDate;
		this.mobBankingYn = mobBankingYn;
		this.lastAccessDate = lastAccessDate;
		this.lastAccessTime = lastAccessTime;
		this.pinChangeDate = pinChangeDate;
		this.pinChangeTime = pinChangeTime;
		this.tpinChangeDate = tpinChangeDate;
		this.tpinChangeTime = tpinChangeTime;
		this.pinPrintDate = pinPrintDate;
		this.pinPrintCount = pinPrintCount;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.transPassPin = transPassPin;
		this.smsTrnDate = smsTrnDate;
		this.smsLmtAmt = smsLmtAmt;
		this.appTrnDate = appTrnDate;
		this.appLmtAmt = appLmtAmt;
		this.nickName = nickName;
		this.regNo = regNo;
		this.newTransPin = newTransPin;
		this.newQueryPin = newQueryPin;
	}

	@Id

	@Column(name = "CustNo", unique = true, nullable = false, length = 19)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "CustName", nullable = false, length = 30)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "MobileNo", nullable = false, length = 12)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "TransPin", nullable = false, length = 40)
	public String getTransPin() {
		return this.transPin;
	}

	public void setTransPin(String transPin) {
		this.transPin = transPin;
	}

	@Column(name = "QueryPin", nullable = false, length = 40)
	public String getQueryPin() {
		return this.queryPin;
	}

	public void setQueryPin(String queryPin) {
		this.queryPin = queryPin;
	}

	@Column(name = "BrCode", nullable = false)
	public int getBrCode() {
		return this.brCode;
	}

	public void setBrCode(int brCode) {
		this.brCode = brCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MobBankingYN", nullable = false, length = 1)
	public char getMobBankingYn() {
		return this.mobBankingYn;
	}

	public void setMobBankingYn(char mobBankingYn) {
		this.mobBankingYn = mobBankingYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastAccessDate", nullable = false, length = 23)
	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastAccessTime", nullable = false, length = 23)
	public Date getLastAccessTime() {
		return this.lastAccessTime;
	}

	public void setLastAccessTime(Date lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinChangeDate", nullable = false, length = 23)
	public Date getPinChangeDate() {
		return this.pinChangeDate;
	}

	public void setPinChangeDate(Date pinChangeDate) {
		this.pinChangeDate = pinChangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinChangeTime", nullable = false, length = 23)
	public Date getPinChangeTime() {
		return this.pinChangeTime;
	}

	public void setPinChangeTime(Date pinChangeTime) {
		this.pinChangeTime = pinChangeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TPinChangeDate", nullable = false, length = 23)
	public Date getTpinChangeDate() {
		return this.tpinChangeDate;
	}

	public void setTpinChangeDate(Date tpinChangeDate) {
		this.tpinChangeDate = tpinChangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TPinChangeTime", nullable = false, length = 23)
	public Date getTpinChangeTime() {
		return this.tpinChangeTime;
	}

	public void setTpinChangeTime(Date tpinChangeTime) {
		this.tpinChangeTime = tpinChangeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinPrintDate", nullable = false, length = 23)
	public Date getPinPrintDate() {
		return this.pinPrintDate;
	}

	public void setPinPrintDate(Date pinPrintDate) {
		this.pinPrintDate = pinPrintDate;
	}

	@Column(name = "PinPrintCount", nullable = false)
	public int getPinPrintCount() {
		return this.pinPrintCount;
	}

	public void setPinPrintCount(int pinPrintCount) {
		this.pinPrintCount = pinPrintCount;
	}

	@Column(name = "Add1", nullable = false, length = 30)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "Add2", nullable = false, length = 30)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "Add3", nullable = false, length = 30)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public int getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(int dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public int getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(int dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public int getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(int dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public int getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(int dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public int getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(int dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public int getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(int dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public int getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(int dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public int getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(int dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public int getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(int dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "TransPassPin", nullable = false, length = 40)
	public String getTransPassPin() {
		return this.transPassPin;
	}

	public void setTransPassPin(String transPassPin) {
		this.transPassPin = transPassPin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SmsTrnDate", nullable = false, length = 23)
	public Date getSmsTrnDate() {
		return this.smsTrnDate;
	}

	public void setSmsTrnDate(Date smsTrnDate) {
		this.smsTrnDate = smsTrnDate;
	}

	@Column(name = "SmsLmtAmt", precision = 53, scale = 0)
	public Double getSmsLmtAmt() {
		return this.smsLmtAmt;
	}

	public void setSmsLmtAmt(Double smsLmtAmt) {
		this.smsLmtAmt = smsLmtAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppTrnDate", nullable = false, length = 23)
	public Date getAppTrnDate() {
		return this.appTrnDate;
	}

	public void setAppTrnDate(Date appTrnDate) {
		this.appTrnDate = appTrnDate;
	}

	@Column(name = "AppLmtAmt", precision = 53, scale = 0)
	public Double getAppLmtAmt() {
		return this.appLmtAmt;
	}

	public void setAppLmtAmt(Double appLmtAmt) {
		this.appLmtAmt = appLmtAmt;
	}

	@Column(name = "NickName", nullable = false, length = 20)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "RegNo", length = 12)
	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	@Column(name = "NewTransPin", nullable = false, length = 40)
	public String getNewTransPin() {
		return this.newTransPin;
	}

	public void setNewTransPin(String newTransPin) {
		this.newTransPin = newTransPin;
	}

	@Column(name = "NewQueryPin", nullable = false, length = 40)
	public String getNewQueryPin() {
		return this.newQueryPin;
	}

	public void setNewQueryPin(String newQueryPin) {
		this.newQueryPin = newQueryPin;
	}

}
