package com.sil.hbm;

// default package
// Generated Sep 8, 2016 12:22:49 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350078 generated by hbm2java
 */
@Entity
@Table(name = "D350078", uniqueConstraints = @UniqueConstraint(columnNames = "MobileNo"))
@DynamicInsert
@DynamicUpdate
public class D350078 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7582594571518862014L;
	private D350078Id id;
	private String emailId;
	private String countryCd;
	private String facilitiesFlag;
	private String facilitiesTransFlag;
	private short atmcount;
	private short mbbcount;
	private short tbcount;
	private short pcbcount;
	private short smscount;
	private short ibcount;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private Date appTrnDate;
	private double appLmtAmt;

	public D350078() {
	}

	public D350078(D350078Id id, String countryCd, String facilitiesFlag, String facilitiesTransFlag, short atmcount,
			short mbbcount, short tbcount, short pcbcount, short smscount, short ibcount, int dbtrAddMk, int dbtrAddMb,
			short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs,
			Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd,
			Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt,
			short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId,
			int dbtrLhisTrnNo, Date appTrnDate, double appLmtAmt) {
		this.id = id;
		this.countryCd = countryCd;
		this.facilitiesFlag = facilitiesFlag;
		this.facilitiesTransFlag = facilitiesTransFlag;
		this.atmcount = atmcount;
		this.mbbcount = mbbcount;
		this.tbcount = tbcount;
		this.pcbcount = pcbcount;
		this.smscount = smscount;
		this.ibcount = ibcount;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.appTrnDate = appTrnDate;
		this.appLmtAmt = appLmtAmt;
	}

	public D350078(D350078Id id, String emailId, String countryCd, String facilitiesFlag, String facilitiesTransFlag,
			short atmcount, short mbbcount, short tbcount, short pcbcount, short smscount, short ibcount, int dbtrAddMk,
			int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb,
			short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs,
			Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd,
			Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded,
			short dbtrUpdtChkId, int dbtrLhisTrnNo, Date appTrnDate, double appLmtAmt) {
		this.id = id;
		this.emailId = emailId;
		this.countryCd = countryCd;
		this.facilitiesFlag = facilitiesFlag;
		this.facilitiesTransFlag = facilitiesTransFlag;
		this.atmcount = atmcount;
		this.mbbcount = mbbcount;
		this.tbcount = tbcount;
		this.pcbcount = pcbcount;
		this.smscount = smscount;
		this.ibcount = ibcount;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.appTrnDate = appTrnDate;
		this.appLmtAmt = appLmtAmt;
	}

	public D350078(D350078Id id, String countryCd, String facilitiesFlag, String facilitiesTransFlag, String emailId, short atmcount,
			short mbbcount, short tbcount, short pcbcount, short smscount, short ibcount, Date appTrnDate, short appLmtAmt) {
		// TODO Auto-generated constructor stub
		this.id = id;
		this.emailId = emailId;
		this.countryCd = countryCd;
		this.facilitiesFlag = facilitiesFlag;
		this.facilitiesTransFlag = facilitiesTransFlag;
		this.atmcount = atmcount;
		this.mbbcount = mbbcount;
		this.tbcount = tbcount;
		this.pcbcount = pcbcount;
		this.smscount = smscount;
		this.ibcount = ibcount;
		this.appTrnDate = appTrnDate;
		this.appLmtAmt = appLmtAmt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false, length = 19)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo", unique = true, nullable = false, length = 13)) })
	public D350078Id getId() {
		return this.id;
	}

	public void setId(D350078Id id) {
		this.id = id;
	}

	@Column(name = "EmailId", length = 35)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "CountryCd", nullable = false, length = 3)
	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	@Column(name = "FacilitiesFlag", nullable = false, length = 8)
	public String getFacilitiesFlag() {
		return this.facilitiesFlag;
	}

	public void setFacilitiesFlag(String facilitiesFlag) {
		this.facilitiesFlag = facilitiesFlag;
	}

	@Column(name = "FacilitiesTransFlag", nullable = false, length = 8)
	public String getFacilitiesTransFlag() {
		return this.facilitiesTransFlag;
	}

	public void setFacilitiesTransFlag(String facilitiesTransFlag) {
		this.facilitiesTransFlag = facilitiesTransFlag;
	}

	@Column(name = "ATMCount", nullable = false)
	public short getAtmcount() {
		return this.atmcount;
	}

	public void setAtmcount(short atmcount) {
		this.atmcount = atmcount;
	}

	@Column(name = "MBBCount", nullable = false)
	public short getMbbcount() {
		return this.mbbcount;
	}

	public void setMbbcount(short mbbcount) {
		this.mbbcount = mbbcount;
	}

	@Column(name = "TBCount", nullable = false)
	public short getTbcount() {
		return this.tbcount;
	}

	public void setTbcount(short tbcount) {
		this.tbcount = tbcount;
	}

	@Column(name = "PCBCount", nullable = false)
	public short getPcbcount() {
		return this.pcbcount;
	}

	public void setPcbcount(short pcbcount) {
		this.pcbcount = pcbcount;
	}

	@Column(name = "SMSCount", nullable = false)
	public short getSmscount() {
		return this.smscount;
	}

	public void setSmscount(short smscount) {
		this.smscount = smscount;
	}

	@Column(name = "IBCount", nullable = false)
	public short getIbcount() {
		return this.ibcount;
	}

	public void setIbcount(short ibcount) {
		this.ibcount = ibcount;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppTrnDate", nullable = false, length = 23)
	public Date getAppTrnDate() {
		return this.appTrnDate;
	}

	public void setAppTrnDate(Date appTrnDate) {
		this.appTrnDate = appTrnDate;
	}

	@Column(name = "AppLmtAmt", nullable = false, precision = 53, scale = 0)
	
	public double getAppLmtAmt() {
		return this.appLmtAmt;
	}

	public void setAppLmtAmt(double appLmtAmt) {
		this.appLmtAmt = appLmtAmt;
	}

	@Override
	public String toString() {
		return "D350078 [id=" + id + ", emailId=" + emailId + ", countryCd=" + countryCd + ", facilitiesFlag="
				+ facilitiesFlag + ", facilitiesTransFlag=" + facilitiesTransFlag + ", atmcount=" + atmcount
				+ ", mbbcount=" + mbbcount + ", tbcount=" + tbcount + ", pcbcount=" + pcbcount + ", smscount="
				+ smscount + ", ibcount=" + ibcount + ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb=" + dbtrAddMb
				+ ", dbtrAddMs=" + dbtrAddMs + ", dbtrAddMd=" + dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt + ", dbtrAddCk="
				+ dbtrAddCk + ", dbtrAddCb=" + dbtrAddCb + ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd=" + dbtrAddCd
				+ ", dbtrAddCt=" + dbtrAddCt + ", dbtrLupdMk=" + dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb
				+ ", dbtrLupdMs=" + dbtrLupdMs + ", dbtrLupdMd=" + dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt
				+ ", dbtrLupdCk=" + dbtrLupdCk + ", dbtrLupdCb=" + dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs
				+ ", dbtrLupdCd=" + dbtrLupdCd + ", dbtrLupdCt=" + dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone
				+ ", dbtrRecStat=" + dbtrRecStat + ", dbtrAuthDone=" + dbtrAuthDone + ", dbtrAuthNeeded="
				+ dbtrAuthNeeded + ", dbtrUpdtChkId=" + dbtrUpdtChkId + ", dbtrLhisTrnNo=" + dbtrLhisTrnNo
				+ ", appTrnDate=" + appTrnDate + ", appLmtAmt=" + appLmtAmt + "]";
	}

	
	
}
