package com.sil.hbm;
// Generated Jan 19, 2017 5:20:57 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350038 generated by hbm2java
 */
@Entity
@Table(name = "D350038")
@DynamicInsert
@DynamicUpdate
public class D350038 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5372790567032956989L;
	private String ifscode;
	private Integer nbin;
	private String bankname;
	private Integer dbtrAddMk;
	private Integer dbtrAddMb;
	private Short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private Integer dbtrAddCk;
	private Integer dbtrAddCb;
	private Short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private Integer dbtrLupdMk;
	private Integer dbtrLupdMb;
	private Short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private Integer dbtrLupdCk;
	private Integer dbtrLupdCb;
	private Short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private Short dbtrTauthDone;
	private Byte dbtrRecStat;
	private Byte dbtrAuthDone;
	private Byte dbtrAuthNeeded;
	private Short dbtrUpdtChkId;
	private Integer dbtrLhisTrnNo;

	public D350038() {
	}

	public D350038(String ifscode) {
		this.ifscode = ifscode;
	}

	public D350038(String ifscode, Integer nbin, String bankname, Integer dbtrAddMk, Integer dbtrAddMb, Short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, Integer dbtrAddCk, Integer dbtrAddCb, Short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, Integer dbtrLupdMk, Integer dbtrLupdMb, Short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			Integer dbtrLupdCk, Integer dbtrLupdCb, Short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt,
			Short dbtrTauthDone, Byte dbtrRecStat, Byte dbtrAuthDone, Byte dbtrAuthNeeded, Short dbtrUpdtChkId,
			Integer dbtrLhisTrnNo) {
		this.ifscode = ifscode;
		this.nbin = nbin;
		this.bankname = bankname;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Id

	@Column(name = "IFSCode", unique = true, nullable = false, length = 11)
	public String getIfscode() {
		return this.ifscode;
	}

	public void setIfscode(String ifscode) {
		this.ifscode = ifscode;
	}

	@Column(name = "NBIN")
	public Integer getNbin() {
		return this.nbin;
	}

	public void setNbin(Integer nbin) {
		this.nbin = nbin;
	}

	@Column(name = "BANKNAME", length = 50)
	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	@Column(name = "DbtrAddMk")
	public Integer getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(Integer dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb")
	public Integer getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(Integer dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs")
	public Short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(Short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk")
	public Integer getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(Integer dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb")
	public Integer getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(Integer dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs")
	public Short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(Short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk")
	public Integer getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(Integer dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb")
	public Integer getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(Integer dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs")
	public Short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(Short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk")
	public Integer getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(Integer dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb")
	public Integer getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(Integer dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs")
	public Short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(Short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone")
	public Short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(Short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat")
	public Byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(Byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone")
	public Byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(Byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded")
	public Byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(Byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId")
	public Short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(Short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo")
	public Integer getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(Integer dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

}
