package com.sil.hbm;
// Generated 20 Sep, 2016 2:32:51 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350037 generated by hbm2java
 */
@Entity
@Table(name = "D350037")
@DynamicInsert
@DynamicUpdate
public class D350037 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7626762707423265227L;
	private D350037Id id;
	private String mobNo1;
	private String mmid1;
	private String accNo;
	private String ifscCd;
	private Double tranAmt;
	private String rrsponseCd;
	private String responseDesc;
	private String rrnNo;
	private String stan;
	private Date transactionDate;
	private String drcr;
	private String responseCd;
	private String source;

	public D350037() {
	}

	public D350037(D350037Id id, String accNo, String ifscCd, String rrsponseCd, String responseDesc, String rrnNo,
			String stan) {
		this.id = id;
		this.accNo = accNo;
		this.ifscCd = ifscCd;
		this.rrsponseCd = rrsponseCd;
		this.responseDesc = responseDesc;
		this.rrnNo = rrnNo;
		this.stan = stan;
	}

	public D350037(D350037Id id, String mobNo1, String mmid1, String accNo, String ifscCd, Double tranAmt,
			String rrsponseCd, String responseDesc, String rrnNo, String stan, Date transactionDate, String drcr,
			String responseCd) {
		this.id = id;
		this.mobNo1 = mobNo1;
		this.mmid1 = mmid1;
		this.accNo = accNo;
		this.ifscCd = ifscCd;
		this.tranAmt = tranAmt;
		this.rrsponseCd = rrsponseCd;
		this.responseDesc = responseDesc;
		this.rrnNo = rrnNo;
		this.stan = stan;
		this.transactionDate = transactionDate;
		this.drcr = drcr;
		this.responseCd = responseCd;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LbrCode", nullable = false)),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", nullable = false, length = 23)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", nullable = false, length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo", nullable = false)),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo", nullable = false)),
			@AttributeOverride(name = "source", column = @Column(name = "SOURCE", nullable = false)),
			@AttributeOverride(name = "entryTime", column = @Column(name = "EntryTime", nullable = false, length = 23)) })
	public D350037Id getId() {
		return this.id;
	}

	public void setId(D350037Id id) {
		this.id = id;
	}

	@Column(name = "MobNo1", length = 20)
	public String getMobNo1() {
		return this.mobNo1;
	}

	public void setMobNo1(String mobNo1) {
		this.mobNo1 = mobNo1;
	}

	@Column(name = "MMID1", length = 15)
	public String getMmid1() {
		return this.mmid1;
	}

	public void setMmid1(String mmid1) {
		this.mmid1 = mmid1;
	}

	@Column(name = "AccNo", nullable = false, length = 20)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "IfscCd", nullable = false, length = 15)
	public String getIfscCd() {
		return this.ifscCd;
	}

	public void setIfscCd(String ifscCd) {
		this.ifscCd = ifscCd;
	}

	@Column(name = "TranAmt", precision = 53, scale = 0)
	public Double getTranAmt() {
		return this.tranAmt;
	}

	public void setTranAmt(Double tranAmt) {
		this.tranAmt = tranAmt;
	}

	@Column(name = "RrsponseCd", nullable = true, length = 8)
	public String getRrsponseCd() {
		return this.rrsponseCd;
	}

	public void setRrsponseCd(String rrsponseCd) {
		this.rrsponseCd = rrsponseCd;
	}

	@Column(name = "ResponseDesc", nullable = false, length = 100)
	public String getResponseDesc() {
		return this.responseDesc;
	}

	public void setResponseDesc(String responseDesc) {
		this.responseDesc = responseDesc;
	}

	@Column(name = "RrnNo", nullable = false, length = 20)
	public String getRrnNo() {
		return this.rrnNo;
	}

	public void setRrnNo(String rrnNo) {
		this.rrnNo = rrnNo;
	}

	@Column(name = "STAN", nullable = false, length = 20)
	public String getStan() {
		return this.stan;
	}

	public void setStan(String stan) {
		this.stan = stan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransactionDate", length = 23)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "DRCR", length = 2)
	public String getDrcr() {
		return this.drcr;
	}

	public void setDrcr(String drcr) {
		this.drcr = drcr;
	}

	@Column(name = "ResponseCd", length = 8)
	public String getResponseCd() {
		return this.responseCd;
	}

	public void setResponseCd(String responseCd) {
		this.responseCd = responseCd;
	}

	@Column(name = "SOURCE", length = 100)
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	
	
	

}
