package com.sil.hbm;
// Generated 20 Sep, 2016 2:32:51 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D350037Id generated by hbm2java
 */
@Embeddable
public class D350037Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5980894010556163749L;
	private int lbrCode;
	private Date entryDate;
	private String batchCd;
	private int setNo;
	private int scrollNo;
	private Date entryTime;

	public D350037Id() {
	}

	public D350037Id(int lbrCode, Date entryDate, String batchCd, int setNo, int scrollNo, Date entryTime) {
		this.lbrCode = lbrCode;
		this.entryDate = entryDate;
		this.batchCd = batchCd;
		this.setNo = setNo;
		this.scrollNo = scrollNo;
		this.entryTime = entryTime;
	}

	@Column(name = "LbrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "EntryDate", nullable = false, length = 23)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "BatchCd", nullable = false, length = 8)
	public String getBatchCd() {
		return this.batchCd;
	}

	public void setBatchCd(String batchCd) {
		this.batchCd = batchCd;
	}

	@Column(name = "SetNo", nullable = false)
	public int getSetNo() {
		return this.setNo;
	}

	public void setSetNo(int setNo) {
		this.setNo = setNo;
	}

	@Column(name = "ScrollNo", nullable = false)
	public int getScrollNo() {
		return this.scrollNo;
	}

	public void setScrollNo(int scrollNo) {
		this.scrollNo = scrollNo;
	}

	@Column(name = "EntryTime", nullable = false, length = 23)
	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D350037Id))
			return false;
		D350037Id castOther = (D350037Id) other;

		return (this.getLbrCode() == castOther.getLbrCode())
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null
						&& castOther.getEntryDate() != null && this.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getBatchCd() == castOther.getBatchCd()) || (this.getBatchCd() != null
						&& castOther.getBatchCd() != null && this.getBatchCd().equals(castOther.getBatchCd())))
				&& (this.getSetNo() == castOther.getSetNo()) && (this.getScrollNo() == castOther.getScrollNo())
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this.getEntryTime() != null
						&& castOther.getEntryTime() != null && this.getEntryTime().equals(castOther.getEntryTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLbrCode();
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getBatchCd() == null ? 0 : this.getBatchCd().hashCode());
		result = 37 * result + this.getSetNo();
		result = 37 * result + this.getScrollNo();
		result = 37 * result + (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		return result;
	}

}
