package com.sil.hbm;
// Generated Dec 16, 2016 3:58:39 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;



/**
 * D350044 generated by hbm2java
 */
@Entity
@Table(name = "D350044")
@DynamicInsert
@DynamicUpdate
public class D350044 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7466266317782025837L;
	private D350044Id id;

	public D350044() {
	}

	public D350044(D350044Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LbrCode")),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", length = 23)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo")),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo")),
			@AttributeOverride(name = "mobNo1", column = @Column(name = "MobNo1", length = 12)),
			@AttributeOverride(name = "mmid1", column = @Column(name = "MMID1", length = 8)),
			@AttributeOverride(name = "mobNo2", column = @Column(name = "MobNo2", length = 12)),
			@AttributeOverride(name = "mmid2", column = @Column(name = "MMID2", length = 8)),
			@AttributeOverride(name = "tranAmt", column = @Column(name = "TranAmt")),
			@AttributeOverride(name = "responseCd", column = @Column(name = "ResponseCd", length = 8)),
			@AttributeOverride(name = "responseDesc", column = @Column(name = "ResponseDesc", length = 100)),
			@AttributeOverride(name = "rrnNo", column = @Column(name = "RrnNo", length = 20)),
			@AttributeOverride(name = "stan", column = @Column(name = "STAN", length = 20)),
			@AttributeOverride(name = "entryTime", column = @Column(name = "EntryTime", length = 23)),
			@AttributeOverride(name = "transactionDate", column = @Column(name = "TransactionDate", length = 23)),
			@AttributeOverride(name = "drcr", column = @Column(name = "DRCR", length = 2)) })
	public D350044Id getId() {
		return this.id;
	}

	public void setId(D350044Id id) {
		this.id = id;
	}

}
