package com.sil.hbm;
// Generated Jan 24, 2017 11:07:08 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350033 generated by hbm2java
 */
@Entity
@Table(name = "D350033",  uniqueConstraints = @UniqueConstraint(columnNames = "CustNo"))
@DynamicInsert
@DynamicUpdate
public class D350033 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2526961495070833978L;
	private D350033Id id;

	public D350033() {
	}

	public D350033(D350033Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", unique = true, nullable = false, length = 19)),
			@AttributeOverride(name = "mobPinPrint", column = @Column(name = "MobPinPrint", nullable = false)),
			@AttributeOverride(name = "mobPinPrintDate", column = @Column(name = "MobPinPrintDate", nullable = false, length = 23)),
			@AttributeOverride(name = "transPassPinPrint", column = @Column(name = "TransPassPinPrint", nullable = false)),
			@AttributeOverride(name = "transPassPinPrintDate", column = @Column(name = "TransPassPinPrintDate", nullable = false, length = 23)) })
	public D350033Id getId() {
		return this.id;
	}

	public void setId(D350033Id id) {
		this.id = id;
	}

}
