package com.sil.hbm;
// Generated Jan 24, 2017 11:07:08 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350035 generated by hbm2java
 */
@Entity
@Table(name = "D350035")
@DynamicInsert
@DynamicUpdate
public class D350035 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8641087710077413208L;
	private D350035Id id;
	private char isDuplicate;
	private String remarks;

	public D350035() {
	}

	public D350035(D350035Id id, char isDuplicate, String remarks) {
		this.id = id;
		this.isDuplicate = isDuplicate;
		this.remarks = remarks;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false, length = 19)),
			@AttributeOverride(name = "genDate", column = @Column(name = "GenDate", nullable = false, length = 23)),
			@AttributeOverride(name = "genTime", column = @Column(name = "GenTime", nullable = false, length = 23)) })
	public D350035Id getId() {
		return this.id;
	}

	public void setId(D350035Id id) {
		this.id = id;
	}

	@Column(name = "IsDuplicate", nullable = false, length = 1)
	public char getIsDuplicate() {
		return this.isDuplicate;
	}

	public void setIsDuplicate(char isDuplicate) {
		this.isDuplicate = isDuplicate;
	}

	@Column(name = "Remarks", nullable = false, length = 25)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
