package com.sil.hbm;

// default package
// Generated Sep 8, 2016 12:22:49 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350076 generated by hbm2java
 */
@Entity
@Table(name = "D350076")
@DynamicInsert
@DynamicUpdate
public class D350076 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -308234780234185491L;
	private String custNo;
	private char custtype;
	private String custName;
	private String transPin;
	private String queryPin;
	private short brCode;
	private int cityCode;
	private Date createDate;
	private String smartCardNo;
	private char teleBankingSrYn;
	private char pcbankingSrYn;
	private char interNetBankingSrYn;
	private char smsbankingSr;
	private Date lastAccessDate;
	private Date lastAccessTime;
	private Date pinChangeDate;
	private Date pinChangeTime;
	private Date tpinChangeDate;
	private Date tpinChangeTime;
	private Date pinPrintDate;
	private short pinPrintCount;
	private char status;
	private String makerId;
	private String checkerId;
	private String add1;
	private String add2;
	private String add3;
	private String pinCode;
	private String phone;
	private String cityCd;
	private char cashYn;
	private char drClgYn;
	private char crClgYn;
	private char trfYn;
	private char abbYn;
	private char atmYn;
	private double cashLimit;
	private double drClgLimit;
	private double crClgLimit;
	private double trfLimit;
	private double abbLimit;
	private double atmLimit;
	private byte stat;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private String ibqueryPin;
	private String custUsrId;
	private char rtgsneftyn;
	private double rtgslimit;
	private double neftlimit;
	private Date nefttransDate;
	private double nefttranAmt;
	private Date rtgstransDate;
	private double rtgstranAmt;
	private String oltppin;
	private Date appTrnDate;
	private double appLmtAmt;
	private char pinTyp;
	private byte oltppinFlag;
	private Date oltpchangeDate;
	private Date oltpchangeTime;
	private String regNo;
	private char chqSyncYn;
	private Date payeeAddTrnDt;
	private byte payeeCount;
	private byte transCount;
	private byte trfLmtPerDay;
	private byte payeeLmtPerDay;

	public D350076() {
	}

	
	@Id
	@Column(name = "CustNo", unique = true, nullable = false, length = 19)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "Custtype", nullable = false, length = 1)
	public char getCusttype() {
		return this.custtype;
	}

	public void setCusttype(char custtype) {
		this.custtype = custtype;
	}

	@Column(name = "CustName", nullable = false, length = 30)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "TransPin", nullable = false, length = 40)
	public String getTransPin() {
		return this.transPin;
	}

	public void setTransPin(String transPin) {
		this.transPin = transPin;
	}

	@Column(name = "QueryPin", nullable = false, length = 40)
	public String getQueryPin() {
		return this.queryPin;
	}

	public void setQueryPin(String queryPin) {
		this.queryPin = queryPin;
	}

	@Column(name = "BrCode", nullable = false)
	public short getBrCode() {
		return this.brCode;
	}

	public void setBrCode(short brCode) {
		this.brCode = brCode;
	}

	@Column(name = "CityCode", nullable = false)
	public int getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(int cityCode) {
		this.cityCode = cityCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "SmartCardNo", nullable = false, length = 20)
	public String getSmartCardNo() {
		return this.smartCardNo;
	}

	public void setSmartCardNo(String smartCardNo) {
		this.smartCardNo = smartCardNo;
	}

	@Column(name = "TeleBankingSrYN", nullable = false, length = 1)
	public char getTeleBankingSrYn() {
		return this.teleBankingSrYn;
	}

	public void setTeleBankingSrYn(char teleBankingSrYn) {
		this.teleBankingSrYn = teleBankingSrYn;
	}

	@Column(name = "PCBankingSrYN", nullable = false, length = 1)
	public char getPcbankingSrYn() {
		return this.pcbankingSrYn;
	}

	public void setPcbankingSrYn(char pcbankingSrYn) {
		this.pcbankingSrYn = pcbankingSrYn;
	}

	@Column(name = "InterNetBankingSrYN", nullable = false, length = 1)
	public char getInterNetBankingSrYn() {
		return this.interNetBankingSrYn;
	}

	public void setInterNetBankingSrYn(char interNetBankingSrYn) {
		this.interNetBankingSrYn = interNetBankingSrYn;
	}

	@Column(name = "SMSBankingSr", nullable = false, length = 1)
	public char getSmsbankingSr() {
		return this.smsbankingSr;
	}

	public void setSmsbankingSr(char smsbankingSr) {
		this.smsbankingSr = smsbankingSr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastAccessDate", nullable = false, length = 23)
	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastAccessTime", nullable = false, length = 23)
	public Date getLastAccessTime() {
		return this.lastAccessTime;
	}

	public void setLastAccessTime(Date lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinChangeDate", nullable = false, length = 23)
	public Date getPinChangeDate() {
		return this.pinChangeDate;
	}

	public void setPinChangeDate(Date pinChangeDate) {
		this.pinChangeDate = pinChangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinChangeTime", nullable = false, length = 23)
	public Date getPinChangeTime() {
		return this.pinChangeTime;
	}

	public void setPinChangeTime(Date pinChangeTime) {
		this.pinChangeTime = pinChangeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TPinChangeDate", nullable = false, length = 23)
	public Date getTpinChangeDate() {
		return this.tpinChangeDate;
	}

	public void setTpinChangeDate(Date tpinChangeDate) {
		this.tpinChangeDate = tpinChangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TPinChangeTime", nullable = false, length = 23)
	public Date getTpinChangeTime() {
		return this.tpinChangeTime;
	}

	public void setTpinChangeTime(Date tpinChangeTime) {
		this.tpinChangeTime = tpinChangeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PinPrintDate", nullable = false, length = 23)
	public Date getPinPrintDate() {
		return this.pinPrintDate;
	}

	public void setPinPrintDate(Date pinPrintDate) {
		this.pinPrintDate = pinPrintDate;
	}

	@Column(name = "PinPrintCount", nullable = false)
	public short getPinPrintCount() {
		return this.pinPrintCount;
	}

	public void setPinPrintCount(short pinPrintCount) {
		this.pinPrintCount = pinPrintCount;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "MakerId", nullable = false, length = 8)
	public String getMakerId() {
		return this.makerId;
	}

	public void setMakerId(String makerId) {
		this.makerId = makerId;
	}

	@Column(name = "CheckerId", nullable = false, length = 8)
	public String getCheckerId() {
		return this.checkerId;
	}

	public void setCheckerId(String checkerId) {
		this.checkerId = checkerId;
	}

	@Column(name = "Add1", nullable = false, length = 30)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "Add2", nullable = false, length = 30)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "Add3", nullable = false, length = 30)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "PinCode", nullable = false, length = 8)
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "Phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "CityCd", nullable = false, length = 3)
	public String getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(String cityCd) {
		this.cityCd = cityCd;
	}

	@Column(name = "CashYn", nullable = false, length = 1)
	public char getCashYn() {
		return this.cashYn;
	}

	public void setCashYn(char cashYn) {
		this.cashYn = cashYn;
	}

	@Column(name = "DrClgYn", nullable = false, length = 1)
	public char getDrClgYn() {
		return this.drClgYn;
	}

	public void setDrClgYn(char drClgYn) {
		this.drClgYn = drClgYn;
	}

	@Column(name = "CrClgYn", nullable = false, length = 1)
	public char getCrClgYn() {
		return this.crClgYn;
	}

	public void setCrClgYn(char crClgYn) {
		this.crClgYn = crClgYn;
	}

	@Column(name = "TrfYn", nullable = false, length = 1)
	public char getTrfYn() {
		return this.trfYn;
	}

	public void setTrfYn(char trfYn) {
		this.trfYn = trfYn;
	}

	@Column(name = "AbbYn", nullable = false, length = 1)
	public char getAbbYn() {
		return this.abbYn;
	}

	public void setAbbYn(char abbYn) {
		this.abbYn = abbYn;
	}

	@Column(name = "AtmYn", nullable = false, length = 1)
	public char getAtmYn() {
		return this.atmYn;
	}

	public void setAtmYn(char atmYn) {
		this.atmYn = atmYn;
	}

	@Column(name = "CashLimit", nullable = false, precision = 53, scale = 0)
	public double getCashLimit() {
		return this.cashLimit;
	}

	public void setCashLimit(double cashLimit) {
		this.cashLimit = cashLimit;
	}

	@Column(name = "DrClgLimit", nullable = false, precision = 53, scale = 0)
	public double getDrClgLimit() {
		return this.drClgLimit;
	}

	public void setDrClgLimit(double drClgLimit) {
		this.drClgLimit = drClgLimit;
	}

	@Column(name = "CrClgLimit", nullable = false, precision = 53, scale = 0)
	public double getCrClgLimit() {
		return this.crClgLimit;
	}

	public void setCrClgLimit(double crClgLimit) {
		this.crClgLimit = crClgLimit;
	}

	@Column(name = "TrfLimit", nullable = false, precision = 53, scale = 0)
	public double getTrfLimit() {
		return this.trfLimit;
	}

	public void setTrfLimit(double trfLimit) {
		this.trfLimit = trfLimit;
	}

	@Column(name = "AbbLimit", nullable = false, precision = 53, scale = 0)
	public double getAbbLimit() {
		return this.abbLimit;
	}

	public void setAbbLimit(double abbLimit) {
		this.abbLimit = abbLimit;
	}

	@Column(name = "AtmLimit", nullable = false, precision = 53, scale = 0)
	public double getAtmLimit() {
		return this.atmLimit;
	}

	public void setAtmLimit(double atmLimit) {
		this.atmLimit = atmLimit;
	}

	@Column(name = "Stat", nullable = false)
	public byte getStat() {
		return this.stat;
	}

	public void setStat(byte stat) {
		this.stat = stat;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "IBQueryPin", nullable = false, length = 40)
	public String getIbqueryPin() {
		return this.ibqueryPin;
	}

	public void setIbqueryPin(String ibqueryPin) {
		this.ibqueryPin = ibqueryPin;
	}

	@Column(name = "CustUsrId", length = 8)
	public String getCustUsrId() {
		return this.custUsrId;
	}

	public void setCustUsrId(String custUsrId) {
		this.custUsrId = custUsrId;
	}

	@Column(name = "RTGSNEFTYN", nullable = false, length = 1)
	public char getRtgsneftyn() {
		return this.rtgsneftyn;
	}

	public void setRtgsneftyn(char rtgsneftyn) {
		this.rtgsneftyn = rtgsneftyn;
	}

	@Column(name = "RTGSLimit", nullable = false, precision = 53, scale = 0)
	public double getRtgslimit() {
		return this.rtgslimit;
	}

	public void setRtgslimit(double rtgslimit) {
		this.rtgslimit = rtgslimit;
	}

	@Column(name = "NEFTLimit", nullable = false, precision = 53, scale = 0)
	public double getNeftlimit() {
		return this.neftlimit;
	}

	public void setNeftlimit(double neftlimit) {
		this.neftlimit = neftlimit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEFTTransDate", nullable = false, length = 23)
	public Date getNefttransDate() {
		return this.nefttransDate;
	}

	public void setNefttransDate(Date nefttransDate) {
		this.nefttransDate = nefttransDate;
	}

	@Column(name = "NEFTTranAmt", nullable = false, precision = 53, scale = 0)
	public double getNefttranAmt() {
		return this.nefttranAmt;
	}

	public void setNefttranAmt(double nefttranAmt) {
		this.nefttranAmt = nefttranAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RTGSTransDate", nullable = false, length = 23)
	public Date getRtgstransDate() {
		return this.rtgstransDate;
	}

	public void setRtgstransDate(Date rtgstransDate) {
		this.rtgstransDate = rtgstransDate;
	}

	@Column(name = "RTGSTranAmt", nullable = false, precision = 53, scale = 0)
	public double getRtgstranAmt() {
		return this.rtgstranAmt;
	}

	public void setRtgstranAmt(double rtgstranAmt) {
		this.rtgstranAmt = rtgstranAmt;
	}

	@Column(name = "OLTPPin", nullable = false, length = 40)
	public String getOltppin() {
		return this.oltppin;
	}

	public void setOltppin(String oltppin) {
		this.oltppin = oltppin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppTrnDate", nullable = false, length = 23)
	public Date getAppTrnDate() {
		return this.appTrnDate;
	}

	public void setAppTrnDate(Date appTrnDate) {
		this.appTrnDate = appTrnDate;
	}

	@Column(name = "AppLmtAmt", nullable = false, precision = 53, scale = 0)
	public double getAppLmtAmt() {
		return this.appLmtAmt;
	}

	public void setAppLmtAmt(double appLmtAmt) {
		this.appLmtAmt = appLmtAmt;
	}

	@Column(name = "PinTyp", nullable = false, length = 1)
	public char getPinTyp() {
		return this.pinTyp;
	}

	public void setPinTyp(char pinTyp) {
		this.pinTyp = pinTyp;
	}

	@Column(name = "OLTPPinFlag", nullable = false)
	public byte getOltppinFlag() {
		return this.oltppinFlag;
	}

	public void setOltppinFlag(byte oltppinFlag) {
		this.oltppinFlag = oltppinFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OLTPChangeDate", nullable = false, length = 23)
	public Date getOltpchangeDate() {
		return this.oltpchangeDate;
	}

	public void setOltpchangeDate(Date oltpchangeDate) {
		this.oltpchangeDate = oltpchangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OLTPChangeTime", nullable = false, length = 23)
	public Date getOltpchangeTime() {
		return this.oltpchangeTime;
	}

	public void setOltpchangeTime(Date oltpchangeTime) {
		this.oltpchangeTime = oltpchangeTime;
	}

	@Column(name = "RegNo", nullable = false, length = 12)
	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	@Column(name = "ChqSyncYN", nullable = false, length = 1)
	public char getChqSyncYn() {
		return this.chqSyncYn;
	}

	public void setChqSyncYn(char chqSyncYn) {
		this.chqSyncYn = chqSyncYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PayeeAddTrnDt", nullable = false, length = 23)
	public Date getPayeeAddTrnDt() {
		return this.payeeAddTrnDt;
	}

	public void setPayeeAddTrnDt(Date payeeAddTrnDt) {
		this.payeeAddTrnDt = payeeAddTrnDt;
	}

	@Column(name = "PayeeCount", nullable = false)
	public byte getPayeeCount() {
		return this.payeeCount;
	}

	public void setPayeeCount(byte payeeCount) {
		this.payeeCount = payeeCount;
	}

	@Column(name = "TransCount", nullable = false)
	public byte getTransCount() {
		return this.transCount;
	}

	public void setTransCount(byte transCount) {
		this.transCount = transCount;
	}

	@Column(name = "TrfLmtPerDay", nullable = false)
	public byte getTrfLmtPerDay() {
		return this.trfLmtPerDay;
	}

	public void setTrfLmtPerDay(byte trfLmtPerDay) {
		this.trfLmtPerDay = trfLmtPerDay;
	}

	@Column(name = "PayeeLmtPerDay", nullable = false)
	public byte getPayeeLmtPerDay() {
		return this.payeeLmtPerDay;
	}

	public void setPayeeLmtPerDay(byte payeeLmtPerDay) {
		this.payeeLmtPerDay = payeeLmtPerDay;
	}

}
