package com.sil.hbm;
// Generated Jan 24, 2017 11:07:08 AM by Hibernate Tools 5.2.0.Beta1
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**AA
 * D350032 generated by hbm2java
 */
@Entity
@Table(name = "D350032")
@DynamicInsert
@DynamicUpdate
public class D350032 implements java.io.Serializable {
	private static final long serialVersionUID = 6939560690690816544L;
	private D350032Id id;
	private String acctNo;
	private int brCode;
	private String acctName;

	public D350032() {
	}

	public D350032(D350032Id id, String acctNo, int brCode, String acctName) {
		this.id = id;
		this.acctNo = acctNo;
		this.brCode = brCode;
		this.acctName = acctName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false, length = 19)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo", nullable = false, length = 12)),
			@AttributeOverride(name = "mmid", column = @Column(name = "MMID", nullable = false, length = 7)) })
	public D350032Id getId() {
		return this.id;
	}

	public void setId(D350032Id id) {
		this.id = id;
	}

	@Column(name = "AcctNo", nullable = false, length = 32)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	@Column(name = "BrCode", nullable = false)
	public int getBrCode() {
		return this.brCode;
	}

	public void setBrCode(int brCode) {
		this.brCode = brCode;
	}

	@Column(name = "AcctName", nullable = false, length = 50)
	public String getAcctName() {
		return this.acctName;
	}

	public void setAcctName(String acctName) {
		this.acctName = acctName;
	}

}
