package com.sil.hbm;
// Generated Dec 16, 2016 3:58:39 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350059 generated by hbm2java
 */
@Entity
@Table(name = "D350059")
@DynamicInsert
@DynamicUpdate
public class D350059 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4330330998872654495L;
	private D350059Id id;

	public D350059() {
	}

	public D350059(D350059Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LbrCode")),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", length = 23)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo")),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo")),
			@AttributeOverride(name = "mobNo1", column = @Column(name = "MobNo1", length = 20)),
			@AttributeOverride(name = "mmid1", column = @Column(name = "MMID1", length = 15)),
			@AttributeOverride(name = "accNo", column = @Column(name = "AccNo", length = 20)),
			@AttributeOverride(name = "ifscCd", column = @Column(name = "IfscCd", length = 15)),
			@AttributeOverride(name = "tranAmt", column = @Column(name = "TranAmt")),
			@AttributeOverride(name = "responseCd", column = @Column(name = "ResponseCd", length = 8)),
			@AttributeOverride(name = "responseDesc", column = @Column(name = "ResponseDesc", length = 100)),
			@AttributeOverride(name = "rrnNo", column = @Column(name = "RrnNo", length = 20)),
			@AttributeOverride(name = "stan", column = @Column(name = "STAN", length = 20)),
			@AttributeOverride(name = "entryTime", column = @Column(name = "EntryTime", length = 23)),
			@AttributeOverride(name = "transactionDate", column = @Column(name = "TransactionDate", length = 23)),
			@AttributeOverride(name = "drcr", column = @Column(name = "DRCR", length = 2)) })
	public D350059Id getId() {
		return this.id;
	}

	public void setId(D350059Id id) {
		this.id = id;
	}

}
