package com.sil.hbm;
// Generated Dec 16, 2016 3:58:39 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D350044Id generated by hbm2java
 */
@Embeddable
public class D350044Id implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2558199027797433680L;
	private Integer lbrCode;
	private Date entryDate;
	private String batchCd;
	private Integer setNo;
	private Integer scrollNo;
	private String mobNo1;
	private String mmid1;
	private String mobNo2;
	private String mmid2;
	private Integer tranAmt;
	private String responseCd;
	private String responseDesc;
	private String rrnNo;
	private String stan;
	private Date entryTime;
	private Date transactionDate;
	private String drcr;

	public D350044Id() {
	}

	public D350044Id(Integer lbrCode, Date entryDate, String batchCd, Integer setNo, Integer scrollNo, String mobNo1,
			String mmid1, String mobNo2, String mmid2, Integer tranAmt, String responseCd, String responseDesc,
			String rrnNo, String stan, Date entryTime, Date transactionDate, String drcr) {
		this.lbrCode = lbrCode;
		this.entryDate = entryDate;
		this.batchCd = batchCd;
		this.setNo = setNo;
		this.scrollNo = scrollNo;
		this.mobNo1 = mobNo1;
		this.mmid1 = mmid1;
		this.mobNo2 = mobNo2;
		this.mmid2 = mmid2;
		this.tranAmt = tranAmt;
		this.responseCd = responseCd;
		this.responseDesc = responseDesc;
		this.rrnNo = rrnNo;
		this.stan = stan;
		this.entryTime = entryTime;
		this.transactionDate = transactionDate;
		this.drcr = drcr;
	}

	@Column(name = "LbrCode")
	public Integer getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(Integer lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "EntryDate", length = 23)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "BatchCd", length = 8)
	public String getBatchCd() {
		return this.batchCd;
	}

	public void setBatchCd(String batchCd) {
		this.batchCd = batchCd;
	}

	@Column(name = "SetNo")
	public Integer getSetNo() {
		return this.setNo;
	}

	public void setSetNo(Integer setNo) {
		this.setNo = setNo;
	}

	@Column(name = "ScrollNo")
	public Integer getScrollNo() {
		return this.scrollNo;
	}

	public void setScrollNo(Integer scrollNo) {
		this.scrollNo = scrollNo;
	}

	@Column(name = "MobNo1", length = 12)
	public String getMobNo1() {
		return this.mobNo1;
	}

	public void setMobNo1(String mobNo1) {
		this.mobNo1 = mobNo1;
	}

	@Column(name = "MMID1", length = 8)
	public String getMmid1() {
		return this.mmid1;
	}

	public void setMmid1(String mmid1) {
		this.mmid1 = mmid1;
	}

	@Column(name = "MobNo2", length = 12)
	public String getMobNo2() {
		return this.mobNo2;
	}

	public void setMobNo2(String mobNo2) {
		this.mobNo2 = mobNo2;
	}

	@Column(name = "MMID2", length = 8)
	public String getMmid2() {
		return this.mmid2;
	}

	public void setMmid2(String mmid2) {
		this.mmid2 = mmid2;
	}

	@Column(name = "TranAmt")
	public Integer getTranAmt() {
		return this.tranAmt;
	}

	public void setTranAmt(Integer tranAmt) {
		this.tranAmt = tranAmt;
	}

	@Column(name = "ResponseCd", length = 8)
	public String getResponseCd() {
		return this.responseCd;
	}

	public void setResponseCd(String responseCd) {
		this.responseCd = responseCd;
	}

	@Column(name = "ResponseDesc", length = 100)
	public String getResponseDesc() {
		return this.responseDesc;
	}

	public void setResponseDesc(String responseDesc) {
		this.responseDesc = responseDesc;
	}

	@Column(name = "RrnNo", length = 20)
	public String getRrnNo() {
		return this.rrnNo;
	}

	public void setRrnNo(String rrnNo) {
		this.rrnNo = rrnNo;
	}

	@Column(name = "STAN", length = 20)
	public String getStan() {
		return this.stan;
	}

	public void setStan(String stan) {
		this.stan = stan;
	}

	@Column(name = "EntryTime", length = 23)
	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	@Column(name = "TransactionDate", length = 23)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "DRCR", length = 2)
	public String getDrcr() {
		return this.drcr;
	}

	public void setDrcr(String drcr) {
		this.drcr = drcr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D350044Id))
			return false;
		D350044Id castOther = (D350044Id) other;

		return ((this.getLbrCode() == castOther.getLbrCode()) || (this.getLbrCode() != null
				&& castOther.getLbrCode() != null && this.getLbrCode().equals(castOther.getLbrCode())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null
						&& castOther.getEntryDate() != null && this.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getBatchCd() == castOther.getBatchCd()) || (this.getBatchCd() != null
						&& castOther.getBatchCd() != null && this.getBatchCd().equals(castOther.getBatchCd())))
				&& ((this.getSetNo() == castOther.getSetNo()) || (this.getSetNo() != null
						&& castOther.getSetNo() != null && this.getSetNo().equals(castOther.getSetNo())))
				&& ((this.getScrollNo() == castOther.getScrollNo()) || (this.getScrollNo() != null
						&& castOther.getScrollNo() != null && this.getScrollNo().equals(castOther.getScrollNo())))
				&& ((this.getMobNo1() == castOther.getMobNo1()) || (this.getMobNo1() != null
						&& castOther.getMobNo1() != null && this.getMobNo1().equals(castOther.getMobNo1())))
				&& ((this.getMmid1() == castOther.getMmid1()) || (this.getMmid1() != null
						&& castOther.getMmid1() != null && this.getMmid1().equals(castOther.getMmid1())))
				&& ((this.getMobNo2() == castOther.getMobNo2()) || (this.getMobNo2() != null
						&& castOther.getMobNo2() != null && this.getMobNo2().equals(castOther.getMobNo2())))
				&& ((this.getMmid2() == castOther.getMmid2()) || (this.getMmid2() != null
						&& castOther.getMmid2() != null && this.getMmid2().equals(castOther.getMmid2())))
				&& ((this.getTranAmt() == castOther.getTranAmt()) || (this.getTranAmt() != null
						&& castOther.getTranAmt() != null && this.getTranAmt().equals(castOther.getTranAmt())))
				&& ((this.getResponseCd() == castOther.getResponseCd()) || (this.getResponseCd() != null
						&& castOther.getResponseCd() != null && this.getResponseCd().equals(castOther.getResponseCd())))
				&& ((this.getResponseDesc() == castOther.getResponseDesc())
						|| (this.getResponseDesc() != null && castOther.getResponseDesc() != null
								&& this.getResponseDesc().equals(castOther.getResponseDesc())))
				&& ((this.getRrnNo() == castOther.getRrnNo()) || (this.getRrnNo() != null
						&& castOther.getRrnNo() != null && this.getRrnNo().equals(castOther.getRrnNo())))
				&& ((this.getStan() == castOther.getStan()) || (this.getStan() != null && castOther.getStan() != null
						&& this.getStan().equals(castOther.getStan())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this.getEntryTime() != null
						&& castOther.getEntryTime() != null && this.getEntryTime().equals(castOther.getEntryTime())))
				&& ((this.getTransactionDate() == castOther.getTransactionDate())
						|| (this.getTransactionDate() != null && castOther.getTransactionDate() != null
								&& this.getTransactionDate().equals(castOther.getTransactionDate())))
				&& ((this.getDrcr() == castOther.getDrcr()) || (this.getDrcr() != null && castOther.getDrcr() != null
						&& this.getDrcr().equals(castOther.getDrcr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLbrCode() == null ? 0 : this.getLbrCode().hashCode());
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getBatchCd() == null ? 0 : this.getBatchCd().hashCode());
		result = 37 * result + (getSetNo() == null ? 0 : this.getSetNo().hashCode());
		result = 37 * result + (getScrollNo() == null ? 0 : this.getScrollNo().hashCode());
		result = 37 * result + (getMobNo1() == null ? 0 : this.getMobNo1().hashCode());
		result = 37 * result + (getMmid1() == null ? 0 : this.getMmid1().hashCode());
		result = 37 * result + (getMobNo2() == null ? 0 : this.getMobNo2().hashCode());
		result = 37 * result + (getMmid2() == null ? 0 : this.getMmid2().hashCode());
		result = 37 * result + (getTranAmt() == null ? 0 : this.getTranAmt().hashCode());
		result = 37 * result + (getResponseCd() == null ? 0 : this.getResponseCd().hashCode());
		result = 37 * result + (getResponseDesc() == null ? 0 : this.getResponseDesc().hashCode());
		result = 37 * result + (getRrnNo() == null ? 0 : this.getRrnNo().hashCode());
		result = 37 * result + (getStan() == null ? 0 : this.getStan().hashCode());
		result = 37 * result + (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		result = 37 * result + (getTransactionDate() == null ? 0 : this.getTransactionDate().hashCode());
		result = 37 * result + (getDrcr() == null ? 0 : this.getDrcr().hashCode());
		return result;
	}

}
