package com.sil.hbm;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
/**
 * D350094 generated by hbm2java
 */
@Entity
@Table(name = "D350094")
@DynamicInsert
@DynamicUpdate
public class D350094 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5030799609584984589L;
	private D350094Id id;

	public D350094() {
	}

	public D350094(D350094Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LbrCode")),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", length = 23)),
			@AttributeOverride(name = "transactionDate", column = @Column(name = "TransactionDate", length = 23)),
			@AttributeOverride(name = "ref", column = @Column(name = "Ref", length = 50)),
			@AttributeOverride(name = "drCr", column = @Column(name = "DrCr", length = 2)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo")),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo")),
			@AttributeOverride(name = "mobNo1", column = @Column(name = "MobNo1", length = 12)),
			@AttributeOverride(name = "mmid1", column = @Column(name = "MMID1", length = 8)),
			@AttributeOverride(name = "mobNo2", column = @Column(name = "MobNo2", length = 12)),
			@AttributeOverride(name = "mmid2", column = @Column(name = "MMID2", length = 8)),
			@AttributeOverride(name = "tranAmt", column = @Column(name = "TranAmt")),
			@AttributeOverride(name = "responsecd", column = @Column(name = "RESPONSECD", length = 8)),
			@AttributeOverride(name = "responsedesc", column = @Column(name = "RESPONSEDESC", length = 100)),
			@AttributeOverride(name = "rrnno", column = @Column(name = "RRNNO", length = 20)),
			@AttributeOverride(name = "stan", column = @Column(name = "STAN", length = 20)),
			@AttributeOverride(name = "entrytime", column = @Column(name = "ENTRYTIME", length = 23)),
			@AttributeOverride(name = "merchrespcd", column = @Column(name = "MERCHRESPCD", length = 8)),
			@AttributeOverride(name = "merchmessage", column = @Column(name = "MERCHMESSAGE", length = 100)) })
	public D350094Id getId() {
		return this.id;
	}

	public void setId(D350094Id id) {
		this.id = id;
	}

}
