package com.sil.hbm;
// Generated 20 Sep, 2016 2:32:51 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350036 generated by hbm2java
 */
@Entity
@Table(name = "D350036")
@DynamicInsert
@DynamicUpdate
public class D350036 implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4679643153445094065L;
	private D350036Id id;
	private String mobNo1;
	private String mmid1;
	private String mobNo2;
	private String mmid2;
	private Double tranAmt;
	private String responseCd;
	private String responseDesc;
	private String rrnNo;
	private String stan;
	private String merchRespCd;
	private String merchMessage;
	private Date transactionDate;
	private String drcr;
	private String source;

	public D350036() {
	}

	public D350036(D350036Id id, String mobNo1, String mmid1, String mobNo2, String mmid2, String responseCd,
			String responseDesc, String rrnNo, String stan) {
		this.id = id;
		this.mobNo1 = mobNo1;
		this.mmid1 = mmid1;
		this.mobNo2 = mobNo2;
		this.mmid2 = mmid2;
		this.responseCd = responseCd;
		this.responseDesc = responseDesc;
		this.rrnNo = rrnNo;
		this.stan = stan;
	}

	public D350036(D350036Id id, String mobNo1, String mmid1, String mobNo2, String mmid2, Double tranAmt,
			String responseCd, String responseDesc, String rrnNo, String stan, String merchRespCd, String merchMessage,
			Date transactionDate, String drcr) {
		this.id = id;
		this.mobNo1 = mobNo1;
		this.mmid1 = mmid1;
		this.mobNo2 = mobNo2;
		this.mmid2 = mmid2;
		this.tranAmt = tranAmt;
		this.responseCd = responseCd;
		this.responseDesc = responseDesc;
		this.rrnNo = rrnNo;
		this.stan = stan;
		this.merchRespCd = merchRespCd;
		this.merchMessage = merchMessage;
		this.transactionDate = transactionDate;
		this.drcr = drcr;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lbrCode", column = @Column(name = "LbrCode", nullable = false)),
			@AttributeOverride(name = "entryDate", column = @Column(name = "EntryDate", nullable = false, length = 23)),
			@AttributeOverride(name = "batchCd", column = @Column(name = "BatchCd", nullable = false, length = 8)),
			@AttributeOverride(name = "setNo", column = @Column(name = "SetNo", nullable = false)),
			@AttributeOverride(name = "scrollNo", column = @Column(name = "ScrollNo", nullable = false)),
			@AttributeOverride(name = "source", column = @Column(name = "SOURCE", nullable = false)),
			@AttributeOverride(name = "entryTime", column = @Column(name = "EntryTime", nullable = false, length = 23)) })
	public D350036Id getId() {
		return this.id;
	}

	public void setId(D350036Id id) {
		this.id = id;
	}

	@Column(name = "MobNo1", nullable = false, length = 12)
	public String getMobNo1() {
		return this.mobNo1;
	}

	public void setMobNo1(String mobNo1) {
		this.mobNo1 = mobNo1;
	}

	@Column(name = "MMID1", nullable = false, length = 8)
	public String getMmid1() {
		return this.mmid1;
	}

	public void setMmid1(String mmid1) {
		this.mmid1 = mmid1;
	}

	@Column(name = "MobNo2", nullable = false, length = 12)
	public String getMobNo2() {
		return this.mobNo2;
	}

	public void setMobNo2(String mobNo2) {
		this.mobNo2 = mobNo2;
	}

	@Column(name = "MMID2", nullable = false, length = 8)
	public String getMmid2() {
		return this.mmid2;
	}

	public void setMmid2(String mmid2) {
		this.mmid2 = mmid2;
	}

	@Column(name = "TranAmt", precision = 53, scale = 0)
	public Double getTranAmt() {
		return this.tranAmt;
	}

	public void setTranAmt(Double tranAmt) {
		this.tranAmt = tranAmt;
	}

	@Column(name = "ResponseCd", nullable = false, length = 8)
	public String getResponseCd() {
		return this.responseCd;
	}

	public void setResponseCd(String responseCd) {
		this.responseCd = responseCd;
	}

	@Column(name = "ResponseDesc", nullable = false, length = 100)
	public String getResponseDesc() {
		return this.responseDesc;
	}

	public void setResponseDesc(String responseDesc) {
		this.responseDesc = responseDesc;
	}

	@Column(name = "RrnNo", nullable = false, length = 20)
	public String getRrnNo() {
		return this.rrnNo;
	}

	public void setRrnNo(String rrnNo) {
		this.rrnNo = rrnNo;
	}

	@Column(name = "STAN", nullable = false, length = 20)
	public String getStan() {
		return this.stan;
	}

	public void setStan(String stan) {
		this.stan = stan;
	}

	@Column(name = "MerchRespCd", length = 8)
	public String getMerchRespCd() {
		return this.merchRespCd;
	}

	public void setMerchRespCd(String merchRespCd) {
		this.merchRespCd = merchRespCd;
	}

	@Column(name = "MerchMessage", length = 100)
	public String getMerchMessage() {
		return this.merchMessage;
	}

	public void setMerchMessage(String merchMessage) {
		this.merchMessage = merchMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransactionDate", length = 23)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "DRCR", length = 2)
	public String getDrcr() {
		return this.drcr;
	}

	public void setDrcr(String drcr) {
		this.drcr = drcr;
	}

	@Column(name = "SOURCE", length = 100)
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	
}
