package com.sil.hbm;
// Generated Dec 16, 2017 12:20:42 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350066 generated by hbm2java
 */
@Entity
@Table(name = "D350066")
@DynamicInsert
@DynamicUpdate
public class D350066 implements java.io.Serializable {
	private static final long serialVersionUID = 1420722972563539630L;
	private D350066Id id;
	private String pan;
	private double transAmt;
	private int sysAutNo;
	private int reconNo;
	private String atmAcctId;
	private String toAcctId;
	private byte reversal;
	private String filler;
	private byte status;
	private short response;
	private int setNo;
	private int scroll;
	private int error;
	private int errLeg2;
	private String batchCd;
	private Date entryDate;
	private String processCode;
	private Date captureDate;
	private String acctNo102;
	private String acctNo103;
	private String originalDataElements;
	private int lbrCode;
	private int msgType;
	private String networkId;
	private String merchantId;
	private String terminalName;
	private String acqTerminalBankName;
	private String isotransactionCurr;
	private Date vcrEntryDate;
	private int vcrInstrumentType;
	private String issuerId;
	private char atmcontrollerSuspect;
	private String atmauthNo;

	public D350066() {
	}

	public D350066(D350066Id id, String pan, double transAmt, int sysAutNo, int reconNo, String atmAcctId,
			String toAcctId, byte reversal, String filler, byte status, short response, int setNo, int scroll,
			int error, int errLeg2, String batchCd, Date entryDate, String processCode, Date captureDate,
			String acctNo102, String acctNo103, String originalDataElements, int lbrCode, int msgType, String networkId,
			String merchantId, String terminalName, String acqTerminalBankName, String isotransactionCurr,
			Date vcrEntryDate, int vcrInstrumentType, String issuerId, char atmcontrollerSuspect, String atmauthNo) {
		this.id = id;
		this.pan = pan;
		this.transAmt = transAmt;
		this.sysAutNo = sysAutNo;
		this.reconNo = reconNo;
		this.atmAcctId = atmAcctId;
		this.toAcctId = toAcctId;
		this.reversal = reversal;
		this.filler = filler;
		this.status = status;
		this.response = response;
		this.setNo = setNo;
		this.scroll = scroll;
		this.error = error;
		this.errLeg2 = errLeg2;
		this.batchCd = batchCd;
		this.entryDate = entryDate;
		this.processCode = processCode;
		this.captureDate = captureDate;
		this.acctNo102 = acctNo102;
		this.acctNo103 = acctNo103;
		this.originalDataElements = originalDataElements;
		this.lbrCode = lbrCode;
		this.msgType = msgType;
		this.networkId = networkId;
		this.merchantId = merchantId;
		this.terminalName = terminalName;
		this.acqTerminalBankName = acqTerminalBankName;
		this.isotransactionCurr = isotransactionCurr;
		this.vcrEntryDate = vcrEntryDate;
		this.vcrInstrumentType = vcrInstrumentType;
		this.issuerId = issuerId;
		this.atmcontrollerSuspect = atmcontrollerSuspect;
		this.atmauthNo = atmauthNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "aquirerId", column = @Column(name = "AquirerId", nullable = false, length = 11)),
			@AttributeOverride(name = "atmid", column = @Column(name = "ATMID", nullable = false, length = 16)),
			@AttributeOverride(name = "retrRefNo", column = @Column(name = "RetrRefNo", nullable = false, length = 12)),
			@AttributeOverride(name = "atmdate", column = @Column(name = "ATMDate", nullable = false, length = 23)),
			@AttributeOverride(name = "atmtime", column = @Column(name = "ATMTime", nullable = false, length = 23)),
			@AttributeOverride(name = "drCr", column = @Column(name = "DrCr", nullable = false, length = 1)),
			@AttributeOverride(name = "brCode", column = @Column(name = "BrCode", nullable = false)),
			@AttributeOverride(name = "destBrCode", column = @Column(name = "DestBrCode", nullable = false)),
			@AttributeOverride(name = "atmTransType", column = @Column(name = "AtmTransType", nullable = false, length = 8)) })
	public D350066Id getId() {
		return this.id;
	}

	public void setId(D350066Id id) {
		this.id = id;
	}

	@Column(name = "PAN", nullable = false, length = 19)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "TransAmt", nullable = false, precision = 53, scale = 0)
	public double getTransAmt() {
		return this.transAmt;
	}

	public void setTransAmt(double transAmt) {
		this.transAmt = transAmt;
	}

	@Column(name = "SysAutNo", nullable = false)
	public int getSysAutNo() {
		return this.sysAutNo;
	}

	public void setSysAutNo(int sysAutNo) {
		this.sysAutNo = sysAutNo;
	}

	@Column(name = "ReconNo", nullable = false)
	public int getReconNo() {
		return this.reconNo;
	}

	public void setReconNo(int reconNo) {
		this.reconNo = reconNo;
	}

	@Column(name = "AtmAcctId", nullable = false, length = 32)
	public String getAtmAcctId() {
		return this.atmAcctId;
	}

	public void setAtmAcctId(String atmAcctId) {
		this.atmAcctId = atmAcctId;
	}

	@Column(name = "ToAcctId", nullable = false, length = 32)
	public String getToAcctId() {
		return this.toAcctId;
	}

	public void setToAcctId(String toAcctId) {
		this.toAcctId = toAcctId;
	}

	@Column(name = "Reversal", nullable = false)
	public byte getReversal() {
		return this.reversal;
	}

	public void setReversal(byte reversal) {
		this.reversal = reversal;
	}

	@Column(name = "Filler", nullable = false, length = 10)
	public String getFiller() {
		return this.filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "Response", nullable = false)
	public short getResponse() {
		return this.response;
	}

	public void setResponse(short response) {
		this.response = response;
	}

	@Column(name = "SetNo", nullable = false)
	public int getSetNo() {
		return this.setNo;
	}

	public void setSetNo(int setNo) {
		this.setNo = setNo;
	}

	@Column(name = "Scroll", nullable = false)
	public int getScroll() {
		return this.scroll;
	}

	public void setScroll(int scroll) {
		this.scroll = scroll;
	}

	@Column(name = "Error", nullable = false)
	public int getError() {
		return this.error;
	}

	public void setError(int error) {
		this.error = error;
	}

	@Column(name = "ErrLeg2", nullable = false)
	public int getErrLeg2() {
		return this.errLeg2;
	}

	public void setErrLeg2(int errLeg2) {
		this.errLeg2 = errLeg2;
	}

	@Column(name = "BatchCd", nullable = false, length = 8)
	public String getBatchCd() {
		return this.batchCd;
	}

	public void setBatchCd(String batchCd) {
		this.batchCd = batchCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EntryDate", nullable = false, length = 23)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "ProcessCode", nullable = false, length = 6)
	public String getProcessCode() {
		return this.processCode;
	}

	public void setProcessCode(String processCode) {
		this.processCode = processCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CaptureDate", nullable = false, length = 23)
	public Date getCaptureDate() {
		return this.captureDate;
	}

	public void setCaptureDate(Date captureDate) {
		this.captureDate = captureDate;
	}

	@Column(name = "AcctNo102", nullable = false, length = 28)
	public String getAcctNo102() {
		return this.acctNo102;
	}

	public void setAcctNo102(String acctNo102) {
		this.acctNo102 = acctNo102;
	}

	@Column(name = "AcctNo103", nullable = false, length = 28)
	public String getAcctNo103() {
		return this.acctNo103;
	}

	public void setAcctNo103(String acctNo103) {
		this.acctNo103 = acctNo103;
	}

	@Column(name = "OriginalDataElements", nullable = false, length = 128)
	public String getOriginalDataElements() {
		return this.originalDataElements;
	}

	public void setOriginalDataElements(String originalDataElements) {
		this.originalDataElements = originalDataElements;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "MsgType", nullable = false)
	public int getMsgType() {
		return this.msgType;
	}

	public void setMsgType(int msgType) {
		this.msgType = msgType;
	}

	@Column(name = "NetworkID", nullable = false, length = 6)
	public String getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(String networkId) {
		this.networkId = networkId;
	}

	@Column(name = "MerchantID", nullable = false, length = 4)
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "TerminalName", nullable = false, length = 8)
	public String getTerminalName() {
		return this.terminalName;
	}

	public void setTerminalName(String terminalName) {
		this.terminalName = terminalName;
	}

	@Column(name = "AcqTerminalBankName", nullable = false, length = 40)
	public String getAcqTerminalBankName() {
		return this.acqTerminalBankName;
	}

	public void setAcqTerminalBankName(String acqTerminalBankName) {
		this.acqTerminalBankName = acqTerminalBankName;
	}

	@Column(name = "ISOTransactionCurr", nullable = false, length = 3)
	public String getIsotransactionCurr() {
		return this.isotransactionCurr;
	}

	public void setIsotransactionCurr(String isotransactionCurr) {
		this.isotransactionCurr = isotransactionCurr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VcrEntryDate", nullable = false, length = 23)
	public Date getVcrEntryDate() {
		return this.vcrEntryDate;
	}

	public void setVcrEntryDate(Date vcrEntryDate) {
		this.vcrEntryDate = vcrEntryDate;
	}

	@Column(name = "VcrInstrumentType", nullable = false)
	public int getVcrInstrumentType() {
		return this.vcrInstrumentType;
	}

	public void setVcrInstrumentType(int vcrInstrumentType) {
		this.vcrInstrumentType = vcrInstrumentType;
	}

	@Column(name = "IssuerId", nullable = false, length = 11)
	public String getIssuerId() {
		return this.issuerId;
	}

	public void setIssuerId(String issuerId) {
		this.issuerId = issuerId;
	}

	@Column(name = "ATMControllerSuspect", nullable = false, length = 1)
	public char getAtmcontrollerSuspect() {
		return this.atmcontrollerSuspect;
	}

	public void setAtmcontrollerSuspect(char atmcontrollerSuspect) {
		this.atmcontrollerSuspect = atmcontrollerSuspect;
	}

	@Column(name = "ATMAuthNo", nullable = false, length = 6)
	public String getAtmauthNo() {
		return this.atmauthNo;
	}

	public void setAtmauthNo(String atmauthNo) {
		this.atmauthNo = atmauthNo;
	}
	@Override
	public String toString() {
		return "D350066 [id=" + id + ", pan=" + pan + ", transAmt=" + transAmt + ", sysAutNo=" + sysAutNo + ", reconNo="
				+ reconNo + ", atmAcctId=" + atmAcctId + ", toAcctId=" + toAcctId + ", reversal=" + reversal
				+ ", filler=" + filler + ", status=" + status + ", response=" + response + ", setNo=" + setNo
				+ ", scroll=" + scroll + ", error=" + error + ", errLeg2=" + errLeg2 + ", batchCd=" + batchCd
				+ ", entryDate=" + entryDate + ", processCode=" + processCode + ", captureDate=" + captureDate
				+ ", acctNo102=" + acctNo102 + ", acctNo103=" + acctNo103 + ", originalDataElements="
				+ originalDataElements + ", lbrCode=" + lbrCode + ", msgType=" + msgType + ", networkId=" + networkId
				+ ", merchantId=" + merchantId + ", terminalName=" + terminalName + ", acqTerminalBankName="
				+ acqTerminalBankName + ", isotransactionCurr=" + isotransactionCurr + ", vcrEntryDate=" + vcrEntryDate
				+ ", vcrInstrumentType=" + vcrInstrumentType + ", issuerId=" + issuerId + ", atmcontrollerSuspect="
				+ atmcontrollerSuspect + ", atmauthNo=" + atmauthNo + "]";
	}
	
}
