package com.sil.hbm;
// Generated Dec 16, 2017 12:20:42 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D350066Id generated by hbm2java
 */
@Embeddable
public class D350066Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4505787356719513362L;
	private String aquirerId;
	private String atmid;
	private String retrRefNo;
	private Date atmdate;
	private Date atmtime;
	private char drCr;
	private int brCode;
	private int destBrCode;
	private String atmTransType;

	public D350066Id() {
	}

	public D350066Id(String aquirerId, String atmid, String retrRefNo, Date atmdate, Date atmtime, char drCr,
			int brCode, int destBrCode, String atmTransType) {
		this.aquirerId = aquirerId;
		this.atmid = atmid;
		this.retrRefNo = retrRefNo;
		this.atmdate = atmdate;
		this.atmtime = atmtime;
		this.drCr = drCr;
		this.brCode = brCode;
		this.destBrCode = destBrCode;
		this.atmTransType = atmTransType;
	}

	@Column(name = "AquirerId", nullable = false, length = 11)
	public String getAquirerId() {
		return this.aquirerId;
	}

	public void setAquirerId(String aquirerId) {
		this.aquirerId = aquirerId;
	}

	@Column(name = "ATMID", nullable = false, length = 16)
	public String getAtmid() {
		return this.atmid;
	}

	public void setAtmid(String atmid) {
		this.atmid = atmid;
	}

	@Column(name = "RetrRefNo", nullable = false, length = 12)
	public String getRetrRefNo() {
		return this.retrRefNo;
	}

	public void setRetrRefNo(String retrRefNo) {
		this.retrRefNo = retrRefNo;
	}

	@Column(name = "ATMDate", nullable = false, length = 23)
	public Date getAtmdate() {
		return this.atmdate;
	}

	public void setAtmdate(Date atmdate) {
		this.atmdate = atmdate;
	}

	@Column(name = "ATMTime", nullable = false, length = 23)
	public Date getAtmtime() {
		return this.atmtime;
	}

	public void setAtmtime(Date atmtime) {
		this.atmtime = atmtime;
	}

	@Column(name = "DrCr", nullable = false, length = 1)
	public char getDrCr() {
		return this.drCr;
	}

	public void setDrCr(char drCr) {
		this.drCr = drCr;
	}

	@Column(name = "BrCode", nullable = false)
	public int getBrCode() {
		return this.brCode;
	}

	public void setBrCode(int brCode) {
		this.brCode = brCode;
	}

	@Column(name = "DestBrCode", nullable = false)
	public int getDestBrCode() {
		return this.destBrCode;
	}

	public void setDestBrCode(int destBrCode) {
		this.destBrCode = destBrCode;
	}

	@Column(name = "AtmTransType", nullable = false, length = 8)
	public String getAtmTransType() {
		return this.atmTransType;
	}

	public void setAtmTransType(String atmTransType) {
		this.atmTransType = atmTransType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D350066Id))
			return false;
		D350066Id castOther = (D350066Id) other;

		return ((this.getAquirerId() == castOther.getAquirerId()) || (this.getAquirerId() != null
				&& castOther.getAquirerId() != null && this.getAquirerId().equals(castOther.getAquirerId())))
				&& ((this.getAtmid() == castOther.getAtmid()) || (this.getAtmid() != null
						&& castOther.getAtmid() != null && this.getAtmid().equals(castOther.getAtmid())))
				&& ((this.getRetrRefNo() == castOther.getRetrRefNo()) || (this.getRetrRefNo() != null
						&& castOther.getRetrRefNo() != null && this.getRetrRefNo().equals(castOther.getRetrRefNo())))
				&& ((this.getAtmdate() == castOther.getAtmdate()) || (this.getAtmdate() != null
						&& castOther.getAtmdate() != null && this.getAtmdate().equals(castOther.getAtmdate())))
				&& ((this.getAtmtime() == castOther.getAtmtime()) || (this.getAtmtime() != null
						&& castOther.getAtmtime() != null && this.getAtmtime().equals(castOther.getAtmtime())))
				&& (this.getDrCr() == castOther.getDrCr()) && (this.getBrCode() == castOther.getBrCode())
				&& (this.getDestBrCode() == castOther.getDestBrCode())
				&& ((this.getAtmTransType() == castOther.getAtmTransType())
						|| (this.getAtmTransType() != null && castOther.getAtmTransType() != null
								&& this.getAtmTransType().equals(castOther.getAtmTransType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAquirerId() == null ? 0 : this.getAquirerId().hashCode());
		result = 37 * result + (getAtmid() == null ? 0 : this.getAtmid().hashCode());
		result = 37 * result + (getRetrRefNo() == null ? 0 : this.getRetrRefNo().hashCode());
		result = 37 * result + (getAtmdate() == null ? 0 : this.getAtmdate().hashCode());
		result = 37 * result + (getAtmtime() == null ? 0 : this.getAtmtime().hashCode());
		result = 37 * result + this.getDrCr();
		result = 37 * result + this.getBrCode();
		result = 37 * result + this.getDestBrCode();
		result = 37 * result + (getAtmTransType() == null ? 0 : this.getAtmTransType().hashCode());
		return result;
	}

}
