package com.sil.hbm;

// default package
// Generated Sep 8, 2016 12:22:49 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D350077 generated by hbm2java
 */
@Entity
@Table(name = "D350077")
@DynamicInsert
@DynamicUpdate
public class D350077 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7379415128997242532L;
	private D350077Id id;
	private Date createDate;
	private Date createTime;
	private char status;
	private String makerId;
	private String checkerId;
	private double fundTrfLimit;
	private double trnAmount;
	private Date lastTrnDate;

	public D350077() {
	}

	public D350077(D350077Id id, Date createDate, Date createTime, char status, String makerId, String checkerId,
			double fundTrfLimit, double trnAmount, Date lastTrnDate) {
		this.id = id;
		this.createDate = createDate;
		this.createTime = createTime;
		this.status = status;
		this.makerId = makerId;
		this.checkerId = checkerId;
		this.fundTrfLimit = fundTrfLimit;
		this.trnAmount = trnAmount;
		this.lastTrnDate = lastTrnDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false, length = 19)),
			@AttributeOverride(name = "brCode", column = @Column(name = "BrCode", nullable = false)),
			@AttributeOverride(name = "acctNo", column = @Column(name = "AcctNo", nullable = false, length = 32)) })
	public D350077Id getId() {
		return this.id;
	}

	public void setId(D350077Id id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "MakerId", nullable = false, length = 15)
	public String getMakerId() {
		return this.makerId;
	}

	public void setMakerId(String makerId) {
		this.makerId = makerId;
	}

	@Column(name = "CheckerId", nullable = false, length = 15)
	public String getCheckerId() {
		return this.checkerId;
	}

	public void setCheckerId(String checkerId) {
		this.checkerId = checkerId;
	}

	@Column(name = "FundTrfLimit", nullable = false, precision = 53, scale = 0)
	public double getFundTrfLimit() {
		return this.fundTrfLimit;
	}

	public void setFundTrfLimit(double fundTrfLimit) {
		this.fundTrfLimit = fundTrfLimit;
	}

	@Column(name = "TrnAmount", nullable = false, precision = 53, scale = 0)
	public double getTrnAmount() {
		return this.trnAmount;
	}

	public void setTrnAmount(double trnAmount) {
		this.trnAmount = trnAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastTrnDate", nullable = false, length = 23)
	public Date getLastTrnDate() {
		return this.lastTrnDate;
	}

	public void setLastTrnDate(Date lastTrnDate) {
		this.lastTrnDate = lastTrnDate;
	}

}
