package com.sil.hbm;
// Generated Apr 17, 2018 3:06:40 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D390077 generated by hbm2java
 */
@Entity
@Table(name = "D390077")
@DynamicInsert
@DynamicUpdate
public class D390077 implements java.io.Serializable {

	private static final long serialVersionUID = -6879371720489608698L;
	private D390077Id id;
	private int lbrCode;
	private String prdAcctId;
	private String firstname;
	private String middlename;
	private String lastname;
	private String emailaddress;
	private Date dateofbirth;
	private String mothermaidenname;
	private String gender;
	private String customerType;
	private String occupation;
	private String politicallyExposedPerson;
	private String annualIncome;
	private String city;
	private String state;
	private String rescountry;
	private String resaddress1;
	private String resaddress2;
	private String pincode;
	private String lcity;
	private String lstate;
	private String lcountry;
	private String laddress1;
	private String laddress2;
	private String lpincode;
	private String customerStatus;
	private String product;
	private String nationality;
	private int fatcadecl;
	private String sourceIncomeType;
	private String bcagent;
	private String kycflag;
	private String onboardflag;
	private String rblCustId;
	private String rblAccNo;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private int dailyTrnLimit;
	private int maxTrnAmt;
	private Date limitdate;

	public D390077() {
	}

	public D390077(D390077Id id, int lbrCode, String prdAcctId, String firstname, String middlename, String lastname,
			String emailaddress, Date dateofbirth, String mothermaidenname, String gender, String customerType,
			String occupation, String politicallyExposedPerson, String annualIncome, String city, String state,
			String rescountry, String resaddress1, String resaddress2, String pincode, String lcity, String lstate,
			String lcountry, String laddress1, String laddress2, String lpincode, String customerStatus, String product,
			String nationality, int fatcadecl, String sourceIncomeType, String bcagent, String kycflag,
			String onboardflag, String rblCustId, String rblAccNo, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo,
			int dailyTrnLimit, int maxTrnAmt, Date limitdate) {
		this.id = id;
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.emailaddress = emailaddress;
		this.dateofbirth = dateofbirth;
		this.mothermaidenname = mothermaidenname;
		this.gender = gender;
		this.customerType = customerType;
		this.occupation = occupation;
		this.politicallyExposedPerson = politicallyExposedPerson;
		this.annualIncome = annualIncome;
		this.city = city;
		this.state = state;
		this.rescountry = rescountry;
		this.resaddress1 = resaddress1;
		this.resaddress2 = resaddress2;
		this.pincode = pincode;
		this.lcity = lcity;
		this.lstate = lstate;
		this.lcountry = lcountry;
		this.laddress1 = laddress1;
		this.laddress2 = laddress2;
		this.lpincode = lpincode;
		this.customerStatus = customerStatus;
		this.product = product;
		this.nationality = nationality;
		this.fatcadecl = fatcadecl;
		this.sourceIncomeType = sourceIncomeType;
		this.bcagent = bcagent;
		this.kycflag = kycflag;
		this.onboardflag = onboardflag;
		this.rblCustId = rblCustId;
		this.rblAccNo = rblAccNo;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.dailyTrnLimit = dailyTrnLimit;
		this.maxTrnAmt = maxTrnAmt;
		this.limitdate = limitdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo", nullable = false, length = 20)),
			@AttributeOverride(name = "cardAlias", column = @Column(name = "CardAlias", nullable = false, length = 50)) })
	public D390077Id getId() {
		return this.id;
	}

	public void setId(D390077Id id) {
		this.id = id;
	}

	@Column(name = "LbrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "Firstname", nullable = false, length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "Middlename", nullable = false, length = 50)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "Lastname", nullable = false, length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "Emailaddress", nullable = false, length = 100)
	public String getEmailaddress() {
		return this.emailaddress;
	}

	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dateofbirth", nullable = false, length = 23)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "Mothermaidenname", nullable = false, length = 50)
	public String getMothermaidenname() {
		return this.mothermaidenname;
	}

	public void setMothermaidenname(String mothermaidenname) {
		this.mothermaidenname = mothermaidenname;
	}

	@Column(name = "Gender", nullable = false, length = 50)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "CustomerType", nullable = false, length = 20)
	public String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	@Column(name = "Occupation", nullable = false, length = 100)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "PoliticallyExposedPerson", nullable = false, length = 2)
	public String getPoliticallyExposedPerson() {
		return this.politicallyExposedPerson;
	}

	public void setPoliticallyExposedPerson(String politicallyExposedPerson) {
		this.politicallyExposedPerson = politicallyExposedPerson;
	}

	@Column(name = "AnnualIncome", nullable = false, length = 20)
	public String getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(String annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "City", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false, length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Rescountry", nullable = false, length = 100)
	public String getRescountry() {
		return this.rescountry;
	}

	public void setRescountry(String rescountry) {
		this.rescountry = rescountry;
	}

	@Column(name = "Resaddress1", nullable = false, length = 100)
	public String getResaddress1() {
		return this.resaddress1;
	}

	public void setResaddress1(String resaddress1) {
		this.resaddress1 = resaddress1;
	}

	@Column(name = "Resaddress2", nullable = false, length = 100)
	public String getResaddress2() {
		return this.resaddress2;
	}

	public void setResaddress2(String resaddress2) {
		this.resaddress2 = resaddress2;
	}

	@Column(name = "Pincode", nullable = false, length = 6)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "Lcity", nullable = false, length = 100)
	public String getLcity() {
		return this.lcity;
	}

	public void setLcity(String lcity) {
		this.lcity = lcity;
	}

	@Column(name = "Lstate", nullable = false, length = 100)
	public String getLstate() {
		return this.lstate;
	}

	public void setLstate(String lstate) {
		this.lstate = lstate;
	}

	@Column(name = "Lcountry", nullable = false, length = 100)
	public String getLcountry() {
		return this.lcountry;
	}

	public void setLcountry(String lcountry) {
		this.lcountry = lcountry;
	}

	@Column(name = "Laddress1", nullable = false, length = 100)
	public String getLaddress1() {
		return this.laddress1;
	}

	public void setLaddress1(String laddress1) {
		this.laddress1 = laddress1;
	}

	@Column(name = "Laddress2", nullable = false, length = 100)
	public String getLaddress2() {
		return this.laddress2;
	}

	public void setLaddress2(String laddress2) {
		this.laddress2 = laddress2;
	}

	@Column(name = "Lpincode", nullable = false, length = 6)
	public String getLpincode() {
		return this.lpincode;
	}

	public void setLpincode(String lpincode) {
		this.lpincode = lpincode;
	}

	@Column(name = "CustomerStatus", nullable = false, length = 20)
	public String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(String customerStatus) {
		this.customerStatus = customerStatus;
	}

	@Column(name = "Product", nullable = false, length = 50)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "Nationality", nullable = false, length = 50)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "Fatcadecl", nullable = false)
	public int getFatcadecl() {
		return this.fatcadecl;
	}

	public void setFatcadecl(int fatcadecl) {
		this.fatcadecl = fatcadecl;
	}

	@Column(name = "SourceIncomeType", nullable = false, length = 20)
	public String getSourceIncomeType() {
		return this.sourceIncomeType;
	}

	public void setSourceIncomeType(String sourceIncomeType) {
		this.sourceIncomeType = sourceIncomeType;
	}

	@Column(name = "Bcagent", nullable = false, length = 50)
	public String getBcagent() {
		return this.bcagent;
	}

	public void setBcagent(String bcagent) {
		this.bcagent = bcagent;
	}

	@Column(name = "KYCFLAG", nullable = false, length = 2)
	public String getKycflag() {
		return this.kycflag;
	}

	public void setKycflag(String kycflag) {
		this.kycflag = kycflag;
	}

	@Column(name = "ONBOARDFLAG", nullable = false, length = 2)
	public String getOnboardflag() {
		return this.onboardflag;
	}

	public void setOnboardflag(String onboardflag) {
		this.onboardflag = onboardflag;
	}

	@Column(name = "RBL_CUST_ID", nullable = false, length = 20)
	public String getRblCustId() {
		return this.rblCustId;
	}

	public void setRblCustId(String rblCustId) {
		this.rblCustId = rblCustId;
	}

	@Column(name = "RBL_ACC_NO", nullable = false, length = 20)
	public String getRblAccNo() {
		return this.rblAccNo;
	}

	public void setRblAccNo(String rblAccNo) {
		this.rblAccNo = rblAccNo;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "DAILY_TRN_LIMIT", nullable = false)
	public int getDailyTrnLimit() {
		return this.dailyTrnLimit;
	}

	public void setDailyTrnLimit(int dailyTrnLimit) {
		this.dailyTrnLimit = dailyTrnLimit;
	}

	@Column(name = "MAX_TRN_AMT", nullable = false)
	public int getMaxTrnAmt() {
		return this.maxTrnAmt;
	}

	public void setMaxTrnAmt(int maxTrnAmt) {
		this.maxTrnAmt = maxTrnAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LIMITDATE", nullable = false, length = 23)
	public Date getLimitdate() {
		return this.limitdate;
	}

	public void setLimitdate(Date limitdate) {
		this.limitdate = limitdate;
	}

}
