package com.sil.hbm;
// Generated Jan 14, 2017 1:00:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D390075 generated by hbm2java
 */
@Entity
@Table(name = "D390075" )
@DynamicInsert
@DynamicUpdate
public class D390075 implements java.io.Serializable {

	private static final long serialVersionUID = -9020929854191027042L;
	private D390075Id id;
	private Date appDt;
	private Date issueDt;
	private String cardNo;
	private String brPrdCd;
	private int brAccNo;
	private int brSubAccNo;
	private int brSubSubAccNo;
	private Date expiryDt;
	private double amtAuth;
	private double amtRemaining;
	private Date cycleBeginDt;
	private String embName;
	private byte status;
	private byte cardPeriod;
	private String add1;
	private String add2;
	private String add3;
	private String cityCd;
	private String countryCd;
	private int pinCd;
	private String tel1;
	private String tel2;
	private String email;
	private String mobileNo;
	private char gender;
	private char embosGenYn;
	private Date embosGenYndate;
	private int custNo;
	private byte cardStage;
	private byte schemeType;
	private char bkNwAccYn;
	private byte cardCat;
	private char crdType;
	private Date dateOfB;
	private Date cardUpldDt;
	private int brCode1;
	private String prdCd1;
	private int acNo1;
	private int brCode2;
	private String prdCd2;
	private int acNo2;
	private int brCode3;
	private String prdCd3;
	private int acNo3;
	private int brCode4;
	private String prdCd4;
	private int acNo4;
	private int brCode5;
	private String prdCd5;
	private int acNo5;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;

	public D390075() {
	}

	public D390075(D390075Id id, Date appDt, Date issueDt, String cardNo, String brPrdCd, int brAccNo, int brSubAccNo,
			int brSubSubAccNo, Date expiryDt, double amtAuth, double amtRemaining, Date cycleBeginDt, String embName,
			byte status, byte cardPeriod, String add1, String add2, String add3, String cityCd, String countryCd,
			int pinCd, String tel1, String tel2, String email, String mobileNo, char gender, char embosGenYn,
			Date embosGenYndate, int custNo, byte cardStage, byte schemeType, char bkNwAccYn, byte cardCat,
			char crdType, Date dateOfB, Date cardUpldDt, int brCode1, String prdCd1, int acNo1, int brCode2,
			String prdCd2, int acNo2, int brCode3, String prdCd3, int acNo3, int brCode4, String prdCd4, int acNo4,
			int brCode5, String prdCd5, int acNo5, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt,
			int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk,
			int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat,
			byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.id = id;
		this.appDt = appDt;
		this.issueDt = issueDt;
		this.cardNo = cardNo;
		this.brPrdCd = brPrdCd;
		this.brAccNo = brAccNo;
		this.brSubAccNo = brSubAccNo;
		this.brSubSubAccNo = brSubSubAccNo;
		this.expiryDt = expiryDt;
		this.amtAuth = amtAuth;
		this.amtRemaining = amtRemaining;
		this.cycleBeginDt = cycleBeginDt;
		this.embName = embName;
		this.status = status;
		this.cardPeriod = cardPeriod;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.cityCd = cityCd;
		this.countryCd = countryCd;
		this.pinCd = pinCd;
		this.tel1 = tel1;
		this.tel2 = tel2;
		this.email = email;
		this.mobileNo = mobileNo;
		this.gender = gender;
		this.embosGenYn = embosGenYn;
		this.embosGenYndate = embosGenYndate;
		this.custNo = custNo;
		this.cardStage = cardStage;
		this.schemeType = schemeType;
		this.bkNwAccYn = bkNwAccYn;
		this.cardCat = cardCat;
		this.crdType = crdType;
		this.dateOfB = dateOfB;
		this.cardUpldDt = cardUpldDt;
		this.brCode1 = brCode1;
		this.prdCd1 = prdCd1;
		this.acNo1 = acNo1;
		this.brCode2 = brCode2;
		this.prdCd2 = prdCd2;
		this.acNo2 = acNo2;
		this.brCode3 = brCode3;
		this.prdCd3 = prdCd3;
		this.acNo3 = acNo3;
		this.brCode4 = brCode4;
		this.prdCd4 = prdCd4;
		this.acNo4 = acNo4;
		this.brCode5 = brCode5;
		this.prdCd5 = prdCd5;
		this.acNo5 = acNo5;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "brcode", column = @Column(name = "Brcode", nullable = false)),
			@AttributeOverride(name = "appNo", column = @Column(name = "AppNo", nullable = false)) })
	public D390075Id getId() {
		return this.id;
	}

	public void setId(D390075Id id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AppDt", nullable = false, length = 23)
	public Date getAppDt() {
		return this.appDt;
	}

	public void setAppDt(Date appDt) {
		this.appDt = appDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IssueDt", nullable = false, length = 23)
	public Date getIssueDt() {
		return this.issueDt;
	}

	public void setIssueDt(Date issueDt) {
		this.issueDt = issueDt;
	}

	@Column(name = "CardNo", nullable = false, length = 16)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "BrPrdCd", nullable = false, length = 8)
	public String getBrPrdCd() {
		return this.brPrdCd;
	}

	public void setBrPrdCd(String brPrdCd) {
		this.brPrdCd = brPrdCd;
	}

	@Column(name = "BrAccNo", nullable = false)
	public int getBrAccNo() {
		return this.brAccNo;
	}

	public void setBrAccNo(int brAccNo) {
		this.brAccNo = brAccNo;
	}

	@Column(name = "BrSubAccNo", nullable = false)
	public int getBrSubAccNo() {
		return this.brSubAccNo;
	}

	public void setBrSubAccNo(int brSubAccNo) {
		this.brSubAccNo = brSubAccNo;
	}

	@Column(name = "BrSubSubAccNo", nullable = false)
	public int getBrSubSubAccNo() {
		return this.brSubSubAccNo;
	}

	public void setBrSubSubAccNo(int brSubSubAccNo) {
		this.brSubSubAccNo = brSubSubAccNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpiryDt", nullable = false, length = 23)
	public Date getExpiryDt() {
		return this.expiryDt;
	}

	public void setExpiryDt(Date expiryDt) {
		this.expiryDt = expiryDt;
	}

	@Column(name = "AmtAuth", nullable = false, precision = 53, scale = 0)
	public double getAmtAuth() {
		return this.amtAuth;
	}

	public void setAmtAuth(double amtAuth) {
		this.amtAuth = amtAuth;
	}

	@Column(name = "AmtRemaining", nullable = false, precision = 53, scale = 0)
	public double getAmtRemaining() {
		return this.amtRemaining;
	}

	public void setAmtRemaining(double amtRemaining) {
		this.amtRemaining = amtRemaining;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CycleBeginDt", nullable = false, length = 23)
	public Date getCycleBeginDt() {
		return this.cycleBeginDt;
	}

	public void setCycleBeginDt(Date cycleBeginDt) {
		this.cycleBeginDt = cycleBeginDt;
	}

	@Column(name = "EmbName", nullable = false, length = 25)
	public String getEmbName() {
		return this.embName;
	}

	public void setEmbName(String embName) {
		this.embName = embName;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "CardPeriod", nullable = false)
	public byte getCardPeriod() {
		return this.cardPeriod;
	}

	public void setCardPeriod(byte cardPeriod) {
		this.cardPeriod = cardPeriod;
	}

	@Column(name = "Add1", nullable = false, length = 35)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "Add2", nullable = false, length = 35)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "Add3", nullable = false, length = 35)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "CityCd", nullable = false, length = 3)
	public String getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(String cityCd) {
		this.cityCd = cityCd;
	}

	@Column(name = "CountryCd", nullable = false, length = 3)
	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	@Column(name = "PinCd", nullable = false)
	public int getPinCd() {
		return this.pinCd;
	}

	public void setPinCd(int pinCd) {
		this.pinCd = pinCd;
	}

	@Column(name = "Tel1", nullable = false, length = 20)
	public String getTel1() {
		return this.tel1;
	}

	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	@Column(name = "Tel2", nullable = false, length = 20)
	public String getTel2() {
		return this.tel2;
	}

	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MobileNo", nullable = false, length = 20)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "Gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Column(name = "EmbosGenYN", nullable = false, length = 1)
	public char getEmbosGenYn() {
		return this.embosGenYn;
	}

	public void setEmbosGenYn(char embosGenYn) {
		this.embosGenYn = embosGenYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EmbosGenYNDate", nullable = false, length = 23)
	public Date getEmbosGenYndate() {
		return this.embosGenYndate;
	}

	public void setEmbosGenYndate(Date embosGenYndate) {
		this.embosGenYndate = embosGenYndate;
	}

	@Column(name = "CustNo", nullable = false)
	public int getCustNo() {
		return this.custNo;
	}

	public void setCustNo(int custNo) {
		this.custNo = custNo;
	}

	@Column(name = "CardStage", nullable = false)
	public byte getCardStage() {
		return this.cardStage;
	}

	public void setCardStage(byte cardStage) {
		this.cardStage = cardStage;
	}

	@Column(name = "SchemeType", nullable = false)
	public byte getSchemeType() {
		return this.schemeType;
	}

	public void setSchemeType(byte schemeType) {
		this.schemeType = schemeType;
	}

	@Column(name = "BkNwAccYN", nullable = false, length = 1)
	public char getBkNwAccYn() {
		return this.bkNwAccYn;
	}

	public void setBkNwAccYn(char bkNwAccYn) {
		this.bkNwAccYn = bkNwAccYn;
	}

	@Column(name = "CardCat", nullable = false)
	public byte getCardCat() {
		return this.cardCat;
	}

	public void setCardCat(byte cardCat) {
		this.cardCat = cardCat;
	}

	@Column(name = "CrdType", nullable = false, length = 1)
	public char getCrdType() {
		return this.crdType;
	}

	public void setCrdType(char crdType) {
		this.crdType = crdType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateOfB", nullable = false, length = 23)
	public Date getDateOfB() {
		return this.dateOfB;
	}

	public void setDateOfB(Date dateOfB) {
		this.dateOfB = dateOfB;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CardUpldDt", nullable = false, length = 23)
	public Date getCardUpldDt() {
		return this.cardUpldDt;
	}

	public void setCardUpldDt(Date cardUpldDt) {
		this.cardUpldDt = cardUpldDt;
	}

	@Column(name = "BrCode1", nullable = false)
	public int getBrCode1() {
		return this.brCode1;
	}

	public void setBrCode1(int brCode1) {
		this.brCode1 = brCode1;
	}

	@Column(name = "PrdCd1", nullable = false, length = 8)
	public String getPrdCd1() {
		return this.prdCd1;
	}

	public void setPrdCd1(String prdCd1) {
		this.prdCd1 = prdCd1;
	}

	@Column(name = "AcNo1", nullable = false)
	public int getAcNo1() {
		return this.acNo1;
	}

	public void setAcNo1(int acNo1) {
		this.acNo1 = acNo1;
	}

	@Column(name = "BrCode2", nullable = false)
	public int getBrCode2() {
		return this.brCode2;
	}

	public void setBrCode2(int brCode2) {
		this.brCode2 = brCode2;
	}

	@Column(name = "PrdCd2", nullable = false, length = 8)
	public String getPrdCd2() {
		return this.prdCd2;
	}

	public void setPrdCd2(String prdCd2) {
		this.prdCd2 = prdCd2;
	}

	@Column(name = "AcNo2", nullable = false)
	public int getAcNo2() {
		return this.acNo2;
	}

	public void setAcNo2(int acNo2) {
		this.acNo2 = acNo2;
	}

	@Column(name = "BrCode3", nullable = false)
	public int getBrCode3() {
		return this.brCode3;
	}

	public void setBrCode3(int brCode3) {
		this.brCode3 = brCode3;
	}

	@Column(name = "PrdCd3", nullable = false, length = 8)
	public String getPrdCd3() {
		return this.prdCd3;
	}

	public void setPrdCd3(String prdCd3) {
		this.prdCd3 = prdCd3;
	}

	@Column(name = "AcNo3", nullable = false)
	public int getAcNo3() {
		return this.acNo3;
	}

	public void setAcNo3(int acNo3) {
		this.acNo3 = acNo3;
	}

	@Column(name = "BrCode4", nullable = false)
	public int getBrCode4() {
		return this.brCode4;
	}

	public void setBrCode4(int brCode4) {
		this.brCode4 = brCode4;
	}

	@Column(name = "PrdCd4", nullable = false, length = 8)
	public String getPrdCd4() {
		return this.prdCd4;
	}

	public void setPrdCd4(String prdCd4) {
		this.prdCd4 = prdCd4;
	}

	@Column(name = "AcNo4", nullable = false)
	public int getAcNo4() {
		return this.acNo4;
	}

	public void setAcNo4(int acNo4) {
		this.acNo4 = acNo4;
	}

	@Column(name = "BrCode5", nullable = false)
	public int getBrCode5() {
		return this.brCode5;
	}

	public void setBrCode5(int brCode5) {
		this.brCode5 = brCode5;
	}

	@Column(name = "PrdCd5", nullable = false, length = 8)
	public String getPrdCd5() {
		return this.prdCd5;
	}

	public void setPrdCd5(String prdCd5) {
		this.prdCd5 = prdCd5;
	}

	@Column(name = "AcNo5", nullable = false)
	public int getAcNo5() {
		return this.acNo5;
	}

	public void setAcNo5(int acNo5) {
		this.acNo5 = acNo5;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

}
