package com.sil.hbm;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D390061 generated by hbm2java
 */
@Entity
@Table(name = "D390061")
@DynamicInsert
@DynamicUpdate
public class D390061 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6113086453118850903L;
	private D390061Id id;
	private int lbrCode;
	private String prdAcctId;
	private String cardHolder;
	private double standingLmt;
	private double standingBal;
	private Date standTranDate;
	private String filler;
	private short dbtrBijIdx;
	private short dbtrUaeIdx;

	public D390061() {
	}

	public D390061(D390061Id id, int lbrCode, String prdAcctId, String cardHolder, double standingLmt,
			double standingBal, Date standTranDate, String filler, short dbtrBijIdx, short dbtrUaeIdx) {
		this.id = id;
		this.lbrCode = lbrCode;
		this.prdAcctId = prdAcctId;
		this.cardHolder = cardHolder;
		this.standingLmt = standingLmt;
		this.standingBal = standingBal;
		this.standTranDate = standTranDate;
		this.filler = filler;
		this.dbtrBijIdx = dbtrBijIdx;
		this.dbtrUaeIdx = dbtrUaeIdx;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cardId", column = @Column(name = "CardId", nullable = false, length = 30)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SrNo", nullable = false)) })
	public D390061Id getId() {
		return this.id;
	}

	public void setId(D390061Id id) {
		this.id = id;
	}

	@Column(name = "LBrCode", nullable = false)
	public int getLbrCode() {
		return this.lbrCode;
	}

	public void setLbrCode(int lbrCode) {
		this.lbrCode = lbrCode;
	}

	@Column(name = "PrdAcctId", nullable = false, length = 32)
	public String getPrdAcctId() {
		return this.prdAcctId;
	}

	public void setPrdAcctId(String prdAcctId) {
		this.prdAcctId = prdAcctId;
	}

	@Column(name = "CardHolder", nullable = false, length = 50)
	public String getCardHolder() {
		return this.cardHolder;
	}

	public void setCardHolder(String cardHolder) {
		this.cardHolder = cardHolder;
	}

	@Column(name = "StandingLmt", nullable = false, precision = 53, scale = 0)
	public double getStandingLmt() {
		return this.standingLmt;
	}

	public void setStandingLmt(double standingLmt) {
		this.standingLmt = standingLmt;
	}

	@Column(name = "StandingBal", nullable = false, precision = 53, scale = 0)
	public double getStandingBal() {
		return this.standingBal;
	}

	public void setStandingBal(double standingBal) {
		this.standingBal = standingBal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StandTranDate", nullable = false, length = 23)
	public Date getStandTranDate() {
		return this.standTranDate;
	}

	public void setStandTranDate(Date standTranDate) {
		this.standTranDate = standTranDate;
	}

	@Column(name = "Filler", nullable = false, length = 50)
	public String getFiller() {
		return this.filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}

	@Column(name = "DbtrBijIdx", nullable = false)
	public short getDbtrBijIdx() {
		return this.dbtrBijIdx;
	}

	public void setDbtrBijIdx(short dbtrBijIdx) {
		this.dbtrBijIdx = dbtrBijIdx;
	}

	@Column(name = "DbtrUaeIdx", nullable = false)
	public short getDbtrUaeIdx() {
		return this.dbtrUaeIdx;
	}

	public void setDbtrUaeIdx(short dbtrUaeIdx) {
		this.dbtrUaeIdx = dbtrUaeIdx;
	}

}
