package com.sil.hbm;
// Generated Jan 14, 2017 1:00:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * D390075Id generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class D390075Id implements java.io.Serializable {

	private int brcode;
	private int appNo;

	public D390075Id() {
	}

	public D390075Id(int brcode, int appNo) {
		this.brcode = brcode;
		this.appNo = appNo;
	}

	@Column(name = "Brcode", nullable = false)
	public int getBrcode() {
		return this.brcode;
	}

	public void setBrcode(int brcode) {
		this.brcode = brcode;
	}

	@Column(name = "AppNo", nullable = false)
	public int getAppNo() {
		return this.appNo;
	}

	public void setAppNo(int appNo) {
		this.appNo = appNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof D390075Id))
			return false;
		D390075Id castOther = (D390075Id) other;

		return (this.getBrcode() == castOther.getBrcode()) && (this.getAppNo() == castOther.getAppNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBrcode();
		result = 37 * result + this.getAppNo();
		return result;
	}

}
