package com.sil.hbm;
// Generated Jan 2, 2017 7:32:52 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D500028 generated by hbm2java
 */
@Entity
@Table(name = "D500028")
@DynamicInsert
@DynamicUpdate
public class D500028 implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7919769383297319565L;
	private String placeCd;
	private String placeCdDesc;
	private String stateCd;
	private String cntryCd;
	private char indforeign;
	private int fplDbtrAddMk;
	private int fplDbtrAddMb;
	private short fplDbtrAddMs;
	private Date fplDbtrAddMd;
	private Date fplDbtrAddMt;
	private int fplDbtrAddCk;
	private int fplDbtrAddCb;
	private short fplDbtrAddCs;
	private Date fplDbtrAddCd;
	private Date fplDbtrAddCt;
	private int fplDbtrLupdMk;
	private int fplDbtrLupdMb;
	private short fplDbtrLupdMs;
	private Date fplDbtrLupdMd;
	private Date fplDbtrLupdMt;
	private int fplDbtrLupdCk;
	private int fplDbtrLupdCb;
	private short fplDbtrLupdCs;
	private Date fplDbtrLupdCd;
	private Date fplDbtrLupdCt;
	private short fplDbtrTauthDone;
	private byte fplDbtrRecStat;
	private byte fplDbtrAuthDone;
	private byte fplDbtrAuthNeeded;
	private short fplDbtrUpdtChkId;
	private int fplDbtrLhisTrnNo;

	public D500028() {
	}

	public D500028(String placeCd, String placeCdDesc, String stateCd, String cntryCd, char indforeign,
			int fplDbtrAddMk, int fplDbtrAddMb, short fplDbtrAddMs, Date fplDbtrAddMd, Date fplDbtrAddMt,
			int fplDbtrAddCk, int fplDbtrAddCb, short fplDbtrAddCs, Date fplDbtrAddCd, Date fplDbtrAddCt,
			int fplDbtrLupdMk, int fplDbtrLupdMb, short fplDbtrLupdMs, Date fplDbtrLupdMd, Date fplDbtrLupdMt,
			int fplDbtrLupdCk, int fplDbtrLupdCb, short fplDbtrLupdCs, Date fplDbtrLupdCd, Date fplDbtrLupdCt,
			short fplDbtrTauthDone, byte fplDbtrRecStat, byte fplDbtrAuthDone, byte fplDbtrAuthNeeded,
			short fplDbtrUpdtChkId, int fplDbtrLhisTrnNo) {
		this.placeCd = placeCd;
		this.placeCdDesc = placeCdDesc;
		this.stateCd = stateCd;
		this.cntryCd = cntryCd;
		this.indforeign = indforeign;
		this.fplDbtrAddMk = fplDbtrAddMk;
		this.fplDbtrAddMb = fplDbtrAddMb;
		this.fplDbtrAddMs = fplDbtrAddMs;
		this.fplDbtrAddMd = fplDbtrAddMd;
		this.fplDbtrAddMt = fplDbtrAddMt;
		this.fplDbtrAddCk = fplDbtrAddCk;
		this.fplDbtrAddCb = fplDbtrAddCb;
		this.fplDbtrAddCs = fplDbtrAddCs;
		this.fplDbtrAddCd = fplDbtrAddCd;
		this.fplDbtrAddCt = fplDbtrAddCt;
		this.fplDbtrLupdMk = fplDbtrLupdMk;
		this.fplDbtrLupdMb = fplDbtrLupdMb;
		this.fplDbtrLupdMs = fplDbtrLupdMs;
		this.fplDbtrLupdMd = fplDbtrLupdMd;
		this.fplDbtrLupdMt = fplDbtrLupdMt;
		this.fplDbtrLupdCk = fplDbtrLupdCk;
		this.fplDbtrLupdCb = fplDbtrLupdCb;
		this.fplDbtrLupdCs = fplDbtrLupdCs;
		this.fplDbtrLupdCd = fplDbtrLupdCd;
		this.fplDbtrLupdCt = fplDbtrLupdCt;
		this.fplDbtrTauthDone = fplDbtrTauthDone;
		this.fplDbtrRecStat = fplDbtrRecStat;
		this.fplDbtrAuthDone = fplDbtrAuthDone;
		this.fplDbtrAuthNeeded = fplDbtrAuthNeeded;
		this.fplDbtrUpdtChkId = fplDbtrUpdtChkId;
		this.fplDbtrLhisTrnNo = fplDbtrLhisTrnNo;
	}

	@Id

	@Column(name = "PlaceCd", unique = true, nullable = false, length = 3)
	public String getPlaceCd() {
		return this.placeCd;
	}

	public void setPlaceCd(String placeCd) {
		this.placeCd = placeCd;
	}

	@Column(name = "PlaceCdDesc", nullable = false, length = 35)
	public String getPlaceCdDesc() {
		return this.placeCdDesc;
	}

	public void setPlaceCdDesc(String placeCdDesc) {
		this.placeCdDesc = placeCdDesc;
	}

	@Column(name = "StateCd", nullable = false, length = 3)
	public String getStateCd() {
		return this.stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	@Column(name = "CntryCd", nullable = false, length = 2)
	public String getCntryCd() {
		return this.cntryCd;
	}

	public void setCntryCd(String cntryCd) {
		this.cntryCd = cntryCd;
	}

	@Column(name = "Indforeign", nullable = false, length = 1)
	public char getIndforeign() {
		return this.indforeign;
	}

	public void setIndforeign(char indforeign) {
		this.indforeign = indforeign;
	}

	@Column(name = "FplDbtrAddMk", nullable = false)
	public int getFplDbtrAddMk() {
		return this.fplDbtrAddMk;
	}

	public void setFplDbtrAddMk(int fplDbtrAddMk) {
		this.fplDbtrAddMk = fplDbtrAddMk;
	}

	@Column(name = "FplDbtrAddMb", nullable = false)
	public int getFplDbtrAddMb() {
		return this.fplDbtrAddMb;
	}

	public void setFplDbtrAddMb(int fplDbtrAddMb) {
		this.fplDbtrAddMb = fplDbtrAddMb;
	}

	@Column(name = "FplDbtrAddMs", nullable = false)
	public short getFplDbtrAddMs() {
		return this.fplDbtrAddMs;
	}

	public void setFplDbtrAddMs(short fplDbtrAddMs) {
		this.fplDbtrAddMs = fplDbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrAddMd", nullable = false, length = 23)
	public Date getFplDbtrAddMd() {
		return this.fplDbtrAddMd;
	}

	public void setFplDbtrAddMd(Date fplDbtrAddMd) {
		this.fplDbtrAddMd = fplDbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrAddMt", nullable = false, length = 23)
	public Date getFplDbtrAddMt() {
		return this.fplDbtrAddMt;
	}

	public void setFplDbtrAddMt(Date fplDbtrAddMt) {
		this.fplDbtrAddMt = fplDbtrAddMt;
	}

	@Column(name = "FplDbtrAddCk", nullable = false)
	public int getFplDbtrAddCk() {
		return this.fplDbtrAddCk;
	}

	public void setFplDbtrAddCk(int fplDbtrAddCk) {
		this.fplDbtrAddCk = fplDbtrAddCk;
	}

	@Column(name = "FplDbtrAddCb", nullable = false)
	public int getFplDbtrAddCb() {
		return this.fplDbtrAddCb;
	}

	public void setFplDbtrAddCb(int fplDbtrAddCb) {
		this.fplDbtrAddCb = fplDbtrAddCb;
	}

	@Column(name = "FplDbtrAddCs", nullable = false)
	public short getFplDbtrAddCs() {
		return this.fplDbtrAddCs;
	}

	public void setFplDbtrAddCs(short fplDbtrAddCs) {
		this.fplDbtrAddCs = fplDbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrAddCd", nullable = false, length = 23)
	public Date getFplDbtrAddCd() {
		return this.fplDbtrAddCd;
	}

	public void setFplDbtrAddCd(Date fplDbtrAddCd) {
		this.fplDbtrAddCd = fplDbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrAddCt", nullable = false, length = 23)
	public Date getFplDbtrAddCt() {
		return this.fplDbtrAddCt;
	}

	public void setFplDbtrAddCt(Date fplDbtrAddCt) {
		this.fplDbtrAddCt = fplDbtrAddCt;
	}

	@Column(name = "FplDbtrLupdMk", nullable = false)
	public int getFplDbtrLupdMk() {
		return this.fplDbtrLupdMk;
	}

	public void setFplDbtrLupdMk(int fplDbtrLupdMk) {
		this.fplDbtrLupdMk = fplDbtrLupdMk;
	}

	@Column(name = "FplDbtrLupdMb", nullable = false)
	public int getFplDbtrLupdMb() {
		return this.fplDbtrLupdMb;
	}

	public void setFplDbtrLupdMb(int fplDbtrLupdMb) {
		this.fplDbtrLupdMb = fplDbtrLupdMb;
	}

	@Column(name = "FplDbtrLupdMs", nullable = false)
	public short getFplDbtrLupdMs() {
		return this.fplDbtrLupdMs;
	}

	public void setFplDbtrLupdMs(short fplDbtrLupdMs) {
		this.fplDbtrLupdMs = fplDbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrLupdMd", nullable = false, length = 23)
	public Date getFplDbtrLupdMd() {
		return this.fplDbtrLupdMd;
	}

	public void setFplDbtrLupdMd(Date fplDbtrLupdMd) {
		this.fplDbtrLupdMd = fplDbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrLupdMt", nullable = false, length = 23)
	public Date getFplDbtrLupdMt() {
		return this.fplDbtrLupdMt;
	}

	public void setFplDbtrLupdMt(Date fplDbtrLupdMt) {
		this.fplDbtrLupdMt = fplDbtrLupdMt;
	}

	@Column(name = "FplDbtrLupdCk", nullable = false)
	public int getFplDbtrLupdCk() {
		return this.fplDbtrLupdCk;
	}

	public void setFplDbtrLupdCk(int fplDbtrLupdCk) {
		this.fplDbtrLupdCk = fplDbtrLupdCk;
	}

	@Column(name = "FplDbtrLupdCb", nullable = false)
	public int getFplDbtrLupdCb() {
		return this.fplDbtrLupdCb;
	}

	public void setFplDbtrLupdCb(int fplDbtrLupdCb) {
		this.fplDbtrLupdCb = fplDbtrLupdCb;
	}

	@Column(name = "FplDbtrLupdCs", nullable = false)
	public short getFplDbtrLupdCs() {
		return this.fplDbtrLupdCs;
	}

	public void setFplDbtrLupdCs(short fplDbtrLupdCs) {
		this.fplDbtrLupdCs = fplDbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrLupdCd", nullable = false, length = 23)
	public Date getFplDbtrLupdCd() {
		return this.fplDbtrLupdCd;
	}

	public void setFplDbtrLupdCd(Date fplDbtrLupdCd) {
		this.fplDbtrLupdCd = fplDbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FplDbtrLupdCt", nullable = false, length = 23)
	public Date getFplDbtrLupdCt() {
		return this.fplDbtrLupdCt;
	}

	public void setFplDbtrLupdCt(Date fplDbtrLupdCt) {
		this.fplDbtrLupdCt = fplDbtrLupdCt;
	}

	@Column(name = "FplDbtrTAuthDone", nullable = false)
	public short getFplDbtrTauthDone() {
		return this.fplDbtrTauthDone;
	}

	public void setFplDbtrTauthDone(short fplDbtrTauthDone) {
		this.fplDbtrTauthDone = fplDbtrTauthDone;
	}

	@Column(name = "FplDbtrRecStat", nullable = false)
	public byte getFplDbtrRecStat() {
		return this.fplDbtrRecStat;
	}

	public void setFplDbtrRecStat(byte fplDbtrRecStat) {
		this.fplDbtrRecStat = fplDbtrRecStat;
	}

	@Column(name = "FplDbtrAuthDone", nullable = false)
	public byte getFplDbtrAuthDone() {
		return this.fplDbtrAuthDone;
	}

	public void setFplDbtrAuthDone(byte fplDbtrAuthDone) {
		this.fplDbtrAuthDone = fplDbtrAuthDone;
	}

	@Column(name = "FplDbtrAuthNeeded", nullable = false)
	public byte getFplDbtrAuthNeeded() {
		return this.fplDbtrAuthNeeded;
	}

	public void setFplDbtrAuthNeeded(byte fplDbtrAuthNeeded) {
		this.fplDbtrAuthNeeded = fplDbtrAuthNeeded;
	}

	@Column(name = "FplDbtrUpdtChkId", nullable = false)
	public short getFplDbtrUpdtChkId() {
		return this.fplDbtrUpdtChkId;
	}

	public void setFplDbtrUpdtChkId(short fplDbtrUpdtChkId) {
		this.fplDbtrUpdtChkId = fplDbtrUpdtChkId;
	}

	@Column(name = "FplDbtrLHisTrnNo", nullable = false)
	public int getFplDbtrLhisTrnNo() {
		return this.fplDbtrLhisTrnNo;
	}

	public void setFplDbtrLhisTrnNo(int fplDbtrLhisTrnNo) {
		this.fplDbtrLhisTrnNo = fplDbtrLhisTrnNo;
	}

	@Override
	public String toString() {
		return "D500028 [placeCd=" + placeCd + ", placeCdDesc=" + placeCdDesc + ", stateCd=" + stateCd + ", cntryCd="
				+ cntryCd + ", indforeign=" + indforeign + ", fplDbtrAddMk=" + fplDbtrAddMk + ", fplDbtrAddMb="
				+ fplDbtrAddMb + ", fplDbtrAddMs=" + fplDbtrAddMs + ", fplDbtrAddMd=" + fplDbtrAddMd + ", fplDbtrAddMt="
				+ fplDbtrAddMt + ", fplDbtrAddCk=" + fplDbtrAddCk + ", fplDbtrAddCb=" + fplDbtrAddCb + ", fplDbtrAddCs="
				+ fplDbtrAddCs + ", fplDbtrAddCd=" + fplDbtrAddCd + ", fplDbtrAddCt=" + fplDbtrAddCt
				+ ", fplDbtrLupdMk=" + fplDbtrLupdMk + ", fplDbtrLupdMb=" + fplDbtrLupdMb + ", fplDbtrLupdMs="
				+ fplDbtrLupdMs + ", fplDbtrLupdMd=" + fplDbtrLupdMd + ", fplDbtrLupdMt=" + fplDbtrLupdMt
				+ ", fplDbtrLupdCk=" + fplDbtrLupdCk + ", fplDbtrLupdCb=" + fplDbtrLupdCb + ", fplDbtrLupdCs="
				+ fplDbtrLupdCs + ", fplDbtrLupdCd=" + fplDbtrLupdCd + ", fplDbtrLupdCt=" + fplDbtrLupdCt
				+ ", fplDbtrTauthDone=" + fplDbtrTauthDone + ", fplDbtrRecStat=" + fplDbtrRecStat + ", fplDbtrAuthDone="
				+ fplDbtrAuthDone + ", fplDbtrAuthNeeded=" + fplDbtrAuthNeeded + ", fplDbtrUpdtChkId="
				+ fplDbtrUpdtChkId + ", fplDbtrLhisTrnNo=" + fplDbtrLhisTrnNo + "]";
	}

}
