package com.sil.hbm;
// Generated Jan 2, 2017 7:39:08 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D500027 generated by hbm2java
 */
@Entity
@Table(name = "D500027")
@DynamicInsert
@DynamicUpdate
public class D500027 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7207342916838307360L;
	private String cntryCd;
	private String countryName;
	private String countryName1;
	private char cntryType;
	private char zone;
	private char gracePrdYn;
	private short gracePrd;
	private char ecgcCoverYn;
	private char grading;
	private char restrictedYn;
	private int fcnDbtrAddMk;
	private int fcnDbtrAddMb;
	private short fcnDbtrAddMs;
	private Date fcnDbtrAddMd;
	private Date fcnDbtrAddMt;
	private int fcnDbtrAddCk;
	private int fcnDbtrAddCb;
	private short fcnDbtrAddCs;
	private Date fcnDbtrAddCd;
	private Date fcnDbtrAddCt;
	private int fcnDbtrLupdMk;
	private int fcnDbtrLupdMb;
	private short fcnDbtrLupdMs;
	private Date fcnDbtrLupdMd;
	private Date fcnDbtrLupdMt;
	private int fcnDbtrLupdCk;
	private int fcnDbtrLupdCb;
	private short fcnDbtrLupdCs;
	private Date fcnDbtrLupdCd;
	private Date fcnDbtrLupdCt;
	private short fcnDbtrTauthDone;
	private byte fcnDbtrRecStat;
	private byte fcnDbtrAuthDone;
	private byte fcnDbtrAuthNeeded;
	private short fcnDbtrUpdtChkId;
	private int fcnDbtrLhisTrnNo;

	public D500027() {
	}

	public D500027(String cntryCd, String countryName, String countryName1, char cntryType, char zone, char gracePrdYn,
			short gracePrd, char ecgcCoverYn, char grading, char restrictedYn, int fcnDbtrAddMk, int fcnDbtrAddMb,
			short fcnDbtrAddMs, Date fcnDbtrAddMd, Date fcnDbtrAddMt, int fcnDbtrAddCk, int fcnDbtrAddCb,
			short fcnDbtrAddCs, Date fcnDbtrAddCd, Date fcnDbtrAddCt, int fcnDbtrLupdMk, int fcnDbtrLupdMb,
			short fcnDbtrLupdMs, Date fcnDbtrLupdMd, Date fcnDbtrLupdMt, int fcnDbtrLupdCk, int fcnDbtrLupdCb,
			short fcnDbtrLupdCs, Date fcnDbtrLupdCd, Date fcnDbtrLupdCt, short fcnDbtrTauthDone, byte fcnDbtrRecStat,
			byte fcnDbtrAuthDone, byte fcnDbtrAuthNeeded, short fcnDbtrUpdtChkId, int fcnDbtrLhisTrnNo) {
		this.cntryCd = cntryCd;
		this.countryName = countryName;
		this.countryName1 = countryName1;
		this.cntryType = cntryType;
		this.zone = zone;
		this.gracePrdYn = gracePrdYn;
		this.gracePrd = gracePrd;
		this.ecgcCoverYn = ecgcCoverYn;
		this.grading = grading;
		this.restrictedYn = restrictedYn;
		this.fcnDbtrAddMk = fcnDbtrAddMk;
		this.fcnDbtrAddMb = fcnDbtrAddMb;
		this.fcnDbtrAddMs = fcnDbtrAddMs;
		this.fcnDbtrAddMd = fcnDbtrAddMd;
		this.fcnDbtrAddMt = fcnDbtrAddMt;
		this.fcnDbtrAddCk = fcnDbtrAddCk;
		this.fcnDbtrAddCb = fcnDbtrAddCb;
		this.fcnDbtrAddCs = fcnDbtrAddCs;
		this.fcnDbtrAddCd = fcnDbtrAddCd;
		this.fcnDbtrAddCt = fcnDbtrAddCt;
		this.fcnDbtrLupdMk = fcnDbtrLupdMk;
		this.fcnDbtrLupdMb = fcnDbtrLupdMb;
		this.fcnDbtrLupdMs = fcnDbtrLupdMs;
		this.fcnDbtrLupdMd = fcnDbtrLupdMd;
		this.fcnDbtrLupdMt = fcnDbtrLupdMt;
		this.fcnDbtrLupdCk = fcnDbtrLupdCk;
		this.fcnDbtrLupdCb = fcnDbtrLupdCb;
		this.fcnDbtrLupdCs = fcnDbtrLupdCs;
		this.fcnDbtrLupdCd = fcnDbtrLupdCd;
		this.fcnDbtrLupdCt = fcnDbtrLupdCt;
		this.fcnDbtrTauthDone = fcnDbtrTauthDone;
		this.fcnDbtrRecStat = fcnDbtrRecStat;
		this.fcnDbtrAuthDone = fcnDbtrAuthDone;
		this.fcnDbtrAuthNeeded = fcnDbtrAuthNeeded;
		this.fcnDbtrUpdtChkId = fcnDbtrUpdtChkId;
		this.fcnDbtrLhisTrnNo = fcnDbtrLhisTrnNo;
	}

	@Id

	@Column(name = "CntryCd", unique = true, nullable = false, length = 2)
	public String getCntryCd() {
		return this.cntryCd;
	}

	public void setCntryCd(String cntryCd) {
		this.cntryCd = cntryCd;
	}

	@Column(name = "CountryName", nullable = false, length = 35)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "CountryName1", nullable = false, length = 35)
	public String getCountryName1() {
		return this.countryName1;
	}

	public void setCountryName1(String countryName1) {
		this.countryName1 = countryName1;
	}

	@Column(name = "CntryType", nullable = false, length = 1)
	public char getCntryType() {
		return this.cntryType;
	}

	public void setCntryType(char cntryType) {
		this.cntryType = cntryType;
	}

	@Column(name = "Zone", nullable = false, length = 1)
	public char getZone() {
		return this.zone;
	}

	public void setZone(char zone) {
		this.zone = zone;
	}

	@Column(name = "GracePrdYN", nullable = false, length = 1)
	public char getGracePrdYn() {
		return this.gracePrdYn;
	}

	public void setGracePrdYn(char gracePrdYn) {
		this.gracePrdYn = gracePrdYn;
	}

	@Column(name = "GracePrd", nullable = false)
	public short getGracePrd() {
		return this.gracePrd;
	}

	public void setGracePrd(short gracePrd) {
		this.gracePrd = gracePrd;
	}

	@Column(name = "EcgcCoverYN", nullable = false, length = 1)
	public char getEcgcCoverYn() {
		return this.ecgcCoverYn;
	}

	public void setEcgcCoverYn(char ecgcCoverYn) {
		this.ecgcCoverYn = ecgcCoverYn;
	}

	@Column(name = "Grading", nullable = false, length = 1)
	public char getGrading() {
		return this.grading;
	}

	public void setGrading(char grading) {
		this.grading = grading;
	}

	@Column(name = "RestrictedYN", nullable = false, length = 1)
	public char getRestrictedYn() {
		return this.restrictedYn;
	}

	public void setRestrictedYn(char restrictedYn) {
		this.restrictedYn = restrictedYn;
	}

	@Column(name = "FcnDbtrAddMk", nullable = false)
	public int getFcnDbtrAddMk() {
		return this.fcnDbtrAddMk;
	}

	public void setFcnDbtrAddMk(int fcnDbtrAddMk) {
		this.fcnDbtrAddMk = fcnDbtrAddMk;
	}

	@Column(name = "FcnDbtrAddMb", nullable = false)
	public int getFcnDbtrAddMb() {
		return this.fcnDbtrAddMb;
	}

	public void setFcnDbtrAddMb(int fcnDbtrAddMb) {
		this.fcnDbtrAddMb = fcnDbtrAddMb;
	}

	@Column(name = "FcnDbtrAddMs", nullable = false)
	public short getFcnDbtrAddMs() {
		return this.fcnDbtrAddMs;
	}

	public void setFcnDbtrAddMs(short fcnDbtrAddMs) {
		this.fcnDbtrAddMs = fcnDbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrAddMd", nullable = false, length = 23)
	public Date getFcnDbtrAddMd() {
		return this.fcnDbtrAddMd;
	}

	public void setFcnDbtrAddMd(Date fcnDbtrAddMd) {
		this.fcnDbtrAddMd = fcnDbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrAddMt", nullable = false, length = 23)
	public Date getFcnDbtrAddMt() {
		return this.fcnDbtrAddMt;
	}

	public void setFcnDbtrAddMt(Date fcnDbtrAddMt) {
		this.fcnDbtrAddMt = fcnDbtrAddMt;
	}

	@Column(name = "FcnDbtrAddCk", nullable = false)
	public int getFcnDbtrAddCk() {
		return this.fcnDbtrAddCk;
	}

	public void setFcnDbtrAddCk(int fcnDbtrAddCk) {
		this.fcnDbtrAddCk = fcnDbtrAddCk;
	}

	@Column(name = "FcnDbtrAddCb", nullable = false)
	public int getFcnDbtrAddCb() {
		return this.fcnDbtrAddCb;
	}

	public void setFcnDbtrAddCb(int fcnDbtrAddCb) {
		this.fcnDbtrAddCb = fcnDbtrAddCb;
	}

	@Column(name = "FcnDbtrAddCs", nullable = false)
	public short getFcnDbtrAddCs() {
		return this.fcnDbtrAddCs;
	}

	public void setFcnDbtrAddCs(short fcnDbtrAddCs) {
		this.fcnDbtrAddCs = fcnDbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrAddCd", nullable = false, length = 23)
	public Date getFcnDbtrAddCd() {
		return this.fcnDbtrAddCd;
	}

	public void setFcnDbtrAddCd(Date fcnDbtrAddCd) {
		this.fcnDbtrAddCd = fcnDbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrAddCt", nullable = false, length = 23)
	public Date getFcnDbtrAddCt() {
		return this.fcnDbtrAddCt;
	}

	public void setFcnDbtrAddCt(Date fcnDbtrAddCt) {
		this.fcnDbtrAddCt = fcnDbtrAddCt;
	}

	@Column(name = "FcnDbtrLupdMk", nullable = false)
	public int getFcnDbtrLupdMk() {
		return this.fcnDbtrLupdMk;
	}

	public void setFcnDbtrLupdMk(int fcnDbtrLupdMk) {
		this.fcnDbtrLupdMk = fcnDbtrLupdMk;
	}

	@Column(name = "FcnDbtrLupdMb", nullable = false)
	public int getFcnDbtrLupdMb() {
		return this.fcnDbtrLupdMb;
	}

	public void setFcnDbtrLupdMb(int fcnDbtrLupdMb) {
		this.fcnDbtrLupdMb = fcnDbtrLupdMb;
	}

	@Column(name = "FcnDbtrLupdMs", nullable = false)
	public short getFcnDbtrLupdMs() {
		return this.fcnDbtrLupdMs;
	}

	public void setFcnDbtrLupdMs(short fcnDbtrLupdMs) {
		this.fcnDbtrLupdMs = fcnDbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrLupdMd", nullable = false, length = 23)
	public Date getFcnDbtrLupdMd() {
		return this.fcnDbtrLupdMd;
	}

	public void setFcnDbtrLupdMd(Date fcnDbtrLupdMd) {
		this.fcnDbtrLupdMd = fcnDbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrLupdMt", nullable = false, length = 23)
	public Date getFcnDbtrLupdMt() {
		return this.fcnDbtrLupdMt;
	}

	public void setFcnDbtrLupdMt(Date fcnDbtrLupdMt) {
		this.fcnDbtrLupdMt = fcnDbtrLupdMt;
	}

	@Column(name = "FcnDbtrLupdCk", nullable = false)
	public int getFcnDbtrLupdCk() {
		return this.fcnDbtrLupdCk;
	}

	public void setFcnDbtrLupdCk(int fcnDbtrLupdCk) {
		this.fcnDbtrLupdCk = fcnDbtrLupdCk;
	}

	@Column(name = "FcnDbtrLupdCb", nullable = false)
	public int getFcnDbtrLupdCb() {
		return this.fcnDbtrLupdCb;
	}

	public void setFcnDbtrLupdCb(int fcnDbtrLupdCb) {
		this.fcnDbtrLupdCb = fcnDbtrLupdCb;
	}

	@Column(name = "FcnDbtrLupdCs", nullable = false)
	public short getFcnDbtrLupdCs() {
		return this.fcnDbtrLupdCs;
	}

	public void setFcnDbtrLupdCs(short fcnDbtrLupdCs) {
		this.fcnDbtrLupdCs = fcnDbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrLupdCd", nullable = false, length = 23)
	public Date getFcnDbtrLupdCd() {
		return this.fcnDbtrLupdCd;
	}

	public void setFcnDbtrLupdCd(Date fcnDbtrLupdCd) {
		this.fcnDbtrLupdCd = fcnDbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FcnDbtrLupdCt", nullable = false, length = 23)
	public Date getFcnDbtrLupdCt() {
		return this.fcnDbtrLupdCt;
	}

	public void setFcnDbtrLupdCt(Date fcnDbtrLupdCt) {
		this.fcnDbtrLupdCt = fcnDbtrLupdCt;
	}

	@Column(name = "FcnDbtrTAuthDone", nullable = false)
	public short getFcnDbtrTauthDone() {
		return this.fcnDbtrTauthDone;
	}

	public void setFcnDbtrTauthDone(short fcnDbtrTauthDone) {
		this.fcnDbtrTauthDone = fcnDbtrTauthDone;
	}

	@Column(name = "FcnDbtrRecStat", nullable = false)
	public byte getFcnDbtrRecStat() {
		return this.fcnDbtrRecStat;
	}

	public void setFcnDbtrRecStat(byte fcnDbtrRecStat) {
		this.fcnDbtrRecStat = fcnDbtrRecStat;
	}

	@Column(name = "FcnDbtrAuthDone", nullable = false)
	public byte getFcnDbtrAuthDone() {
		return this.fcnDbtrAuthDone;
	}

	public void setFcnDbtrAuthDone(byte fcnDbtrAuthDone) {
		this.fcnDbtrAuthDone = fcnDbtrAuthDone;
	}

	@Column(name = "FcnDbtrAuthNeeded", nullable = false)
	public byte getFcnDbtrAuthNeeded() {
		return this.fcnDbtrAuthNeeded;
	}

	public void setFcnDbtrAuthNeeded(byte fcnDbtrAuthNeeded) {
		this.fcnDbtrAuthNeeded = fcnDbtrAuthNeeded;
	}

	@Column(name = "FcnDbtrUpdtChkId", nullable = false)
	public short getFcnDbtrUpdtChkId() {
		return this.fcnDbtrUpdtChkId;
	}

	public void setFcnDbtrUpdtChkId(short fcnDbtrUpdtChkId) {
		this.fcnDbtrUpdtChkId = fcnDbtrUpdtChkId;
	}

	@Column(name = "FcnDbtrLHisTrnNo", nullable = false)
	public int getFcnDbtrLhisTrnNo() {
		return this.fcnDbtrLhisTrnNo;
	}

	public void setFcnDbtrLhisTrnNo(int fcnDbtrLhisTrnNo) {
		this.fcnDbtrLhisTrnNo = fcnDbtrLhisTrnNo;
	}

	@Override
	public String toString() {
		return "D500027 [cntryCd=" + cntryCd + ", countryName=" + countryName + ", countryName1=" + countryName1
				+ ", cntryType=" + cntryType + ", zone=" + zone + ", gracePrdYn=" + gracePrdYn + ", gracePrd="
				+ gracePrd + ", ecgcCoverYn=" + ecgcCoverYn + ", grading=" + grading + ", restrictedYn=" + restrictedYn
				+ ", fcnDbtrAddMk=" + fcnDbtrAddMk + ", fcnDbtrAddMb=" + fcnDbtrAddMb + ", fcnDbtrAddMs=" + fcnDbtrAddMs
				+ ", fcnDbtrAddMd=" + fcnDbtrAddMd + ", fcnDbtrAddMt=" + fcnDbtrAddMt + ", fcnDbtrAddCk=" + fcnDbtrAddCk
				+ ", fcnDbtrAddCb=" + fcnDbtrAddCb + ", fcnDbtrAddCs=" + fcnDbtrAddCs + ", fcnDbtrAddCd=" + fcnDbtrAddCd
				+ ", fcnDbtrAddCt=" + fcnDbtrAddCt + ", fcnDbtrLupdMk=" + fcnDbtrLupdMk + ", fcnDbtrLupdMb="
				+ fcnDbtrLupdMb + ", fcnDbtrLupdMs=" + fcnDbtrLupdMs + ", fcnDbtrLupdMd=" + fcnDbtrLupdMd
				+ ", fcnDbtrLupdMt=" + fcnDbtrLupdMt + ", fcnDbtrLupdCk=" + fcnDbtrLupdCk + ", fcnDbtrLupdCb="
				+ fcnDbtrLupdCb + ", fcnDbtrLupdCs=" + fcnDbtrLupdCs + ", fcnDbtrLupdCd=" + fcnDbtrLupdCd
				+ ", fcnDbtrLupdCt=" + fcnDbtrLupdCt + ", fcnDbtrTauthDone=" + fcnDbtrTauthDone + ", fcnDbtrRecStat="
				+ fcnDbtrRecStat + ", fcnDbtrAuthDone=" + fcnDbtrAuthDone + ", fcnDbtrAuthNeeded=" + fcnDbtrAuthNeeded
				+ ", fcnDbtrUpdtChkId=" + fcnDbtrUpdtChkId + ", fcnDbtrLhisTrnNo=" + fcnDbtrLhisTrnNo + "]";
	}

}
