package com.sil.hbm;
// Generated Mar 7, 2017 1:37:54 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * D946120 generated by hbm2java
 */
@Entity
@Table(name = "D946120")
@DynamicInsert
@DynamicUpdate
public class D946120 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6746264966672170589L;
	private D946120Id id;
	private String fldNo;
	private byte catType;
	private String fld1;
	private String fld2;
	private String fld3;
	private String fld4;
	private String fld5;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private Integer benifbankcd;
	private String benifmobileno;
	private String nepalbenifacno;
	private String benifbankname;
	private Double sbichrgsamt;
	private Double indonepalamt;

	private Double sbitotalamt = new Double(0);

	public D946120() {
	}

	public D946120(D946120Id id, String fldNo, byte catType, String fld1, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs,
			Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd,
			Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt,
			int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone,
			byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo) {
		this.id = id;
		this.fldNo = fldNo;
		this.catType = catType;
		this.fld1 = fld1;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	public D946120(D946120Id id, String fldNo, byte catType, String fld1, String fld2, String fld3, String fld4,
			String fld5, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk,
			int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb,
			short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs,
			Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone,
			byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo, Integer benifbankcd, String benifmobileno,
			String nepalbenifacno, String benifbankname, Double sbichrgsamt, Double indonepalamt) {
		this.id = id;
		this.fldNo = fldNo;
		this.catType = catType;
		this.fld1 = fld1;
		this.fld2 = fld2;
		this.fld3 = fld3;
		this.fld4 = fld4;
		this.fld5 = fld5;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.benifbankcd = benifbankcd;
		this.benifmobileno = benifmobileno;
		this.nepalbenifacno = nepalbenifacno;
		this.benifbankname = benifbankname;
		this.sbichrgsamt = sbichrgsamt;
		this.indonepalamt = indonepalamt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "obrCode", column = @Column(name = "OBrCode", nullable = false)),
			@AttributeOverride(name = "iwOwMsg", column = @Column(name = "IwOwMsg", nullable = false, length = 1)),
			@AttributeOverride(name = "msgStype", column = @Column(name = "MsgSType", nullable = false, length = 3)),
			@AttributeOverride(name = "msgDate", column = @Column(name = "MsgDate", nullable = false, length = 23)),
			@AttributeOverride(name = "refNo", column = @Column(name = "RefNo", nullable = false, length = 16)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SrNo", nullable = false)) })
	public D946120Id getId() {
		return this.id;
	}

	public void setId(D946120Id id) {
		this.id = id;
	}

	@Column(name = "FldNo", nullable = false, length = 4)
	public String getFldNo() {
		return this.fldNo;
	}

	public void setFldNo(String fldNo) {
		this.fldNo = fldNo;
	}

	@Column(name = "CatType", nullable = false)
	public byte getCatType() {
		return this.catType;
	}

	public void setCatType(byte catType) {
		this.catType = catType;
	}

	@Column(name = "Fld1", nullable = false, length = 34)
	public String getFld1() {
		return this.fld1;
	}

	public void setFld1(String fld1) {
		this.fld1 = fld1;
	}

	@Column(name = "Fld2", length = 140)
	public String getFld2() {
		return this.fld2;
	}

	public void setFld2(String fld2) {
		this.fld2 = fld2;
	}

	@Column(name = "Fld3", length = 140)
	public String getFld3() {
		return this.fld3;
	}

	public void setFld3(String fld3) {
		this.fld3 = fld3;
	}

	@Column(name = "Fld4", length = 140)
	public String getFld4() {
		return this.fld4;
	}

	public void setFld4(String fld4) {
		this.fld4 = fld4;
	}

	@Column(name = "Fld5", length = 140)
	public String getFld5() {
		return this.fld5;
	}

	public void setFld5(String fld5) {
		this.fld5 = fld5;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "BENIFBANKCD")
	public Integer getBenifbankcd() {
		return this.benifbankcd;
	}

	public void setBenifbankcd(Integer benifbankcd) {
		this.benifbankcd = benifbankcd;
	}

	@Column(name = "BENIFMOBILENO", length = 20)
	public String getBenifmobileno() {
		return this.benifmobileno;
	}

	public void setBenifmobileno(String benifmobileno) {
		this.benifmobileno = benifmobileno;
	}

	@Column(name = "NEPALBENIFACNO", length = 34)
	public String getNepalbenifacno() {
		return this.nepalbenifacno;
	}

	public void setNepalbenifacno(String nepalbenifacno) {
		this.nepalbenifacno = nepalbenifacno;
	}

	@Column(name = "BENIFBANKNAME", length = 140)
	public String getBenifbankname() {
		return this.benifbankname;
	}

	public void setBenifbankname(String benifbankname) {
		this.benifbankname = benifbankname;
	}

	@Column(name = "SBICHRGSAMT", precision = 53, scale = 0)
	public Double getSbichrgsamt() {
		return this.sbichrgsamt;
	}

	public void setSbichrgsamt(Double sbichrgsamt) {
		this.sbichrgsamt = sbichrgsamt;
	}

	@Column(name = "INDONEPALAMT", precision = 53, scale = 0)
	public Double getIndonepalamt() {
		return this.indonepalamt;
	}

	public void setIndonepalamt(Double indonepalamt) {
		this.indonepalamt = indonepalamt;
	}

	@Transient
	public Double getSbitotalamt() {
		return sbitotalamt;
	}

	public void setSbitotalamt(Double sbitotalamt) {
		this.sbitotalamt = sbitotalamt;
	}

	@Override
	public String toString() {
		return "D946120 [id=" + id + ", fldNo=" + fldNo + ", catType=" + catType + ", fld1=" + fld1 + ", fld2=" + fld2
				+ ", fld3=" + fld3 + ", fld4=" + fld4 + ", fld5=" + fld5 + ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb="
				+ dbtrAddMb + ", dbtrAddMs=" + dbtrAddMs + ", dbtrAddMd=" + dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt
				+ ", dbtrAddCk=" + dbtrAddCk + ", dbtrAddCb=" + dbtrAddCb + ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd="
				+ dbtrAddCd + ", dbtrAddCt=" + dbtrAddCt + ", dbtrLupdMk=" + dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb
				+ ", dbtrLupdMs=" + dbtrLupdMs + ", dbtrLupdMd=" + dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt
				+ ", dbtrLupdCk=" + dbtrLupdCk + ", dbtrLupdCb=" + dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs
				+ ", dbtrLupdCd=" + dbtrLupdCd + ", dbtrLupdCt=" + dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone
				+ ", dbtrRecStat=" + dbtrRecStat + ", dbtrAuthDone=" + dbtrAuthDone + ", dbtrAuthNeeded="
				+ dbtrAuthNeeded + ", dbtrUpdtChkId=" + dbtrUpdtChkId + ", dbtrLhisTrnNo=" + dbtrLhisTrnNo
				+ ", benifbankcd=" + benifbankcd + ", benifmobileno=" + benifmobileno + ", nepalbenifacno="
				+ nepalbenifacno + ", benifbankname=" + benifbankname + ", sbichrgsamt=" + sbichrgsamt
				+ ", indonepalamt=" + indonepalamt + ", sbitotalamt=" + sbitotalamt + "]";
	}

	
}
