package com.sil.hbm;
// Generated Mar 20, 2017 5:19:22 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
//import java.beans.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.sil.commonswitch.GrpCdWiseValidationResult;
import com.sil.commonswitch.ValidationResult;
import com.sil.commonswitch.Voucher;
import com.sil.domain.RtgsMsgFieldRows;

/**
 * D946020 generated by hbm2java
 */
@Entity
@Table(name = "D946020")
@DynamicInsert
@DynamicUpdate
public class D946020 implements java.io.Serializable {
	private static final long serialVersionUID = -5625902306932982304L;
	
	private List<RtgsMsgFieldRows> rowsList = new ArrayList<RtgsMsgFieldRows>();
	
	private GrpCdWiseValidationResult grpCdWiseValidationResult=new GrpCdWiseValidationResult();
	
	private ValidationResult validationResult=new ValidationResult();
	private D946020Id id;
	private String rrefNo;
	private String utrno;
	private int utrseqNo;
	private String ordIfsccd;
	private String benIfsccd;
	private Date valueDate;
	private String currCd;
	private double amount;
	private byte msgStat;
	private byte msgPriority;
	private String ordAcctId;
	private String ordDesc1;
	private String ordDesc2;
	private String ordDesc3;
	private String ordDesc4;
	private String benFldNo;
	private String benDesc1;
	private String benDesc2;
	private String benDesc3;
	private String benDesc4;
	private String benDesc5;
	private String chrgType;
	private char ackIdentifier;
	private String reasonCd;
	private int reconNo;
	private byte reqAuthNos;
	private byte preAuthNos;
	private int dbtrAddMk;
	private int dbtrAddMb;
	private short dbtrAddMs;
	private Date dbtrAddMd;
	private Date dbtrAddMt;
	private int dbtrAddCk;
	private int dbtrAddCb;
	private short dbtrAddCs;
	private Date dbtrAddCd;
	private Date dbtrAddCt;
	private int dbtrLupdMk;
	private int dbtrLupdMb;
	private short dbtrLupdMs;
	private Date dbtrLupdMd;
	private Date dbtrLupdMt;
	private int dbtrLupdCk;
	private int dbtrLupdCb;
	private short dbtrLupdCs;
	private Date dbtrLupdCd;
	private Date dbtrLupdCt;
	private short dbtrTauthDone;
	private byte dbtrRecStat;
	private byte dbtrAuthDone;
	private byte dbtrAuthNeeded;
	private short dbtrUpdtChkId;
	private int dbtrLhisTrnNo;
	private byte msgTrfType;
	private byte rtnRsnCode;
	private byte insType;
	private String insNo;
	private double chrgsAmt;
	private byte mobEmlType;
	private String mobileEmail;
	private byte transCdRtgs;
	private String orgRefNo;
	private String nutrno;
	private String transId;
	private Date interfaceTime;
	private Date interfaceDate;
	private String msgId;
	private Date omsgTime;
	private Date omsgDate;
	private String rmsgType;
	private String rreasondesc;
	private String onutrno;

	
	
	
	
	
	
	
	
	public D946020() {
	}

	public D946020(D946020Id id, String rrefNo, int utrseqNo, String ordIfsccd, String benIfsccd, Date valueDate,
			String currCd, double amount, byte msgStat, byte msgPriority, String ordAcctId, String ordDesc1,
			String ordDesc2, String ordDesc3, String ordDesc4, String benFldNo, String benDesc1, String benDesc2,
			String benDesc3, String benDesc4, String benDesc5, String chrgType, char ackIdentifier, int reconNo,
			byte reqAuthNos, byte preAuthNos, int dbtrAddMk, int dbtrAddMb, short dbtrAddMs, Date dbtrAddMd,
			Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs, Date dbtrAddCd, Date dbtrAddCt,
			int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd, Date dbtrLupdMt, int dbtrLupdCk,
			int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt, short dbtrTauthDone, byte dbtrRecStat,
			byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId, int dbtrLhisTrnNo, byte msgTrfType,
			byte rtnRsnCode, byte insType, String insNo, double chrgsAmt, byte mobEmlType, String mobileEmail,
			byte transCdRtgs, String orgRefNo, String nutrno, String transId, Date interfaceTime, Date interfaceDate,
			String msgId, Date omsgTime, Date omsgDate, String rmsgType, String rreasondesc, String onutrno) {
		this.id = id;
		this.rrefNo = rrefNo;
		this.utrseqNo = utrseqNo;
		this.ordIfsccd = ordIfsccd;
		this.benIfsccd = benIfsccd;
		this.valueDate = valueDate;
		this.currCd = currCd;
		this.amount = amount;
		this.msgStat = msgStat;
		this.msgPriority = msgPriority;
		this.ordAcctId = ordAcctId;
		this.ordDesc1 = ordDesc1;
		this.ordDesc2 = ordDesc2;
		this.ordDesc3 = ordDesc3;
		this.ordDesc4 = ordDesc4;
		this.benFldNo = benFldNo;
		this.benDesc1 = benDesc1;
		this.benDesc2 = benDesc2;
		this.benDesc3 = benDesc3;
		this.benDesc4 = benDesc4;
		this.benDesc5 = benDesc5;
		this.chrgType = chrgType;
		this.ackIdentifier = ackIdentifier;
		this.reconNo = reconNo;
		this.reqAuthNos = reqAuthNos;
		this.preAuthNos = preAuthNos;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.msgTrfType = msgTrfType;
		this.rtnRsnCode = rtnRsnCode;
		this.insType = insType;
		this.insNo = insNo;
		this.chrgsAmt = chrgsAmt;
		this.mobEmlType = mobEmlType;
		this.mobileEmail = mobileEmail;
		this.transCdRtgs = transCdRtgs;
		this.orgRefNo = orgRefNo;
		this.nutrno = nutrno;
		this.transId = transId;
		this.interfaceTime = interfaceTime;
		this.interfaceDate = interfaceDate;
		this.msgId = msgId;
		this.omsgTime = omsgTime;
		this.omsgDate = omsgDate;
		this.rmsgType = rmsgType;
		this.rreasondesc = rreasondesc;
		this.onutrno = onutrno;
	}

	public D946020(D946020Id id, String rrefNo, String utrno, int utrseqNo, String ordIfsccd, String benIfsccd,
			Date valueDate, String currCd, double amount, byte msgStat, byte msgPriority, String ordAcctId,
			String ordDesc1, String ordDesc2, String ordDesc3, String ordDesc4, String benFldNo, String benDesc1,
			String benDesc2, String benDesc3, String benDesc4, String benDesc5, String chrgType, char ackIdentifier,
			String reasonCd, int reconNo, byte reqAuthNos, byte preAuthNos, int dbtrAddMk, int dbtrAddMb,
			short dbtrAddMs, Date dbtrAddMd, Date dbtrAddMt, int dbtrAddCk, int dbtrAddCb, short dbtrAddCs,
			Date dbtrAddCd, Date dbtrAddCt, int dbtrLupdMk, int dbtrLupdMb, short dbtrLupdMs, Date dbtrLupdMd,
			Date dbtrLupdMt, int dbtrLupdCk, int dbtrLupdCb, short dbtrLupdCs, Date dbtrLupdCd, Date dbtrLupdCt,
			short dbtrTauthDone, byte dbtrRecStat, byte dbtrAuthDone, byte dbtrAuthNeeded, short dbtrUpdtChkId,
			int dbtrLhisTrnNo, byte msgTrfType, byte rtnRsnCode, byte insType, String insNo, double chrgsAmt,
			byte mobEmlType, String mobileEmail, byte transCdRtgs, String orgRefNo, String nutrno, String transId,
			Date interfaceTime, Date interfaceDate, String msgId, Date omsgTime, Date omsgDate, String rmsgType,
			String rreasondesc, String onutrno) {
		this.id = id;
		this.rrefNo = rrefNo;
		this.utrno = utrno;
		this.utrseqNo = utrseqNo;
		this.ordIfsccd = ordIfsccd;
		this.benIfsccd = benIfsccd;
		this.valueDate = valueDate;
		this.currCd = currCd;
		this.amount = amount;
		this.msgStat = msgStat;
		this.msgPriority = msgPriority;
		this.ordAcctId = ordAcctId;
		this.ordDesc1 = ordDesc1;
		this.ordDesc2 = ordDesc2;
		this.ordDesc3 = ordDesc3;
		this.ordDesc4 = ordDesc4;
		this.benFldNo = benFldNo;
		this.benDesc1 = benDesc1;
		this.benDesc2 = benDesc2;
		this.benDesc3 = benDesc3;
		this.benDesc4 = benDesc4;
		this.benDesc5 = benDesc5;
		this.chrgType = chrgType;
		this.ackIdentifier = ackIdentifier;
		this.reasonCd = reasonCd;
		this.reconNo = reconNo;
		this.reqAuthNos = reqAuthNos;
		this.preAuthNos = preAuthNos;
		this.dbtrAddMk = dbtrAddMk;
		this.dbtrAddMb = dbtrAddMb;
		this.dbtrAddMs = dbtrAddMs;
		this.dbtrAddMd = dbtrAddMd;
		this.dbtrAddMt = dbtrAddMt;
		this.dbtrAddCk = dbtrAddCk;
		this.dbtrAddCb = dbtrAddCb;
		this.dbtrAddCs = dbtrAddCs;
		this.dbtrAddCd = dbtrAddCd;
		this.dbtrAddCt = dbtrAddCt;
		this.dbtrLupdMk = dbtrLupdMk;
		this.dbtrLupdMb = dbtrLupdMb;
		this.dbtrLupdMs = dbtrLupdMs;
		this.dbtrLupdMd = dbtrLupdMd;
		this.dbtrLupdMt = dbtrLupdMt;
		this.dbtrLupdCk = dbtrLupdCk;
		this.dbtrLupdCb = dbtrLupdCb;
		this.dbtrLupdCs = dbtrLupdCs;
		this.dbtrLupdCd = dbtrLupdCd;
		this.dbtrLupdCt = dbtrLupdCt;
		this.dbtrTauthDone = dbtrTauthDone;
		this.dbtrRecStat = dbtrRecStat;
		this.dbtrAuthDone = dbtrAuthDone;
		this.dbtrAuthNeeded = dbtrAuthNeeded;
		this.dbtrUpdtChkId = dbtrUpdtChkId;
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
		this.msgTrfType = msgTrfType;
		this.rtnRsnCode = rtnRsnCode;
		this.insType = insType;
		this.insNo = insNo;
		this.chrgsAmt = chrgsAmt;
		this.mobEmlType = mobEmlType;
		this.mobileEmail = mobileEmail;
		this.transCdRtgs = transCdRtgs;
		this.orgRefNo = orgRefNo;
		this.nutrno = nutrno;
		this.transId = transId;
		this.interfaceTime = interfaceTime;
		this.interfaceDate = interfaceDate;
		this.msgId = msgId;
		this.omsgTime = omsgTime;
		this.omsgDate = omsgDate;
		this.rmsgType = rmsgType;
		this.rreasondesc = rreasondesc;
		this.onutrno = onutrno;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "obrCode", column = @Column(name = "OBrCode", nullable = false)),
			@AttributeOverride(name = "iwOwMsg", column = @Column(name = "IwOwMsg", nullable = false, length = 1)),
			@AttributeOverride(name = "msgStype", column = @Column(name = "MsgSType", nullable = false, length = 3)),
			@AttributeOverride(name = "msgDate", column = @Column(name = "MsgDate", nullable = false, length = 23)),
			@AttributeOverride(name = "refNo", column = @Column(name = "RefNo", nullable = false, length = 16)) })
	public D946020Id getId() {
		return this.id;
	}

	public void setId(D946020Id id) {
		this.id = id;
	}

	@Column(name = "RRefNo", nullable = false, length = 16)
	public String getRrefNo() {
		return this.rrefNo;
	}

	public void setRrefNo(String rrefNo) {
		this.rrefNo = rrefNo;
	}

	@Column(name = "UTRNo", length = 35)
	public String getUtrno() {
		return this.utrno;
	}

	public void setUtrno(String utrno) {
		this.utrno = utrno;
	}

	@Column(name = "UTRSeqNo", nullable = false)
	public int getUtrseqNo() {
		return this.utrseqNo;
	}

	public void setUtrseqNo(int utrseqNo) {
		this.utrseqNo = utrseqNo;
	}

	@Column(name = "OrdIFSCCd", nullable = false, length = 11)
	public String getOrdIfsccd() {
		return this.ordIfsccd;
	}

	public void setOrdIfsccd(String ordIfsccd) {
		this.ordIfsccd = ordIfsccd;
	}

	@Column(name = "BenIFSCCd", nullable = false, length = 11)
	public String getBenIfsccd() {
		return this.benIfsccd;
	}

	public void setBenIfsccd(String benIfsccd) {
		this.benIfsccd = benIfsccd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValueDate", nullable = false, length = 23)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	@Column(name = "CurrCd", nullable = false, length = 3)
	public String getCurrCd() {
		return this.currCd;
	}

	public void setCurrCd(String currCd) {
		this.currCd = currCd;
	}

	@Column(name = "Amount", nullable = false, precision = 53, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "MsgStat", nullable = false)
	public byte getMsgStat() {
		return this.msgStat;
	}

	public void setMsgStat(byte msgStat) {
		this.msgStat = msgStat;
	}

	@Column(name = "MsgPriority", nullable = false)
	public byte getMsgPriority() {
		return this.msgPriority;
	}

	public void setMsgPriority(byte msgPriority) {
		this.msgPriority = msgPriority;
	}

	@Column(name = "OrdAcctId", nullable = false, length = 32)
	public String getOrdAcctId() {
		return this.ordAcctId;
	}

	public void setOrdAcctId(String ordAcctId) {
		this.ordAcctId = ordAcctId;
	}

	@Column(name = "OrdDesc1", nullable = false, length = 34)
	public String getOrdDesc1() {
		return this.ordDesc1;
	}

	public void setOrdDesc1(String ordDesc1) {
		this.ordDesc1 = ordDesc1;
	}

	@Column(name = "OrdDesc2", nullable = false, length = 34)
	public String getOrdDesc2() {
		return this.ordDesc2;
	}

	public void setOrdDesc2(String ordDesc2) {
		this.ordDesc2 = ordDesc2;
	}

	@Column(name = "OrdDesc3", nullable = false, length = 34)
	public String getOrdDesc3() {
		return this.ordDesc3;
	}

	public void setOrdDesc3(String ordDesc3) {
		this.ordDesc3 = ordDesc3;
	}

	@Column(name = "OrdDesc4", nullable = false, length = 34)
	public String getOrdDesc4() {
		return this.ordDesc4;
	}

	public void setOrdDesc4(String ordDesc4) {
		this.ordDesc4 = ordDesc4;
	}

	@Column(name = "BenFldNo", nullable = false, length = 4)
	public String getBenFldNo() {
		return this.benFldNo;
	}

	public void setBenFldNo(String benFldNo) {
		this.benFldNo = benFldNo;
	}

	@Column(name = "BenDesc1", nullable = false, length = 34)
	public String getBenDesc1() {
		return this.benDesc1;
	}

	public void setBenDesc1(String benDesc1) {
		this.benDesc1 = benDesc1;
	}

	@Column(name = "BenDesc2", nullable = false, length = 34)
	public String getBenDesc2() {
		return this.benDesc2;
	}

	public void setBenDesc2(String benDesc2) {
		this.benDesc2 = benDesc2;
	}

	@Column(name = "BenDesc3", nullable = false, length = 34)
	public String getBenDesc3() {
		return this.benDesc3;
	}

	public void setBenDesc3(String benDesc3) {
		this.benDesc3 = benDesc3;
	}

	@Column(name = "BenDesc4", nullable = false, length = 34)
	public String getBenDesc4() {
		return this.benDesc4;
	}

	public void setBenDesc4(String benDesc4) {
		this.benDesc4 = benDesc4;
	}

	@Column(name = "BenDesc5", nullable = false, length = 34)
	public String getBenDesc5() {
		return this.benDesc5;
	}

	public void setBenDesc5(String benDesc5) {
		this.benDesc5 = benDesc5;
	}

	@Column(name = "ChrgType", nullable = false, length = 3)
	public String getChrgType() {
		return this.chrgType;
	}

	public void setChrgType(String chrgType) {
		this.chrgType = chrgType;
	}

	@Column(name = "AckIdentifier", nullable = false, length = 1)
	public char getAckIdentifier() {
		return this.ackIdentifier;
	}

	public void setAckIdentifier(char ackIdentifier) {
		this.ackIdentifier = ackIdentifier;
	}

	@Column(name = "ReasonCd", length = 4)
	public String getReasonCd() {
		return this.reasonCd;
	}

	public void setReasonCd(String reasonCd) {
		this.reasonCd = reasonCd;
	}

	@Column(name = "ReconNo", nullable = false)
	public int getReconNo() {
		return this.reconNo;
	}

	public void setReconNo(int reconNo) {
		this.reconNo = reconNo;
	}

	@Column(name = "ReqAuthNos", nullable = false)
	public byte getReqAuthNos() {
		return this.reqAuthNos;
	}

	public void setReqAuthNos(byte reqAuthNos) {
		this.reqAuthNos = reqAuthNos;
	}

	@Column(name = "PreAuthNos", nullable = false)
	public byte getPreAuthNos() {
		return this.preAuthNos;
	}

	public void setPreAuthNos(byte preAuthNos) {
		this.preAuthNos = preAuthNos;
	}

	@Column(name = "DbtrAddMk", nullable = false)
	public int getDbtrAddMk() {
		return this.dbtrAddMk;
	}

	public void setDbtrAddMk(int dbtrAddMk) {
		this.dbtrAddMk = dbtrAddMk;
	}

	@Column(name = "DbtrAddMb", nullable = false)
	public int getDbtrAddMb() {
		return this.dbtrAddMb;
	}

	public void setDbtrAddMb(int dbtrAddMb) {
		this.dbtrAddMb = dbtrAddMb;
	}

	@Column(name = "DbtrAddMs", nullable = false)
	public short getDbtrAddMs() {
		return this.dbtrAddMs;
	}

	public void setDbtrAddMs(short dbtrAddMs) {
		this.dbtrAddMs = dbtrAddMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMd", nullable = false, length = 23)
	public Date getDbtrAddMd() {
		return this.dbtrAddMd;
	}

	public void setDbtrAddMd(Date dbtrAddMd) {
		this.dbtrAddMd = dbtrAddMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddMt", nullable = false, length = 23)
	public Date getDbtrAddMt() {
		return this.dbtrAddMt;
	}

	public void setDbtrAddMt(Date dbtrAddMt) {
		this.dbtrAddMt = dbtrAddMt;
	}

	@Column(name = "DbtrAddCk", nullable = false)
	public int getDbtrAddCk() {
		return this.dbtrAddCk;
	}

	public void setDbtrAddCk(int dbtrAddCk) {
		this.dbtrAddCk = dbtrAddCk;
	}

	@Column(name = "DbtrAddCb", nullable = false)
	public int getDbtrAddCb() {
		return this.dbtrAddCb;
	}

	public void setDbtrAddCb(int dbtrAddCb) {
		this.dbtrAddCb = dbtrAddCb;
	}

	@Column(name = "DbtrAddCs", nullable = false)
	public short getDbtrAddCs() {
		return this.dbtrAddCs;
	}

	public void setDbtrAddCs(short dbtrAddCs) {
		this.dbtrAddCs = dbtrAddCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCd", nullable = false, length = 23)
	public Date getDbtrAddCd() {
		return this.dbtrAddCd;
	}

	public void setDbtrAddCd(Date dbtrAddCd) {
		this.dbtrAddCd = dbtrAddCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrAddCt", nullable = false, length = 23)
	public Date getDbtrAddCt() {
		return this.dbtrAddCt;
	}

	public void setDbtrAddCt(Date dbtrAddCt) {
		this.dbtrAddCt = dbtrAddCt;
	}

	@Column(name = "DbtrLupdMk", nullable = false)
	public int getDbtrLupdMk() {
		return this.dbtrLupdMk;
	}

	public void setDbtrLupdMk(int dbtrLupdMk) {
		this.dbtrLupdMk = dbtrLupdMk;
	}

	@Column(name = "DbtrLupdMb", nullable = false)
	public int getDbtrLupdMb() {
		return this.dbtrLupdMb;
	}

	public void setDbtrLupdMb(int dbtrLupdMb) {
		this.dbtrLupdMb = dbtrLupdMb;
	}

	@Column(name = "DbtrLupdMs", nullable = false)
	public short getDbtrLupdMs() {
		return this.dbtrLupdMs;
	}

	public void setDbtrLupdMs(short dbtrLupdMs) {
		this.dbtrLupdMs = dbtrLupdMs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMd", nullable = false, length = 23)
	public Date getDbtrLupdMd() {
		return this.dbtrLupdMd;
	}

	public void setDbtrLupdMd(Date dbtrLupdMd) {
		this.dbtrLupdMd = dbtrLupdMd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdMt", nullable = false, length = 23)
	public Date getDbtrLupdMt() {
		return this.dbtrLupdMt;
	}

	public void setDbtrLupdMt(Date dbtrLupdMt) {
		this.dbtrLupdMt = dbtrLupdMt;
	}

	@Column(name = "DbtrLupdCk", nullable = false)
	public int getDbtrLupdCk() {
		return this.dbtrLupdCk;
	}

	public void setDbtrLupdCk(int dbtrLupdCk) {
		this.dbtrLupdCk = dbtrLupdCk;
	}

	@Column(name = "DbtrLupdCb", nullable = false)
	public int getDbtrLupdCb() {
		return this.dbtrLupdCb;
	}

	public void setDbtrLupdCb(int dbtrLupdCb) {
		this.dbtrLupdCb = dbtrLupdCb;
	}

	@Column(name = "DbtrLupdCs", nullable = false)
	public short getDbtrLupdCs() {
		return this.dbtrLupdCs;
	}

	public void setDbtrLupdCs(short dbtrLupdCs) {
		this.dbtrLupdCs = dbtrLupdCs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCd", nullable = false, length = 23)
	public Date getDbtrLupdCd() {
		return this.dbtrLupdCd;
	}

	public void setDbtrLupdCd(Date dbtrLupdCd) {
		this.dbtrLupdCd = dbtrLupdCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DbtrLupdCt", nullable = false, length = 23)
	public Date getDbtrLupdCt() {
		return this.dbtrLupdCt;
	}

	public void setDbtrLupdCt(Date dbtrLupdCt) {
		this.dbtrLupdCt = dbtrLupdCt;
	}

	@Column(name = "DbtrTAuthDone", nullable = false)
	public short getDbtrTauthDone() {
		return this.dbtrTauthDone;
	}

	public void setDbtrTauthDone(short dbtrTauthDone) {
		this.dbtrTauthDone = dbtrTauthDone;
	}

	@Column(name = "DbtrRecStat", nullable = false)
	public byte getDbtrRecStat() {
		return this.dbtrRecStat;
	}

	public void setDbtrRecStat(byte dbtrRecStat) {
		this.dbtrRecStat = dbtrRecStat;
	}

	@Column(name = "DbtrAuthDone", nullable = false)
	public byte getDbtrAuthDone() {
		return this.dbtrAuthDone;
	}

	public void setDbtrAuthDone(byte dbtrAuthDone) {
		this.dbtrAuthDone = dbtrAuthDone;
	}

	@Column(name = "DbtrAuthNeeded", nullable = false)
	public byte getDbtrAuthNeeded() {
		return this.dbtrAuthNeeded;
	}

	public void setDbtrAuthNeeded(byte dbtrAuthNeeded) {
		this.dbtrAuthNeeded = dbtrAuthNeeded;
	}

	@Column(name = "DbtrUpdtChkId", nullable = false)
	public short getDbtrUpdtChkId() {
		return this.dbtrUpdtChkId;
	}

	public void setDbtrUpdtChkId(short dbtrUpdtChkId) {
		this.dbtrUpdtChkId = dbtrUpdtChkId;
	}

	@Column(name = "DbtrLHisTrnNo", nullable = false)
	public int getDbtrLhisTrnNo() {
		return this.dbtrLhisTrnNo;
	}

	public void setDbtrLhisTrnNo(int dbtrLhisTrnNo) {
		this.dbtrLhisTrnNo = dbtrLhisTrnNo;
	}

	@Column(name = "MsgTrfType", nullable = false)
	public byte getMsgTrfType() {
		return this.msgTrfType;
	}

	public void setMsgTrfType(byte msgTrfType) {
		this.msgTrfType = msgTrfType;
	}

	@Column(name = "RtnRsnCode", nullable = false)
	public byte getRtnRsnCode() {
		return this.rtnRsnCode;
	}

	public void setRtnRsnCode(byte rtnRsnCode) {
		this.rtnRsnCode = rtnRsnCode;
	}

	@Column(name = "InsType", nullable = false)
	public byte getInsType() {
		return this.insType;
	}

	public void setInsType(byte insType) {
		this.insType = insType;
	}

	@Column(name = "InsNo", nullable = false, length = 12)
	public String getInsNo() {
		return this.insNo;
	}

	public void setInsNo(String insNo) {
		this.insNo = insNo;
	}

	@Column(name = "ChrgsAmt", nullable = false, precision = 53, scale = 0)
	public double getChrgsAmt() {
		return this.chrgsAmt;
	}

	public void setChrgsAmt(double chrgsAmt) {
		this.chrgsAmt = chrgsAmt;
	}

	@Column(name = "MobEmlType", nullable = false)
	public byte getMobEmlType() {
		return this.mobEmlType;
	}

	public void setMobEmlType(byte mobEmlType) {
		this.mobEmlType = mobEmlType;
	}

	@Column(name = "MobileEmail", nullable = false, length = 62)
	public String getMobileEmail() {
		return this.mobileEmail;
	}

	public void setMobileEmail(String mobileEmail) {
		this.mobileEmail = mobileEmail;
	}

	@Column(name = "TransCdRtgs", nullable = false)
	public byte getTransCdRtgs() {
		return this.transCdRtgs;
	}

	public void setTransCdRtgs(byte transCdRtgs) {
		this.transCdRtgs = transCdRtgs;
	}

	@Column(name = "OrgRefNo", nullable = false, length = 16)
	public String getOrgRefNo() {
		return this.orgRefNo;
	}

	public void setOrgRefNo(String orgRefNo) {
		this.orgRefNo = orgRefNo;
	}

	@Column(name = "NUTRNo", nullable = false, length = 22)
	public String getNutrno() {
		return this.nutrno;
	}

	public void setNutrno(String nutrno) {
		this.nutrno = nutrno;
	}

	@Column(name = "TransId", nullable = false, length = 22)
	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InterfaceTime", nullable = false, length = 23)
	public Date getInterfaceTime() {
		return this.interfaceTime;
	}

	public void setInterfaceTime(Date interfaceTime) {
		this.interfaceTime = interfaceTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InterfaceDate", nullable = false, length = 23)
	public Date getInterfaceDate() {
		return this.interfaceDate;
	}

	public void setInterfaceDate(Date interfaceDate) {
		this.interfaceDate = interfaceDate;
	}

	@Column(name = "MsgId", nullable = false, length = 22)
	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OMsgTime", nullable = false, length = 23)
	public Date getOmsgTime() {
		return this.omsgTime;
	}

	public void setOmsgTime(Date omsgTime) {
		this.omsgTime = omsgTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OMsgDate", nullable = false, length = 23)
	public Date getOmsgDate() {
		return this.omsgDate;
	}

	public void setOmsgDate(Date omsgDate) {
		this.omsgDate = omsgDate;
	}

	@Column(name = "RMsgType", nullable = false, length = 3)
	public String getRmsgType() {
		return this.rmsgType;
	}

	public void setRmsgType(String rmsgType) {
		this.rmsgType = rmsgType;
	}

	@Column(name = "RREASONDESC", nullable = false, length = 60)
	public String getRreasondesc() {
		return this.rreasondesc;
	}

	public void setRreasondesc(String rreasondesc) {
		this.rreasondesc = rreasondesc;
	}

	@Column(name = "ONUTRNO", nullable = false, length = 22)
	public String getOnutrno() {
		return this.onutrno;
	}

	public void setOnutrno(String onutrno) {
		this.onutrno = onutrno;
	}

	public void setGrpCdWiseValidationResult(
			GrpCdWiseValidationResult grpCdWiseValidationResult) {
		this.grpCdWiseValidationResult = grpCdWiseValidationResult;
	}
	@Transient
	public ValidationResult getValidationResult() {
		return validationResult;
	}
	@Transient
	public GrpCdWiseValidationResult getGrpCdWiseValidationResult() {
		return grpCdWiseValidationResult;
	}

	public void setValidationResult(ValidationResult validationResult) {
		this.validationResult = validationResult;
	}

	@Transient 
	public List<RtgsMsgFieldRows> getRowsList() {
		return rowsList;
	}
	
	public void setRowsList(List<RtgsMsgFieldRows> rowsList) {
		this.rowsList = rowsList;
	}

	@Override
	public String toString() {
		return "D946020 [rowsList=" + rowsList + ", grpCdWiseValidationResult=" + grpCdWiseValidationResult
				+ ", validationResult=" + validationResult + ", id=" + id + ", rrefNo=" + rrefNo + ", utrno=" + utrno
				+ ", utrseqNo=" + utrseqNo + ", ordIfsccd=" + ordIfsccd + ", benIfsccd=" + benIfsccd + ", valueDate="
				+ valueDate + ", currCd=" + currCd + ", amount=" + amount + ", msgStat=" + msgStat + ", msgPriority="
				+ msgPriority + ", ordAcctId=" + ordAcctId + ", ordDesc1=" + ordDesc1 + ", ordDesc2=" + ordDesc2
				+ ", ordDesc3=" + ordDesc3 + ", ordDesc4=" + ordDesc4 + ", benFldNo=" + benFldNo + ", benDesc1="
				+ benDesc1 + ", benDesc2=" + benDesc2 + ", benDesc3=" + benDesc3 + ", benDesc4=" + benDesc4
				+ ", benDesc5=" + benDesc5 + ", chrgType=" + chrgType + ", ackIdentifier=" + ackIdentifier
				+ ", reasonCd=" + reasonCd + ", reconNo=" + reconNo + ", reqAuthNos=" + reqAuthNos + ", preAuthNos="
				+ preAuthNos + ", dbtrAddMk=" + dbtrAddMk + ", dbtrAddMb=" + dbtrAddMb + ", dbtrAddMs=" + dbtrAddMs
				+ ", dbtrAddMd=" + dbtrAddMd + ", dbtrAddMt=" + dbtrAddMt + ", dbtrAddCk=" + dbtrAddCk + ", dbtrAddCb="
				+ dbtrAddCb + ", dbtrAddCs=" + dbtrAddCs + ", dbtrAddCd=" + dbtrAddCd + ", dbtrAddCt=" + dbtrAddCt
				+ ", dbtrLupdMk=" + dbtrLupdMk + ", dbtrLupdMb=" + dbtrLupdMb + ", dbtrLupdMs=" + dbtrLupdMs
				+ ", dbtrLupdMd=" + dbtrLupdMd + ", dbtrLupdMt=" + dbtrLupdMt + ", dbtrLupdCk=" + dbtrLupdCk
				+ ", dbtrLupdCb=" + dbtrLupdCb + ", dbtrLupdCs=" + dbtrLupdCs + ", dbtrLupdCd=" + dbtrLupdCd
				+ ", dbtrLupdCt=" + dbtrLupdCt + ", dbtrTauthDone=" + dbtrTauthDone + ", dbtrRecStat=" + dbtrRecStat
				+ ", dbtrAuthDone=" + dbtrAuthDone + ", dbtrAuthNeeded=" + dbtrAuthNeeded + ", dbtrUpdtChkId="
				+ dbtrUpdtChkId + ", dbtrLhisTrnNo=" + dbtrLhisTrnNo + ", msgTrfType=" + msgTrfType + ", rtnRsnCode="
				+ rtnRsnCode + ", insType=" + insType + ", insNo=" + insNo + ", chrgsAmt=" + chrgsAmt + ", mobEmlType="
				+ mobEmlType + ", mobileEmail=" + mobileEmail + ", transCdRtgs=" + transCdRtgs + ", orgRefNo="
				+ orgRefNo + ", nutrno=" + nutrno + ", transId=" + transId + ", interfaceTime=" + interfaceTime
				+ ", interfaceDate=" + interfaceDate + ", msgId=" + msgId + ", omsgTime=" + omsgTime + ", omsgDate="
				+ omsgDate + ", rmsgType=" + rmsgType + ", rreasondesc=" + rreasondesc + ", onutrno=" + onutrno + "]";
	}
	
	
}
