package com.sil.hbm;
// Generated Jul 6, 2017 1:26:50 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Fatmmaster generated by hbm2java
 */
@Entity
@Table(name = "FATMMASTER")
@DynamicInsert
@DynamicUpdate
public class Fatmmaster implements java.io.Serializable {
	private static final long serialVersionUID = 313322597483351183L;
	private String atmid;
	private Integer lbrcode;
	private String location;
	private Integer pincode;
	private String address;
	private String atmtype;
	private String atmmodel;
	private String os;
	private String ip;
	private String natip;
	private Integer trnxscount;
	private Integer latitude;
	private Integer longitude;
	private String citycd;
	private String stateCode;
	private String add1;
	private String add2;
	private String add3;
	private String status;

	public Fatmmaster() {
	}

	public Fatmmaster(String atmid) {
		this.atmid = atmid;
	}

	public Fatmmaster(String atmid, Integer lbrcode, String location, Integer pincode, String address, String atmtype,
			String atmmodel, String os, String ip, String natip, Integer trnxscount, Integer latitude,
			Integer longitude, String citycd, String stateCode, String add1, String add2, String add3, String status) {
		this.atmid = atmid;
		this.lbrcode = lbrcode;
		this.location = location;
		this.pincode = pincode;
		this.address = address;
		this.atmtype = atmtype;
		this.atmmodel = atmmodel;
		this.os = os;
		this.ip = ip;
		this.natip = natip;
		this.trnxscount = trnxscount;
		this.latitude = latitude;
		this.longitude = longitude;
		this.citycd = citycd;
		this.stateCode = stateCode;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.status = status;
	}

	@Id

	@Column(name = "ATMID", unique = true, nullable = false, length = 10)
	public String getAtmid() {
		return this.atmid;
	}

	public void setAtmid(String atmid) {
		this.atmid = atmid;
	}

	@Column(name = "LBRCODE")
	public Integer getLbrcode() {
		return this.lbrcode;
	}

	public void setLbrcode(Integer lbrcode) {
		this.lbrcode = lbrcode;
	}

	@Column(name = "LOCATION", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "PINCODE")
	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

	@Column(name = "ADDRESS", length = 40)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "ATMTYPE", length = 10)
	public String getAtmtype() {
		return this.atmtype;
	}

	public void setAtmtype(String atmtype) {
		this.atmtype = atmtype;
	}

	@Column(name = "ATMMODEL", length = 25)
	public String getAtmmodel() {
		return this.atmmodel;
	}

	public void setAtmmodel(String atmmodel) {
		this.atmmodel = atmmodel;
	}

	@Column(name = "OS", length = 10)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "IP", length = 15)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "NATIP", length = 15)
	public String getNatip() {
		return this.natip;
	}

	public void setNatip(String natip) {
		this.natip = natip;
	}

	@Column(name = "TRNXSCOUNT")
	public Integer getTrnxscount() {
		return this.trnxscount;
	}

	public void setTrnxscount(Integer trnxscount) {
		this.trnxscount = trnxscount;
	}

	@Column(name = "LATITUDE")
	public Integer getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Integer latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE")
	public Integer getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Integer longitude) {
		this.longitude = longitude;
	}

	@Column(name = "CITYCD", length = 3)
	public String getCitycd() {
		return this.citycd;
	}

	public void setCitycd(String citycd) {
		this.citycd = citycd;
	}

	@Column(name = "STATE_CODE", length = 3)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "ADD1", length = 30)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "ADD2", length = 30)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "ADD3", length = 30)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
