package com.sil.hbm;
// Generated Jan 14, 2017 12:55:01 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mpostransaction generated by hbm2java
 */
@Entity
@Table(name = "MPOSTRANSACTION")
public class Mpostransaction implements java.io.Serializable {

	private static final long serialVersionUID = -3337390609958547423L;
	private String id;
	private int rrn;
	private Date transactiondate;
	private BigDecimal amount;
	private Date transdate;
	private String fromaccount;
	private String toaccount;
	private String drcr;

	public Mpostransaction() {
	}

	public Mpostransaction(String id, int rrn, Date transactiondate) {
		this.id = id;
		this.rrn = rrn;
		this.transactiondate = transactiondate;
	}

	public Mpostransaction(String id, int rrn, Date transactiondate, BigDecimal amount, Date transdate,
			String fromaccount, String toaccount, String drcr) {
		this.id = id;
		this.rrn = rrn;
		this.transactiondate = transactiondate;
		this.amount = amount;
		this.transdate = transdate;
		this.fromaccount = fromaccount;
		this.toaccount = toaccount;
		this.drcr = drcr;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "RRN", nullable = false)
	public int getRrn() {
		return this.rrn;
	}

	public void setRrn(int rrn) {
		this.rrn = rrn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRANSACTIONDATE", nullable = false, length = 10)
	public Date getTransactiondate() {
		return this.transactiondate;
	}

	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}

	@Column(name = "AMOUNT", precision = 12)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSDATE", length = 23)
	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	@Column(name = "FROMACCOUNT", length = 28)
	public String getFromaccount() {
		return this.fromaccount;
	}

	public void setFromaccount(String fromaccount) {
		this.fromaccount = fromaccount;
	}

	@Column(name = "TOACCOUNT", length = 28)
	public String getToaccount() {
		return this.toaccount;
	}

	public void setToaccount(String toaccount) {
		this.toaccount = toaccount;
	}

	@Column(name = "DRCR", length = 2)
	public String getDrcr() {
		return this.drcr;
	}

	public void setDrcr(String drcr) {
		this.drcr = drcr;
	}

}
