package com.sil.hbm;
// Generated Nov 7, 2017 5:30:06 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrepaidCardLinkedMaster generated by hbm2java
 */
@Entity
@Table(name = "PREPAID_CARD_LINKED_MASTER")
public class PrepaidCardLinkedMaster implements java.io.Serializable {
	private static final long serialVersionUID = 5180332885475745162L;
	private PrepaidCardLinkedMasterId id;
	private String acctNo;
	private int brCode;
	private String acctName;
	private String cardno;	public PrepaidCardLinkedMaster() {
	}

	public PrepaidCardLinkedMaster(PrepaidCardLinkedMasterId id, String acctNo, int brCode, String acctName) {
		this.id = id;
		this.acctNo = acctNo;
		this.brCode = brCode;
		this.acctName = acctName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CustNo", nullable = false, length = 19)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo", nullable = false, length = 12)),
			@AttributeOverride(name = "insno", column = @Column(name = "INSNO", nullable = false, length = 7)) })
	public PrepaidCardLinkedMasterId getId() {
		return this.id;
	}

	public void setId(PrepaidCardLinkedMasterId id) {
		this.id = id;
	}

	@Column(name = "AcctNo", nullable = false, length = 32)
	public String getAcctNo() {
		return this.acctNo;
	}

	public void setAcctNo(String acctNo) {
		this.acctNo = acctNo;
	}

	@Column(name = "BrCode", nullable = false)
	public int getBrCode() {
		return this.brCode;
	}

	public void setBrCode(int brCode) {
		this.brCode = brCode;
	}

	@Column(name = "AcctName", nullable = false, length = 50)
	public String getAcctName() {
		return this.acctName;
	}

	public void setAcctName(String acctName) {
		this.acctName = acctName;
	}

	@Override
	public String toString() {
		return "PrepaidCardLinkedMaster [id=" + id + ", acctNo=" + acctNo + ", brCode=" + brCode + ", acctName="
				+ acctName + "]";
	}
	
	@Column(name = "CARDNO", nullable = false, length = 20)
	public String getCardno() {
		return cardno;
	}

	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

}
