package com.sil.hbm;
// Generated Nov 7, 2017 5:30:06 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrepaidCardLinkedMasterId generated by hbm2java
 */
@Embeddable
public class PrepaidCardLinkedMasterId implements java.io.Serializable {
	private static final long serialVersionUID = 6242261122142226562L;
	private String custNo;
	private String mobileNo;
	private String insno;

	public PrepaidCardLinkedMasterId() {
	}

	public PrepaidCardLinkedMasterId(String custNo, String mobileNo, String insno) {
		this.custNo = custNo;
		this.mobileNo = mobileNo;
		this.insno = insno;
	}

	@Column(name = "CustNo", nullable = false, length = 19)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "MobileNo", nullable = false, length = 12)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "INSNO", nullable = false, length = 7)
	public String getInsno() {
		return this.insno;
	}

	public void setInsno(String insno) {
		this.insno = insno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrepaidCardLinkedMasterId))
			return false;
		PrepaidCardLinkedMasterId castOther = (PrepaidCardLinkedMasterId) other;

		return ((this.getCustNo() == castOther.getCustNo()) || (this.getCustNo() != null
				&& castOther.getCustNo() != null && this.getCustNo().equals(castOther.getCustNo())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this.getMobileNo() != null
						&& castOther.getMobileNo() != null && this.getMobileNo().equals(castOther.getMobileNo())))
				&& ((this.getInsno() == castOther.getInsno()) || (this.getInsno() != null
						&& castOther.getInsno() != null && this.getInsno().equals(castOther.getInsno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCustNo() == null ? 0 : this.getCustNo().hashCode());
		result = 37 * result + (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		result = 37 * result + (getInsno() == null ? 0 : this.getInsno().hashCode());
		return result;
	}

}
