package com.sil.hbm;
// Generated Apr 16, 2018 3:14:25 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * SmsRequest generated by hbm2java
 */
@Entity
@Table(name = "SMS_REQUEST")
@DynamicInsert
@DynamicUpdate
public class SmsRequest implements java.io.Serializable {

	private static final long serialVersionUID = -5838168293795115702L;
	private SmsRequestId id;
	private String sms;

	public SmsRequest() {
	}

	public SmsRequest(SmsRequestId id, String sms) {
		this.id = id;

		this.sms = sms;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bankcode", column = @Column(name = "BANKCODE", nullable = false, length = 4)),
			@AttributeOverride(name = "cardAliaceNo", column = @Column(name = "CARD_ALIACE_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MOBILE_NO", nullable = false, length = 10)) })
	public SmsRequestId getId() {
		return this.id;
	}

	public void setId(SmsRequestId id) {
		this.id = id;
	}

	@Column(name = "SMS", nullable = false, length = 200)
	public String getSms() {
		return this.sms;
	}

	public void setSms(String sms) {
		this.sms = sms;
	}

}
