package com.sil.hbm;
// Generated Apr 16, 2018 3:14:25 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsRequestId generated by hbm2java
 */
@Embeddable
public class SmsRequestId implements java.io.Serializable {
	
	private static final long serialVersionUID = 4542807364658891467L;
	private String bankcode;
	private String cardAliaceNo;
	private String mobileNo;
	private Date reqDate;
	private Date reqTime;


	public SmsRequestId() {
	}

	public SmsRequestId(String bankcode, String cardAliaceNo, String mobileNo,Date reqDate,Date reqTime) {
		this.bankcode = bankcode;
		this.cardAliaceNo = cardAliaceNo;
		this.mobileNo = mobileNo;
		this.reqDate=reqDate;
		this.reqTime=reqTime;
	}

	@Column(name = "BANKCODE", nullable = false, length = 4)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "CARD_ALIACE_NO", nullable = false, length = 20)
	public String getCardAliaceNo() {
		return this.cardAliaceNo;
	}

	public void setCardAliaceNo(String cardAliaceNo) {
		this.cardAliaceNo = cardAliaceNo;
	}

	@Column(name = "MOBILE_NO", nullable = false, length = 10)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "REQ_DATE", nullable = false, length = 10)
	public Date getReqDate() {
		return reqDate;
	}

	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "REQ_TIME", nullable = false, length = 16)
	public Date getReqTime() {
		return reqTime;
	}

	public void setReqTime(Date reqTime) {
		this.reqTime = reqTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SmsRequestId))
			return false;
		SmsRequestId castOther = (SmsRequestId) other;

		return ((this.getBankcode() == castOther.getBankcode()) || (this.getBankcode() != null
				&& castOther.getBankcode() != null && this.getBankcode().equals(castOther.getBankcode())))
				&& ((this.getCardAliaceNo() == castOther.getCardAliaceNo())
						|| (this.getCardAliaceNo() != null && castOther.getCardAliaceNo() != null
								&& this.getCardAliaceNo().equals(castOther.getCardAliaceNo())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this.getMobileNo() != null
						&& castOther.getMobileNo() != null && this.getMobileNo().equals(castOther.getMobileNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankcode() == null ? 0 : this.getBankcode().hashCode());
		result = 37 * result + (getCardAliaceNo() == null ? 0 : this.getCardAliaceNo().hashCode());
		result = 37 * result + (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		return result;
	}

}
